import {mediaPolicyVersion,validateMediaDeclaration,readBoundedBody,verifyMediaHeader,screenPracticeImage} from '../../media-safety';
import {identity,readState,checkOrigin,db,bucket,activeExplore,craftEnrolled,requireLesson,errorResponse} from '../../service';
export const dynamic='force-dynamic';
export async function POST(req:Request){let uploadId='';try{checkOrigin(req);const u=await identity();validateMediaDeclaration(req.headers.get('x-content-declaration'),req.headers.get('x-screening-consent'));const {state:s}=await readState(u.userId);const lessonKey=req.headers.get('x-lesson-key');if(lessonKey){requireLesson(s,lessonKey)}else if(!activeExplore(s)&&!craftEnrolled(s))throw new Error('Open a free practice assignment to upload your work.');const type=req.headers.get('content-type')||'';if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm','video/quicktime'].includes(type))throw new Error('Upload JPG, PNG, WebP, MP4, WebM or MOV.');const size=Number(req.headers.get('x-file-size'));const max=type.startsWith('image/')?5*1024*1024:25*1024*1024;if(!Number.isInteger(size)||size<1||size>max)throw new Error('Use an image under 5 MB or a video under 25 MB. Larger videos can be linked.');const name=decodeURIComponent(req.headers.get('x-file-name')||'upload').replace(/[^\p{L}\p{N} ._()-]/gu,'').slice(0,120)||'upload';uploadId=crypto.randomUUID();const r=await db().prepare('INSERT INTO uploads(id,user_id,name,type,size,created_at) SELECT ?,?,?,?,?,? WHERE (SELECT COALESCE(SUM(size),0) FROM uploads WHERE user_id=?) + ? <= 104857600').bind(uploadId,u.userId,name,type,size,Date.now(),u.userId,size).run();if(!r.meta.changes){uploadId='';throw new Error('Your 100 MB pilot storage is full. Use a viewing link instead.')}
const bytes=await readBoundedBody(req,size);verifyMediaHeader(bytes,type);const screening=type.startsWith('image/')?await screenPracticeImage(bytes,type):{status:'declared-safe-video-not-automatically-reviewed'};await bucket().put(uploadId,bytes,{httpMetadata:{contentType:type},customMetadata:{owner:u.userId,policy:mediaPolicyVersion,screening:screening.status}});
return Response.json({id:uploadId,name,type,size});}catch(e){if(uploadId){await bucket().delete(uploadId).catch(()=>{});await db().prepare('DELETE FROM uploads WHERE id=?').bind(uploadId).run().catch(()=>{})}return errorResponse(e)}}
export async function GET(){try{const u=await identity();return Response.json((await db().prepare('SELECT id,name,type,size,created_at FROM uploads WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all()).results,{headers:{'Cache-Control':'no-store'}})}catch(e){return errorResponse(e)}}
export async function DELETE(req:Request){try{checkOrigin(req);const u=await identity();const id=new URL(req.url).searchParams.get('id');if(!id)throw new Error('Choose an upload.');const f=await db().prepare('SELECT id FROM uploads WHERE id=? AND user_id=?').bind(id,u.userId).first();if(!f)throw new Error('Upload not found.');const {state:s}=await readState(u.userId);const archived=await db().prepare("SELECT id FROM reflection_attempts WHERE user_id=? AND json_extract(data,'$.uploadId')=? LIMIT 1").bind(u.userId,id).first();const reviewed=await db().prepare("SELECT id FROM ai_jobs WHERE user_id=? AND status='complete' AND json_extract(CASE WHEN json_valid(answer) THEN answer ELSE '{}' END,'$.uploadId')=? LIMIT 1").bind(u.userId,id).first();if(reviewed||archived||Object.values(s.drafts||{}).some((v:any)=>v.uploadId===id)||s.submissions.some((v:any)=>v.uploadId===id)||Object.values(s.assessments||{}).some((v:any)=>v.history?.some((a:any)=>a.uploadId===id)))throw new Error('This file is attached to saved work. Keep it available for your portfolio.');await bucket().delete(id);await db().prepare('DELETE FROM uploads WHERE id=? AND user_id=?').bind(id,u.userId).run();return Response.json({deleted:true})}catch(e){return errorResponse(e)}}

