'use client';
import './interactives.css';
import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {interactiveComponents} from './interactives';
import {InteractiveKind,InteractiveCheckpoint} from './interactive-contract';
const groups:{title:string;items:{id:InteractiveKind;title:string;intro:string}[]}[]=[
 {title:'See the difference',items:[{id:'before-after',title:'A little light changes everything.',intro:'Move the divider. Notice what returns to the frame.'},{id:'hotspots',title:'Guide the eye.',intro:'Explore the frame and notice what competes for attention.'},{id:'exposure',title:'One image. Three decisions.',intro:'See how camera settings trade light for other qualities.'},{id:'white-balance',title:'Find your neutral.',intro:'Use a white surface to notice a colour cast.'}]},
 {title:'Build the sequence',items:[{id:'shot-sorter',title:'From context to detail.',intro:'Move from the whole situation toward what matters.'},{id:'storyboard',title:'Change the order. Change the story.',intro:'Reveal a place, an action and a result in a different order.'},{id:'shot-list',title:'Give every shot a purpose.',intro:'Build a small plan you can actually film.'},{id:'axis',title:'Keep the viewer oriented.',intro:'Move around the line of action and compare screen direction.'}]},
 {title:'Check and share',items:[{id:'audio-ab',title:'Hear what the noise hides.',intro:'Compare two versions of the same synthetic sound pattern.'},{id:'thirds',title:'Look again at your own frame.',intro:'Place a guide over a still without uploading it.'},{id:'captions',title:'Give the words room.',intro:'Revise a caption and test its reading time.'}]}
];
export default function FoundationReview(){const [group,setGroup]=useState(0),[selected,setSelected]=useState<InteractiveKind>('before-after'),[events,setEvents]=useState<Record<string,InteractiveCheckpoint>>({}),[run,setRun]=useState(0);const item=groups.flatMap(g=>g.items).find(x=>x.id===selected)!,Component=interactiveComponents[selected];return <section className="foundation-review"><div className="review-note"><span>Foundation review</span><p>Try the learning tools. These demonstrations do not change your saved course progress.</p></div><div className="review-groups" role="group" aria-label="Learning tool groups">{groups.map((g,i)=><Button variant={group===i?'default':'outline'} aria-pressed={group===i} key={g.title} onClick={()=>{setGroup(i);setSelected(g.items[0].id)}}>{g.title}</Button>)}</div><div className="review-tools" role="group" aria-label="Learning tools">{groups[group].items.map(x=><button key={x.id} aria-pressed={selected===x.id} onClick={()=>setSelected(x.id)}>{x.id==='before-after'?'Before / after':x.id==='audio-ab'?'Sound comparison':x.id==='axis'?'Line of action':x.id==='thirds'?'Your own still':x.id.replaceAll('-',' ')}</button>)}</div><header className="review-title"><span className="eyebrow">VIDEOGRAPHY / LEARN BY TRYING</span><h1>{item.title}</h1><p>{item.intro}</p></header><div className="interactive-surface" data-interactive={selected}><Component key={selected+'-'+run} instanceId={'foundation-'+selected} onCheckpoint={e=>setEvents(v=>({...v,[selected]:e}))}/></div><div className="review-completion"><span role="status">{events[selected]?'Exploration recorded in this preview':'Move a control to start exploring'}</span><Button variant="ghost" onClick={()=>{setRun(v=>v+1);setEvents(v=>{const n={...v};delete n[selected];return n})}}>Start again</Button></div><details className="lesson-details"><summary>About these examples</summary><p>Four original generated photographs belong to four distinct teaching slots. Other tools use purpose-built diagrams. The sound samples are original synthetic signals. These are working interaction components; complete learning sessions, assessments and course progression come in later stages.</p></details></section>}
