import {reviewDraft,completeReview} from '../../lessons/review-rules';
import {isVisualKey,visualLesson} from '../../lessons/content';
import {validateActivity,validateActivityDraft,validateReflection} from '../../lessons/activity-rules';
import {adoptReadyOnboarding} from '../../onboarding/session';
import {isScenarioProfile,isScenarioKey,scenarioPath} from '../../scenario-engine';
import {normalizeProfile} from '../../profile-validation';
import {buildPersonalPlan,isPersonalized} from '../../personalization';
import {courseKeys,isCourseKey,levels,recommendedLevel,activeLevel} from '../../selfpaced-curriculum';
import {validateReview} from '../../assignment-review';
import {buildProgramme} from '../../videography/programme';
import {basicPaths,basicKeys,basicContext,curriculumVersion,journalTypes} from '../../beginner-curriculum';
import {scoreAttempt,moduleInfo,sequenceFor,assignmentRubric} from '../../learning-rules';
import {identity,readState,saveState,usage,checkOrigin,safeText,safeUrl,mentorFor,requireLesson,activeExplore,craftEnrolled,db,errorResponse} from '../../service';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const user=await identity();await adoptReadyOnboarding(req);const data=await readState(user.userId);return Response.json({...data,user:{name:user.fullName||'Learner',email:user.email},usage:await usage(user.userId,data.state)},{headers:{'Cache-Control':'no-store'}})}catch(e){return errorResponse(e)}}
export async function POST(req:Request){try{
checkOrigin(req);const user=await identity();const raw=await req.text();if(raw.length>24000)throw new Error('This submission is too long.');const b=JSON.parse(raw);const {state:s,revision}=await readState(user.userId);if(b.revision!==revision)throw Object.assign(new Error('Your learning changed in another tab. Refresh and try again.'),{status:409});
const now=new Date().toISOString(),a=b.action,id=()=>crypto.randomUUID();let portfolioChange:any=null;let reflectionChange:any=null;
switch(a){
case 'learning_level':{if(!s.profile)throw new Error('Complete your starting-point diagnostic first.');if(!levels.includes(b.level))throw new Error('Choose a published level.');s.profile.level=b.level;if(isPersonalized(s.profile)){s.profile.levelOverride=b.level;s.personalPlan=buildPersonalPlan(s.profile);}break;}
case 'profile':{s.profile=normalizeProfile(b.profile);s.basicPlan={...basicContext(s.profile),createdAt:now,basis:'curriculum template'};if(isPersonalized(s.profile)||isScenarioProfile(s.profile)){s.personalPlan=buildPersonalPlan(s.profile);if(s.personalPlan.notices?.some((n:any)=>n.blocking))throw new Error('Adjust the blocked format or time choice in your diagnostic before saving this route.');const first=s.personalPlan.paths.slice(0,2).map((p:any)=>p.id);if(isScenarioProfile(s.profile)&&first.length===1)first.push('need-'+s.profile.request.scenario.use_case.toLowerCase()+'-prepare');s.trialPathIds=s.trialPathIds||first;}break;}
case 'explore_activate':{if(b.terms!==true)throw new Error('Confirm the pilot terms before continuing.');if(activeExplore(s))break;const expiry=new Date();expiry.setUTCFullYear(expiry.getUTCFullYear()+1);s.membership={startsAt:now,expiresAt:expiry.toISOString(),plan:'Explore annual',price:999,simulated:true};s.receipts.unshift({id:id(),product:'Explore · one year',amount:999,date:now,simulated:true});break;}
case 'visual_session_save':
case 'visual_session_complete':{
 const key=safeText(b.key,80,1);if(!isVisualKey(key))throw new Error('Choose a published visual session.');requireLesson(s,key);
 const notes=safeText(b.notes,4000,a==='visual_session_complete'?20:0),url=safeUrl(b.url||''),uploadId=safeText(b.uploadId||'',100);let uploadType='';
 if(uploadId){const owned:any=await db().prepare('SELECT type FROM uploads WHERE id=? AND user_id=?').bind(uploadId,user.userId).first();if(!owned)throw new Error('That upload is not available in your account.');uploadType=owned.type;}
 const draftActivity=validateActivityDraft(key,b.activity);if(b.ratings&&(!Array.isArray(b.ratings)||b.ratings.length!==3||b.ratings.some((n:any)=>!Number.isInteger(n)||n< -1||n>4)))throw new Error('Check the three reflection answers.');
 s.drafts[key]={...(s.drafts[key]||{}),notes,url,uploadId,uploadType,visualActivity:draftActivity||null,visualWorkMode:b.workMode==='plan'?'plan':b.workMode==='record'?'record':s.drafts[key]?.visualWorkMode||'record',visualRatings:Array.isArray(b.ratings)?b.ratings.slice(0,3):s.drafts[key]?.visualRatings||[],visualConsent:b.consent===true,visualReview:b.review?reviewDraft(b.review):s.drafts[key]?.visualReview||null,visualCard:Math.max(0,Math.min(5,Number.isInteger(b.card)?b.card:0)),updatedAt:now};
 if(a==='visual_session_complete'){
  const activity=validateActivity(key,b.activity),reflection=b.review?completeReview(key,b.review):validateReflection(key,b.ratings);
  if(!uploadId&&!url&&b.workMode!=='plan')throw new Error('Attach your work or choose a written plan.');
  if(!uploadId&&!url&&notes.trim().length<60)throw new Error('Describe your written plan in at least 60 characters, including what remains untested.');
  if(b.consent!==true)throw new Error('Confirm that your practice is safe to save and you have permission.');
  s.visualSessions=s.visualSessions||{};const prior=s.visualSessions[key];s.visualSessions[key]={version:b.review?2:1,activity,reflection,workMode:b.workMode==='plan'?'plan':'record',consentAt:now,completedAt:prior?.completedAt||now,updatedAt:now};
  s.progress[key]={...(s.progress[key]||{}),done:true,at:s.progress[key]?.at||now,source:'completed-practice',feedbackScore:reflection.score,scoreBasis:b.review?'lesson-knowledge-check':'reflection-feedback'};
  const sub=s.submissions.find((x:any)=>x.visualSession===key);if(!sub&&s.submissions.length>=60)throw new Error('Your saved-work space is full. Export your work from My account before adding another piece.');
  const piece={id:sub?.id||id(),key,notes,url,uploadId,uploadType,createdAt:sub?.createdAt||now,updatedAt:now,status:'saved',feedback:'',scores:null,visualSession:key,practiceScore:reflection.score,practiceBasis:b.review?'lesson-knowledge-check':'reflection-feedback',correction:b.review&&'correction' in reflection?reflection.correction:'',reviewFocus:b.review?reflection.focus:null,workMode:b.workMode==='plan'?'plan':'record'};
  if(sub)s.submissions=s.submissions.map((x:any)=>x.id===sub.id?piece:x);else s.submissions.unshift(piece);
 }
 break;
}
case 'programme_save':{s.programme=buildProgramme(b.programme,s.programme);break;}
case 'programme_update':{if(!s.programme)throw new Error('Make your plan first.');const u=b.update||{};s.programme=buildProgramme({...s.programme,hoursPerWeek:u.hoursPerWeek??s.programme.schedule.hoursPerWeek,startDate:u.startDate??s.programme.schedule.startDate,daysPerWeek:u.daysPerWeek??s.programme.schedule.daysPerWeek,mode:u.mode??s.programme.mode},s.programme);break;}
case 'attach':{const key=safeText(b.key,80,1);requireLesson(s,key);const uploadId=b.uploadId?safeText(b.uploadId,100):'';let uploadType='';if(uploadId){const owned:any=await db().prepare('SELECT type FROM uploads WHERE id=? AND user_id=?').bind(uploadId,user.userId).first();if(!owned)throw new Error('This upload is not available in your account.');uploadType=owned.type}s.drafts[key]={...(s.drafts[key]||{}),uploadId,uploadType,updatedAt:now};break;}
case 'assignment_save':{const key=safeText(b.key,80,1);requireLesson(s,key);const notes=safeText(b.notes,4000);const uploadId=safeText(b.uploadId||'',100);let uploadType='';if(uploadId){const own:any=await db().prepare('SELECT type FROM uploads WHERE id=? AND user_id=?').bind(uploadId,user.userId).first();if(!own)throw new Error('That upload is not available in your account.');uploadType=own.type}s.drafts[key]={...(s.drafts[key]||{}),notes,url:safeUrl(b.url||''),uploadId,uploadType,updatedAt:now};break;}
case 'lesson_save':{const key=safeText(b.key,80,1);const info=requireLesson(s,key);const checks=Array.isArray(b.checks)?b.checks:[];if(checks.length!==info.lesson.checks.length||checks.some((x:any)=>typeof x!=='boolean'))throw new Error('Check your lesson checklist.');const notes=safeText(b.notes,4000);s.drafts[key]={...(s.drafts[key]||{}),notes,checks,updatedAt:now};if(b.complete){if(!s.progress[key])throw new Error('Complete the scored Reflect checkpoint to unlock the next module.');}else if(b.undo){if(isCourseKey(key)||isVisualKey(key))throw new Error('An earned course pass stays available. You can record another attempt.');delete s.progress[key]}break;}
case 'ai_review_accept':
case 'practice_assess':{
 let acceptedReview:any=null;
 if(a==='ai_review_accept'){
  const job:any=await db().prepare("SELECT id,answer FROM ai_jobs WHERE id=? AND user_id=? AND status='complete' AND kind='feedback'").bind(safeText(b.reviewId,100,12),user.userId).first();
  if(!job)throw new Error('That review is not available in your account.');
  const saved=JSON.parse(job.answer);if(saved.type!=='assignment-review-v1')throw new Error('Choose an assignment review.');
  if(saved.rubricSignature&&saved.rubricSignature!==JSON.stringify(assignmentRubric(saved.lessonKey,s.profile)))throw new Error('Your assignment criteria changed. Request a fresh review before saving it to progress.');acceptedReview=validateReview(saved.review,saved.lessonKey,s.profile);if(acceptedReview.total===null)throw new Error('This review needs more evidence before it can be scored.');
  const applied=await db().prepare("SELECT id FROM reflection_attempts WHERE user_id=? AND json_extract(data,'$.reviewId')=? LIMIT 1").bind(user.userId,job.id).first();if(applied)throw new Error('This review has already been saved to your progress.');
  b.key=saved.lessonKey;b.notes=saved.notes;b.uploadId=saved.uploadId;b.url=s.drafts?.[saved.lessonKey]?.url||'';b.ratings=acceptedReview.ratings;b.reviewId=job.id;
 }

 const key=safeText(b.key,80,1);const info=requireLesson(s,key);const notes=safeText(b.notes,4000,20);const url=safeUrl(b.url||'');const uploadId=b.uploadId?safeText(b.uploadId,100):'';let uploadType='';
 if(uploadId){const owned:any=await db().prepare('SELECT id,type FROM uploads WHERE id=? AND user_id=?').bind(uploadId,user.userId).first();if(!owned)throw new Error('This upload is not available in your account.');uploadType=owned.type}
 if(!isCourseKey(key)&&!isScenarioKey(key)&&info.phase!=='pre'&&!url&&!uploadId)throw new Error('Add a still, short video or viewing link from your tryout before scoring it.');
 const result=scoreAttempt(key,b.ratings,s.profile);s.assessments=s.assessments||{};const previous=s.assessments[key];const attempt={id:id(),key,notes,url,uploadId,uploadType,...result,basis:acceptedReview?'ai-first-pass':'self-check',source:acceptedReview?'ai-review':'self-check',reviewId:acceptedReview?b.reviewId:null,aiFeedback:acceptedReview,at:now};
 if(isCourseKey(key)||isScenarioKey(key))reflectionChange=attempt;const history=[attempt,...(previous?.history||[])].slice(0,5);s.assessments[key]={...attempt,attemptCount:(previous?.attemptCount||0)+1,bestScore:Math.max(previous?.bestScore||0,result.total),history};
 s.drafts[key]={...(s.drafts[key]||{}),notes,checks:result.ratings.map(v=>v>=3),ratings:result.ratings,url,uploadId,uploadType,updatedAt:now};
 if(result.passed&&!isVisualKey(key))s.progress[key]={done:true,at:now,source:acceptedReview?'ai-review':'practice-checkpoint',score:result.total};
 if(result.passed&&((isCourseKey(key)&&info.index===4)||(isScenarioKey(key)&&info.index===scenarioPath(info.pathId,s.profile)!.lessons.length-1))){const existing=s.submissions.find((v:any)=>v.weeklyPath===info.pathId);const weekly={id:existing?.id||id(),key,notes,url,uploadId,createdAt:now,status:'saved',feedback:'',scores:null,practiceScore:result.total,practiceBasis:acceptedReview?'ai-review':'self-check',weeklyPath:info.pathId,sessionKeys:isScenarioKey(key)?scenarioPath(info.pathId,s.profile)!.keys:courseKeys.filter(k=>k.startsWith(info.pathId+'-'))};if(existing)s.submissions=s.submissions.map((v:any)=>v.id===existing.id?weekly:v);else s.submissions.unshift(weekly);if(basicKeys.every(k=>s.progress[k]))s.basicCompletedAt=s.basicCompletedAt||now;}
 if(b.submit===true){if(s.submissions.length>=60)throw new Error('This pilot supports up to 60 saved submissions.');s.submissions.unshift({id:id(),key,notes,url,uploadId,createdAt:now,status:info.craft?'awaiting_review':'saved',feedback:'',scores:null,practiceScore:result.total,practiceBasis:acceptedReview?'ai-review':'self-check'})}
 break;
}
case 'journal_save':{const kind=safeText(b.kind,40,1);if(!journalTypes.some(j=>j.id===kind))throw new Error('Choose a learning journal.');s.journals=s.journals||{};s.journals[kind]={text:safeText(b.text,16000),updatedAt:now};break;}
case 'basic_mentor_review':{if(!basicKeys.every(k=>s.progress[k]))throw new Error('Complete the beginner capstone first.');const mentor=mentorFor(b.mentorId);const scores=b.scores;if(!Array.isArray(scores)||scores.length!==6||scores.some((x:any)=>!Number.isInteger(x)||x<0||x>4))throw new Error('Rate all six criteria from 0 to 4.');const total=scores.reduce((n:number,v:number,i:number)=>n+v/4*[25,20,15,20,10,10][i],0);s.basicMentorReview={mentorId:mentor.id,scores,total,approved:total>=70&&scores.every((x:number)=>x>=2),feedback:safeText(b.feedback,4000,20),at:now,simulated:true};break;}
case 'mentor_request':{if(!s.profile)throw new Error('Complete your diagnostic first.');if(b.consent!==true)throw new Error('Consent is needed to share your diagnostic with the selected mentor.');if(s.craft&&!['declined','expired'].includes(s.craft.status))throw new Error('You already have a mentor request or an active Craft journey.');const m=mentorFor(b.mentorId);if(!m.slots.includes(b.slot))throw new Error('Choose an available call preference.');s.craft={mentorId:m.id,slot:b.slot,status:'requested',requestedAt:now,consentAt:now,plan:'',planApproved:false};break;}
case 'mentor_decision':{if(s.craft?.status!=='requested')throw new Error('There is no pending mentor request.');if(b.accept===true){s.craft.status='accepted';s.craft.holdUntil=new Date(Date.now()+48*3600000).toISOString()}else{s.craft.status='declined'}break;}
case 'craft_activate':{if(s.craft?.status!=='accepted')throw new Error('The mentor must accept before checkout.');if(new Date(s.craft.holdUntil).getTime()<=Date.now())throw new Error('Your mentor reservation has expired. Choose a mentor again.');if(b.terms!==true)throw new Error('Confirm the pilot terms.');s.craft.status='paid';s.craft.paidAt=now;s.craft.endsAt=new Date(Date.now()+84*86400000).toISOString();s.receipts.unshift({id:id(),product:'Craft · Beginner Videography',amount:30000,date:now,simulated:true});break;}
case 'mentor_cancel':{if(!s.craft||craftEnrolled(s))throw new Error('An enrolled course cannot be cancelled from this demo control.');s.craft=null;break;}
case 'craft_plan':{if(!craftEnrolled(s))throw new Error('Complete Craft checkout first.');s.craft.plan=safeText(b.plan,10000,80);s.craft.planApproved=false;s.craft.status='paid';break;}
case 'mentor_approve_plan':{if(s.craft?.status!=='paid'||s.craft.plan.length<80)throw new Error('Prepare the learner pathway first.');s.craft.planApproved=true;s.craft.approvedAt=now;s.craft.status='active';break;}
case 'submit':{const key=safeText(b.key,80,1);requireLesson(s,key);const notes=safeText(b.notes,4000,20);const url=safeUrl(b.url||'');const uploadId=b.uploadId?safeText(b.uploadId,100):'';if(uploadId){const owned=await db().prepare('SELECT id FROM uploads WHERE id=? AND user_id=?').bind(uploadId,user.userId).first();if(!owned)throw new Error('This upload is not available in your account.')}if(s.submissions.length>=60)throw new Error('This pilot supports up to 60 saved submissions.');s.submissions.unshift({id:id(),key,notes,url,uploadId,createdAt:now,status:key.startsWith('craft-')?'awaiting_review':'saved',feedback:'',scores:null});break;}
case 'mentor_review':{if(s.craft?.status!=='active')throw new Error('Activate your Craft journey first.');const sub=s.submissions.find((x:any)=>x.id===b.id&&x.key.startsWith('craft-'));if(!sub)throw new Error('That Craft submission was not found.');const scores=b.scores;if(!Array.isArray(scores)||scores.length!==6||scores.some((x:any)=>!Number.isInteger(x)||x<0||x>4))throw new Error('Score every criterion from 0 to 4.');sub.feedback=safeText(b.feedback,4000,20);sub.scores=scores;sub.total=Math.round(scores.reduce((n:number,v:number,i:number)=>n+v/4*[25,20,15,20,10,10][i],0));sub.status=b.approve===true?'approved':'revision_requested';if(sub.status==='approved'&&(sub.total<70||scores.some((x:number)=>x<2)))throw new Error('Approval requires at least 70/100 and every criterion at 2 or higher.');sub.reviewedAt=now;sub.reviewedBy=s.craft.mentorId;break;}
case 'message':{if(!craftEnrolled(s))throw new Error('Enrol in Craft to use the mentor workspace.');s.messages.push({id:id(),text:safeText(b.text,2000,1),role:b.role==='mentor'?'mentor':'learner',at:now});s.messages=s.messages.slice(-100);break;}
case 'checkin':{if(s.craft?.status!=='active')throw new Error('Your Craft pathway is not active yet.');s.checkins.unshift({id:id(),text:safeText(b.text,1500,5),at:now});s.checkins=s.checkins.slice(0,100);break;}
case 'book_call':{if(s.craft?.status!=='active')throw new Error('Activate your Craft pathway first.');const date=safeText(b.date,10,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Choose a valid date.');const at=new Date(date+'T00:00:00+05:30').getTime();if(!Number.isFinite(at)||at<Date.now()-86400000||at>Date.now()+100*86400000)throw new Error('Choose a date within the next 100 days.');const slot=mentorFor(s.craft.mentorId).slots.find(x=>x===b.slot);if(!slot)throw new Error('Choose one of your mentor’s call windows.');const day=new Date(date+'T12:00:00Z').getUTCDay();if(day!==({Tuesday:2,Thursday:4,Saturday:6} as any)[slot.split(' ')[0]])throw new Error('Choose a date that matches the call window.');if(s.bookings.some((x:any)=>x.date===date&&x.slot===slot))throw new Error('You already saved this call.');if(s.bookings.length>=12)throw new Error('Your pilot includes 12 weekly calls.');s.bookings.push({id:id(),date,slot,mentorId:s.craft.mentorId,simulated:true});break;}
case 'cancel_call':s.bookings=s.bookings.filter((x:any)=>x.id!==b.id);break;
case 'switch_request':{if(s.craft?.status!=='active')throw new Error('Activate Craft before requesting a mentor change.');const m=mentorFor(b.mentorId);if(m.id===s.craft.mentorId)throw new Error('Choose a different mentor.');if(!m.slots.includes(b.slot))throw new Error('Choose a call preference.');s.craft.switchRequest={mentorId:m.id,slot:b.slot,at:now};break;}
case 'switch_accept':{if(!s.craft?.switchRequest)throw new Error('No mentor change is pending.');s.craft.mentorId=s.craft.switchRequest.mentorId;s.craft.slot=s.craft.switchRequest.slot;s.craft.switchRequest=null;break;}
case 'portfolio_save':{s.portfolio.title=safeText(b.title,100,1);s.portfolio.bio=safeText(b.bio,1500);const ids=Array.isArray(b.ids)?b.ids:[];if(ids.length>9||new Set(ids).size!==ids.length||ids.some((x:string)=>!s.submissions.find((v:any)=>v.id===x)))throw new Error('Select up to nine of your submissions.');s.portfolio.ids=ids;break;}
case 'portfolio_publish':{if(b.consent!==true)throw new Error('Confirm that the selected work may be shared publicly.');if(!s.portfolio.ids.length)throw new Error('Select at least one portfolio piece first.');s.portfolio.token=s.portfolio.token||id();const items=s.portfolio.ids.map((x:string)=>s.submissions.find((v:any)=>v.id===x)).filter(Boolean).map((v:any)=>({key:v.key,notes:v.notes,url:v.url,uploadId:v.uploadId,status:v.status,total:v.total}));portfolioChange={token:s.portfolio.token,data:JSON.stringify({title:s.portfolio.title,bio:s.portfolio.bio,name:s.profile?.name||'Framepath learner',items,simulatedReviews:true})};break;}
case 'portfolio_unpublish':{if(s.portfolio.token)portfolioChange={removeToken:s.portfolio.token};s.portfolio.token=null;break;}
default:throw new Error('That action is not available.')}
let next:number;if(reflectionChange){const encoded=JSON.stringify(s);const results=await db().batch([db().prepare('UPDATE learners SET data=?,revision=revision+1,updated_at=? WHERE user_id=? AND revision=?').bind(encoded,Date.now(),user.userId,revision),db().prepare('INSERT INTO reflection_attempts(id,user_id,module_key,data,created_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM learners WHERE user_id=? AND revision=? AND data=?)').bind(reflectionChange.id,user.userId,reflectionChange.key,JSON.stringify(reflectionChange),Date.now(),user.userId,revision+1,encoded)]);if(!results[0].meta.changes)throw Object.assign(new Error('Your learning changed in another tab. Refresh and retry.'),{status:409});next=revision+1}else if(portfolioChange){const encoded=JSON.stringify(s);const update=db().prepare('UPDATE learners SET data=?,revision=revision+1,updated_at=? WHERE user_id=? AND revision=?').bind(encoded,Date.now(),user.userId,revision);const condition='EXISTS (SELECT 1 FROM learners WHERE user_id=? AND revision=? AND data=?)';const change=portfolioChange.removeToken?db().prepare('DELETE FROM portfolios WHERE token=? AND user_id=? AND '+condition).bind(portfolioChange.removeToken,user.userId,user.userId,revision+1,encoded):db().prepare('INSERT INTO portfolios(token,user_id,data) SELECT ?,?,? WHERE '+condition+' ON CONFLICT(token) DO UPDATE SET data=excluded.data').bind(portfolioChange.token,user.userId,portfolioChange.data,user.userId,revision+1,encoded);const results=await db().batch([update,change]);if(!results[0].meta.changes)throw Object.assign(new Error('Your learning changed in another tab. Refresh and try again.'),{status:409});next=revision+1}else{next=await saveState(user.userId,s,revision)}return Response.json({state:s,revision:next,usage:await usage(user.userId,s)},{headers:{'Cache-Control':'no-store'}});
}catch(e){return errorResponse(e)}}

