import {categories,scenarios,caseById,initialScenarioRequest} from '../scenario-engine';
import type {GoalChoice,Setup} from './types';
export {categories};
const stop=new Set('a an the to i my our your we me in on of for and with make video videos record recording learn want need film filming create'.split(' '));
const vocabulary:Record<string,string>={daughter:'child school family dance',son:'child school family',relatives:'family memories',dance:'performance dance recital school event',school:'education school performance',return:'return proof condition damaged product',refund:'return proof damaged product',tenant:'tenant damage rental property',flat:'property real estate room',estate:'property real estate',wedding:'wedding ceremony',coach:'sports coaching analysis athlete training',player:'athlete performance sports',damage:'damage evidence condition',rented:'rental tenant room belongings',demonstration:'demo product explainer',lecture:'teacher education lecture',teacher:'education lesson',teach:'education lesson',ngo:'nonprofit fundraising appeal',recipe:'cooking recipe instructions',tutorial:'tutorial teaching steps',bug:'software bug screen recording',stream:'live streaming',livestream:'live streaming',vlog:'travel vlog',animation:'stop motion animation',stopmotion:'stop motion',drone:'aerial drone',parking:'parking location parked',grandmother:'family memories interview',repair:'repair documentation process',selling:'product commercial promotion',shop:'business product commercial',reel:'social content short',captions:'accessibility caption subtitles'};
const terms=(s:string)=>s.toLowerCase().replace(/['’]s\b/g,'').replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(x=>x.length>1&&!stop.has(x));
function intentBoost(query:string,c:any){const q=query.toLowerCase();let n=0;
 if(/damage|tenant|rented|rental|move.out|refund|return.*product/.test(q)){if(c.primary_archetype==='A02')n+=22;else n-=8;if(/rented|rental|move.out/.test(q)&&c.id==='C01-05')n+=15;if(/damage|leak/.test(q)&&c.id==='C01-07')n+=7;if(c.id==='C13-08')n+=/dispute|landlord/.test(q)?15:-10;}
 if(/sport|athlete|player|coach/.test(q)&&/technique|analys|training|form|coach/.test(q)){if(c.primary_archetype==='A04')n+=22;if(c.id==='C11-02')n+=15;}
 if(/product/.test(q)&&/demo|demonstr|explain/.test(q)&&c.id==='C07-02')n+=22;
 if(/daughter|son|school/.test(q)&&/dance|performance|recital/.test(q)&&c.id==='C01-03')n+=20;
 return n;
}
const stems=(s:string)=>new Set(terms(s).map(x=>x.replace(/(?:ing|ed|s)$/,'')));
export function suggestions(query:string,category='',limit=4){const original=terms(query),expanded=[...new Set(original.flatMap(x=>[x,...(vocabulary[x]||'').split(' ').filter(Boolean)]))];return scenarios.filter(c=>!category||c.category_id===category).map(c=>{const name=stems(String(c.source_text)),detail=stems([c.learner_outcome,c.archetype_name,c.category,c.audience].join(' '));let score=intentBoost(query,c);for(const x of expanded){const t=x.replace(/(?:ing|ed|s)$/,'');score+=(name.has(t)?(original.includes(x)?5:2):detail.has(t)?1:0);}return {caseId:c.id,name:c.source_text,category:c.category,categoryId:c.category_id,score}}).filter(x=>!query.trim()||x.score>0).sort((a,b)=>b.score-a.score||a.caseId.localeCompare(b.caseId)).slice(0,limit);}
export function classifyGoal(words:string,selectedCase?:string,clarification?:{subject:string;audience:string}):GoalChoice {if(typeof words!=='string'||words.trim().length<3||words.length>500)throw Error('Use 3–500 characters to describe your video.');const raw=words.trim(),rank=suggestions([raw,clarification?.subject||'',clarification?.audience||''].join(' '),'',4);if(selectedCase&&!caseById(selectedCase))throw Error('Choose an available video goal.');const exact=scenarios.find(c=>c.source_text.toLowerCase()===raw.toLowerCase());const top=rank[0],gap=top?top.score-(rank[1]?.score||0):0;const confidence=selectedCase||exact?1:!top?0:Math.min(.94,Math.round((.2+Math.min(.45,top.score/45)+Math.min(.25,gap/25))*100)/100);return {words:raw,caseId:selectedCase||exact?.id||top?.caseId||'C01-04',custom:!selectedCase&&!exact,confidence,candidates:rank.map(({caseId,name,score})=>({caseId,name,score})),...(clarification?{clarification}:{} )};}
export function defaultSetup(caseId:string):Setup {const r=initialScenarioRequest(caseId);return {gear:['phone'],hours:2,weeks:4,modality:'do',bandwidth:'standard',experience:'starting',name:'',device:'android',accessibility:[],audience:r.outcome.audience||'',structure:'guided',pace:'steady',feedback:'self',sequence:'plan_first',motivation:'finish_task',control:'controlled',orientation:'native',length:null,outdoor:false,authorised:false,localBackup:false,screenRecorder:true,specialist:false,spatial:false};}
export function validateSetup(raw:any,caseId:string):Setup {const d=defaultSetup(caseId),pick=(v:any,opts:any[],fallback:any)=>opts.includes(v)?v:fallback,txt=(v:any,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';const num=(v:any,min:number,max:number,fallback:number)=>Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max?Number(v):fallback;return {...d,gear:Array.isArray(raw?.gear)&&raw.gear.length?[...new Set<string>(raw.gear.filter((g:string)=>['phone','camera','computer','microphone','tripod','drone','360_camera','specialist_capture'].includes(g)))].length?[...new Set<string>(raw.gear.filter((g:string)=>['phone','camera','computer','microphone','tripod','drone','360_camera','specialist_capture'].includes(g)))]:d.gear:d.gear,hours:num(raw?.hours,.5,20,2),weeks:num(raw?.weeks,1,12,4),modality:pick(raw?.modality,['watch','read','do','discuss'],'do'),bandwidth:pick(raw?.bandwidth,['standard','low','offline','stable'],'standard'),experience:pick(raw?.experience,['starting','some','regular','advanced'],'starting'),name:txt(raw?.name,60),device:pick(raw?.device,['android','ios','desktop'],'android'),accessibility:Array.isArray(raw?.accessibility)?raw.accessibility.filter((s:string)=>['captions','descriptions','keyboard','large_text','reduced_motion'].includes(s)):[],audience:txt(raw?.audience),structure:pick(raw?.structure,['guided','open'],'guided'),pace:pick(raw?.pace,['gentle','steady','stretch'],'steady'),feedback:pick(raw?.feedback,['self','ai','peer','mentor'],'self'),sequence:pick(raw?.sequence,['plan_first','shoot_first'],'plan_first'),motivation:pick(raw?.motivation,['finish_task','build_confidence','improve_craft','career'],'finish_task'),control:pick(raw?.control,['controlled','uncontrolled','real_time','one_take'],'controlled'),orientation:pick(raw?.orientation,['native','portrait','landscape','square','spatial'],'native'),length:raw?.length==null?null:num(raw.length,1,14400,60),outdoor:raw?.outdoor===true,authorised:raw?.authorised===true,localBackup:raw?.localBackup===true,screenRecorder:raw?.screenRecorder!==false,specialist:raw?.specialist===true,spatial:raw?.spatial===true};}
