import raw from '../scenario-runtime.json';
import type {Item,Chapter} from './types';
export const chapters:{id:Chapter;name:string;cluster:string}[]=[{id:'story',name:'Story & intent',cluster:'story'},{id:'framing',name:'Framing',cluster:'camera'},{id:'light',name:'Light & exposure',cluster:'lighting'},{id:'sound',name:'Sound',cluster:'sound'},{id:'editing',name:'Editing & pacing',cluster:'editing'},{id:'delivery',name:'Delivery & sharing',cluster:'delivery'},{id:'ethics',name:'Consent & care',cluster:'ethics'},{id:'scenario',name:'Your real task',cluster:'workflow'}];
const bank:Item[]=[];
function q(chapter:Chapter,n:number,band:0|1|2,title:string,choices:string[],answer:number|string,explanation:string,extra:Partial<Item>={}){bank.push({id:chapter+'-'+n,chapter,band,title,choices,answer,explanation,kind:'choice',visual:chapter, ...extra});}
q('story',1,0,'What does this viewer need first?',['Where the action happens','Every setting on the camera','A long logo animation'],0,'Context helps a new viewer understand the action.',{context:'You are showing someone how to fold a paper box.'});
q('story',2,0,'Put a simple process in order.',['Show the materials','Show the important action','Show the result'],'012','A useful process connects materials, action and result.',{kind:'order',visual:'timeline'});
q('story',3,0,'Which opening makes a useful promise?',['Everything about cooking','How to fold this napkin in three steps','Wait until the end for a surprise'],1,'A specific promise tells the viewer what they can learn.' );
q('story',4,1,'Which view actually supports the repair story?',['View A','View B'],1,'The repaired seam is relevant visual evidence; an unrelated plant is not.',{kind:'image-pair',image:'story-medium',visual:undefined});
q('story',5,1,'You have room for one more shot. What is missing?',['Another pretty detail','The action connecting the start and result','A faster transition'],1,'A connecting action explains how the result happened.',{context:'Your sequence shows an empty mug, then a finished drink.'});
q('story',6,1,'Which is the more useful brief?',['Make it cinematic','Show a first-time buyer how this lid opens','Use every camera move'],1,'Audience and outcome guide decisions more clearly than a style adjective.' );
q('story',7,1,'What should an interview cut preserve?',['Only the most dramatic phrase','The speaker’s intended meaning and relevant context','The shortest possible sentence'],1,'Shortening should not distort the meaning of an answer.',{reason:true});
q('story',8,2,'A dramatic shot implies a cause you did not observe. What now?',['Use it because it is compelling','Cut it or clearly separate it from the factual claim','Add tense music'],1,'The edit must not create unsupported causation.',{reason:true});
q('story',9,2,'Two audiences need different explanations. How do you plan?',['One unexplained technical version for everyone','A common core with audience-specific context and delivery','Add all details to both versions'],1,'Keep the core meaning while adapting the needed context.' );
q('story',10,2,'Which test best checks whether the film communicates?',['Ask an unfamiliar viewer what they understood','Count the number of effects','Show it only to the person who wrote the script'],0,'An unfamiliar viewer can reveal missing context without your explanation.' );
q('framing',1,0,'Which notebook view would you keep?',['View A','View B'],1,'The simpler frame keeps the whole subject readable.',{kind:'image-pair',image:'frame-basic',visual:undefined});
q('framing',2,0,'Which frame shows the surroundings as well as the subject?',['Wide','Close detail','Extreme close-up'],0,'A wide view provides context.',{visual:'shot-size'});
q('framing',3,0,'The top of the subject is accidentally cut off. What helps?',['Step back or reframe safely','Use a louder soundtrack','Increase saturation'],0,'Check the edges and reframe before recording.' );
q('framing',4,1,'Which boat view leaves useful space in front?',['View A','View B'],1,'Space toward the bow gives the shape room to lead the eye.',{kind:'image-pair',image:'frame-medium',visual:undefined});
q('framing',5,1,'Which vase view needs its focus corrected?',['View A','View B'],0,'View A prioritises the background instead of the vase.',{kind:'image-pair',image:'focus-medium',visual:undefined});
q('framing',6,1,'Choose the camera that preserves screen direction.',['Camera 1: same side','Camera 2: opposite side','Either, with no establishing context'],0,'Staying on the same side keeps the subject relationship consistent.',{visual:'line'});
q('framing',7,1,'A caption will cover the bottom of a vertical video. Where should the key action sit?',['Under the caption','In the remaining clear area','Outside the frame'],1,'Compose for the usable area of the final delivery.',{visual:'safe-area'});
q('framing',8,2,'Tap the area that competes with the pencil cup.',['Bright wall patch in A','Pencil cup in A','Empty space in B'],0,'The bright wall patch pulls attention away from the intended subject.',{kind:'hotspot',image:'frame-advanced',visual:undefined,config:{hotspots:[{x:28,y:20},{x:14,y:65},{x:80,y:20}]}});
q('framing',9,2,'You must cross the line of action. What makes the change clearer?',['A motivated visible move or a re-establishing wide shot','An unrelated close-up every time','A random jump cut'],0,'A clear spatial bridge can orient the viewer across the line.',{visual:'line',reason:true});
q('framing',10,2,'One camera must cover an unrepeatable action. What takes priority?',['A reliable view that keeps the essential action in frame','Repeatedly chase close-ups','Rotate the phone during the action'],0,'Reliable coverage protects the moment before optional detail.' );
q('light',1,0,'Which spoon view lets you read its texture?',['View A','View B'],1,'Readable light reveals texture without requiring expensive gear.',{kind:'image-pair',image:'light-basic',visual:undefined});
q('light',2,0,'The face is dark against a bright window. What is a practical first move?',['Turn toward gentler window light','Add a strong colour filter','Ignore the face'],0,'Changing the relation to the light can make the subject readable.',{visual:'light-direction'});
q('light',3,0,'What does locking exposure help prevent?',['Unwanted brightness changes during a shot','All camera shake','Every focus error'],0,'Exposure lock prevents automatic brightness changes within its limits.',{visual:'exposure'});
q('light',4,1,'Which linen view has lost highlight detail?',['View A','View B'],0,'View A is too bright to retain the fabric texture.',{kind:'image-pair',image:'light-medium',visual:undefined});
q('light',5,1,'At 25 fps, which shutter is a common starting point for natural motion blur?',['1/50 second','1/2000 second','2 seconds'],0,'Around 1/50 second is a common 25 fps starting point; creative intent and flicker can require changes.',{kind:'settings',visual:'camera-settings'});
q('light',6,1,'ISO doubles from 400 to 800. Which change roughly restores brightness?',['Change 1/50 to 1/100 second','Change 1/50 to 1/25 second','Double ISO again'],0,'Halving exposure time offsets a one-stop ISO increase, with a motion-blur trade-off.',{kind:'settings',visual:'camera-settings'});
q('light',7,1,'A white surface looks orange under a warm lamp. What should you check?',['White balance against a known neutral reference','Only the file name','Only the audio level'],0,'White balance and light sources affect neutral colours.',{visual:'colour'});
q('light',8,2,'Which tumbler setup would you correct before trying to match colour?',['View A','View B'],0,'Mixed sources create different casts that a single global correction may not remove.',{kind:'image-pair',image:'light-advanced',visual:undefined});
q('light',9,2,'Low light, moving subject, no extra lamp. What is the honest trade-off?',['Raise ISO if needed and accept noise to preserve usable motion','A slow shutter always fixes everything','Every phone can open its aperture'],0,'A usable noisy image may serve the task better than unintended motion blur; available controls differ.',{kind:'settings',visual:'camera-settings',reason:true});
q('light',10,2,'Bright highlights are clipped in the original. What can a colour grade recover?',['The missing detail completely','Only detail actually recorded; reshoot or accept the limit','Unlimited highlight information'],1,'A grade cannot recover information that the recording never captured.',{visual:'histogram'});
q('sound',1,0,'Where should a permitted microphone usually start for clearer speech?',['Closer to the speaker, outside the picture if needed','At the far end of a noisy room','Behind a running fan'],0,'A useful voice-to-noise relationship begins at capture.',{visual:'mic-distance'});
q('sound',2,0,'What should you do before an important take?',['Record and listen to a short test','Trust only the moving level bars','Add music first'],0,'A short playback can reveal noise, distortion and missing sound.',{visual:'levels'});
q('sound',3,0,'The meter stays at the red limit. What is the safer next step?',['Lower the recording gain and retest','Increase gain','Fix every overload later'],0,'Clipping can destroy information; set levels with room for louder peaks.',{visual:'levels'});
q('sound',4,1,'Which sample keeps the taps clearer against the background?',['Sample A','Sample B'],0,'Sample A has a cleaner separation between the useful signal and background noise.',{kind:'audio',audio:'taps',visual:'waveform'});
q('sound',5,1,'Why record room tone?',['To help maintain a consistent background across edits','To replace every spoken word','To prove consent'],0,'Room tone can smooth audio edits when recorded under matching conditions.',{visual:'waveform'});
q('sound',6,1,'A voice is clear until music begins. What should you try first?',['Reduce or shape the music under speech','Boost everything equally','Delete the captions'],0,'Balance competing sound so the intended meaning remains clear.',{visual:'mixer'});
q('sound',7,1,'One channel is missing from a stereo test. What next?',['Check routing and connectors, then replay both channels','Assume the missing channel will return on export','Turn up the other channel until it clips'],0,'Confirm the signal path before an important recording.',{visual:'mixer'});
q('sound',8,2,'Which sample has the flattened, distorted peaks?',['Sample A','Sample B'],1,'The deliberately clipped sample loses the original peak shape.',{kind:'audio',audio:'peaks',visual:'waveform'});
q('sound',9,2,'You record 25 fps picture and separate audio. What protects a long take?',['A sync reference and a drift check across the recording','Only line up the first frame and assume the rest','Change random sample rates until it looks right'],0,'A beginning sync alone does not establish end-to-end synchronisation.',{visual:'timeline',reason:true});
q('sound',10,2,'Heavy noise reduction makes words watery. What is the better decision?',['Back off, compare intelligibility and consider a permitted re-record','Keep processing until all ambience vanishes','Hide the problem with loud music'],0,'Repair decisions should preserve meaning rather than maximise processing.',{visual:'waveform'});
q('editing',1,0,'Arrange these actions into a readable process.',['Pick up paper','Fold the paper','Show the finished fold'],'012','The order connects setup, action and result.',{kind:'order',visual:'timeline'});
q('editing',2,0,'The timeline has an unintended empty gap. What will you check?',['The edit and exported playback around that gap','Only the title font','Only the cover image'],0,'A gap can produce unwanted silence or black frames.',{visual:'timeline'});
q('editing',3,0,'Two shots say exactly the same thing. What helps the edit?',['Keep the clearer shot unless repetition has a purpose','Always keep both','Add a transition between every frame'],0,'Each shot should contribute something useful.',{visual:'timeline'});
q('editing',4,1,'Which sequence gives context before detail?',['Wide view','Hands performing the action','Result close-up'],'012','Context first helps the viewer place the detail.',{kind:'order',visual:'timeline'});
q('editing',5,1,'A cut feels late. How should you evaluate a revision?',['Compare versions around the intended action and meaning','Make every shot the same length','Choose the loudest effect'],0,'Pacing follows information, action and feeling, not a fixed cut interval.',{visual:'timeline'});
q('editing',6,1,'What is an audio bridge useful for?',['Carrying sound across a cut to connect related shots','Making every shot louder','Repairing all missing footage'],0,'An audio bridge can link related moments without requiring identical visuals.',{visual:'timeline'});
q('editing',7,1,'Which version is safest to label as a revision?',['Keep the original and save a clearly named new version','Overwrite the only original','Rename all files at random'],0,'Versioning keeps a recoverable comparison.',{visual:'archive'});
q('editing',8,2,'Put a useful finishing check in order.',['Review the full assembly','Fix the highest-impact issue','Export and check outside the editor'],'012','Fix meaning and continuity, then verify the delivered file.',{kind:'order',visual:'timeline',reason:true});
q('editing',9,2,'A reaction shot was filmed at another time. What matters in a factual edit?',['Do not imply a reaction or event that did not occur','Any reaction is fine if it looks convincing','Only match the colour'],0,'Temporal rearrangement must not misrepresent what happened.',{visual:'timeline'});
q('editing',10,2,'A fast cut hides the only view of a critical step. What takes priority?',['Let that step remain understandable','Always cut on the music beat','Add motion blur'],0,'Comprehension can matter more than a rhythmic effect.',{visual:'timeline'});
q('delivery',1,0,'Which export matches a vertical 9:16 brief?',['1080 × 1920','1920 × 1080','1080 × 1080'],0,'Width comes first in these dimensions.',{kind:'settings',visual:'export'});
q('delivery',2,0,'When should you check the exported file?',['Before sending, on the intended type of device','Only inside the editor','Only if someone complains'],0,'An export can differ from the editor preview.',{visual:'export'});
q('delivery',3,0,'Who should be able to open a private family video?',['Only the agreed viewers through appropriate access settings','Everyone by default','Anyone who finds a public search result'],0,'Match distribution to the agreed audience.',{visual:'privacy'});
q('delivery',4,1,'Your viewer has limited mobile data. Which handoff is useful?',['A tested smaller viewing copy plus required captions','Only the largest master file','A link with no permission to open it'],0,'Keep the master separately and give the recipient a usable access copy.',{visual:'export'});
q('delivery',5,1,'Which caption is easier to read in two seconds?',['Add flour. Mix gently.','Add all of the flour and begin mixing the ingredients together very gently for a while.','No caption, even when essential meaning is spoken'],0,'Short, accurate captions reduce reading pressure.',{kind:'caption',visual:'caption'});
q('delivery',6,1,'The recipient cannot open your link. What should you check?',['Their access permission and a logged-out or separate-account test','Only your own signed-in view','The background colour of the player'],0,'Your own access does not prove recipient access.',{visual:'privacy'});
q('delivery',7,1,'Which export choice should drive your format?',['The recipient’s actual specification and a playback test','The largest numbers in every menu','The format used in an unrelated tutorial'],0,'Delivery depends on the receiving system and use.',{kind:'settings',visual:'export'});
q('delivery',8,2,'How do you handle a cropped social copy of factual footage?',['Keep the untouched original and label the cropped sharing copy','Replace the original with the crop','Claim no context was removed without checking'],0,'A derivative should not replace its factual source.',{visual:'archive',reason:true});
q('delivery',9,2,'A caption contains the wrong name. What is the best check?',['Verify the spelling and timing against the source','Trust automatic captions completely','Remove all captions'],0,'Automatic text needs review for names, meaning and timing.',{kind:'caption',visual:'caption'});
q('delivery',10,2,'What makes an archive copy useful later?',['Verified copies, source context and a retrieval test','Only a file called final-final-new','Only a public social upload'],0,'Preservation includes context, integrity and the ability to retrieve.',{visual:'archive'});
q('ethics',1,0,'Before filming an identifiable person, what should you clarify?',['Permission, purpose and intended sharing','Only their favourite colour','Nothing if the camera is small'],0,'Recording and sharing choices should be clear before capture.',{visual:'consent'});
q('ethics',2,0,'What should stay out of a screen-recording practice sample?',['Real passwords, notifications and private records','Fictional demonstration data','A visible pointer'],0,'Use dummy data and remove private details before recording.',{visual:'privacy'});
q('ethics',3,0,'Can a popular music track be used just because it is online?',['No; check the rights and intended use','Yes, every online track is free','Yes, if the volume is low'],0,'Availability online does not grant permission for reuse.',{visual:'consent'});
q('ethics',4,1,'A school permits filming but has not permitted public sharing. What do you do?',['Clarify sharing permission and keep within the agreed audience','Post it publicly immediately','Assume every parent agreed'],0,'Permission to record does not automatically cover wider publication.',{visual:'privacy'});
q('ethics',5,1,'Someone asks not to be included. What should your plan do?',['Respect the boundary and choose a permitted framing or stand-in','Record secretly','Promise to fix it without a workable plan'],0,'A permission boundary needs an actual capture and sharing decision.',{visual:'consent'});
q('ethics',6,1,'You are practising a tenant damage record. What can a course score establish?',['A practice result, not legal validity','Guaranteed legal admissibility','Who is liable'],0,'The course teaches documentation practice, not legal conclusions.',{visual:'archive'});
q('ethics',7,1,'Which sample is appropriate to upload for learning?',['An owned object with no private details','A patient record','An identifiable child without the required permissions'],0,'Use non-sensitive practice material. Keep real sensitive cases off the learning site.',{visual:'privacy'});
q('ethics',8,2,'A contributor agreed to one use. A new use appears later. What is needed?',['Check the agreed scope and seek any additional permission needed','Treat the first agreement as unlimited','Remove their name and assume all uses are allowed'],0,'Purpose and reuse limits matter even when material already exists.',{visual:'consent',reason:true});
q('ethics',9,2,'A technical video looks convincing. Who should validate real safety-critical use?',['The responsible qualified professional','Only the course scoring system','Anyone who likes the colour grade'],0,'A learning assessment cannot authorise safety-critical practice.',{visual:'consent'});
q('ethics',10,2,'A synthetic voice resembles a real person. What must be considered?',['Explicit permission for that use and clear labelling','Only whether it sounds natural','No permission if the clip is short'],0,'Synthetic likeness and voice raise separate permission and disclosure decisions.',{visual:'consent'});

// Ten contextual items per need archetype; reusable rules compose them with the learner's own task.
const scenarioDetails:Record<string,{essential:string;wrong:string;test:string;risk:string;source:string}>={
 A01:{essential:'preserve the recognisable moment and its context',wrong:'replace the moment with unrelated dramatic footage',test:'ask the intended family viewer what they recognise',risk:'sharing a private moment beyond the agreed audience',source:'an original with date, context and agreed access'},
 A02:{essential:'keep factual context and an untouched original',wrong:'remove inconvenient context to make the claim stronger',test:'check whether a separate viewer can understand what was actually observed',risk:'mistaking a practice score for legal validity',source:'the untouched source plus a labelled sharing copy'},
 A03:{essential:'show the steps and the details needed to repeat them',wrong:'hide the difficult step behind a fast montage',test:'ask someone to follow the sequence without extra explanation',risk:'omitting a critical step or safety boundary',source:'the complete process and a clearly labelled short guide'},
 A04:{essential:'keep a stable repeatable view of the whole movement',wrong:'change the angle and zoom continuously during the comparison',test:'compare the same movement phase from consistent views',risk:'claiming a clinical or performance diagnosis from uncalibrated footage',source:'the full movement and separately labelled analysis notes'},
 A05:{essential:'secure permitted reliable coverage of the unrepeatable action',wrong:'stop recording the main action to chase optional details',test:'rehearse power, storage, sound and a fallback before the event',risk:'missing an unrepeatable moment or filming outside permission',source:'continuous essential coverage and backed-up originals'},
 A06:{essential:'preserve the speaker’s meaning and agreed boundaries',wrong:'assemble words into a statement the speaker did not make',test:'check the excerpt against the complete answer',risk:'revealing private details or misrepresenting a contributor',source:'the full permitted answer and consent scope'},
 A07:{essential:'make deliberate visual choices that serve the intended feeling',wrong:'add every effect regardless of the story',test:'compare what a new viewer feels and understands',risk:'confusing attractive images with a coherent piece',source:'the working project and a versioned final master'},
 A08:{essential:'show a place clearly while respecting people and access',wrong:'enter a restricted area for a better angle',test:'ask whether the shots convey both location and distinctive detail',risk:'harm to a place, wildlife or people for a shot',source:'location context and permitted original footage'},
 A09:{essential:'deliver a useful promise to the intended viewer',wrong:'use a misleading hook that the video never answers',test:'check the opening promise against the actual result',risk:'misleading claims or inaccessible text on a phone',source:'a clean master, captions and platform-specific access copies'},
 A10:{essential:'support a truthful claim with visible product evidence',wrong:'imply a benefit that the demonstration does not show',test:'check that the viewer can see the claim being demonstrated',risk:'misleading a buyer or using material without rights',source:'the original demonstration and approved claims or disclosures'},
 A11:{essential:'teach one clear objective in manageable steps',wrong:'pack unrelated objectives into one uninterrupted lecture',test:'give the learner one small task to check understanding',risk:'unreadable information or excluding learners who need alternatives',source:'a reusable teaching master with corrected captions and context'},
 A12:{essential:'show a readable reproducible screen sequence using dummy data',wrong:'record a real account with private notifications visible',test:'repeat the steps and check text on the receiving device',risk:'exposing credentials, messages or confidential records',source:'a privacy-checked capture and a reproducible step log'},
 A13:{essential:'test the experience at the receiving end and plan a fallback',wrong:'assume a good local preview guarantees a good stream',test:'rehearse sound, sync, connection loss and a permitted local recording',risk:'losing the live experience without a backup',source:'the rehearsal notes and permitted local backup'},
 A14:{essential:'separate observed facts, accounts and uncertainty',wrong:'present an unverified account as a recorded fact',test:'trace each claim to a source and retain relevant context',risk:'harm from misinformation or exposing a vulnerable source',source:'original recordings, provenance and restricted source notes'},
 A15:{essential:'record a repeatable setup, timing, scale and limits',wrong:'infer exact measurements from an uncalibrated attractive image',test:'have the responsible technical team check the method and reference',risk:'treating a recording as validated scientific or safety evidence',source:'original data, calibration context and an uncertainty log'},
 A16:{essential:'keep originals, provenance and retrievable access copies',wrong:'overwrite the only source with a compressed upload',test:'verify a separate copy and actually retrieve a sample',risk:'irreversible loss or undocumented alteration',source:'the preserved original, a manifest and verified separate copies'},
 A17:{essential:'plan a safe authorised capture and rehearse on the ground',wrong:'fly first and assume the location permits it',test:'check current authoritative permissions, operator limits and a ground plan',risk:'unsafe or unauthorised flight',source:'the authorised capture plan, context and permitted originals'},
 A18:{essential:'match the target geometry, device and technical pipeline',wrong:'assume a flat MP4 is suitable for every spatial display',test:'check a small sample with the receiving operator and target device',risk:'misalignment, discomfort or unsupported technical claims',source:'pipeline specifications, references and tested source assets'},
 A19:{essential:'control framing, lighting and the change between frames',wrong:'move the camera and exposure randomly between frames',test:'play a short frame-counted sample at the intended rate',risk:'flicker, drift and an unusable long capture',source:'the original frame sequence and timing/settings log'},
 A20:{essential:'preserve meaning in the required accessible form',wrong:'assume automatic captions or a visual-only version meet every need',test:'have an appropriate user or reviewer check meaning and access',risk:'excluding the intended audience or mistranslating meaning',source:'the checked access versions and their source context'}
};
for(const [archetype,d] of Object.entries(scenarioDetails)){const name=(raw.archetypes as any)[archetype].name;
 const templates:{band:0|1|2;title:string;choices:string[];answer:number;reason?:boolean}[]=[
 {band:0,title:'What is the essential job of this video?',choices:[d.essential,'Use the most expensive available camera','Use every effect'],answer:0},
 {band:0,title:'Which action should you avoid?',choices:[d.wrong,'Make a harmless permitted rehearsal','Check the result with the intended viewer'],answer:0},
 {band:0,title:'What should you confirm before recording?',choices:['Purpose, audience and permission','Only the opening font','Nothing if it is a short clip'],answer:0},
 {band:1,title:'Which test best fits your task?',choices:['Count how many transitions you used',d.test,'Check only the file size'],answer:1},
 {band:1,title:'Which risk matters most for this route?',choices:['Using a plain title',d.risk,'Keeping a short practice log'],answer:1},
 {band:1,title:'What should you retain for a useful handoff?',choices:['Only a compressed social copy',d.source,'Only a screenshot of the editor'],answer:1},
 {band:1,title:'Your time is cut in half. What do you protect first?',choices:['The essential outcome and its safety/permission checks','Optional decorative shots before the essential task','Every planned effect'],answer:0},
 {band:2,title:'Your result looks polished but the key test fails. What now?',choices:['Revise the part that fails the task and retest','Publish because it looks professional','Hide the failing part without explaining the limit'],answer:0,reason:true},
 {band:2,title:'A real setting is outside your equipment or permissions. What is a valid learning outcome?',choices:['A labelled safe rehearsal with the untested limits recorded','A claim of full real-world readiness','An unapproved attempt in the real setting'],answer:0},
 {band:2,title:'How should you choose the next improvement?',choices:['Compare specific evidence against the task, then test one change','Buy new equipment without testing the current limit','Copy an unrelated cinematic example'],answer:0}];
 templates.forEach((t,i)=>bank.push({id:'scenario-'+archetype+'-'+(i+1),chapter:'scenario',band:t.band,title:t.title,context:name,kind:'choice',choices:t.choices,answer:t.answer,explanation:'This route should '+d.essential+'. A useful check is to '+d.test+'.',visual:'scenario',reason:t.reason,config:{archetype,essential:d.essential}}));
}
export const questionBank=bank;
export const itemById=(id:string)=>bank.find(q=>q.id===id);
export function itemsFor(chapter:Chapter,archetype:string){return bank.filter(q=>q.chapter===chapter&&(chapter!=='scenario'||q.id.startsWith('scenario-'+archetype+'-')));}
