import {getUser} from '../user';
import {db,readState,saveState} from '../service';
import {profileFor,planFor} from './assessment';
import type {Attempt} from './types';
export const cookieName='fp_onboarding';
async function digest(t:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function onboardingContext(req:Request){const user=await getUser(),raw=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.split('=')[1],token=raw&&/^[a-f0-9]{64}$/.test(raw)?raw:crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),hash=await digest(token);const row:any=user?await db().prepare('SELECT * FROM onboarding_attempts WHERE user_id=? OR (guest_hash=? AND user_id IS NULL) ORDER BY updated_at DESC LIMIT 1').bind(user.userId,hash).first():await db().prepare('SELECT * FROM onboarding_attempts WHERE guest_hash=? AND user_id IS NULL ORDER BY updated_at DESC LIMIT 1').bind(hash).first();return {user,token,hash,row};}
export async function syncProfile(userId:string,a:Attempt){const {state:s,revision}=await readState(userId);if(s.profile?.attemptId===a.id&&s.profile?.updatedAt===a.updatedAt)return;const plan=planFor(a);if(s.profile)s.profileHistory=[...(s.profileHistory||[]),{savedAt:new Date().toISOString(),profile:s.profile}];if(s.profile&&!s.trialPathIds)s.trialPathIds=['basic-w1','basic-w2'];s.profile=profileFor(a);s.personalPlan=plan;s.onboardingMode={mode:a.mode,mentorId:a.mentorId||null,callPreference:a.callPreference||null,shareConsentAt:a.shareConsentAt||null,simulated:a.mode==='mentor'};s.trialPathIds=s.trialPathIds||plan.paths.slice(0,2).map((p:any)=>p.id);if(s.trialPathIds.length===1)s.trialPathIds.push('need-'+a.goal.caseId.toLowerCase()+'-prepare');try{await saveState(userId,s,revision)}catch(e:any){if(e?.status!==409)throw e;const latest=await readState(userId);if(latest.state.profile?.attemptId!==a.id||latest.state.profile?.updatedAt!==a.updatedAt)throw e;}}

export async function adoptReadyOnboarding(req:Request){const c=await onboardingContext(req);if(!c.user||!c.row)return;const a:Attempt=JSON.parse(c.row.data);if(a.status!=='ready')return;if(!c.row.user_id){const claim=await db().prepare('UPDATE onboarding_attempts SET user_id=? WHERE id=? AND user_id IS NULL AND guest_hash=?').bind(c.user.userId,c.row.id,c.hash).run();if(!claim.meta.changes){const row:any=await db().prepare('SELECT user_id FROM onboarding_attempts WHERE id=?').bind(c.row.id).first();if(row?.user_id!==c.user.userId)return;}await db().prepare('UPDATE goal_logs SET user_id=? WHERE attempt_id=? AND user_id IS NULL').bind(c.user.userId,c.row.id).run();}await syncProfile(c.user.userId,a);}

