'use client';
import React,{useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {useLearning} from '../ui';
export default function StillFeedback({lessonKey}:{lessonKey:string}){const {user,mutate}=useLearning(),[file,setFile]=useState<File|null>(null),[consent,setConsent]=useState(false),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<any>(null),[credits,setCredits]=useState<any>(null),[uploaded,setUploaded]=useState<any>(null);const requestId=useRef('');
 async function load(){if(!user)return;try{const r=await fetch('/api/review?key='+encodeURIComponent(lessonKey)),d:any=await r.json();if(!r.ok)throw Error(d.error);setCredits(d.allowance);if(d.reviews?.[0])setReview(d.reviews[0].review);}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[user,lessonKey]);
 async function submit(){if(busy)return;setError('');setBusy(true);try{if(!file||!consent)throw Error('Choose one permitted image and agree to send it for checking.');if(!navigator.onLine)throw Error('Reconnect before uploading. Your file stays on your device.');let image=uploaded;if(!image){const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name),'X-File-Size':String(file.size),'X-Content-Declaration':'non-sensitive-practice-v1','X-Screening-Consent':'yes','X-Lesson-Key':lessonKey},body:file,signal:AbortSignal.timeout(60000)});image=await r.json();if(!r.ok)throw Error(image.error);setUploaded(image);}if(!await mutate('assignment_save',{key:lessonKey,notes,uploadId:image.id}))throw Error('Your draft could not save. Retry before asking for feedback.');requestId.current=requestId.current||crypto.randomUUID();const r=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonKey,notes,uploadId:image.id,requestId:requestId.current}),signal:AbortSignal.timeout(60000)}),d:any=await r.json();if(!r.ok){requestId.current='';throw Error(d.error);}setReview(d.review);setCredits(d.allowance);}catch(e:any){setError(e.name==='TimeoutError'?'The check is taking longer than expected. Reload saved feedback before retrying; your draft may already be saved.':e.message||'Feedback is unavailable. Your learning can continue.');}finally{setBusy(false)}}
 return <div className="ob-still-feedback"><p>Optional feedback on your first practice still. This does not change your diagnostic score. AI can read your notes and one image; it cannot hear sound, watch video or verify consent.</p>{!user?<a href="/auth/google?return_to=%2Fworkspace">Sign in to attach a still privately</a>:<><label>One JPG, PNG or WebP · up to 5 MB<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];setError('');setUploaded(null);setReview(null);requestId.current='';if(f&&(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)){setFile(null);setError('Use one JPG, PNG or WebP under 5 MB.');e.target.value='';}else setFile(f||null)}}/></label><label className="ob-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>This shows my objects or consenting adults, with no children, sensitive records or private details. I agree to send this image and my notes to OpenAI for screening and feedback.</label><a href="/safety">Check consent & safety</a><label>What were you trying, and what did you notice?<textarea rows={3} value={notes} maxLength={4000} onChange={e=>{setNotes(e.target.value);requestId.current=''}}/></label>{credits&&<p className="small">AI helpers: {Math.max(0,(credits.limit||0)-(credits.used||0))} left for this practice.</p>}<Button disabled={busy||!file||!consent||notes.trim().length<20} onClick={submit}>{busy?'Checking your still…':'Get feedback on this still'}</Button><p className="small">Uses the existing practice feedback access. A failed AI call uses no feedback credit. Your original file is kept private; no mentor receives it.</p></>}{error&&<p role="alert" className="notice error">{error}</p>}{review&&<div className="ob-feedback"><h3>Your first look</h3>{['summary','strength','improvement','nextStep','evidenceLimit'].map(k=>review[k]&&<p key={k}>{review[k]}</p>)}<p className="small">Saved with this practice assignment.</p></div>}</div>}
