'use client';
import React from 'react';
import registry from '../../media/onboarding-display.json';
import type {PublicItem} from './types';
export function QuestionVisual({item,onPick,selected}:{item:PublicItem;onPick?:(v:number)=>void;selected?:number|string|null}){
 if(item.image){const a=registry.assets.find(a=>a.id==='fp-diagnostic-'+item.image)!;return <figure className="ob-comparison"><div className="ob-hotspot-image"><img src={a.canonicalUrl} srcSet={a.renditions.map(r=>r.src+' '+r.width+'w').join(',')} sizes="(max-width: 700px) 92vw, 760px" width="1440" height="720" alt={a.alt} loading="lazy" decoding="async"/>{item.kind==='hotspot'&&item.config?.hotspots?.map((h:any,i:number)=><button key={i} className={selected===i?'selected':''} style={{left:h.x+'%',top:h.y+'%'}} aria-label={'Mark: '+item.choices[i]} aria-pressed={selected===i} onClick={()=>onPick?.(i)}>{i+1}</button>)}</div><div className="ob-image-labels"><span>View A</span><span>View B</span></div><figcaption>Original illustrative comparison · Framepath / OpenAI</figcaption></figure>}
 if(item.audio)return <div className="ob-audio"><p>Listen at a comfortable volume. Synthetic examples; no speech.</p>{['a','b'].map(v=><label key={v}>Clip {v.toUpperCase()}<audio controls preload="none" src={'/onboarding/'+item.audio+'-'+v+'.wav'}/></label>)}<p className="small">Cannot hear the clips? Skip this check; it will stay unassessed.</p></div>;
 const visual=item.visual||item.chapter;
 if(['line','shot-size','safe-area','light-direction','mic-distance'].includes(visual))return <svg className="ob-diagram" viewBox="0 0 660 200" role="img" aria-label={visual==='line'?'Two subjects facing each other across a line, with camera positions on both sides.':visual==='safe-area'?'A vertical delivery frame with three marked zones: A at the top, B in the centre, C at the bottom.':'A filming setup with the subject in a frame, camera and surrounding space.'}><rect x="30" y="15" width="600" height="170" rx="14" fill="#182e31" stroke="#73928c"/><path d="M230 30V170M430 30V170M45 72H615M45 128H615" stroke="#496461" strokeDasharray="4 5"/>{visual==='line'?<><circle cx="220" cy="100" r="20" fill="#d9e5b8"/><circle cx="435" cy="100" r="20" fill="#d9e5b8"/><path d="M170 100H485" stroke="#efb48e" strokeWidth="3"/><text x="290" y="64">Camera A</text><text x="290" y="160">Camera B</text></>:visual==='safe-area'?<><rect x="278" y="20" width="105" height="160" fill="none" stroke="#d9e5b8"/>{['A','B','C'].map((s,i)=><text key={s} x="330" y={48+i*55} textAnchor="middle">{s}</text>)}</>:<><circle cx="330" cy="72" r="22" fill="#d9e5b8"/><path d="M285 152Q290 94 330 100Q370 94 375 152" fill="#d9e5b8"/><text x="70" y="48">FRAME</text><text x="450" y="162">CHECK THE EDGES</text></>}</svg>;
 if(visual==='camera-settings')return <div className="ob-camera-ui" role="img" aria-label="Camera settings panel. 25 frames per second. Compare shutter duration, sensitivity and motion."><span>VIDEO · MANUAL</span><div><b>25 <small>FPS</small></b><b>{item.id==='light-6'?'400 → 800':'400'} <small>ISO</small></b><b>1/50 <small>SHUTTER</small></b></div><p>Settings interact. Make a choice for the situation above.</p></div>;
 if(['exposure','histogram','levels','mixer','colour'].includes(visual))return <div className="ob-instrument" role="img" aria-label={'Camera monitor illustration for '+item.title}><div className="ob-monitor-bars">{Array.from({length:20},(_,i)=><i key={i} style={{height:(12+((i*17+item.band*13)%65))+'%'}}/>)}</div><div className="ob-instrument-labels"><span>Shadows</span><span>Midtones</span><span>Highlights</span></div><small>Concept diagram · compare the choices below</small></div>;
 if(['timeline','editing','waveform'].includes(visual))return <div className="ob-timeline" role="img" aria-label="Three shots in a timeline with a separate sound track."><div>{['01 · Context','02 · Action','03 · Result'].map((s,i)=><span key={s} style={{flex:i===1?2:1}}>{s}</span>)}</div><div className="ob-soundtrack">{Array.from({length:50},(_,i)=><i key={i} style={{height:6+(i*19)%30}}/>)}</div></div>;
 // A compact brief diagram visualises the actual constraints; this is not a stock picture.
 return <div className={'ob-brief ob-brief-'+item.chapter}><span className="ob-brief-number">{item.chapter==='scenario'?'YOUR VIDEO':item.chapter.toUpperCase()}</span><strong>{item.context||item.title}</strong><div aria-hidden="true"><i/><b>→</b><i/><b>→</b><i/></div><small>{item.chapter==='ethics'?'People → permission → audience':item.chapter==='delivery'?'Source → export → viewer':item.chapter==='story'?'Intent → action → result':'Notice the constraint. Choose a useful next move.'}</small></div>
}
export function SkillRadar({skills}:{skills:any}){const entries=Object.entries(skills||{}) as [string,any][],point=(i:number,v:number)=>{const angle=i*Math.PI*2/Math.max(1,entries.length)-Math.PI/2;return [150+Math.cos(angle)*v*24,140+Math.sin(angle)*v*24]};return <svg className="ob-radar" viewBox="0 0 300 285" role="img" aria-label={entries.map(([k,s])=>k+': '+s.label).join('; ')}>{[1,2,3,4].map(v=><polygon key={v} points={entries.map((_,i)=>point(i,v).join(',')).join(' ')} fill="none" stroke="#47635d"/>)}<polygon points={entries.map(([,s],i)=>point(i,s.value??0).join(',')).join(' ')} fill="#cddfa847" stroke="#d9e5b8" strokeWidth="2"/>{entries.map(([k,s],i)=>{const [x,y]=point(i,5);return <text key={k} x={x} y={y} textAnchor="middle" fontSize="11" fill="#dce4dd">{k==='framing'?'Frame':k==='scenario'?'Task':k.charAt(0).toUpperCase()+k.slice(1)}</text>})}</svg>}
