import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import path from 'node:path';import fs from 'node:fs';
const require=createRequire(import.meta.url),load=require('../scripts/lib/load-source.cjs'),root=path.resolve('.');
const {questionBank,chapters,itemsFor,itemById}=load(path.join(root,'app/onboarding/question-bank.ts')),{classifyGoal,defaultSetup,suggestions,categories}=load(path.join(root,'app/onboarding/goals.ts')),{assess,commitAnswer,planFor}=load(path.join(root,'app/onboarding/assessment.ts'));
function attempt(words="record my daughter's school dance for relatives"){const goal=classifyGoal(words);return {version:'onboarding-v2',id:'test',revision:0,goal,setup:defaultSetup(goal.caseId),setupStep:6,answers:[],status:'questions',firstFrame:{note:'I moved a distracting object.',made:true},startedAt:'2026-10-07T00:00:00Z',updatedAt:'2026-10-07T00:00:00Z',overrides:{},mode:'self'};}
function complete(mode,words){const a=attempt(words);for(let n=0;n<22;n++){const r=assess(a);if(r.complete)break;const i=itemById(r.next.id),v=mode==='skip'?null:mode==='right'?i.answer:mode==='medium'?(i.band===2?(i.kind==='order'?'210':(Number(i.answer)+1)%i.choices.length):i.answer):i.kind==='order'?'210':(Number(i.answer)+1)%i.choices.length;a.answers.push(commitAnswer(a,{itemId:i.id,value:v,confidence:2,rationale:'The viewer needs this detail.'}));}return a;}
test('eight chapters each have at least ten items across three bands',()=>{assert.equal(chapters.length,8);for(const ch of chapters)for(const a of ch.id==='scenario'?Array.from({length:20},(_,i)=>'A'+String(i+1).padStart(2,'0')):['A01']){const bank=itemsFor(ch.id,a);assert.ok(bank.length>=10);assert.equal(new Set(bank.map(x=>x.band)).size,3);}assert.equal(new Set(questionBank.map(i=>i.id)).size,questionBank.length)});
test('all categories reachable and own school-dance goal retained',()=>{assert.equal(categories.length,18);for(const c of categories)assert.ok(suggestions('',c.id,4).length);const g=classifyGoal("record my daughter's school dance for relatives");assert.equal(g.words,"record my daughter's school dance for relatives");assert.equal(g.custom,true);assert.equal(g.caseId,'C01-03');assert.ok(classifyGoal('zorbles and flurbs').confidence<.65)});
test('adaptive checks reach Basic, Medium and Advanced',()=>{assert.equal(assess(complete('wrong')).label,'Basic');assert.equal(assess(complete('medium')).label,'Medium');assert.equal(assess(complete('right')).label,'Advanced')});
test('skips stay unassessed; 24–28 total steps and no repeated items',()=>{for(const mode of ['right','wrong','medium','skip']){const a=complete(mode);assert.ok(a.answers.length>=18&&a.answers.length<=22);assert.equal(new Set(a.answers.map(x=>x.itemId)).size,a.answers.length);assert.equal(assess(a).complete,true)}assert.ok(Object.values(assess(complete('skip')).skills).every(x=>x.value===null))});
test('public item does not expose answer; selecting without committing cannot move meter',()=>{const a=attempt(),before=assess(a);assert.ok(!('answer' in before.next));assert.ok(!('explanation' in before.next));assert.deepEqual(assess(a),before);assert.throws(()=>commitAnswer(a,{itemId:'story-1',value:0,confidence:2}));});
test('route keeps the exact goal, assessed skills, overrides, distinct weekly time',()=>{const a=complete('right'),p=planFor(a);assert.ok(p.title.includes(a.goal.words));assert.equal(p.profile.level,'advanced');a.setup.hours=2;a.setup.motivation='improve_craft';const two=planFor(a);a.setup.hours=6;const six=planFor(a);assert.notEqual(two.paths.length,six.paths.length);a.overrides.framing=1;assert.equal(planFor(a).profile.request.skillOverrides.camera,1)});
test('eight diagnostic images have one owned bank slot and no lesson reuse',()=>{const assets=JSON.parse(fs.readFileSync('media/onboarding-registry.json'));for(const a of assets.assets.filter(x=>x.kind==='image')){const id=a.id.replace('fp-diagnostic-','');assert.equal(questionBank.filter(i=>i.image===id).length,1)}assert.equal(assets.assets.length,12);});
test('required rationale and confidence are validated; previous answers cannot be replaced',()=>{const a=complete('right');a.answers=a.answers.slice(0,3);const i=assess(a).next;assert.equal(i.reason,true);assert.throws(()=>commitAnswer(a,{itemId:i.id,value:0,confidence:2,rationale:''}));assert.throws(()=>commitAnswer(a,{itemId:i.id,value:0,rationale:'A clear reason'}));});
test('evidence, sport and product intent outrank generic filmmaking matches',()=>{for(const [goal,id] of [['Document damage in my rented flat before moving out','C01-05'],['Analyse a player’s technique during a training session','C11-02'],['Create a product demonstration for an online shop','C07-02']])assert.equal(classifyGoal(goal).caseId,id)});
test('scenario answer rationale is never sent as public configuration',()=>{const a=complete('right');a.answers=a.answers.slice(0,7);const next=assess(a).next;assert.equal(next.chapter,'scenario');assert.equal(next.config,undefined);assert.equal(next.explanation,undefined)});

