import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
const require=createRequire(import.meta.url),load=require('../scripts/lib/load-source.cjs'),root=path.resolve(import.meta.dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const engine=load(root+'/app/scenario-engine.ts'),shared=load(root+'/app/lessons/shared.ts'),content=load(root+'/app/lessons/content.ts'),{labSpecs}=load(root+'/app/lessons/lab-specs.ts'),rules=load(root+'/app/lessons/activity-rules.ts');
function profile(id,hours=6){const request=engine.initialScenarioRequest(id);request.outcome.goal='My exact words: '+engine.caseById(id).source_text;request.outcome.audience='my chosen viewer';request.starting.hours=hours;request.starting.weeks=1;return {diagnosticVersion:'scenario-v1',request};}
test('Every source use and stable stage has working visual lessons with a short first win',()=>{
 assert.equal(engine.scenarios.length,176);assert.equal(engine.categories.length,18);assert.equal(engine.archetypes.length,20);
 for(const c of engine.scenarios)for(const stage of engine.stages){const id='need-'+c.id.toLowerCase()+'-'+stage,p=profile(c.id),route=engine.scenarioPath(id,p),lessons=content.pathLessons(id,p);assert.equal(lessons.length,route.keys.length,id);if(!lessons.length){assert.equal(stage,'foundations');assert.ok(!engine.buildScenarioPlan(p).paths.some(p=>p.id===id));continue;}assert.ok(lessons[0].minutes<=8,id);for(const [i,l] of lessons.entries()){assert.equal(l.key,route.keys[i]);assert.ok(l.image&&l.activity&&l.deeper.length,l.key);assert.equal(l.context.goal,p.request.outcome.goal);assert.equal(l.reflect.length,3);assert.equal(l.weights.reduce((a,b)=>a+b,0),100);assert.ok(l.concept.text.split(/\s+/).length<=80,l.key);assert.ok(l.make.steps.join(' ').split(/\s+/).length<=80,l.key);if(l.canonicalModule)assert.equal(l.canonicalModule,engine.scenarioLesson(l.key,p).sourceModule);}}
});
test('Canonical teaching matches its recorded-media authoring snapshot',()=>{assert.deepEqual(JSON.parse(JSON.stringify(shared.sharedUnits)),read('app/lessons/shared-data.json'));assert.equal(Object.keys(shared.sharedUnits).length,103);assert.equal(shared.sharedPaths.reduce((n,p)=>n+p.keys.length,0),80);assert.equal(new Set(Object.values(shared.sharedUnits).filter(u=>u.archetype).map(u=>u.family)).size,20);});
test('Every canonical activity needs valid controls and an observation; scores never gate progress',()=>{for(const p of shared.sharedPaths)for(const key of p.keys){const l=content.visualLesson(key),s=labSpecs[l.labFamily],data={x:s.range[0],y:s.rangeY[1],order:[0,1,2],controls:['x','y'],changes:2,note:'I compared both controls and recorded what changed.'};assert.doesNotThrow(()=>rules.validateActivity(key,{kind:'shared-lab',version:1,data}));assert.throws(()=>rules.validateActivity(key,{kind:'shared-lab',version:1,data:{...data,controls:['x']}}));assert.throws(()=>rules.validateActivityDraft(key,{kind:'shared-lab',version:1,data:{...data,x:999999}}));assert.equal(rules.validateReflection(key,[0,0,0]).score,0);}});
test('Planning time changes the route without silently overfilling the available budget',()=>{for(const c of engine.scenarios){const small=engine.buildScenarioPlan(profile(c.id,2)),large=engine.buildScenarioPlan(profile(c.id,6));assert.ok(small.keys.length<=large.keys.length,c.id);assert.ok(small.minutes<=120,c.id);assert.ok(large.minutes<=360,c.id);assert.ok(large.keys.every(content.isVisualKey));}});
test('Screen equipment and individual unknown skill remain explicit',()=>{const c=engine.scenarios.find(c=>c.primary_archetype==='A12'),p=profile(c.id);p.request.starting.gear=['computer'];p.request.starting.screen_recorder=false;const l=content.pathLessons('need-'+c.id.toLowerCase()+'-prepare',p).find(l=>l.labFamily==='screen');assert.ok(l);assert.match(l.make.steps.join(' '),/planning|plan|storyboard/i);assert.match(l.context.why,/planning only/);assert.equal(l.context.level,'Not assessed');});
test('Lightweight display indexes cannot drift from their audited image registries',()=>{for(const kind of ['lessons','shared','onboarding']){const index=read('media/'+kind+'-display.json'),registry=read('media/'+kind+'-registry.json');for(const a of index.assets){const original=registry.assets.find(x=>x.id===a.id);assert.ok(original,a.id);assert.equal(a.canonicalUrl,original.canonicalUrl);assert.equal(a.alt,original.alt);assert.deepEqual(a.renditions.map(r=>r.src),original.renditions.map(r=>r.src));}}});
