'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {imageForLesson} from './lesson-imagery';
import {curatedLesson,lessonSkill,subjectFor,goalKinds,goalKind} from './personalization';
import {useLearning} from './ui';
export function AdaptiveLab({lessonKey}:{lessonKey:string}){const {s}=useLearning(),photo=imageForLesson(lessonKey,s.profile),lesson=curatedLesson(s.profile,lessonKey),skill=lessonSkill(lessonKey);const [value,setValue]=useState(0),[choice,setChoice]=useState(0),[failed,setFailed]=useState(false),[playing,setPlaying]=useState(false),[audioError,setAudioError]=useState('');const audio=useRef<AudioContext|null>(null);useEffect(()=>()=>{audio.current?.close().catch(()=>{})},[]);
 const picks=(labels:string[])=> <div className="visual-options">{labels.map((x,i)=><Button key={x} aria-pressed={choice===i} variant={choice===i?'default':'outline'} onClick={()=>setChoice(i)}>{x}</Button>)}</div>;
 const slider=(label:string,min:number,max:number,step=1)=><label className="visual-slider">{label}<input aria-label={label} type="range" value={value} min={min} max={max} step={step} onChange={e=>setValue(Number(e.target.value))}/></label>;
 let controls:React.ReactNode,overlay:React.ReactNode=null,style:React.CSSProperties={},caption='',shape='16 / 10';
 if(skill==='exposure'){style={filter:`brightness(${Math.pow(2,value*.5)})`};controls=slider('Exposure comparison',-2,2,.25);overlay=<span className="camera-readout">{value>0?'+':''}{value} EV</span>;caption='Move from dark to bright. Notice where important textures become difficult to read. This screen simulation cannot recover clipped detail or replace an exposure check on your camera.'}
 else if(skill==='focus'){controls=picks(['Deep focus','Isolate the centre']);overlay=choice?<div className="focus-mask"/>:null;caption=choice?'The centre stays readable while the surrounding image softens. Consider what story information this removes. This is a screen blur, not an optical depth-of-field simulation.':'Look at the subject and its surroundings together. Decide which details the viewer needs before choosing a shallower focus.'}
 else if(skill==='composition'){controls=<>{picks(['Whole frame','Closer','Detail'])}<Button variant="outline" aria-pressed={value===1} onClick={()=>setValue(value===1?0:1)}>Composition grid</Button></>;style={transform:`scale(${[1,1.4,2.1][choice]})`};overlay=value===1?<div className="thirds-guide"/>:null;caption='Crop the frame and notice what disappears. A tighter view changes information; it does not reproduce moving the camera or changing perspective.'}
 else if(skill==='lighting'){controls=picks(['Original light','Stronger contrast','Lifted shadows']);style={filter:choice===1?'contrast(1.5)':choice===2?'contrast(.75) brightness(1.1)':'none'};caption='Compare the balance between bright and dark areas. These digital changes demonstrate contrast; on location, test source direction, diffusion, reflection or negative fill.'}
 else if(skill==='colour'){controls=slider('Warm / cool comparison',-20,20);style={filter:value>=0?`sepia(${value/55}) saturate(${1+value/80})`:`sepia(${Math.abs(value)/55}) hue-rotate(165deg) saturate(${1+Math.abs(value)/80})`};caption='Watch neutral surfaces and skin or product colour as you shift the cast. Colour consistency and the intended feeling both matter. This filter is illustrative, not a colour-managed grade.'}
 else if(skill==='sound'){const db=value-18;controls=<>{slider('Recording level comparison',-12,18)}<Button variant="outline" disabled={playing} onClick={async()=>{setAudioError('');try{const ctx=new AudioContext();audio.current=ctx;await ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=440;g.gain.value=.008+((value+12)/30)*.04;o.connect(g).connect(ctx.destination);o.start();setPlaying(true);o.stop(ctx.currentTime+1);o.onended=()=>{setPlaying(false);void ctx.close()}}catch{setPlaying(false);setAudioError('The test tone is unavailable. You can still use the visual meter.')}}}>{playing?'Playing…':'Play a quiet test tone'}</Button></>;overlay=<div className="audio-visual"><span>Illustrative peak meter</span><div className="photo-meter">{Array.from({length:20},(_,i)=><i key={i} className={i<(value+12)/30*20?i>17?'hot':'lit':''}/>)}</div><strong>{db} dBFS</strong></div>;caption='Leave space below the digital ceiling for louder moments. Compare the meter and test tone; neither measures the background noise or intelligibility of your recording.'}
 else if(skill==='editing'){controls=picks(['Place → action → result','Detail → place → action','Action → detail → result']);overlay=<div className="sequence-overlay">{[['PLACE','ACTION','RESULT'],['DETAIL','PLACE','ACTION'],['ACTION','DETAIL','RESULT']][choice].map((t,i)=><span key={i}><small>{i+1}</small>{t}</span>)}</div>;caption='Change the proposed order and imagine what the viewer learns first. This is a paper-edit comparison. Try both orders with your own footage to judge continuity and pacing.'}
 else if(skill==='delivery'){controls=picks(['16:9','9:16','1:1']);shape=['16 / 9','9 / 16','1'][choice];overlay=<div className="safe-zone"/>;caption='Changing the delivery frame can remove essential details. The inner guide shows a generic text margin, not a platform-specific safe area. Check the actual destination interface.'}
 else{controls=picks(['Inform','Persuade','Evoke a feeling']);overlay=<span className="intent-label">{['What should the viewer understand?','What useful change should the viewer consider?','What should the viewer feel?'][choice]}</span>;caption='The same subject can serve a different purpose. Change the intention, then decide which shot would become your opening. Your assignment turns that choice into a concrete shot plan.'}
 return <div className={'photo-lab adaptive-lab skill-'+skill}><div className="photo-view" style={{aspectRatio:shape,...(skill==='delivery'&&choice===1?{maxWidth:300}:{} )}}>{photo&&!failed?<img src={photo.src} alt={photo.alt} style={style} onError={()=>setFailed(true)} loading="eager"/>:<div className="image-fallback" role="img" aria-label="A tonal calibration chart for the visual comparison"><div style={style}>{Array.from({length:8},(_,i)=><span key={i} style={{background:`hsl(275 12% ${12+i*11}%)`}}/>)}</div><p>{failed?'The reference image is unavailable. Try the control on this tonal chart, or use your own frame.':'Try the control on this tonal chart.'}</p></div>}{overlay}</div><div className="photo-controls">{controls}</div><p className="visual-caption" aria-live="polite">{caption}</p>{audioError&&<p role="alert" className="visual-caption">{audioError}</p>}<div className="visual-application"><strong>For {subjectFor(s.profile)}</strong><p>{lesson.hook}</p></div>{photo&&<small className="visual-source"><a href={photo.source} target="_blank" rel="noreferrer">{photo.credit}</a> · Reference image; not an example of learner work.</small>}</div>
}
