'use client';
import {isScenarioPath,isScenarioKey,scenarioPath,scenarioLesson,buildScenarioPlan,isScenarioProfile} from './scenario-engine';
import {ScenarioDiscovery} from './scenario-learning';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {basicContext} from './beginner-curriculum';
import {coursePaths as basicPaths,keysForLevel,levelForPath,levelNames,goalPractice} from './selfpaced-curriculum';
import {moduleHref,blockingModule,moduleInfo,assignmentRubric,isFreePath,practiceSteps} from './learning-rules';
import {personalKeys,currentPlan,curatedLesson,freeLessonKey} from './personalization';
import {freeReviewKeys} from './assignment-review';
import {SessionDiscovery} from './session-discovery';
import {lessonTitle} from './visual-lab';
import {useLearning,Panel,Go,Gate,Action,UploadField,DateText,isExplore} from './ui';

export function BeginnerSession({pathId,index}:{pathId:string;index:number}){
 const {s,user,loaded,mutate,refresh}=useLearning();const path=isScenarioPath(pathId)?scenarioPath(pathId,s.profile):basicPaths.find(p=>p.id===pathId),key=pathId+'-'+index,lesson=path?.lessons[index]?curatedLesson(s.profile,key):undefined;
 const [tab,setTab]=useState('lesson'),[notes,setNotes]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState<any>(null),[ratings,setRatings]=useState([-1,-1,-1]),[review,setReview]=useState<any>(null),[allowance,setAllowance]=useState<any>(null),[reviewError,setReviewError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<any[]>([]),[selfCheck,setSelfCheck]=useState(false),[saved,setSaved]=useState(false),[reviewLoaded,setReviewLoaded]=useState(false);const lock=useRef(false),requestId=useRef('');
 const level=isScenarioPath(pathId)?path?.level||'beginner':levelForPath(pathId),basicKeys=personalKeys(s,pathId)||(isScenarioPath(pathId)?scenarioPath(pathId,s.profile)!.keys:keysForLevel(level)),plan=currentPlan(s),selectedKeys=plan?.paths.find(p=>p.id===pathId)?.keys||path?.lessons.map((_,i)=>pathId+'-'+i)||[];const assessment=s.assessments?.[key];const blocker=lesson?blockingModule(s,key):null;const entitled=isFreePath(pathId,s)||isExplore(s);const position=basicKeys.indexOf(key),next=basicKeys[position+1],previous=basicKeys[position-1];
 useEffect(()=>{if(!loaded)return;const d=s.drafts?.[key]||s.assessments?.[key];setNotes(d?.notes||'');setUrl(d?.url||'');setRatings(d?.ratings||[-1,-1,-1]);setFile(d?.uploadId?{id:d.uploadId,type:d.uploadType||'',name:'Saved assignment media'}:null);const requested=new URLSearchParams(window.location.search).get('tab');setTab(['make','reflect','assignment'].includes(requested||'')?'assignment':'lesson');setSelfCheck(requested==='reflect'||s.profile?.request?.preferences?.assessment_comfort==='scored');setReview(null);setSaved(false)},[loaded,key]);
 useEffect(()=>{let cancelled=false;setReviewLoaded(false);if(!user){setReviewLoaded(true);return}fetch('/api/review?key='+encodeURIComponent(key)).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);if(!cancelled){setAllowance(d.allowance);setReview(d.reviews?.[0]||null)}}).catch(e=>{if(!cancelled)setReviewError(e.message)}).finally(()=>{if(!cancelled)setReviewLoaded(true)});fetch('/api/attempts?key='+encodeURIComponent(key)).then(r=>r.ok?r.json():[]).then((d:any)=>{if(!cancelled)setHistory(d)}).catch(()=>{});return()=>{cancelled=true}},[user,key,assessment?.id]);
 if(!path||!lesson)return <Panel><h1>Lesson not found</h1><Go href="/explore">All pathways</Go></Panel>;
 const criteria=assignmentRubric(key,s.profile),ctx=basicContext(s.profile);const imageId=file?.type?.startsWith('image/')?file.id:'';const sameReview=review&&review.notes===notes&&review.uploadId===imageId;
 async function save(){const result=await mutate('assignment_save',{key,notes,url,uploadId:file?.id||''});setSaved(!!result);return result}
 async function getReview(){if(lock.current)return;lock.current=true;setBusy(true);setReviewError('');try{if(!await save())return;requestId.current=crypto.randomUUID();const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonKey:key,notes,uploadId:imageId,requestId:requestId.current}),signal:AbortSignal.timeout(60000)});const result:any=await response.json();if(!response.ok)throw Error(result.error||'The review could not finish.');setReview(result);setAllowance(result.allowance);await refresh()}catch(e:any){setReviewError(e.name==='TimeoutError'?'This review is taking longer than expected. Reload this page before retrying; it may have finished.':e.message||'AI review could not finish. Your draft is saved.')}finally{lock.current=false;setBusy(false)}}
 async function scoreSelf(){if(await mutate('practice_assess',{key,notes,ratings,uploadId:file?.id||'',url}))setSelfCheck(false)}
 return <article className="beginner-session"><div className="session-topline"><a className="text-link" href={'/explore/'+pathId}>{isScenarioKey(key)?'Your task':levelNames[level]} · {path.title}</a><span className="small">Session {Math.max(0,selectedKeys.indexOf(key))+1} of {selectedKeys.length}</span></div><div className="simple-session-head"><h1>{lessonTitle(lesson.title)}</h1><details className="course-outline"><summary>Session list</summary><ol>{path.lessons.map((l,i)=>selectedKeys.includes(path.id+'-'+i)&&<li key={i}><a href={moduleHref(path.id+'-'+i)} aria-current={i===index?'page':undefined}>{s.progress[path.id+'-'+i]?'✓ ':''}{i+1}. {lessonTitle(l.title)}</a></li>)}</ol></details></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="simple-tabs"><TabsTrigger value="lesson">Lesson</TabsTrigger><TabsTrigger value="assignment">Assignment{assessment?' · '+assessment.total+'/100':''}</TabsTrigger></TabsList><TabsContent value="lesson" forceMount hidden={tab!=='lesson'}>{isScenarioKey(key)?<ScenarioDiscovery key={key} lessonKey={key} active={tab==='lesson'} onMake={()=>setTab('assignment')}/>:<SessionDiscovery key={key} lesson={lesson} lessonKey={key} active={tab==='lesson'} onMake={()=>setTab('assignment')}/>}</TabsContent><TabsContent value="assignment">
 <div className="assignment-brief"><h2>Your assignment</h2><p className="practice-goal">{isScenarioKey(key)?scenarioLesson(key,s.profile).hook:goalPractice(s.profile).brief}</p><p className="small">{isScenarioKey(key)?'Keep the practice scoped to your task.':'Use '+ctx.subject+'.'} {isFreePath(pathId,s)?'Practice is free for this pathway.':''}</p><p className="practice-prep"><strong>{s.profile?.practiceMode==='gentle'?'Start small.':s.profile?.practiceMode==='stretch'?'Stretch your practice.':'Use what you have.'}</strong> {s.profile?.practiceMode==='gentle'?'Rehearse one part for five minutes before doing the full task.':s.profile?.practiceMode==='stretch'?'After the core task, make a second version with one deliberate change and compare the effect.':'Use your available equipment. Label any controls, specialist equipment or real-world conditions you cannot test.'}</p><ol>{practiceSteps(key,s.profile).map(v=><li key={v}>{v}</li>)}</ol><details><summary>Need a filming alternative?</summary><p>{lesson.alternative}</p></details></div>
 {isScenarioKey(key)&&(!isScenarioProfile(s.profile)||s.profile.request.scenario.use_case!==scenarioLesson(key).scenarioId)?<Panel><h2>Make this task yours</h2><p>Personalise this task before saving an assignment. Your existing work and free allowances stay unchanged.</p><Go href={'/diagnostic?case='+scenarioLesson(key).scenarioId}>Personalise this task</Go></Panel>:!entitled?<Panel><h2>Continue your practice</h2><p>Your two starter pathways include free practice. Annual access opens the remaining assignments.</p><Go href={'/membership?return_to='+encodeURIComponent(moduleHref(key)+'?tab=assignment')}>See learning access</Go></Panel>:<Gate>{blocker?<Panel><h2>Finish your previous assignment</h2><p>{lessonTitle(moduleInfo(blocker).lesson.title)} comes first. You can still explore this lesson.</p><Go href={moduleHref(blocker)+'?tab=assignment'}>Open previous assignment</Go></Panel>:<>
 <div className="assignment-submit"><h2>Get feedback on your work</h2><p className="small">{allowance?.free||!allowance&&freeLessonKey(s,key)?`${Math.max(0,(allowance?.limit??2)-(allowance?.used??0))} free AI reviews left for this session.`:allowance?.eligible?`${Math.max(0,allowance.limit-allowance.used)} reviews left in your annual allowance.`:'Other pathways use your annual AI allowance.'}</p><label htmlFor="assignment-notes">Your work and notes<textarea id="assignment-notes" rows={5} maxLength={4000} value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false)}} placeholder="Include your plan, what you tried, what changed and any viewer responses."/></label><label className="viewing-link">Video or project link · optional<input type="url" value={url} maxLength={1500} onChange={e=>{setUrl(e.target.value);setSaved(false)}} placeholder="https://…"/></label><UploadField lessonKey={key} value={file} onUpload={(f:any)=>{setFile(f);setSaved(false)}}/>{file&&<div className="button-row"><a className="text-link" href={'/api/file/'+file.id} target="_blank" rel="noreferrer">View attachment</a><Button variant="ghost" onClick={()=>{setFile(null);setSaved(false)}}>Remove attachment</Button></div>}<p className="small review-limit">AI reviews your notes and one image still. It cannot watch uploaded videos, hear sound or open viewing links. Add written evidence for those parts.</p><div className="button-row"><Button disabled={busy||!reviewLoaded||notes.trim().length<20||allowance&&!allowance.eligible||allowance&&allowance.used>=allowance.limit} onClick={getReview}>{busy?'Reviewing your assignment…':'Submit for AI review'}</Button><Action outline disabled={busy} onClick={save}>Save draft</Action></div>{saved&&<p className="small" role="status">Draft saved.</p>}{reviewError&&<div className="notice" role="alert"><p>{reviewError}</p><p className="small">You can keep working or use the self-check below.</p></div>}{allowance&&(!allowance.eligible||(allowance.free&&allowance.used>=allowance.limit&&!isExplore(s)))&&<a className="text-link" href={'/membership?return_to='+encodeURIComponent(moduleHref(key)+'?tab=assignment')}>See annual access</a>}</div>
 {review&&<section className="ai-assignment-feedback" aria-label="AI assignment feedback"><div className="review-score"><div><span className="small">AI first-pass review</span><h2>{review.review.total===null?'More evidence needed':review.review.passed?'Ready to continue':'A focus for your next attempt'}</h2></div>{review.review.total!==null&&<strong>{review.review.total}<small>/100</small></strong>}</div><p>{review.review.summary}</p><div className="feedback-pair"><div><h3>What works</h3><p>{review.review.strength}</p></div><div><h3>Improve this</h3><p>{review.review.improvement}</p></div></div><div className="next-practice"><strong>Try next</strong><p>{review.review.nextStep}</p></div><details><summary>Evidence and scoring</summary><p>{review.review.evidenceLimit}</p>{review.review.criteria.map((c:any)=><p key={c.label}><strong>{c.label} · {c.rating===null?'Not enough evidence':c.rating+'/4'}</strong><br/>{c.feedback}</p>)}<p className="small">75/100 and every criterion at least 2/4 to continue. AI can make mistakes; this is a first pass on the evidence provided.</p></details>{!sameReview&&<p className="notice">Your work has changed since this review. Submit it again for updated feedback.</p>}{sameReview&&review.review.total!==null&&assessment?.reviewId!==review.id&&<Action onClick={()=>mutate('ai_review_accept',{reviewId:review.id})}>Save review to my progress</Action>}</section>}
 {assessment&&<Panel className="saved-checkpoint"><span className="small">{assessment.source==='ai-review'?'Saved AI review':'Saved self-check'}</span><h2>{assessment.passed?'Assignment complete':'Revise and try again'} · {assessment.total}/100</h2>{assessment.passed&&index===path.lessons.length-1&&<p>Your pathway project is saved in My work.</p>}<div className="button-row">{s.progress[key]&&(next?<Go href={moduleHref(next)}>Next lesson</Go>:<Go href={isScenarioKey(key)?'/finish/scenario':plan?'/finish/route':'/finish/'+level}>{isScenarioKey(key)?'Review my route':'Finish '+levelNames[level].toLowerCase()+' journey'}</Go>)}<Action outline onClick={()=>mutate('submit',{key,notes,url,uploadId:file?.id||''})} disabled={notes.trim().length<20}>Keep in My work</Action></div></Panel>}
 <details className="manual-check" open={selfCheck} onToggle={e=>setSelfCheck(e.currentTarget.open)}><summary>Use a self-check instead</summary><p className="small">Your own ratings, separate from AI feedback. Minimum 75/100 with each criterion at least 2/4.</p>{criteria.map((c,i)=><label key={c.label}>{c.label}<small>{c.minimum} · {c.weight}%</small><details className="score-anchors"><summary>See examples for 0–4</summary><ol start={0}>{c.anchors.map((anchor:string,n:number)=><li key={n}><strong>{n}/4</strong> {anchor}</li>)}</ol><p className="small">{c.example}</p></details><select aria-label={c.label} value={ratings[i]} onChange={e=>setRatings(v=>v.map((x,n)=>n===i?Number(e.target.value):x))}><option value={-1}>Choose a rating</option>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n}/4 · {['Not tried','Needs work','Meets minimum','Solid','Strong and purposeful'][n]}</option>)}</select></label>)}<Action disabled={ratings.includes(-1)||notes.trim().length<20} onClick={scoreSelf}>Save self-check</Action></details>
 {history.length>1&&<details className="manual-check"><summary>Previous attempts · {history.length}</summary>{history.map(a=><p key={a.id}><DateText value={a.at}/> · {a.total}/100 · {a.source==='ai-review'?'AI first pass':'Self-check'}</p>)}</details>}
 </>}</Gate>}
 </TabsContent></Tabs><div className="session-footer">{previous?<Go outline href={moduleHref(previous)}>Previous lesson</Go>:<a className="text-link" href="/workspace">My journey</a>}<a className="text-link" href="/journals">Journals & templates</a></div></article>
}
