// Source of truth: FramePath Flow.pdf, beginner curriculum, supplied 6 October 2026.
// Sequence, Think questions and assessment weights are authored; AI may not replace them.
export const curriculumVersion='basic-2026-10-v1';
export type BasicLesson={title:string;minutes:number;phase:'pre'|'production'|'post';learn:string;do:string;checks:string[];minimum:string[];retry:string[];resource:number;topic:string;video?:{id:string;title:string;by:string;focus:string};alternative:string};
export type BasicPath={id:string;week:number;title:string;think:string;hours:number;practice:string[];lessons:BasicLesson[];short:string;description:string;outcome:string;duration:string;number:string};
type Row=[string,BasicLesson['phase'],string,string,string[],string[],string[]];
const week=(n:number,title:string,think:string,hours:number,practice:string[],rows:Row[]):BasicPath=>({id:'basic-w'+n,week:n,title,think,hours,practice,short:think,description:think,outcome:n===8?'One Place, One Person, One Minute':'A weekly study you can explain',duration:'5 sessions · ~'+hours+' hours',number:String(n).padStart(2,'0'),lessons:rows.map((r,i)=>({title:r[0],phase:r[1],learn:r[2],do:r[3],checks:r[4],minimum:r[5],retry:r[6],topic:r[0],resource:0,minutes:[60,75,75,90,hours*60-300][i],alternative:'Use stills, a storyboard or a written comparison instead of filming. Describe each planned test and its expected result, label it as a simulation, and apply the same three criteria to that evidence. Do not claim you captured or heard something you only planned.'}))});
export const basicPaths:BasicPath[]=[
week(1,'Purpose and Seeing','Who is this for, and what should they walk away with?',7,['Study a video muted; write the story and purpose you understood.','Choose a familiar place. Write three purposes and five shots for each; keep a Noticing Journal.','Ask a friend to guess the purpose from your shot list.'],[
['Find your why','pre','A topic names what is in the video; purpose names the change you want in the viewer. The same place can inform, persuade, evoke a feeling, document or entertain. A purpose line connects one viewer to one intended takeaway. Keep your first clip as an honest baseline, before trying to improve it.','Record a 30-second baseline of a familiar subject. Answer: who is it for, what should they take away, and why would they care? Write three different purpose lines and five possible shots for each. Save your text and, if available, one still.',['Purpose line clarity','Topic vs purpose','Baseline honesty'],['Name a viewer and what you want them to understand, feel or do.','Write three purposes with different shot choices, not just different topics.','Describe one observable strength and one gap in your unpolished baseline.'],['In 10 minutes, rewrite one purpose line naming a viewer and a takeaway.','In 20 minutes, change the purpose and replace three shots to serve it.','In 10 minutes, compare your baseline with your intention and name one visible gap.']],
['Know your viewer','pre','A useful viewer is a real person in a real viewing situation. Someone scrolling without sound needs an opening they can read visually. Someone unfamiliar with your setting may need more context. Ask one person what they notice before explaining your intention.','Create a Viewer Card: person, need, viewing place, sound on or off, and first-shot idea. Interview one possible viewer. Revise your purpose line using what you heard.',['Viewer specificity','Viewing context → first shot','Revised purpose reflects viewer'],['Identify one specific viewer and their need.','Connect sound, screen or viewing situation to your opening shot.','Record one viewer response and a resulting change to your purpose.'],['Spend 10 minutes replacing “everyone” with one person and a specific need.','Sketch a first shot for sound-off viewing in 15 minutes.','Ask one short question, then revise one phrase in your purpose line.']],
['Learn to see','pre','Observation comes before camera technique. “A busy street” is general; “a hand pauses before passing a warm cup” is specific. Look for light, detail, behaviour, contrast and change. A detail earns its place when you can explain what it tells this viewer.','Take a silent 10-minute walk. Record 15 observations in your Noticing Journal, with at least five specific details. Choose three and explain why each matters to your purpose.',['Specificity','Meaning','Lens range'],['Include at least five concrete details among 15 observations.','Give a viewer-related reason for three observations.','Notice light, detail, behaviour, contrast and change.'],['Observe one corner for 10 minutes and replace five vague descriptions.','Spend 15 minutes adding “this matters because” to three details.','Repeat a 10-minute walk looking only for the category you missed.']],
['Choose your shots','production','A place shot gives context, an action or person shot shows what happens, and a detail directs attention. Hold shots long enough to give an editor choices. Write “This shot exists to…” before filming, then compare your reason with what a viewer actually sees.','Capture six shots: two of place, two of person or action, and two details. Hold each for at least 10 seconds. Add a reason for every shot to the Shot Reasoning Log. Ask a stand-in viewer to guess your purpose.',['Shot-purpose alignment','Category balance and holds',"Viewer’s guess matches purpose"],['Give a purpose-linked reason for each of six shots.','Include two shots per category with 10-second holds.','Record a viewer guess and compare it with your intention.'],['Replace one weak shot and rewrite its reason in 20 minutes.','Film one missing category with a steady 10-second hold.','Show the sequence without explanation; change one shot that confused the viewer.']],
['Prove it','post','Ordering the same place differently changes its meaning. Compare the sequence with your purpose rather than adding effects. Viewer responses are evidence, including disagreement. Return to your baseline and name a specific decision you now make differently.','Show one place in two different ways: two purposes, six shots each and 12 reasoning-log lines. Ask two viewers what each sequence communicates. Compare the result with your baseline and save a weekly reflection.',['Two purposes → two different sequences','Viewer evidence','Baseline comparison'],['Make two six-shot sequences with genuinely different purposes.','Record two viewers’ responses without rewriting them as praise.','Name a specific change from your original baseline.'],['Reorder three shots to clarify the second purpose in 20 minutes.','Ask two viewers one question each and record their actual words.','Compare one baseline frame with a new frame and describe the changed decision.']]
]),
week(2,'Camera and Exposure','Which setting changes how this feels, and which just keeps it correct?',7,['Find your manual or pro controls and try 10 locked-exposure clips.','Film a window in morning, noon and evening; keep a Settings Log.','Compare the same action at 24/25 fps and 50/60 fps where your device supports it.'],[
['Auto-mode truth and set-up','pre','Auto mode makes decisions for you, sometimes changing brightness or focus mid-shot. Resolution, orientation and frame rate should fit the intended screen. Artificial lights can flicker at incompatible shutter settings. Learn the controls you actually have; unsupported settings can be described rather than purchased.','Record three auto-mode clips and note what looks right or wrong. Make a Camera Card listing supported resolution, frame rates, orientation, focus and exposure controls. Run a pre-flight check and test for flicker.',['Camera Card completeness','Pre-flight checklist quality','Settings match delivery plan'],['List your device and its available controls, including limitations.','Check lens, storage, battery, focus, exposure, sound and a test playback.','Connect your resolution, frame rate and orientation to a viewing destination.'],['Spend 15 minutes finding and recording missing camera controls.','Run a 10-minute checklist and replay one test clip.','Choose one destination and correct one mismatched setting.']],
['Exposure','production','Exposure describes recorded brightness. Shutter time, aperture where available, and ISO or exposure compensation affect it in different ways. Very bright highlights and deep shadows may lose detail. Compare controlled tests of one scene so your choice is about purpose, not simply the brightest image.','Make an exposure ladder of one scene at −2, −1, 0, +1 and +2 EV where supported. Identify lost highlight or shadow detail. Choose a version for your purpose and record why.',['Ladder complete','Clipping/lost detail identified','Choice tied to purpose'],['Compare five exposure levels or clearly labelled planned equivalents.','Point to an area with lost highlight or shadow detail.','Explain why the chosen brightness serves your intended feeling or information.'],['Complete the missing exposure comparisons in 20 minutes.','Look at the brightest and darkest areas; annotate one lost detail.','Write two sentences linking your choice to what the viewer needs to see.']],
['Motion feel','production','Frame rate is the number of frames captured each second; shutter time controls blur within a frame. A shutter near twice the frame rate is a common starting point, not a creative law. Faster shutters can feel crisp or jittery; slower ones smear movement. Keep the action constant when comparing.','Pour water or film a similar action. Compare three frame-rate choices and three shutter choices, where supported, for six tests. Build a “how it feels” table and write your own rule of thumb.',['Table completeness','Feel descriptions','Rule of thumb in own words'],['Record six tests or label unsupported settings as planned comparisons.','Describe visible motion differences rather than “good” or “bad”.','Explain a usable frame-rate and shutter choice in your own words.'],['Fill two missing test rows in 20 minutes.','Replay one action and describe blur, smoothness and speed separately.','Write a one-sentence rule with one situation where you would break it.']],
['Colour and focus','production','White balance changes how neutral objects appear under different light sources. Auto white balance may shift within a shot. Focus lock can prevent hunting, but a moving subject may leave the sharp area. Judge the intended subject rather than assuming that one fixed setting fits every shot.','Compare automatic and set white balance in two light conditions. Try five takes of a subject moving toward the camera, aiming for at least three sharp takes. Describe one failure and its fix.',['WB comparison','Focus success','Cause-and-fix explanation'],['Compare auto and set white balance under two lights.','Identify at least three sharp takes out of five, or specify a focus test in the alternative.','Link one observed problem to a plausible adjustment.'],['Photograph a neutral object under two lights and label the colour shift.','Repeat three short focus tests with a marked stopping point.','Change only one suspected cause and compare the result.']],
['Prove it','post','A settings log is useful when it connects controls to visible results. Compare your deliberate settings with the auto-mode baseline. The aim is repeatable exposure, colour and focus that support a purpose. Ask viewers what changes they notice before describing your choices.','Capture one scene in three conditions, making nine shots in total. Save settings and reasons, compare with auto mode, and ask two viewers what changed. Save your weekly study.',['Settings reasoning','Exposure/WB/focus control','Comparison and reflection'],['Record settings and a reason for each of nine shots.','Describe exposure, colour and focus control across the three conditions.','Compare to auto mode and include two viewer responses.'],['Complete the settings and reason for three existing shots.','Reshoot the weakest condition with one corrected control in 25 minutes.','Write a short before-and-after comparison using the viewers’ own words.']]
]),
week(3,'Composition and Shot Sizes','What did I include, and what did I leave out on purpose?',6,['Find ten compositions and capture two-second examples.','Make a wide, medium, close and detail ladder for five subjects.','Recompose for 16:9, 9:16 and 1:1.'],[
['Frame as a decision','pre','A frame selects information. Wide views explain a place; closer views can emphasise action, expression or texture. Size alone does not create meaning: the chosen information must serve the viewer. Consider what falls outside the frame as deliberately as what stays in it.','Make six framings of one person or stand-in object. Label shot size, what you include, what you exclude and what each framing means.',['Shot size range','Include/exclude reasoning','Meaning of each framing'],['Use six framings with visibly different shot sizes.','Explain an inclusion and exclusion for each.','Describe what each framing helps a viewer understand or feel.'],['Create one wider and one closer version in 15 minutes.','Annotate what you removed from three frames and why.','Write a viewer takeaway below each unexplained frame.']],
['Place the subject','production','Thirds, headroom and lead room are tools for directing attention. Give a face room to look or move when that supports the scene. Eyeline affects how connected a viewer feels. Check the edges for accidental crops and choose balance deliberately rather than obeying a grid automatically.','Frame five subjects using deliberate headroom, lead room and eyelines. Annotate a correction for each and explain why it helps.',['Headroom and lead room','Eyeline and balance','Annotated reasoning'],['Show deliberate headroom and space in the direction of action or gaze.','Keep eyelines and balance purposeful across five examples.','Explain each correction using visible evidence.'],['Reframe two awkward crops with clear headroom and lead room.','Compare a centred and offset frame and choose one deliberately.','Add one concrete reason to each unexplained correction.']],
['Depth and lines','production','Foreground, middle ground and background can separate a subject from its setting. Lines can guide attention or pull it away. A bright object behind a face may dominate even when the framing grid looks correct. Check the background before adding another element.','Create three layered shots. Mark foreground, middle ground, background and useful lines. Remove or reframe a distraction and save a comparison.',['Layering','Use of lines','Distraction control'],['Identify foreground, middle ground and background in three shots.','Mark a line that directs attention toward something intentional.','Identify and correct a distracting background element.'],['Build one shot with three clearly labelled depth layers.','Reposition to make one line point toward your subject.','Remove or crop one distracting object and compare both frames.']],
['Formats and safe zones','production','A vertical frame may require moving the camera or subject, not merely cropping the sides. Titles and important details need breathing room around interface overlays. Preview the actual destination because safe areas vary. Preserve the purpose when changing format.','Recompose one idea for 16:9, 9:16 and 1:1. Mark title and subject safe areas. Explain which viewer situation suits each.',['Recomposition quality','Safe-zone awareness','Format tied to viewer'],['Create three deliberate compositions instead of accidental crops.','Keep important detail and titles away from vulnerable edges.','Connect each aspect ratio to a viewing situation.'],['Recompose the most awkward crop by moving camera or subject.','Preview one design on a phone and move an edge-hugging title.','Name a real screen and viewing context for each format.']],
['Prove it','post','A sequence should give new information as shot size changes. Repeating similar frames can feel static even if each is attractive. Use your shot reasoning log to connect variation with purpose, then check the sequence with a viewer.','Create a six-framing sequence that serves your purpose. Keep a reasoning log, show it to a viewer and reflect on one framing decision.',['Purpose-aligned framing','Variety across ladder','Viewer evidence and reflection'],['Give a purpose-linked reason for all six frames.','Use wide, medium, close and detail views meaningfully.','Record a viewer response and one resulting improvement.'],['Replace one frame that does not serve the purpose.','Add a missing shot size and explain its new information.','Show the sequence once and record a specific response.']]
]),
week(4,'Light Basics',"Where is the light coming from, and what does it do to the subject’s face and mood?",6,['Map light at home at three times of day.','Make front, side and backlit window portraits.','Rescue difficult light with a white card or by moving the subject.'],[
['See the light','pre','Light has direction and quality. Small apparent sources often create hard-edged shadows; large apparent sources tend to soften them. Time of day changes both direction and colour. Observe the shadow on the subject before deciding whether you need more equipment.','Make a light map at three times of day. Label direction, hard or soft quality, and the effect on your subject.',['Direction identified','Quality identified','Time-of-day link'],['Mark where light comes from in three observations.','Use shadow edges to distinguish hard and soft light.','Connect the observed change to time of day.'],['Draw one arrow from source to subject for each missing observation.','Compare two shadow edges and describe their difference.','Revisit the same place later and record what changed.']],
['Window light and reflectors','production','Moving around a window changes the balance between bright and shaded areas. A white card bounces some light back without becoming a new powered source. Keep the subject and camera consistent when testing the reflector. Secure the card safely and keep it away from heat.','Try front, side and back light at a window, with and without a white reflector. Compare the face or object and describe the mood.',['Direction comparison','Reflector effect','Mood described'],['Compare front, side and back light on the same subject.','Show or describe the shadow change with and without a reflector.','Connect a lighting difference to the intended mood.'],['Capture the missing light direction in 15 minutes.','Make one paired test changing only the reflector.','Choose one setup and describe what its shadows make you feel.']],
['Mixed light and colour temperature','production','A window and a warm lamp may put different colours on opposite sides of a subject. One white-balance setting cannot always neutralise both. Try switching off a source, moving the subject or embracing a deliberate contrast. Compare before and after in the same framing.','Combine window light and a warm lamp. Identify the colour problem, then switch off a source or set white balance deliberately. Save a before-and-after explanation.',['Mixed-light diagnosis','Fix effectiveness','Colour consistency'],['Identify two differently coloured sources and their effects.','Apply one adjustment and describe the improvement or trade-off.','Check consistency across the subject and nearby shots.'],['Label which source makes each side warm or cool.','Change one source and repeat a controlled comparison.','Match two neighbouring shots and note any remaining colour shift.']],
['Harsh sun and shade','production','Hard overhead sun can create deep eye shadows and bright patches. Moving into open shade or changing the subject’s angle may help more than increasing exposure. A reflector should never dazzle the subject. Protect comfort and permissions before chasing an image.','Rescue a harsh-light setup using shade, repositioning or a reflector. Make a before-and-after study and describe what changed on the face or subject.',['Problem diagnosis','Rescue effectiveness','Face/subject quality'],['Point to a specific harsh-light problem.','Make a controlled before-and-after rescue.','Check useful detail, shadows and subject comfort.'],['Annotate one unwanted shadow or highlight in your first frame.','Move into open shade and compare one new frame.','Adjust the angle until the important detail becomes readable.']],
['Prove it','post','Good lighting choices serve intent and remain understandable when you explain them. Compare conditions consistently, select rather than collect, and use viewer responses to check whether the intended mood survives.','Study one subject in four lighting conditions and make one rescue. State your purpose, collect a viewer response and save your weekly comparison.',['Light chosen for mood/purpose','Technical control','Reflection'],['Explain how a chosen lighting condition serves the intended mood.','Compare four conditions and a controlled rescue.','Include a viewer response and one repeatable lesson.'],['Choose one image and connect its mood to your purpose line.','Redo the weakest setup, changing one variable, in 25 minutes.','Record what a viewer noticed and what you will repeat.']]
]),
week(5,'Sound','What does this place sound like, and can the viewer hear what they need to?',6,['Record 60 seconds of ambience in three places.','Compare a phone microphone and a lavalier if available.','Create a sound-only portrait of a place.'],[
['Listen first','pre','Sound communicates space, distance and activity beyond the frame. Listen before recording: a fan, traffic or footsteps may dominate the voice you want. Describe what you actually hear. AI can read your description or a recorder screenshot; it cannot listen to your recording.','Listen to or record 60 seconds in three places. Describe foreground, background and changing sounds. Keep written observations and an optional recorder screenshot.',['Sounds noticed','Places distinguished','Description specificity'],['Identify foreground and background sounds.','Describe three recognisably different sound environments.','Use concrete descriptions of source, distance or change.'],['Listen for five minutes and name three previously missed sounds.','Compare two places without looking at the picture.','Replace vague “noise” with a source, distance and pattern.']],
['Mics and placement','production','Distance changes the ratio of direct voice to room reflections and noise. A close phone can outperform an expensive microphone placed too far away. Avoid rubbing clothing or pointing a microphone away from speech. Test before committing to a full interview.','Record the same sentence at three distances in two rooms. Compare noise and clarity, then choose a position and explain why. Use text and an optional recorder screenshot.',['Test completeness','Noise comparison','Best choice reasoned'],['Document three distances in two rooms.','Compare background noise and voice clarity.','Choose a setup using the comparison, not the price of the microphone.'],['Complete two missing distance tests in 15 minutes.','Listen with headphones and describe the dominant noise in each room.','Explain which placement makes words easiest to understand.']],
['Levels and monitoring','production','A recorder’s level meter shows signal level, not whether a story is clear. Digital clipping can distort loud peaks. Leave headroom; peaks around −12 dBFS are a useful starting target where a meter supports it. Monitor with headphones and adjust to the actual voice.','Record a sentence at three gain levels. Identify any clipping, set a level with headroom and listen with headphones. Save notes and an optional waveform or meter screenshot.',['Level targeting','Clipping identified','Monitoring practice'],['Set and describe a level that leaves headroom.','Compare three gain levels and identify clipping or its absence.','Record what you noticed through headphone monitoring.'],['Repeat one sentence with lower gain and compare the meter.','Inspect or listen to the loudest point of each test and label it.','Listen to a full test on headphones and note one issue.']],
['Room tone, noise and wind','production','Room tone is the sound of a location when the main action pauses. It can bridge edits without unnatural silence. Wind protection reduces air hitting the microphone, while quieter placement may reduce other noise. Record a comparison rather than assuming a filter solved it.','Capture room tone and compare wind with and without suitable protection. List practical noise fixes and explain the one you would use.',['Room tone captured','Noise/wind mitigation','Fix reasoning'],['Capture or clearly plan consistent room tone for the scene.','Compare an unprotected and protected or repositioned recording.','Connect the chosen fix to a specific noise source.'],['Record a short uninterrupted room-tone sample in the same position.','Repeat a short test sheltered from the wind.','Write one cause and one practical fix for your loudest distraction.']],
['Prove it','post','Dialogue, ambience and music do different jobs. Keep necessary words intelligible before adding a music bed. The same picture can feel very different with silence, location ambience or music. Use audio you have permission to use and describe the meaning change yourself.','Record a clean sentence and an ambience bed. Compare one clip without sound, with ambience and with permitted music. Write what changes and save a weekly sound study.',['Dialogue clarity','Ambience use','Meaning shift described'],['Describe intelligibility and any remaining speech problems.','Use an ambience bed that fits the place without masking speech.','Compare the three versions and explain how their meaning changes.'],['Move the microphone closer and repeat one unclear sentence.','Lower or replace one ambience section that masks words.','Write one sentence per version about its changed feeling.']]
]),
week(6,'Stability, Movement and Coverage','What will the editor need to make this make sense?',7,['Practise ten handheld holds of ten seconds.','Cover a routine with wide, medium, detail and cutaway shots.','Plan a two-person conversation with eyelines and screen direction.'],[
['Steady the camera','production','Stability starts with stance, support and controlled breathing. A tripod is useful but a safe stable surface or braced elbows can also help. Leave a still moment before and after the action. Judge improvement against your own first hold.','Record ten handheld holds of ten seconds. Rate their steadiness, describe your setup and note what improved. Add a setup photo if available.',['Handheld stability','Technique described','Improvement noted'],['Complete ten holds and compare their steadiness.','Describe stance, support or another repeatable technique.','Identify a visible improvement from first to last.'],['Repeat three ten-second holds with braced elbows.','Write the setup steps so someone else could repeat them.','Compare two holds and identify one specific change.']],
['Pans and tilts','production','A pan turns horizontally; a tilt moves vertically. Movement is easier to follow when it reveals something or follows an action. Start and end on useful frames and hold them briefly, giving an editor room to cut. A static shot is a valid choice when movement adds nothing.','Create three motivated pans or tilts. State the reason for each move and include steady start and end holds.',['Smoothness','Motivation','Start and end holds'],['Keep the three moves controlled enough to follow.','Explain what each movement reveals or follows.','Include usable still moments at both ends.'],['Repeat one move more slowly using a stable stance.','Rewrite one reason, then remove a move that adds nothing.','Record one move with three-second holds at both ends.']],
['Coverage','production','Coverage supplies the pieces needed to explain an action in an edit. Wide views establish space; closer views show action and detail. A cutaway can bridge a missing moment, but unrelated decoration may confuse the sequence. Anticipate what the editor will need.','Film a familiar routine with establishing, wide, medium, detail and cutaway views. Complete a Coverage Checklist and explain why each shot is useful.',['Coverage completeness','Cutaway usefulness','Shot variety'],['Include the views needed to understand beginning, action and end.','Choose a cutaway that can bridge or clarify a moment.','Use varied sizes with distinct information.'],['Film the single missing step in the routine.','Replace a decorative cutaway with a relevant action detail.','Add one wide or close view that changes what the viewer knows.']],
['Continuity','production','Consistent screen direction and eyelines help viewers understand where people are. Draw the line between subjects and plan camera positions deliberately. Matching the point of an action across cuts can hide a transition. The aim is readable geography, not a rule for its own sake.','Plan or film a two-person conversation using consenting participants or stand-ins. Diagram camera positions and eyelines. Compare screen direction and one matched action.',['Screen direction','Eyeline consistency','Matching action'],['Keep directions understandable using a position diagram.','Make the participants’ eyelines connect plausibly.','Compare the same action across two shots.'],['Draw the line between subjects and reposition one camera angle.','Reframe one reverse shot to correct the eyeline.','Repeat one action and cut at a matching moment.']],
['Prove it','post','An editor should be able to assemble an understandable process from the shots you captured. A missing step is a coverage problem; a repeated explanation may be an editing problem. Test the sequence without narrating over the viewer’s uncertainty.','Capture and assemble an eight-to-twelve-shot process film. Ask a viewer to describe what happened. Save the coverage checklist, one still and your weekly reflection.',['Sequence cohesion','Coverage sufficient for editing','Reflection'],['Assemble eight to twelve shots into a readable process.','Identify usable coverage and any missing or repeated moment.','Record a viewer response and one improvement.'],['Reorder three shots to make the action clearer.','Capture one missing detail or cutaway in 20 minutes.','Show the film once without explanation and note where the viewer hesitated.']]
]),
week(7,'Editing Fundamentals','Does this cut give new information or emotion?',7,['Organise footage into repeatable folders.','Edit the week-six process film.','Export for three destinations and compare.'],[
['Organise and ingest','post','A predictable folder structure saves time and protects originals. Keep source media, project files and exports distinct, with names that help you find takes. A backup needs another location, not just another folder on the same failing device. Check that copied files open before deleting anything.','Organise your footage, project and exports. Set a naming pattern and a backup plan. Save a screenshot or a written folder tree.',['Structure clarity','Naming consistency','Backup plan'],['Separate source media, projects and exports clearly.','Use a repeatable name pattern for your examples.','Describe an independent backup location and a check that files open.'],['Sort five files into source, project and export folders.','Rename three working copies using one consistent pattern.','Write where a second copy lives and how you will verify it.']],
['Rough cut','post','A rough cut tests order and meaning before polish. Use the week-six coverage to show the action clearly, remove duplicates and note missing moments. Cutting on action can connect angles; accidental black frames or direction changes may interrupt understanding.','Assemble the week-six process footage into a rough cut. Keep a cut log explaining why each change of shot belongs. Check continuity and the ending.',['Cut logic','Continuity','Rough-cut completeness'],['Give a reason for each main cut.','Check movement and action remain understandable.','Finish a viewable beginning, middle and end.'],['Explain and improve the weakest cut in 15 minutes.','Fix one jump in action or screen direction.','Add the missing ending or transition using existing coverage.']],
['Pace and sound','post','Pacing depends on how long viewers need to understand or feel something. In a J-cut the next audio starts before its picture; in an L-cut the previous audio continues under the new picture. Use those overlaps to connect meaning while keeping speech clear above ambience or music.','Revise the pace of your rough cut, add a deliberate J- or L-cut, and balance dialogue with ambience or music. Describe the effect and save a timeline screenshot if available.',['Pacing','Audio balance','J/L cut use'],['Explain and revise at least one too-long or too-short moment.','Keep important speech understandable over other sound.','Use or clearly diagram a motivated audio overlap.'],['Trim or extend one shot and compare the feeling.','Lower one competing sound and replay the sentence.','Create one audio overlap and explain why it joins the shots.']],
['Look and titles','post','Basic correction aims for consistent exposure and colour across shots before a dramatic look. Titles must be readable at the actual viewing size and stay on screen long enough to understand. Simple consistent styling can support a film more than many different effects.','Match the colour of neighbouring shots and add one readable title. Preview on a phone or intended screen and save a before-and-after note.',['Colour match','Title legibility','Consistency'],['Compare neighbouring shots for exposure and colour continuity.','Check title contrast, duration and safe placement on the destination screen.','Use a deliberate, consistent visual style.'],['Correct the most visibly mismatched pair of shots.','Enlarge, simplify or hold one hard-to-read title longer.','Remove one inconsistent title or visual effect.']],
['Prove it','post','A shorter cut forces priorities: preserve what carries the purpose and remove repetition. Export settings should fit the destination, but the exported file still needs playback review. Compare image, sound, titles and file behaviour rather than trusting the timeline preview.','Recut a 60-second film to 30 seconds. Prepare versions for YouTube, Instagram and WhatsApp using suitable formats. Compare the exports and explain what survived the shorter edit and why.',['Edit decisions explained','Export comparison','What survived and why'],['Explain the main decisions in reducing sixty seconds to thirty.','Compare three destination exports or clearly specified export plans.','Connect retained moments to the film’s purpose.'],['Explain and make one high-impact removal.','Replay or inspect one export and record a concrete issue.','Identify the three essential moments and justify keeping them.']]
]),
week(8,'Story Basics and Capstone','Why would a stranger care about this?',8,['Try three different openings.','Shoot and edit “One Place, One Person, One Minute”.','Ask three viewers where their attention dropped.'],[
['Story shape','pre','A mini-story has a situation, a change and a result. A list of facts may explain a place without giving viewers a reason to care. A person who wants something provides direction. Try openings that invite a question rather than promising something the film cannot deliver.','Turn a plain fact about your place into a mini-story. Identify beginning, middle and end, connect a person to a want, and write three possible openings.',['Story shape','Person-want link','Opening options'],['Describe a beginning, change and ending.','Connect a person with something they want.','Write three meaningfully different openings.'],['Rewrite the middle around one change in 15 minutes.','Finish the sentence “This person wants…” with a specific outcome.','Write one visual, one question-led and one action-led opening.']],
['Person, want, obstacle','pre','A small obstacle creates movement without manufacturing conflict. Choose someone you can approach respectfully and film with permission. A Viewer Card and purpose line should connect that person’s situation with a stranger’s reason to watch. Avoid making claims about a person that they have not shared.','Choose a person or a clearly labelled fictional stand-in. State their want and obstacle, then write your Viewer Card and capstone purpose line.',['Want clarity','Obstacle','Purpose and viewer'],['Describe a specific want in plain language.','Name a credible obstacle without inventing personal facts.','Connect the story to a viewer and intended takeaway.'],['Replace a vague wish with a visible, filmable goal.','Identify one real small difficulty and confirm your understanding.','Rewrite the purpose for a viewer unfamiliar with the person.']],
['Interview and voice-over','production','Open questions invite stories; leading questions may impose your conclusion. Ask permission, keep the setting comfortable and listen before preparing the next question. A short voice-over can connect images but should not repeat everything the viewer already sees.','Prepare five open interview questions. Conduct a short consensual interview, or role-play it explicitly. Transcribe the best answer and draft a brief voice-over.',['Question quality','Approach and rapport note','VO clarity'],['Write five questions that invite more than yes or no.','Describe consent, comfort and how you listened.','Draft a clear voice-over that adds useful information.'],['Rewrite two leading questions as open invitations.','Add a short permission and comfort check to your interview plan.','Cut one repetitive voice-over sentence and read the rest aloud.']],
['Hooks, endings and shoot','production','An opening sets an expectation; an ending should answer or develop it. Plan the capstone around the person, place and purpose rather than collecting attractive but unrelated shots. A Shot Reasoning Log helps you notice missing evidence while you can still film it.','Make the capstone shot list, including hook and ending. Shoot your planned coverage with permissions and write “This shot exists to…” for each shot. Save one representative still.',['Hook','Ending','Shot-purpose alignment'],['Create an opening that honestly invites interest in this story.','Plan an ending connected to the opening and purpose.','Give a purpose-linked reason for each planned or captured shot.'],['Try one alternative opening shot in 20 minutes.','Capture or storyboard one ending that resolves your opening.','Replace one decorative shot with a meaningful story detail.']],
['Capstone and review','post','Your capstone brings intention, camera work, sound and editing together. Compare it with the first baseline using evidence. Ask three viewers where attention dropped and make a focused revision. A self-check completes the beginner journey; an optional mentor demo review is separate and is not a professional credential.','Finish “One Place, One Person, One Minute”: a 60–90 second film. Include your purpose line, Shot Reasoning Log, Settings Log, three viewer responses and what you would change. Save your final reflection; optionally try a mentor review.',['Story and intent','Craft control','Process and reflection'],['Tell a readable 60–90 second story with a clear purpose.','Explain exposure, sound and editing decisions using your own evidence.','Include the required logs, three viewer responses and a baseline comparison.'],['Make one edit that clarifies the person’s want or outcome.','Improve the weakest exposure, sound or editing issue in 25 minutes.','Complete one missing log or viewer response and state your next experiment.']]
])];
export const basicKeys=basicPaths.flatMap(p=>p.lessons.map((_,i)=>p.id+'-'+i));
export function basicContext(profile:any){const goal=profile?.goal||'Explore videography';const subject=profile?.subject?.trim()||(/product|business|reel/i.test(goal)?'one product you can access':/edit|clips/i.test(goal)?'the subject in your existing clips':'one familiar everyday place or action');return {version:curriculumVersion,level:'basic',goal,subject,paceDays:profile?.paceDays||7,practiceMode:profile?.practiceMode||'core',viewer:/product|business|reel/i.test(goal)?'A scrolling customer, possibly watching without sound.':'A viewer who does not yet know this subject.',approach:/edit|clips/i.test(goal)?'Reuse your existing clips. Add only two or three missing shots when useful.':'Return to this subject as you practise each new skill.',people:profile?.people||'Ask permission before filming identifiable people.'};}
export const journalTypes=[{id:'noticing',name:'Noticing Journal',prompt:'10 minutes · 15 observations · at least five specifics. Notice light, detail, behaviour, contrast and change.'},{id:'shots',name:'Shot Reasoning Log',prompt:'Shot number | “This shot exists to…” | What the viewer should understand or feel.'},{id:'settings',name:'Settings Log',prompt:'Date | Shot | Resolution / fps | Shutter | ISO / EV | White balance | Focus | Why.'},{id:'deconstruction',name:'Weekly Deconstruction',prompt:'Study 2–3 minutes of a film you can access. Count shots, estimate average shot length and notice where sound leads.'},{id:'decisions',name:'Decision Journal',prompt:'Three choices | Alternative considered | Why I chose this | What happened.'}];
export const templateNames=['Purpose Line Checklist','Viewer Card','Noticing Journal','Shot Reasoning Log','Camera Card and Pre-flight Checklist','Settings Log','Shot Size Ladder','Light Map','Coverage Checklist','Folder and Naming Guide','Interview Question Sheet','Reflection Sheet'];

// Creator-owned resources; linked and embedded, never copied or represented as Framepath productions.
basicPaths[0].lessons[0].video={"id": "WMcWLFtGnAs", "title": "Directing Without Words: Visual Storytelling in Film", "by": "StudioBinder", "focus": "Notice the intended feeling and the visual evidence that creates it."};
basicPaths[0].lessons[1].video={"id": "WMcWLFtGnAs", "title": "Directing Without Words: Visual Storytelling in Film", "by": "StudioBinder", "focus": "Watch as an unfamiliar viewer: what context does the opening give you?"};
basicPaths[0].lessons[2].video={"id": "WMcWLFtGnAs", "title": "Directing Without Words: Visual Storytelling in Film", "by": "StudioBinder", "focus": "Notice meaningful details, behaviour and changes before naming camera techniques."};
basicPaths[0].lessons[3].video={"id": "AyML8xuKfoc", "title": "Every Shot Size Explained", "by": "StudioBinder", "focus": "Look for place, action and detail, then connect each shot to a purpose."};
basicPaths[0].lessons[4].video={"id": "FVR8zz8ci2k", "title": "Six Essential Film Editing Techniques", "by": "StudioBinder", "focus": "Notice how different ordering changes information or emotion."};
basicPaths[1].lessons[0].video={"id": "SsIEcGbwgN0", "title": "Shutter Speed and the Exposure Triangle", "by": "StudioBinder", "focus": "Focus on the relationship between frame rate, shutter and recorded movement."};
basicPaths[1].lessons[1].video={"id": "cy9wPDKd-dU", "title": "Camera ISO and the Exposure Triangle", "by": "StudioBinder", "focus": "Notice brightness, noise and the trade-offs in an exposure choice."};
basicPaths[1].lessons[2].video={"id": "SsIEcGbwgN0", "title": "Shutter Speed and the Exposure Triangle", "by": "StudioBinder", "focus": "Compare the feel of motion at different shutter settings."};
basicPaths[1].lessons[3].video={"id": "APLq7aPlDhk", "title": "Colour Temperature and White Balance", "by": "StudioBinder", "focus": "Focus on automatic versus deliberate white balance; use the reading for the focus test."};
basicPaths[1].lessons[4].video={"id": "cy9wPDKd-dU", "title": "Camera ISO and the Exposure Triangle", "by": "StudioBinder", "focus": "Revisit the exposure examples and compare them with your settings log."};
basicPaths[2].lessons[0].video={"id": "AyML8xuKfoc", "title": "Every Shot Size Explained", "by": "StudioBinder", "focus": "Identify which information each shot size includes or excludes."};
basicPaths[2].lessons[1].video={"id": "qQNiqzuXjoM", "title": "Camera Framing and Visual Storytelling", "by": "StudioBinder", "focus": "Look at subject placement, eyelines and relationships within the frame."};
basicPaths[2].lessons[2].video={"id": "qQNiqzuXjoM", "title": "Camera Framing and Visual Storytelling", "by": "StudioBinder", "focus": "Notice how foreground and background influence attention."};
basicPaths[2].lessons[3].video={"id": "T0YHA2yxCwM", "title": "Aspect Ratios in Film", "by": "StudioBinder", "focus": "Compare the information available in differently shaped frames."};
basicPaths[2].lessons[4].video={"id": "AyML8xuKfoc", "title": "Every Shot Size Explained", "by": "StudioBinder", "focus": "Compare the shot-size ladder with your own six-frame sequence."};
basicPaths[3].lessons[0].video={"id": "r2nD_knsNrc", "title": "Cinematic Lighting: Types of Light", "by": "StudioBinder", "focus": "Notice direction and the difference between hard and soft shadow edges."};
basicPaths[3].lessons[1].video={"id": "hGEsOcF3PoM", "title": "The Basics of Lighting for Film", "by": "Cinecom.net", "focus": "Apply the light-control ideas to one window and a white card."};
basicPaths[3].lessons[2].video={"id": "APLq7aPlDhk", "title": "Colour Temperature and White Balance", "by": "StudioBinder", "focus": "Look for how differently coloured sources affect the same subject."};
basicPaths[3].lessons[3].video={"id": "r2nD_knsNrc", "title": "Cinematic Lighting: Types of Light", "by": "StudioBinder", "focus": "Use the hard-versus-soft comparison to plan a shade or reflector rescue."};
basicPaths[3].lessons[4].video={"id": "r2nD_knsNrc", "title": "Cinematic Lighting: Types of Light", "by": "StudioBinder", "focus": "Compare the intended mood with the chosen light direction and quality."};
basicPaths[4].lessons[0].video={"id": "wbEt3IBCMI8", "title": "A Vlogger’s Guide to Better Sound", "by": "RØDE", "focus": "Listen for the relationship between a voice and its surroundings."};
basicPaths[4].lessons[1].video={"id": "wbEt3IBCMI8", "title": "A Vlogger’s Guide to Better Sound", "by": "RØDE", "focus": "Focus on microphone distance and unwanted background sound."};
basicPaths[4].lessons[2].video={"id": "wbEt3IBCMI8", "title": "A Vlogger’s Guide to Better Sound", "by": "RØDE", "focus": "Focus on monitoring and levels; follow the read-and-observe guide for the three-gain test."};
basicPaths[4].lessons[3].video={"id": "SBG3KXLyGcQ", "title": "Reduce Wind Noise When Recording Outside", "by": "RØDE", "focus": "Compare protection and positioning for an outdoor recording."};
basicPaths[4].lessons[4].video={"id": "wbEt3IBCMI8", "title": "A Vlogger’s Guide to Better Sound", "by": "RØDE", "focus": "Consider which sounds help a viewer understand the place and the words."};
basicPaths[5].lessons[0].video={"id": "iAZvLA_K94w", "title": "Panning and Tilting Camera Movements", "by": "StudioBinder", "focus": "Compare still holds with movement; rehearse a steady starting and ending frame."};
basicPaths[5].lessons[1].video={"id": "iAZvLA_K94w", "title": "Panning and Tilting Camera Movements", "by": "StudioBinder", "focus": "Watch how a pan or tilt reveals information."};
basicPaths[5].lessons[2].video={"id": "AyML8xuKfoc", "title": "Every Shot Size Explained", "by": "StudioBinder", "focus": "Plan the wide, medium, detail and cutaway coverage your editor will need."};
basicPaths[5].lessons[3].video={"id": "iW0bKUfvH2c", "title": "The 180 Degree Rule in Film", "by": "StudioBinder", "focus": "Diagram the line between subjects and the consistent screen direction."};
basicPaths[5].lessons[4].video={"id": "FVR8zz8ci2k", "title": "Six Essential Film Editing Techniques", "by": "StudioBinder", "focus": "Notice what coverage makes the cuts understandable."};
basicPaths[6].lessons[0].video={"id": "fYlwId_z_yU", "title": "Introduction to Editing · DaVinci Resolve 17", "by": "Blackmagic Design", "focus": "Use the media organisation and project workflow sections. Software controls may differ in your editor."};
basicPaths[6].lessons[1].video={"id": "fYlwId_z_yU", "title": "Introduction to Editing · DaVinci Resolve 17", "by": "Blackmagic Design", "focus": "Focus on assembling and trimming a first sequence. The full software tutorial is longer than this session’s viewing block."};
basicPaths[6].lessons[2].video={"id": "FVR8zz8ci2k", "title": "Six Essential Film Editing Techniques", "by": "StudioBinder", "focus": "Find the split-edit examples: J-cuts and L-cuts."};
basicPaths[6].lessons[3].video={"id": "APLq7aPlDhk", "title": "Colour Temperature and White Balance", "by": "StudioBinder", "focus": "Review neutral colour and consistency, then use the reading for titles and export checks."};
basicPaths[6].lessons[4].video={"id": "fYlwId_z_yU", "title": "Introduction to Editing · DaVinci Resolve 17", "by": "Blackmagic Design", "focus": "Use the export section and compare your actual destination files. Controls vary by software version."};
basicPaths[7].lessons[0].video={"id": "tvqjp1CxxD8", "title": "Three Act Structure Explained", "by": "StudioBinder", "focus": "Reduce the structure to a beginning, a change and an ending."};
basicPaths[7].lessons[1].video={"id": "tvqjp1CxxD8", "title": "Three Act Structure Explained", "by": "StudioBinder", "focus": "Identify a person, what they want, and what stands in their way."};
basicPaths[7].lessons[2].video={"id": "wbEt3IBCMI8", "title": "A Vlogger’s Guide to Better Sound", "by": "RØDE", "focus": "Use the recording advice for a clear interview; follow the reading for questions, rapport and voice-over."};
basicPaths[7].lessons[3].video={"id": "WMcWLFtGnAs", "title": "Directing Without Words: Visual Storytelling in Film", "by": "StudioBinder", "focus": "Notice how an opening and ending communicate without explanation."};
basicPaths[7].lessons[4].video={"id": "3QRrsiMe4wI", "title": "The Pen · A Short Film", "by": "StudioBinder", "focus": "Deconstruct this short film, then compare your own story intent and decisions. The example is shorter than the viewing block."};
