import {pathLessons} from './lessons/content';
import {coursePaths as basicPaths} from './selfpaced-curriculum';
export type Lesson={title:string;minutes:number;learn:string;do:string;checks:string[];resource:number};
export const resources=[
 {title:'Framing and composition',by:'StudioBinder',videoId:'qQNiqzuXjoM',url:'https://www.youtube.com/watch?v=qQNiqzuXjoM',type:'YouTube lesson',note:'Place, action, detail.'},
 {title:'Camera angles and their meaning',by:'StudioBinder',videoId:'wLfZL9PZI9k',url:'https://www.youtube.com/watch?v=wLfZL9PZI9k',type:'YouTube lesson',note:'Choose the feeling of a shot.'},
 {title:'Frame your first sequence',by:'StudioBinder',videoId:'qQNiqzuXjoM',url:'https://www.youtube.com/watch?v=qQNiqzuXjoM',type:'YouTube lesson',note:'Apply wide, medium and close shots with your phone.'},
 {title:'Introduction to editing · DaVinci Resolve 17',by:'Blackmagic Design',videoId:'fYlwId_z_yU',url:'https://www.blackmagicdesign.com/products/davinciresolve/training',type:'YouTube lesson',note:'An introduction to editing principles. Software controls may differ in newer versions.'},
 {title:'The basics of light for video',by:'Cinecom.net',videoId:'hGEsOcF3PoM',url:'https://www.youtube.com/watch?v=hGEsOcF3PoM',type:'YouTube lesson',note:'Learn light direction, then try it with your window.'}
];
export const legacyPaths:{id:string;title:string;short:string;description:string;outcome:string;duration:string;number:string;lessons:Lesson[]}[]=[
{id:'product-reel',title:'Your first product reel',short:'Make something worth stopping for.',description:'Turn one product, your phone and a window into a 15–30 second video.',outcome:'A finished vertical product reel',duration:'5 sessions · about 4 hours',number:'01',lessons:[
{title:'Find the one thing worth saying',minutes:25,learn:'A useful product video makes one clear promise. Pick one viewer and one reason this product matters to them. Avoid trying to explain every feature in the same reel.',do:'Pick a real product beside you. Shoot two 5-second tests: the product sitting still, then someone using it. Watch both and write three lines: your viewer, the visible benefit and the closing action.',checks:['I named one specific viewer','My benefit can be shown on camera','I have one clear closing action'],resource:2},
{title:'Build a five-shot story',minutes:35,learn:'A wide shot introduces the setting. A medium shot shows use. Close shots reveal texture or detail. A simple beginning, middle and end makes separate clips feel connected.',do:'Use your phone to capture five test stills: introduction, detail, product in use, result and closing hero shot. Arrange them in story order. Label each frame with its action and intended 3–6 second duration.',checks:['Each shot has a different purpose','My opening makes the product clear','My last shot leaves room for a caption'],resource:0},
{title:'Film beside a window',minutes:60,learn:'A large window can give soft directional light. Place the product to one side of it, turn off competing room lights and check the brightest area. Keep the camera steady and leave a little time before and after each action.',do:'Clean the lens. Record vertically at 1080p if available. Film two takes of your five shots, keeping the background simple. Capture an extra close-up as a backup.',checks:['Focus stays on the product','Bright areas retain visible detail','All five shots use the same orientation'],resource:4},
{title:'Give your edit a rhythm',minutes:70,learn:'Start with the clearest image, remove waiting time and cut when the viewer has understood the action. Music supports the story; it should not conceal weak visuals. Use music you have permission to use.',do:'Create a 15–30 second sequence in an editor available to you. Use straight cuts first. Add one readable benefit caption and a closing action. Export a draft and watch it on your phone.',checks:['The product appears early','Captions fit within the safe area','Audio is comfortable and licensed'],resource:3},
{title:'Review, refine and share',minutes:35,learn:'Watch your reel once without sound and once with sound. If the idea only works when you explain it, simplify the sequence. A focused revision teaches more than adding another effect.',do:'Write what works, one change you made and one thing to improve next time. Upload a still or attach your video link. Ask AI for a first-pass check of your written plan or still, then make your own final choice.',checks:['The reel is 15–30 seconds','The benefit is clear without explanation','I recorded one lesson for my next shoot'],resource:0}
]},
{id:'everyday-story',title:'Your first everyday story',short:'Make the ordinary worth watching.',description:'Film one familiar action and shape it into a 30-second story.',outcome:'A 20–40 second everyday film',duration:'5 sessions · about 4 hours',number:'04',lessons:[
{title:'Find a story in the everyday',minutes:25,learn:'A small action can carry a complete story. A cup of tea, a plant being watered or a workspace being prepared has a beginning, a change and an ending.',do:'Try filming a familiar action in one 10-second take, such as pouring water. Watch it back. Pick its beginning, change and ending, then describe the feeling you want to create in your film.',checks:['I can film the action with permission','My story has a beginning and ending','I named a feeling for the viewer'],resource:0},
{title:'Plan your five-shot sequence',minutes:35,learn:'Different shot sizes give an edit useful choices. Show where we are, what is happening and one detail that matters.',do:'Take five test stills of your action: one wide view, two medium views and two details. Arrange them as a storyboard. Label what changes in each frame before the final shoot.',checks:['I included place, action and detail','Each shot adds new information','My order follows the action'],resource:0},
{title:'Film with the light you have',minutes:60,learn:'A steady phone and a single window can be enough. Light the subject from the side and keep the background simple.',do:'Record two takes of each planned shot. Keep the phone orientation consistent and record a few seconds before and after each action.',checks:['The subject stays in focus','The orientation stays consistent','I recorded extra time around the action'],resource:4},
{title:'Make your first story edit',minutes:70,learn:'Clarity comes before effects. Arrange the action, remove repeated moments and use sound to help the viewer follow.',do:'Use an editor available to you to create a 20–40 second sequence. Start with straight cuts. Check it once with sound and once without.',checks:['The action is clear without explanation','Cuts have no accidental gaps','Any audio is mine or used with permission'],resource:3},
{title:'Watch, revise and keep it',minutes:35,learn:'A finished first film is a starting point. Compare it with your original intention and choose one meaningful revision.',do:'Make one revision. Save your film or a viewing link with a note about your biggest discovery and the next thing you want to practise.',checks:['I made one deliberate revision','I reviewed the exported film','I recorded my next practice goal'],resource:1}
]},
{id:'natural-light',title:'Better light, with your phone',short:'Find your light before your gear.',description:'Understand window light and make a clear before-and-after lighting study.',outcome:'A two-setup product lighting study',duration:'4 sessions · about 3 hours',number:'02',lessons:[
{title:'Learn to see direction',minutes:30,learn:'Move an object around a window and watch where the shadow falls. Front light can feel even; side light reveals texture. Back light needs care because your phone may darken the subject.',do:'Take three stills of the same object with the window in front, beside and behind it. Label each position and describe the mood you notice.',checks:['The object stays the same','I labelled the light direction','I can point to a change in the shadow'],resource:4},
{title:'Control the contrast',minutes:45,learn:'The bright side and shadow side do not need to match. A white card can gently lift a shadow; a dark surface can deepen it. Reflectors should stay stable and away from heat.',do:'Place your object beside a window. Photograph it without a reflector, then with a white sheet of paper outside the frame. Compare the texture and shape in both shots.',checks:['The window position is consistent','The reflector is outside the frame','I can explain which version fits the product'],resource:4},
{title:'Keep exposure and focus steady',minutes:45,learn:'Automatic exposure can change during a shot. If your phone supports exposure and focus lock, practise using them. Protect highlights and avoid digital zoom when moving closer would work.',do:'Record two 10-second clips of a hand using the product. Compare automatic settings with locked settings if supported. Write down the trade-off you see.',checks:['The subject stays sharp','Brightness does not distract from the action','The hand and product fit inside the frame'],resource:1},
{title:'Make your lighting study',minutes:45,learn:'A before-and-after comparison is useful evidence when the framing stays consistent. Describe what you changed rather than simply calling one shot better.',do:'Select two stills or clips with identical framing and different light control. Upload one representative still, link the full comparison and explain which setup you would repeat.',checks:['I changed one lighting variable','I described the reason for my choice','I saved the setup so I can repeat it'],resource:4}
]},
{id:'first-edit',title:'Turn clips into a story',short:'Make the pieces belong together.',description:'Shape existing clips into a short, clear sequence with clean sound and captions.',outcome:'A polished 20–40 second edit',duration:'5 sessions · about 4 hours',number:'03',lessons:[
{title:'Choose a story, then your clips',minutes:30,learn:'Organising clips around a simple action prevents the edit from becoming a collection of unrelated moments. Keep your original media safe and edit copies or linked project files.',do:'Choose 6–10 clips you own. Give the sequence a one-sentence idea. Label each clip as beginning, middle, ending or backup.',checks:['I have permission to use the clips','I can describe the story in one sentence','My originals are backed up'],resource:3},
{title:'Build the first assembly',minutes:50,learn:'The first assembly establishes order. Leave transitions and effects alone while you decide what belongs. A missing moment may be solved by a cutaway rather than another long shot.',do:'Arrange a beginning, middle and ending. Remove repeats. Export a rough 20–40 second cut and note any moment that feels confusing.',checks:['The action has a beginning and ending','I removed repeated information','I recorded one unclear moment'],resource:3},
{title:'Cut for clarity',minutes:50,learn:'A cut changes what the viewer pays attention to. Try cutting near an action and compare it with cutting after the action. Keep continuity clear before experimenting with speed.',do:'Make two versions of one transition: on action and after action. Pick the clearer version. Trim the full sequence until every shot has a purpose.',checks:['There are no accidental black frames','The action is understandable','My pacing matches the subject'],resource:0},
{title:'Add sound and accessible captions',minutes:45,learn:'Dialogue must remain intelligible beneath music. Captions should stay visible long enough to read and contrast with the background. Check the actual phone screen rather than only your editor preview.',do:'Balance dialogue or natural sound, add licensed music only if useful, and write accurate captions. Watch with sound muted and check names and spelling.',checks:['Speech is clear','Captions are accurate and readable','I have permission for the audio'],resource:3},
{title:'Export with intention',minutes:45,learn:'Match the export to the place you intend to show it. A vertical reel and a widescreen story have different framing needs. Review the exported file, not only the timeline.',do:'Export a 20–40 second video, watch it from beginning to end and attach a viewing link or upload a file. Record your biggest improvement and one next experiment.',checks:['The aspect ratio fits my destination','The exported file plays correctly','I reviewed the final sound and captions'],resource:3}
]}
];
// Rebuilt sessions keep their historical keys so saved work remains attached.
for(const path of legacyPaths){const lessons=pathLessons(path.id);if(!lessons.length)continue;path.duration=`${lessons.length} sessions · ${lessons.reduce((n,l)=>n+l.minutes,0)} minutes of guided practice`;path.lessons=lessons.map((l,i)=>({...path.lessons[i],title:l.title,minutes:l.minutes,learn:l.concept.text,do:l.make.steps.join(' '),checks:[...l.reflect]}));}
export const weeks:Lesson[]=[
{title:'See your starting point',minutes:360,learn:'Good filming begins with observation. Learn how framing, steadiness and a clear subject change a shot before adding equipment.',do:'Film a 20–30 second everyday action with a beginning and ending. Write your intention, equipment and biggest difficulty. This is your baseline for week 12.',checks:['I recorded a baseline','My subject is clear','I wrote a short reflection'],resource:2},
{title:'Cover one simple action',minutes:360,learn:'Wide, medium and close shots help a viewer understand place, action and detail. Coverage gives your edit choices.',do:'Film a five-shot sequence of a simple action such as making tea. Include a wide shot, medium shot and meaningful close-ups.',checks:['I used three shot sizes','I kept screen direction consistent','My sequence makes sense'],resource:0},
{title:'Make light work for you',minutes:360,learn:'Direction, softness and contrast shape the image. Work with one window before adding another light source.',do:'Film the same subject in two lighting setups. Include a still from each and explain which supports your intention.',checks:['I protected highlights','My focus is steady','I explained the lighting choice'],resource:4},
{title:'Project 1 · The everyday story',minutes:360,learn:'Continuity helps separate shots feel like one action. Look for matching positions, movement and sound across cuts.',do:'Finish a 30–45 second everyday story from your coverage. Submit your cut, shot list and reflection for a mentor review.',checks:['My story has a clear progression','The edit has no accidental gaps','I responded to earlier feedback'],resource:3},
{title:'Listen before you record',minutes:360,learn:'A quiet location and a close microphone often matter more than effects later. Test the sound and listen with headphones.',do:'Record 20 seconds of clean natural sound and a short spoken line. Compare two recording distances and describe the difference.',checks:['Speech is intelligible','There is no distracting clipping','I saved room tone'],resource:3},
{title:'Plan a product story',minutes:360,learn:'A brief links audience, benefit and creative choices. Plan the story around one visible benefit and a realistic shoot.',do:'Choose a product, write a one-page brief and make a six-shot storyboard. Include props, location, lighting and a simple schedule.',checks:['I identified the audience','Each shot supports the benefit','My plan fits my time and gear'],resource:0},
{title:'Shape the rough cut',minutes:360,learn:'An early rough cut reveals missing coverage while you still have time to reshoot. Prioritise clarity before visual polish.',do:'Film your product story and create a 30–45 second rough cut. Ask for first-pass feedback on your shot list or a still, then list two changes for your mentor.',checks:['I finished a rough cut','I identified two specific issues','I planned any necessary pickup shots'],resource:3},
{title:'Project 2 · The product film',minutes:360,learn:'A finished product film needs clear messaging, consistent framing and controlled sound. Revisions should answer the brief.',do:'Submit the final 30–45 second product film, a still and a reflection on changes made after review.',checks:['My benefit is clear','Titles and audio are readable','I documented my revisions'],resource:3},
{title:'Find a short story',minutes:360,learn:'A small, filmable idea is more useful than a complex idea you cannot finish. Find a change, a desire or a discovery that can happen in one location.',do:'Pitch a 60–90 second story. Include a one-paragraph outline, shot plan, permissions and a schedule. Get the concept reviewed before filming.',checks:['My story has a change','I can film it with available resources','I have permission from participants'],resource:4},
{title:'Produce your short film',minutes:360,learn:'A shot list helps the shoot stay focused, but you should also notice moments that support the story. Check picture and sound before moving locations.',do:'Film your planned shots and assemble a rough cut. Keep backups and attach a note about any changes from the plan.',checks:['I captured the essential shots','I checked sound on location','I backed up my footage'],resource:1},
{title:'Revise with purpose',minutes:360,learn:'Feedback becomes useful when you turn it into specific changes. Choose a few high-impact revisions and compare the results.',do:'Revise your short film after mentor feedback. Check story, framing, exposure, pacing and sound. Prepare a before-and-after reflection.',checks:['I acted on the review','I checked the complete export','I can explain my key creative choices'],resource:3},
{title:'Project 3 · Your next frame',minutes:360,learn:'Your final work shows how your decisions have changed. Compare it with your baseline using evidence rather than confidence alone.',do:'Submit a 60–90 second short film and select your three portfolio pieces. Compare with week 1, describe your contribution and complete a final mentor review.',checks:['I submitted three projects','I compared my final work with the baseline','I identified my next learning goal'],resource:4}
];
export const mentors=[
{id:'maya',name:'Maya',initials:'M',focus:'Visual storytelling',tagline:'Learn to notice. Then learn to frame.',bio:'A fictional pilot mentor for learners who want to make everyday stories and short films. This teaching style starts with observation and builds toward deliberate camera choices.',style:'Story first · Gentle, specific critique · Weekly practice',slots:['Tuesday · 7:00 pm IST','Thursday · 7:30 pm IST'],sample:'Your close-up makes the action clear. Try one wider opening shot so we know where we are. Keep the final reaction a little longer: that is where the story lands.',blueprint:'Prioritise intent, visual storytelling, coverage and reflection. Use simple everyday scenes before product films. Give one observation, one question and one practical next step.',color:'forest'},
{id:'arjun',name:'Arjun',initials:'A',focus:'Product & lifestyle video',tagline:'Make every shot earn its place.',bio:'A fictional pilot mentor for learners interested in small-business videos and product films. This teaching style uses practical briefs and repeatable lighting setups.',style:'Brief first · Direct, practical critique · Repeatable setups',slots:['Saturday · 10:00 am IST','Saturday · 11:00 am IST'],sample:'The product is clear, but the benefit arrives late. Open with the product in use, then show the detail. Move the white reflector closer to soften the shadow on the label.',blueprint:'Prioritise audience, product benefits, lighting consistency, shot efficiency and repeatable editing workflows. Review against a practical small-business brief.',color:'ochre'}
];
export const rubric=[['Story & intent',25],['Framing & coverage',20],['Light & exposure',15],['Editing & pacing',20],['Sound',10],['Process & reflection',10]] as const;
export function freshState(){return {profile:null,membership:null,craft:null,progress:{},assessments:{},drafts:{},submissions:[],messages:[],checkins:[],bookings:[],receipts:[],portfolio:{title:'My videography journey',bio:'',ids:[],token:null}}}
export type State=ReturnType<typeof freshState> & any;


export const paths=[...basicPaths,...legacyPaths];
