export type Discovery={hook:string;question:string;choices:[string,string][];best:number;topics:[string,string];example:string;experiment?:'exposure'|'frame'|'sound'|'sequence'};
const d=(hook:string,question:string,choices:[string,string][],best:number,topics:[string,string],example:string,experiment?:Discovery['experiment']):Discovery=>({hook,question,choices,best,topics,example,experiment});
// Authored teaching layer over the existing 40-session curriculum. These warm-ups are ungraded.
export const discovery:Record<string,Discovery>={
'basic-w1-0':d('One café. Two different films.','You want someone to feel the café is a calm place to read. Which opening earns its place?',[
 ['A quiet page turning beside a cup','The detail supports a feeling of calm. The shot has a job, beyond showing a café.'],['A fast montage of the entire menu','That could help someone choose lunch. It serves a different purpose.'],['A spinning logo','A logo identifies the place, but gives little evidence of what it feels like.']],0,['Topic or purpose?','Give each shot a job'],'“A café” is a topic. “Help a busy student picture a peaceful break” is a purpose. The second sentence changes which moments you film.'),
'basic-w1-1':d('Your viewer has the sound off.','A customer watches on a crowded bus. What should the first shot do?',[
 ['Rely on a spoken introduction','They may miss the point entirely with the sound off.'],['Show the product solving a recognisable problem','A visible action can communicate before a voice-over is heard.'],['Save all context for the final title','The viewer needs enough context to decide to keep watching.']],1,['Picture one viewer','Let context shape the opening'],'A commuter seeing a leaking bottle replaced by a sealed one gets useful information without audio. The same opening might need more explanation for someone unfamiliar with the product.'),
'basic-w1-2':d('Spot the detail worth filming.','Which observation gives you a specific moment to capture?',[
 ['The market is interesting','This is an impression. Look for visible evidence of what interests you.'],['There are people everywhere','This describes the setting, but not a revealing moment.'],['A seller straightens one bruised fruit before a customer arrives','This gives you a behaviour, an object and a moment that may reveal care.']],2,['Observe before naming','Connect a detail to meaning'],'“The kitchen is busy” becomes “flour hangs in the light as a hand pauses above the dough.” The second observation suggests a shot and a rhythm.'),
'basic-w1-3':d('What is missing from these shots?','You have a close-up of coffee and a hand pouring it. What helps a new viewer locate the action?',[
 ['A view of the counter and its surroundings','A place shot supplies context; the close-ups can then add useful detail.'],['Another almost identical cup close-up','This repeats information rather than locating the action.'],['A faster transition','A transition cannot supply missing visual information.']],0,['Place, action, detail','Hold for the editor'],'A wide counter, a medium pouring action and a close-up of rising steam answer where, what and what to notice. Hold each shot so the editor can choose its beginning and end.'),
'basic-w1-4':d('The same footage can disagree.','How would you turn a peaceful café study into a study of morning pressure?',[
 ['Keep every shot and only change the title','The title claims a change; the images still need to support it.'],['Choose queues, quick hands and interruptions','Those details offer evidence of pressure. Order and duration can strengthen that reading.'],['Add the most dramatic filter','A look can affect mood but does not replace meaningful choices.']],1,['Order creates meaning','Compare with evidence'],'A lingering empty table followed by a slow pour suggests calm. A queue followed by several interrupted orders suggests pressure. Ask viewers what they actually understood.'),
'basic-w2-0':d('Your camera changes its mind.','You pan past a bright window and the room suddenly goes dark. What is worth testing first?',[
 ['A different logo','The change happened during capture; branding is unrelated.'],['More digital zoom','Zoom changes the view, not the automatic exposure decision.'],['Lock exposure on the subject, if supported','Compare an automatic take with a locked one to see whether brightness stays useful.']],2,['Meet your actual controls','Test before the take'],'Before filming a shop, replay ten seconds that include its bright doorway. A quick test can reveal exposure shifts, flicker or focus hunting before the important action.'),
'basic-w2-1':d('Brighter is not always better.','A pale label sits beside a dark object. Move the exposure and watch which details disappear.',[
 ['Always choose the brightest version','Brightening may erase the label. Choose the information that matters to your viewer.'],['Keep the important detail readable','Good exposure serves your intention; the middle setting is not automatically correct in every scene.'],['Fix every clipped highlight later','Once detail is not recorded, bright areas may have nothing useful to recover.']],1,['What exposure changes','Brightness has trade-offs'],'For a product label, protect readable lettering. For a silhouette, a dark subject may be intentional. Describe what the viewer needs to see before choosing a level.','exposure'),
'basic-w2-2':d('Crisp or smeared: which feels right?','The frame rate stays the same. A faster shutter makes a moving hand look more frozen in each frame. What changed?',[
 ['Blur inside each frame','Shutter time affects motion blur. It is different from how many frames are recorded each second.'],['The number of frames per second','Frame rate has not changed in this comparison.'],['The length of the finished story','A shutter change does not set the edit length.']],0,['Frames versus shutter','Choose a motion feeling'],'A pour shot with a short shutter can show crisp droplets. A longer shutter can smear them. Compare at the same playback speed and keep the action similar.'),
'basic-w2-3':d('Why did the white cup turn orange?','One side of a room has daylight and another has a warm lamp. What would make a useful test?',[
 ['Change colour, focus and angle together','Too many changes make the cause hard to identify.'],['Assume auto white balance is always wrong','Auto can be useful. Compare its behaviour in this particular scene.'],['Compare auto and set white balance in the same framing','You can then point to what changed, including whether neutral objects stayed consistent.']],2,['Keep colour deliberate','Keep the intended subject sharp'],'Film a neutral object near each source, then test focus separately with a marked stopping point. A colour cast and a soft subject are different problems.'),
'basic-w2-4':d('Could you repeat your favourite take?','Which note would help you recreate a deliberate camera choice?',[
 ['“This one looked cinematic”','That describes a judgement but not a repeatable choice.'],['“Locked focus on the label; lowered exposure to keep the lettering”','The note connects a control to visible evidence and a purpose.'],['“Used the expensive camera”','The device name alone does not explain the result.']],1,['Log a reason, not just a number','Compare controlled results'],'If your subject was readable in shade but clipped in sun, note what you changed and what stayed constant. Your log becomes a guide for the next shoot.'),
'basic-w3-0':d('What disappears when you get closer?','Change the frame in this diagram. Which view best explains where the subject is?',[
 ['The wide view','It includes more context. A closer view can help later when detail becomes the priority.'],['The detail view','Detail can reveal texture, but it usually removes location clues.'],['Every view says the same thing','Framing changes available information even when the subject stays the same.']],0,['A frame includes and excludes','Choose the information'],'A whole workbench explains the setting. Hands explain the action. A stitch explains precision. Use each size for a different job.','frame'),
'basic-w3-1':d('Give the glance somewhere to go.','A subject looks to the right. What is a useful composition to compare with a tight right-edge crop?',[
 ['More empty space behind the head only','That may feel constrained. Decide whether that tension serves this scene.'],['Cutting off more of the face','An accidental crop can distract from the expression.'],['Room on the right, in the direction of the glance','Lead room can make the gaze feel connected to something beyond the frame.']],2,['Placement guides attention','Check the edges'],'Centre a stand-in, then move it left with space to its right. Compare balance and implied direction. The grid is a tool for a decision, not a rule to obey.'),
'basic-w3-2':d('Your background is stealing the scene.','A bright sign behind your subject gets all the attention. What is the simplest controlled comparison?',[
 ['Add several new foreground props','More layers can add clutter before solving the distraction.'],['Move slightly so the sign leaves the frame','A small position change can separate the subject and remove competing information.'],['Ignore it because the subject is on a third','A grid cannot guarantee a clear centre of attention.']],1,['Build useful layers','Remove a distraction'],'A doorway in the foreground, a maker in the middle and shelves behind can create depth. Check that a bright shelf label does not become the unintended subject.'),
'basic-w3-3':d('A vertical crop can lose the point.','A wide shot shows two people passing an object. A centre crop removes both hands. What next?',[
 ['Recompose the action for the taller frame','Move the camera or subjects so the exchange remains readable.'],['Keep the crop because it fills the screen','Filling the screen is not enough if the story information disappears.'],['Cover the missing action with a title','A title may explain the action but does not restore its visual evidence.']],0,['Change shape, preserve meaning','Leave room for the destination'],'For a phone story, stack the important action inside a tall frame. Check titles on the actual viewing screen, where interface overlays may cover the edges.','frame'),
'basic-w3-4':d('Six attractive frames. One boring sequence.','All six shots show the same object at the same size. What would add meaningful variety?',[
 ['Six different filters','The viewer still receives much the same information.'],['Random zooms on every cut','Movement without a reason can distract.'],['A setting, an action and a revealing detail','Each new frame can answer a different viewer question.']],2,['Vary information, not decoration','Check what a viewer understood'],'Start wide enough to locate a maker, move closer to a task, then show a small result. Ask what the viewer learned from each change of size.'),
'basic-w4-0':d('Read the shadow before the setting.','Which clue best distinguishes hard from soft light on a subject?',[
 ['The brand of the lamp','Apparent source size and the setup matter more than the label.'],['The sharpness of the shadow edge','Hard light makes more defined edges; a larger apparent source tends to soften them.'],['Whether the scene is indoors','Both hard and soft light are possible indoors and outdoors.']],1,['Find direction','Read quality from shadows'],'A small bare light can draw a crisp nose shadow. A broad window can make the transition gentler. Observe the edge before deciding which feeling fits.'),
'basic-w4-1':d('Can a white card become your second light?','Beside a window, one side of the subject is in deep shade. What can a white card do?',[
 ['Bounce some window light back into the shade','Compare the same frame with and without the card to see the effect.'],['Create light without a source','A reflector redirects existing light; it needs something to reflect.'],['Guarantee a completely shadowless image','Its effect depends on position, size and available light.']],0,['Move around the window','Control the shadow gently'],'Use side light to reveal texture, then bring a white card near the shaded side. Decide how much contrast suits the subject rather than removing every shadow.'),
'basic-w4-2':d('One face. Two colours.','Daylight lights one side; a warm lamp lights the other. Why might one white-balance setting disappoint?',[
 ['White balance controls focus instead','Focus and colour balance solve different problems.'],['Mixed light is always unusable','Colour contrast can be intentional when it supports the story.'],['The sources have different colours','One overall correction may not neutralise both; test removing or repositioning one source.']],2,['Name the competing sources','Change one source'],'Try a before-and-after with the lamp off. If the colour becomes more consistent but the scene feels flatter, you have a visible trade-off to choose between.'),
'basic-w4-3':d('The sun is too harsh. You have no lamp.','What is a useful first experiment with a bright, squinting subject?',[
 ['Move them into safe open shade','This can soften the light; check the background and exposure again.'],['Tell them to stare into the sun','Comfort and eye safety matter. Choose a different position.'],['Increase exposure until the shadows vanish','That can lose bright detail without improving the light direction.']],0,['Find a kinder source','Compare the rescue'],'A step under an awning may remove hard patches on a face. Reframe so the background does not overwhelm the subject, then compare the two versions.'),
'basic-w4-4':d('Same subject. Different mood.','How would you make a convincing comparison of two lighting intentions?',[
 ['Change subject, location and camera for each','It becomes difficult to isolate what the light contributed.'],['Keep the subject similar and explain the light change','Controlled comparisons connect direction and quality to the feeling.'],['Ask a viewer only whether they liked it','Ask what it felt like, then compare that response with your intention.']],1,['Light for a purpose','Let a viewer test the mood'],'Make a welcoming version and a more tense version of one subject. Keep a diagram of each source and ask viewers which feeling each version communicates.'),
'basic-w5-0':d('Close your eyes. Is the place still there?','Which sound would make a bakery scene more specific?',[
 ['Only a generic music track','Music can set mood, but may not tell us what this place sounds like.'],['Digital silence between every word','Abrupt silence can make edits feel disconnected.'],['Trays moving and the oven door closing','Specific sounds can establish the place and support what the images show.']],2,['Listen in layers','Choose what matters'],'Separate a voice, meaningful actions and background ambience. Note what helps a viewer understand the scene and what masks the important sound.'),
'basic-w5-1':d('Louder is not the same as clearer.','A distant voice is buried in traffic. What should you test before simply raising gain?',[
 ['Move the microphone closer, without obstructing the speaker','A closer position can improve the voice relative to background noise.'],['Turn everything up','Gain also raises unwanted sound captured by the microphone.'],['Add music louder than the traffic','This may make speech still harder to understand.']],0,['Distance changes the balance','Test placement by listening'],'Compare the same sentence at two safe microphone distances. Keep the recording settings similar and listen for voice clarity, room echo and handling noise.'),
'basic-w5-2':d('The loudest take may be the damaged one.','Move the simulated peak level. What is the useful aim while recording a varying voice?',[
 ['Keep peaks at the digital ceiling','Unexpected loud syllables may clip. Leave headroom.'],['Keep speech clear with room for louder moments','Monitor a real test recording; this meter only illustrates the margin before clipping.'],['Record so low that the voice is barely audible','Turning up a very low recording can reveal unwanted noise.']],1,['Levels and headroom','Monitor the actual recording'],'A quiet rehearsal does not predict a sudden laugh. Ask for a louder line during the sound check, watch the meter and replay it on headphones.','sound'),
'basic-w5-3':d('The cut sounds like a hole.','Speech edits leave abrupt gaps in the room sound. What recording may help smooth those joins?',[
 ['Unrelated loud music','It can hide the issue while introducing a different atmosphere.'],['A random outdoor recording','It may not match the original acoustic space.'],['Room tone captured in the same setup','Matching ambience can bridge edits while preserving a believable space.']],2,['Capture the room','Reduce problems at the source'],'Record a quiet stretch of the actual room after the interview. Outdoors, test safe shelter and suitable wind protection before hoping to repair the sound later.'),
'basic-w5-4':d('Could someone follow it without the picture?','What is the strongest check of a sound-led study?',[
 ['Listen without watching and note what is understandable','This exposes unclear words and missing place or action cues.'],['Look only at a colourful waveform','A waveform shows level patterns, not whether a sentence makes sense.'],['Use the most expensive export setting','Export settings do not repair unclear capture.']],0,['Build a readable sound scene','Compare ears with intention'],'Play your study with the screen hidden. Ask what place, action or words a listener recognised, then compare the answer with the role you gave each sound.'),
'basic-w6-0':d('A moving subject does not need a moving camera.','Hands are doing delicate work. What is a useful first take?',[
 ['Move constantly to make it exciting','Extra movement may compete with the important action.'],['Hold a supported, steady frame','A stable view lets the action carry the scene and gives the editor usable holds.'],['Zoom repeatedly while walking','This adds several variables before you have a clear baseline.']],1,['Stability supports attention','Give a take usable ends'],'Brace safely or use a stable support, begin recording before the action and keep holding afterwards. Compare with a handheld version rather than assuming movement adds value.'),
'basic-w6-1':d('Where should this pan stop?','A pan reveals a waiting customer. Which plan makes the movement purposeful?',[
 ['Keep panning until the clip feels long enough','Duration alone does not give the movement a reason.'],['Start and stop abruptly at random','Unplanned ends can be hard to use in an edit.'],['Rehearse a clear start, reveal and settled end','A movement becomes useful when it delivers new information and leaves a readable frame.']],2,['Move for new information','Rehearse the endpoints'],'Start on a closed door, pan to a person waiting beside it and hold. The movement reveals a relationship. A static pair of shots might communicate it just as well.'),
'basic-w6-2':d('Your editor has three beautiful details—and no story.','Which shot would make a sequence of tools easier to understand?',[
 ['A wider view of someone using them','Context and action connect the details to an understandable event.'],['A fourth unrelated tool close-up','It adds another object without explaining the event.'],['A shot of the camera itself','It is useful only if it serves the story you are telling.']],0,['Cover the action','Leave yourself choices'],'Capture a wide action, a closer action, a detail and a relevant cutaway. In the sequence below, compare the information you receive first.','sequence'),
'basic-w6-3':d('The cup jumped between cuts.','The cup is in the left hand in one shot and the right hand in the next. What would help?',[
 ['Ignore every mismatch','Some mismatches distract enough to break the action.'],['Track position and action across takes','Continuity notes help you choose compatible shots or deliberately use a cutaway.'],['Add a stronger colour grade','Colour cannot explain a physical jump in the action.']],1,['Track action and direction','Keep the viewer oriented'],'Sketch the line between two subjects and label where cameras sit. Then check hand, prop and gaze positions before repeating the action from another size.'),
'basic-w6-4':d('Can you make sense of these shots in a new order?','What is the best evidence that your coverage worked?',[
 ['The number of shots alone','Many shots can still miss a crucial action.'],['Every shot moves','Movement does not guarantee clarity.'],['A viewer follows the action across the cuts','Use their points of confusion to identify missing or mismatched coverage.']],2,['Assemble before adding polish','Notice the missing link'],'Reorder the cards, then imagine a cut between each pair. Where would you need another action or detail to make the change understandable?','sequence'),
'basic-w7-0':d('Which file is the usable take?','Your folder contains twenty files named “final”. What would help the next editing session?',[
 ['Consistent folders, descriptive names and a separate backup','You can find source media and recover it if a working copy fails.'],['Rename every file “final-final”','That does not distinguish content or versions.'],['Delete originals as soon as you import them','An editing project may depend on those files. Preserve your source media.']],0,['Make media findable','Protect the source'],'A clip name such as “counter_pour_take02” and separate folders for footage, audio and exports reduce guesswork. Keep a backup outside the working copy.'),
'basic-w7-1':d('What should this cut reveal next?','The viewer has seen where the action happens. What is a useful next question?',[
 ['Which transition pack should I buy?','First make the sequence understandable with simple cuts.'],['What new information does the next shot add?','A rough cut tests meaning and order before detailed polish.'],['How can I use every clip I filmed?','Unused clips are fine when they do not serve the story.']],1,['Assemble the story first','Trim for meaning'],'Try place → action → result, then start with the result instead. Which version creates the expectation you want? There is no single correct order for every purpose.','sequence'),
'basic-w7-2':d('You hear the next scene before you see it.','A shop bell begins over the last image of the street, then the picture cuts inside. What does that do?',[
 ['It is necessarily an editing mistake','Sound can deliberately lead an image change.'],['It changes the camera frame rate','This is an edit relationship, not a capture setting.'],['It lets sound lead the viewer into the next scene','This is a J-cut. Test whether the overlap helps the transition feel motivated.']],2,['Let sound lead or linger','Pace changes attention'],'A J-cut introduces the next sound early; an L-cut lets the previous sound continue after the picture changes. Choose the overlap because of meaning, not because it is available.'),
'basic-w7-3':d('The cut is clear. The title is unreadable.','A thin pale title sits on a bright window. What should you compare first?',[
 ['A clearer position, size or contrast','Readable information matters more than a decorative type treatment.'],['A second equally pale title','More text does not fix contrast.'],['A dramatic look on every shot','First match the shots and keep important text readable.']],0,['Match before styling','Titles should survive the screen'],'Preview a title at phone size. Compare neighbouring shots for brightness and neutral colour before applying a look, then check whether the look harms skin or product detail.'),
'basic-w7-4':d('It looked fine in the editor. Does the export work?','Which check belongs after exporting?',[
 ['Assume the timeline guarantees the file','The delivered file can reveal framing, audio or export issues.'],['Replay the actual file on its intended screen','Check picture, sound, titles, duration and ending in the delivered version.'],['Judge only the file size','Size alone does not tell you whether the result communicates clearly.']],1,['Deliver for a real destination','Watch the file a viewer receives'],'Open the exported film on a phone with headphones and without them. Look for a cropped title, an unexpectedly quiet sentence or a black tail after the ending.'),
'basic-w8-0':d('A list of events is not yet a story.','Which small sequence gives a viewer a change to follow?',[
 ['Street, wall, sky','These can establish a mood, but no change is clear yet.'],['Three unrelated beautiful objects','Beauty alone does not connect the events.'],['A locked shop, a key turning, the first customer entering','A beginning becomes a different situation. That change can carry a small story.']],2,['Begin with a situation','Let something change'],'A maker begins with a broken object and ends with a repaired one. The difficulty and the choices between those moments make the change worth following.'),
'basic-w8-1':d('Give a stranger a reason to care.','Which idea contains a person, a want and an obstacle?',[
 ['A baker wants to finish an order before the power goes out','The goal and difficulty create a question a viewer can follow.'],['A bakery has a blue door','This is a setting detail; it may support a story but does not supply a want.'],['A montage of equipment','Tools become meaningful when connected to someone doing something.']],0,['A person wants something','An obstacle creates a question'],'A student wants a quiet place to practise but the room is noisy. You can tell that small, honest story through choices and actions without manufacturing a conflict.'),
'basic-w8-2':d('Which question opens a story?','You want a maker to describe a difficult moment. Which question gives them room?',[
 ['“It was hard, wasn’t it?”','That leads toward a yes/no answer and supplies your interpretation.'],['“Can you describe the moment it nearly went wrong?”','It invites a specific memory in their own words. Keep comfort and permission central.'],['“Tell me the exact line I wrote for you”','That may be scripted narration, but it is not an open interview question.']],1,['Invite a real answer','Let pictures do some talking'],'Ask permission, listen without interrupting and follow a concrete detail. In voice-over, add what the picture cannot tell us rather than describing every visible action.'),
'basic-w8-3':d('An opening makes a promise.','A film opens on a broken cup. Which ending could honestly pay off that opening?',[
 ['A random sunset','It may be attractive, but does not resolve or develop the opening question.'],['A title claiming a repair we never see','Claims need enough evidence for the viewer to follow.'],['The repaired cup being used—or a clear reason it could not be repaired','Either ending can resolve the promise if the film shows how it got there.']],2,['Invite curiosity honestly','Return to the opening promise'],'Write the question your first image raises. Put the shot that answers or changes it beside your planned ending. If they feel unrelated, adjust the plan before shooting.'),
'basic-w8-4':d('Is the film finished—or just exported?','Three viewers lose interest at the same moment. What is a useful next step?',[
 ['Inspect that moment and make one focused revision','Their response is evidence. Compare a deliberate revision with the original.'],['Keep only the most flattering response','Disagreement and confusion can reveal useful improvements.'],['Replace the whole film immediately','First identify what caused the problem; a smaller change may solve it.']],0,['Bring intention and craft together','Use feedback as evidence'],'Compare your 60–90 second capstone with your first baseline. Name one stronger story choice, one craft improvement and one experiment to carry into your next film.')
};
