'use client';
import React,{useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Aperture,Clapperboard,Film,Scissors,Sun,Smartphone,Camera,Monitor,Check,Play,Clock} from 'lucide-react';
import {paths,weeks,mentors} from './catalog';
import {PhaseMap} from './phase-map';
import {nextModule,moduleInfo,moduleHref,phaseFor} from './learning-rules';
import {useLearning,Go,Action,Panel,Badge,Gate,PathCard,SubmissionCard} from './ui';

const draftKey='framepath-diagnostic-draft-v2';
const initial={name:'',goal:'',gear:'Smartphone',hours:4,experience:'Starting fresh',answers:[-1,-1,-1]};
const goals=[{label:'A product reel',goal:'Make product reels for my business',Icon:Clapperboard},{label:'An everyday story',goal:'Tell everyday stories through short films',Icon:Film},{label:'A better edit',goal:'Turn my clips into a better edit',Icon:Scissors},{label:'Find my starting point',goal:'Explore videography and learn the basics',Icon:Aperture}];
export function recommend(profile:any){const goal=(profile?.goal||'').toLowerCase();return paths.find(p=>p.id===(/edit|clips|cut/.test(goal)?'first-edit':/light|exposure|shadow/.test(goal)?'natural-light':/product|business|café|cafe|shop|brand|reel/.test(goal)?'product-reel':'everyday-story'))!}
export function Home(){const [goal,setGoal]=useState('');return <section className="start-screen"><div className="start-meta"><span>VIDEOGRAPHY / YOUR FIRST FRAME</span><span>01 — START HERE</span></div><h1>What do you want to<br/>learn to <em>create?</em></h1><div className="goal-options">{goals.map(({label,goal:g,Icon})=><a className="goal-choice" key={label} href={'/diagnostic?goal='+encodeURIComponent(g)}><Icon size={23}/><span>{label}</span></a>)}</div><form className="goal-input" onSubmit={e=>{e.preventDefault();window.location.assign('/diagnostic?goal='+encodeURIComponent(goal.trim()))}}><label className="sr-only" htmlFor="custom-goal">Your own video idea</label><input id="custom-goal" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Or tell us your own idea…" required minLength={5} maxLength={500}/><Button type="submit" disabled={goal.trim().length<5}>Find my path</Button></form><p className="start-hint">Your goal. Your pace. A place to begin.</p><div className="journey-trail" aria-label="Your learning journey"><span className="active">Discover</span><i/><span>Learn</span><i/><span>Make</span><i/><span>Grow</span></div></section>}

const questions=[{label:'LIGHT',Icon:Sun,q:'Your subject looks dark against a window. What would you try?',answers:['Add a transition','Let the window light its front or side','Use more digital zoom']},{label:'STORY',Icon:Scissors,q:'What comes first in a rough edit?',answers:['Make the story clear','Add lots of effects','Choose an export format']},{label:'SHARING',Icon:Film,q:'Which music belongs in your published reel?',answers:['Any trending track','Any clip under 30 seconds','Music I own or have permission to use']}];
function Choices({value,onChange,options,label}:any){const id=React.useId();return <RadioGroup aria-label={label} value={String(value)} onValueChange={onChange} className="diagnostic-choices">{options.map((o:any,i:number)=>{const option=typeof o==='string'?{value:o,label:o}:o;const Icon=option.Icon;return <label className="diagnostic-choice" htmlFor={id+i} key={option.value}><RadioGroupItem id={id+i} value={String(option.value)}/>{Icon&&<Icon size={28}/>}<span>{option.label}</span>{option.detail&&<small>{option.detail}</small>}</label>})}</RadioGroup>}
export function Diagnostic(){const {s,user,loaded,mutate}=useLearning();const [form,setForm]=useState<any>(initial),[step,setStep]=useState(0),[ready,setReady]=useState(false),[report,setReport]=useState(false);
useEffect(()=>{if(!loaded||ready)return;const goal=new URLSearchParams(window.location.search).get('goal');let draft:any=null;try{draft=JSON.parse(sessionStorage.getItem(draftKey)||'null')}catch{};const valid=draft&&typeof draft.form?.goal==='string'&&Array.isArray(draft.form?.answers)&&draft.form.answers.length===3;
if(valid&&(!goal||goal===draft.form.goal)){setForm({...initial,...draft.form});setStep(Math.max(0,Math.min(5,Number(draft.step)||0)));setReport(!!draft.report)}else if(s.profile&&!goal){setForm({...initial,...s.profile});setReport(true)}else{setForm({...initial,...(s.profile||{}),goal:goal||s.profile?.goal||''});setReport(false)}setReady(true)},[loaded,ready,s.profile]);
useEffect(()=>{if(ready){try{sessionStorage.setItem(draftKey,JSON.stringify({form,step,report}))}catch{}}},[form,step,report,ready]);
const update=(key:string,value:any)=>setForm((p:any)=>({...p,[key]:value}));
async function save(){if(await mutate('profile',{profile:form})){try{sessionStorage.removeItem(draftKey)}catch{};window.location.assign('/workspace')}}
const score=form.answers.filter((a:number,i:number)=>a===[1,0,2][i]).length;const path=recommend(form);const q=questions[step-3];
const valid=step===0?form.name.trim().length>0&&form.goal.trim().length>=5:step===1?!!form.gear&&!!form.experience:step===2?form.hours>=1&&form.hours<=20:form.answers[step-3]>=0;
if(!ready)return <Panel><p role="status">Opening your starting point…</p></Panel>;
if(report)return <><PageIntro label="YOUR LEARNING SNAPSHOT" title="Your next frame starts here."/><div className="snapshot-layout"><Panel className="snapshot"><div className="row between"><Badge>{form.name || 'Your'} starting point</Badge><Aperture size={32}/></div><h2>{form.goal}</h2><div className="setup-chips"><span><Clock size={17}/>{form.hours}h / week</span><span>{form.gear}</span></div><div className="skill-signals">{questions.map((v,i)=><div key={v.label}><v.Icon size={24}/><span>{v.label}</span><div className="signal-line"><i style={{width:form.answers[i]===[1,0,2][i]?'100%':'30%'}}/></div><small>{form.answers[i]===[1,0,2][i]?'Ready to practise':'Start with the basics'}</small></div>)}</div><p className="small">Based on your answers, not a skill certification. Your first film will tell us more.</p><Button variant="outline" onClick={()=>{setReport(false);setStep(0)}}>Edit answers</Button></Panel><Panel className="next-frame"><span className="eyebrow">YOUR RECOMMENDED FIRST PROJECT</span><h2>{path.title}</h2><p>{path.outcome}</p><PhaseMap compact/><p>{path.lessons.length} short sessions · about {Math.ceil(path.lessons.reduce((n,l)=>n+l.minutes,0)/60/form.hours)} week{Math.ceil(path.lessons.reduce((n,l)=>n+l.minutes,0)/60/form.hours)>1?'s':''} at your pace.</p>{!user?<><Go href={'/auth/google?return_to='+encodeURIComponent('/diagnostic')}>Sign in & save my path</Go><a className="text-link preview-link" href={'/explore/'+path.id+'/0'}>Preview the first lesson</a></>:<Action onClick={save}>Save & start learning</Action>}<p className="small">{score<2?'We’ll begin with simple light and clear storytelling.':'Turn what you recognise into a small finished project.'}</p></Panel></div></>;
return <section className="diagnostic-wizard"><div className="row between"><span className="eyebrow">YOUR STARTING POINT</span><span className="small">{step+1} / 6</span></div><Progress value={(step+1)/6*100}/><form onSubmit={e=>{e.preventDefault();if(valid){if(step===5)setReport(true);else setStep(step+1)}}}><div className="question-icon">{step===0?<Film/>:step===1?<Camera/>:step===2?<Clock/>:q&&<q.Icon/>}</div><h1>{step===0?'Let’s make it yours.':step===1?'What’s your starting setup?':step===2?'How much time feels right?':q.q}</h1>{step===0?<><label>What should we call you?<input autoComplete="given-name" maxLength={60} required value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Your video goal<textarea value={form.goal} onChange={e=>update('goal',e.target.value)} rows={2} minLength={5} maxLength={500} required/></label></>:step===1?<><Choices label="Your equipment" value={form.gear} onChange={(v:string)=>update('gear',v)} options={[{value:'Smartphone',label:'My phone',Icon:Smartphone},{value:'Smartphone and computer',label:'Phone + computer',Icon:Monitor},{value:'Camera and computer',label:'Camera + computer',Icon:Camera}]}/><label htmlFor="experience">How familiar does filming feel?</label><select id="experience" value={form.experience} onChange={e=>update('experience',e.target.value)}><option>Starting fresh</option><option>I film casually</option><option>I have edited a few videos</option></select></>:step===2?<Choices label="Hours per week" value={form.hours} onChange={(v:string)=>update('hours',Number(v))} options={[{value:2,label:'2 hours',detail:'A little each week'},{value:4,label:'4 hours',detail:'Room to experiment'},{value:6,label:'6 hours',detail:'A steady practice'},{value:10,label:'10 hours',detail:'Time to go deeper'}]}/>:<Choices label={q.q} value={form.answers[step-3]} onChange={(v:string)=>update('answers',form.answers.map((a:number,i:number)=>i===step-3?Number(v):a))} options={q.answers.map((a,i)=>({value:i,label:a}))}/>}<div className="button-row between">{step>0?<Button variant="outline" type="button" onClick={()=>setStep(step-1)}>Back</Button>:<a className="text-link" href="/">Change idea</a>}<Button disabled={!valid} type="submit">{step===5?'See my snapshot':'Continue'}</Button></div></form><p className="small wizard-note">No right level to begin. This helps us find yours.</p></section>}
function PageIntro({label,title}:any){return <div className="page-head"><div><p className="kicker">{label}</p><h1>{title}</h1></div></div>}
export function Workspace(){const {s}=useLearning();const path=recommend(s.profile);const next=path.lessons.findIndex((_,i)=>!s.progress[path.id+'-'+i]);const mentor=mentors.find(m=>m.id===s.craft?.mentorId);const active=s.craft?.status==='active';const craftNextKey=nextModule(s,'craft');const craftNext=craftNextKey?moduleInfo(craftNextKey).index:-1;const complete=Object.keys(s.progress).length;return <><PageIntro label="MY JOURNEY" title={s.profile?'Keep creating, '+s.profile.name+'.':'Your next frame awaits.'}/><Gate>{!s.profile?<Panel className="empty"><Aperture size={44}/><h2>Start with your learning snapshot.</h2><Go href="/diagnostic">Find my starting point</Go></Panel>:<><div className="journey-dashboard"><Panel className="next-frame"><div className="row between"><Badge>{active?'MENTOR GUIDED':'YOUR NEXT SESSION'}</Badge><span className="small">{complete} complete</span></div><h2>{active?weeks[Math.max(0,craftNext)].title:path.lessons[Math.max(0,next)].title}</h2><p>{active?'Beginner Videography · with '+mentor?.name:path.title}</p><PhaseMap compact/><Go href={active?'/craft/week/'+(Math.max(0,craftNext)+1):'/explore/'+path.id+'/'+Math.max(0,next)}>{(active?craftNext:next)<0?'Revisit your work':'Continue learning'}</Go></Panel><Panel className="journey-side"><span className="eyebrow">YOUR DIRECTION</span><h2>{s.profile.goal}</h2><p>{s.profile.hours}h / week · {s.profile.gear}</p><div className="button-row"><Go href="/diagnostic" outline>My snapshot</Go><Go href="/portfolio" outline>My work · {s.submissions.length}</Go></div></Panel></div><div className="mentor-invitation"><div className="mentor-mini"><span>M</span><span>A</span></div><div><h2>{mentor?'Learning with '+mentor.name:'Grow with a mentor you choose.'}</h2><p>{mentor?'Your pathway, feedback and weekly conversations.':'Take this practice further with a guided 12-week course.'}</p></div><Go href={active?'/my-mentor':s.craft?'/craft/enrol':'/craft'} outline>{active?'My mentor':s.craft?'Continue setup':'Meet your next step'}</Go></div><div className="section-heading"><h2>More ways to practise</h2><a className="text-link" href="/explore">All projects</a></div><div className="cards-grid">{paths.map(p=><PathCard key={p.id} path={p}/>)}</div>{s.submissions.length>0&&<details className="lesson-details"><summary>Recent work · {s.submissions.length}</summary>{s.submissions.slice(0,3).map((sub:any)=><SubmissionCard key={sub.id} sub={sub}/>)}</details>}</>}</Gate></>}
