import {CourseLesson} from './selfpaced-curriculum';
import {scenarioResources,tagExistingResource} from './scenario-resources';
export type LearningResource={id:string;title:string;creator:string;topic:string;type:string;host:string;source:string;focus:string;level:string;youtubeId?:string;vimeoId?:string;devices?:string[];archetypes?:string[];levels?:string[];format?:string;bandwidth?:string;verification?:string;checkedAt?:string};
const existingResources:LearningResource[]=[
  {
    "id": "storytelling",
    "title": "Directing Without Words: Visual Storytelling in Film",
    "creator": "StudioBinder",
    "topic": "Story",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=WMcWLFtGnAs",
    "youtubeId": "WMcWLFtGnAs",
    "focus": "Notice the intended feeling and the visual evidence that creates it.",
    "level": "All levels"
  },
  {
    "id": "shot-sizes",
    "title": "Every Shot Size Explained",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=AyML8xuKfoc",
    "youtubeId": "AyML8xuKfoc",
    "focus": "Look for place, action and detail, then connect each shot to a purpose.",
    "level": "All levels"
  },
  {
    "id": "editing-cuts",
    "title": "Six Essential Film Editing Techniques",
    "creator": "StudioBinder",
    "topic": "Editing",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=FVR8zz8ci2k",
    "youtubeId": "FVR8zz8ci2k",
    "focus": "Notice how different ordering changes information or emotion.",
    "level": "All levels"
  },
  {
    "id": "shutter",
    "title": "Shutter Speed and the Exposure Triangle",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=SsIEcGbwgN0",
    "youtubeId": "SsIEcGbwgN0",
    "focus": "Focus on the relationship between frame rate, shutter and recorded movement.",
    "level": "All levels"
  },
  {
    "id": "exposure",
    "title": "Camera ISO and the Exposure Triangle",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=cy9wPDKd-dU",
    "youtubeId": "cy9wPDKd-dU",
    "focus": "Notice brightness, noise and the trade-offs in an exposure choice.",
    "level": "All levels"
  },
  {
    "id": "white-balance",
    "title": "Colour Temperature and White Balance",
    "creator": "StudioBinder",
    "topic": "Lighting",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=APLq7aPlDhk",
    "youtubeId": "APLq7aPlDhk",
    "focus": "Focus on automatic versus deliberate white balance; use the reading for the focus test.",
    "level": "All levels"
  },
  {
    "id": "framing",
    "title": "Camera Framing and Visual Storytelling",
    "creator": "StudioBinder",
    "topic": "Story",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=qQNiqzuXjoM",
    "youtubeId": "qQNiqzuXjoM",
    "focus": "Look at subject placement, eyelines and relationships within the frame.",
    "level": "All levels"
  },
  {
    "id": "formats",
    "title": "Aspect Ratios in Film",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=T0YHA2yxCwM",
    "youtubeId": "T0YHA2yxCwM",
    "focus": "Compare the information available in differently shaped frames.",
    "level": "All levels"
  },
  {
    "id": "lighting",
    "title": "Cinematic Lighting: Types of Light",
    "creator": "StudioBinder",
    "topic": "Lighting",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=r2nD_knsNrc",
    "youtubeId": "r2nD_knsNrc",
    "focus": "Notice direction and the difference between hard and soft shadow edges.",
    "level": "All levels"
  },
  {
    "id": "lighting-basics",
    "title": "The Basics of Lighting for Film",
    "creator": "Cinecom.net",
    "topic": "Lighting",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=hGEsOcF3PoM",
    "youtubeId": "hGEsOcF3PoM",
    "focus": "Apply the light-control ideas to one window and a white card.",
    "level": "All levels"
  },
  {
    "id": "rode-sound",
    "title": "A Vlogger’s Guide to Better Sound",
    "creator": "RØDE",
    "topic": "Sound",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=wbEt3IBCMI8",
    "youtubeId": "wbEt3IBCMI8",
    "focus": "Listen for the relationship between a voice and its surroundings.",
    "level": "All levels"
  },
  {
    "id": "rode-wind",
    "title": "Reduce Wind Noise When Recording Outside",
    "creator": "RØDE",
    "topic": "Sound",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=SBG3KXLyGcQ",
    "youtubeId": "SBG3KXLyGcQ",
    "focus": "Compare protection and positioning for an outdoor recording.",
    "level": "All levels"
  },
  {
    "id": "camera-movement",
    "title": "Panning and Tilting Camera Movements",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=iAZvLA_K94w",
    "youtubeId": "iAZvLA_K94w",
    "focus": "Compare still holds with movement; rehearse a steady starting and ending frame.",
    "level": "All levels"
  },
  {
    "id": "screen-direction",
    "title": "The 180 Degree Rule in Film",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=iW0bKUfvH2c",
    "youtubeId": "iW0bKUfvH2c",
    "focus": "Diagram the line between subjects and the consistent screen direction.",
    "level": "All levels"
  },
  {
    "id": "resolve-original",
    "title": "Introduction to Editing · DaVinci Resolve 17",
    "creator": "Blackmagic Design",
    "topic": "Editing",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=fYlwId_z_yU",
    "youtubeId": "fYlwId_z_yU",
    "focus": "Use the media organisation and project workflow sections. Software controls may differ in your editor.",
    "level": "All levels"
  },
  {
    "id": "three-acts",
    "title": "Three Act Structure Explained",
    "creator": "StudioBinder",
    "topic": "Story",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=tvqjp1CxxD8",
    "youtubeId": "tvqjp1CxxD8",
    "focus": "Reduce the structure to a beginning, a change and an ending.",
    "level": "All levels"
  },
  {
    "id": "short-film",
    "title": "The Pen · A Short Film",
    "creator": "StudioBinder",
    "topic": "Story",
    "type": "Video",
    "host": "YouTube",
    "source": "https://www.youtube.com/watch?v=3QRrsiMe4wI",
    "youtubeId": "3QRrsiMe4wI",
    "focus": "Deconstruct this short film, then compare your own story intent and decisions. The example is shorter than the viewing block.",
    "level": "All levels"
  },
  {
    "id": "resolve-edit-1",
    "title": "Introduction to editing · Part 1",
    "creator": "Blackmagic Design",
    "topic": "Editing",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-editing-part-1",
    "vimeoId": "1121056378",
    "focus": "Build a simple sequence, then pause and try the same operation in your editor.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-edit-2",
    "title": "Refining an edit · Part 2",
    "creator": "Blackmagic Design",
    "topic": "Editing",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-editing-part-2",
    "vimeoId": "659481873",
    "focus": "Study trimming, sound bridges and revisions. Controls may differ in your version.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-multicam",
    "title": "Multicam editing",
    "creator": "Blackmagic Design",
    "topic": "Editing",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#multicam-editing",
    "vimeoId": "659481886",
    "focus": "Observe sync and angle selection; practise with a short sequence.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-color",
    "title": "Introduction to colour",
    "creator": "Blackmagic Design",
    "topic": "Colour",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-color",
    "vimeoId": "662444535",
    "focus": "Compare shot matching before applying a creative look.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-advanced-color",
    "title": "Advanced colour",
    "creator": "Blackmagic Design",
    "topic": "Colour",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#advanced-color",
    "vimeoId": "662444855",
    "focus": "Focus on one correction, then inspect its behaviour through the shot.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-delivery",
    "title": "Delivering content",
    "creator": "Blackmagic Design",
    "topic": "Delivery",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#delivering-content",
    "vimeoId": "662445335",
    "focus": "Check presets and exported files against your own delivery brief.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-color-management",
    "title": "Colour management",
    "creator": "Blackmagic Design",
    "topic": "Colour",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#color-management",
    "vimeoId": "662489460",
    "focus": "Identify input, working and output assumptions before grading.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-audio",
    "title": "Introduction to audio",
    "creator": "Blackmagic Design",
    "topic": "Sound",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-audio",
    "vimeoId": "659185216",
    "focus": "Balance essential sound before adding background layers.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-sound-design",
    "title": "Introduction to sound design",
    "creator": "Blackmagic Design",
    "topic": "Sound",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-sound-design",
    "vimeoId": "659185384",
    "focus": "Notice how separate sound layers establish a place.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-mixing",
    "title": "Introduction to mixing",
    "creator": "Blackmagic Design",
    "topic": "Sound",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-mixing",
    "vimeoId": "659185402",
    "focus": "Use meters and listening together; keep processing reversible.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "resolve-fusion",
    "title": "Introduction to Fusion",
    "creator": "Blackmagic Design",
    "topic": "Editing",
    "type": "Video",
    "host": "Vimeo",
    "source": "https://www.blackmagicdesign.com/products/davinciresolve/training#introduction-to-fusion",
    "vimeoId": "659472216",
    "focus": "Start with a simple title or composite, then inspect its readability.",
    "level": "Intermediate / advanced"
  },
  {
    "id": "adobe-edit",
    "title": "Editing in Premiere",
    "creator": "Adobe",
    "topic": "Editing",
    "type": "Video tutorial",
    "host": "www.adobe.com",
    "source": "https://www.adobe.com/learn/premiere-pro/web/create-edit-sequence",
    "focus": "Explore the official editing walkthrough. The tutorial is free; Premiere may require a paid licence.",
    "level": "All levels"
  },
  {
    "id": "adobe-captions",
    "title": "Captions and accessibility",
    "creator": "Adobe",
    "topic": "Delivery",
    "type": "Video tutorial",
    "host": "www.adobe.com",
    "source": "https://www.adobe.com/learn/premiere-pro/web/subtitles",
    "focus": "Follow the video and transcript, then proofread your own captions.",
    "level": "All levels"
  },
  {
    "id": "lighting-guide",
    "title": "Film lighting techniques",
    "creator": "StudioBinder",
    "topic": "Lighting",
    "type": "Guide + videos",
    "host": "www.studiobinder.com",
    "source": "https://www.studiobinder.com/blog/film-lighting-techniques/",
    "focus": "Compare light direction and quality against your own scene.",
    "level": "All levels"
  },
  {
    "id": "practical-light",
    "title": "Practical and motivated light",
    "creator": "StudioBinder / Aputure",
    "topic": "Lighting",
    "type": "Guide + videos",
    "host": "www.studiobinder.com",
    "source": "https://www.studiobinder.com/blog/what-is-practical-lighting-in-film/",
    "focus": "Study how an in-frame source can motivate the scene lighting.",
    "level": "All levels"
  },
  {
    "id": "rode-location",
    "title": "Location sound tips",
    "creator": "RØDE / Levi Allen",
    "topic": "Sound",
    "type": "Guide + video",
    "host": "rode.com",
    "source": "https://rode.com/en-us/about/news-info/5-tips-for-great-sound-on-the-rode-with-levi-allen",
    "focus": "Plan microphone position and a fallback for difficult conditions.",
    "level": "All levels"
  },
  {
    "id": "imovie-phone",
    "title": "Edit on an iPhone",
    "creator": "Apple",
    "topic": "Editing",
    "type": "Reading guide",
    "host": "support.apple.com",
    "source": "https://support.apple.com/guide/imovie-iphone/welcome/ios",
    "focus": "Use the official mobile editing guide for your installed version.",
    "level": "All levels"
  },
  {
    "id": "imovie-mac",
    "title": "Edit in iMovie on Mac",
    "creator": "Apple",
    "topic": "Editing",
    "type": "Reading guide",
    "host": "support.apple.com",
    "source": "https://support.apple.com/guide/imovie/welcome/mac",
    "focus": "Start a project and learn the available editing controls.",
    "level": "All levels"
  },
  {
    "id": "lens-guide",
    "title": "Focal length and field of view",
    "creator": "StudioBinder",
    "topic": "Camera",
    "type": "Guide + videos",
    "host": "www.studiobinder.com",
    "source": "https://www.studiobinder.com/blog/focal-length-camera-lenses-explained/",
    "focus": "Compare field of view from a fixed camera position, then study the effect of moving it.",
    "level": "All levels"
  }
];
export const learningResources:LearningResource[]=[...existingResources.map(tagExistingResource),...scenarioResources];
export function resourcesFor(lesson:CourseLesson):LearningResource[]{const primary=lesson.resourceIds?.map(id=>learningResources.find(r=>r.id===id)).filter(Boolean) as LearningResource[]|undefined;if(primary?.length)return primary;const v=lesson.video;if(!v)return [];const r=learningResources.find(r=>r.youtubeId===v.id);const first=r||{id:v.id,title:v.title,creator:v.by,topic:'Camera',type:'Video',host:'YouTube',source:'https://www.youtube.com/watch?v='+v.id,youtubeId:v.id,focus:v.focus,level:'Beginner'};const extra=learningResources.find(x=>x.topic===first.topic&&x.creator!==first.creator);return [first,...(extra?[extra]:[])];}
