'use client';
import React,{useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';import {Progress} from '@/components/ui/progress';
import {Aperture,Clapperboard,ScanLine,Film,Check,Clock,BookOpen,Users,Calendar,Sparkles} from 'lucide-react';
import {paths,weeks,mentors,resources} from './catalog';
import {PhaseMap} from './phase-map';
import {useLearning,Go,Action,CheckField,PageHead,Panel,Badge,Gate,DateText,isExplore,isCraft,Resource,PathCard,AIBox,UploadField,SubmissionCard,FeedbackText} from './ui';
export function Explore(){return <><PageHead eyebrow="YOUR PRACTICE LIBRARY" title="A small project. A new skill." action={<Go href="/workspace" outline>My journey</Go>}/><PhaseMap/><div className="cards-grid">{paths.map(p=><PathCard key={p.id} path={p}/>)}</div><p className="small" style={{marginTop:24}}>Product reel and Everyday story include free practice, uploads and reflection checkpoints. Sign in to save your work.</p></>}
export {Lesson} from './lesson';
export function Membership(){const {s,usage,mutate}=useLearning();const [terms,setTerms]=useState(false);const [returnTo,setReturnTo]=useState('/workspace');useEffect(()=>{const target=new URLSearchParams(window.location.search).get('return_to');if(target&&/^\/explore\/[a-z-]+\/\d+$/.test(target))setReturnTo(target)},[]);return <><PageHead eyebrow="YOUR ACCESS" title={isExplore(s)?'A year of possibilities.':'More room to explore.'}>Two pathways are free. Annual access adds every published Explore pathway and a shared AI allowance.</PageHead><div className="two-col"><Panel className="membership-card"><Badge>EXPLORE ANNUAL</Badge><div className="price">₹999<span> / year</span></div><p>One payment. One calendar year. No automatic renewal in this pilot.</p><ul className="tick-list"><li><Check/>All published Explore paths</li><li><Check/>12 pathway adaptations</li><li><Check/>120 short AI questions</li><li><Check/>12 first-pass AI feedback checks</li><li><Check/>Private notes, uploads and saved progress</li></ul><p className="small">The allowance is shared across paths for the whole year. Starting another path does not reset it. Craft mentorship is purchased separately.</p><Gate>{isExplore(s)?<div className="notice success"><strong>Demo membership active</strong><p>Valid until <DateText value={s.membership.expiresAt}/></p><Go href={returnTo}>Continue learning</Go></div>:<><CheckField checked={terms} onChange={setTerms}>I understand this is simulated checkout. No money will be charged and no card details are collected.</CheckField><Action disabled={!terms} onClick={()=>mutate('explore_activate',{terms})}>Activate demo annual access</Action></>}</Gate></Panel><div className="stack"><Panel><h2>Your shared AI allowance</h2>{[['plan','Pathway adaptations',12],['question','Questions',120],['feedback','Feedback checks',12]].map(([kind,name,limit])=>{const used=usage.find((v:any)=>v.scope==='explore'&&v.kind===kind)?.used||0;return <div className="quota" key={String(kind)}><div className="row between"><span>{name}</span><strong>{Math.max(0,Number(limit)-used)} / {limit}</strong></div><Progress value={used/Number(limit)*100}/></div>})}<p className="small">AI accepts text and one selected image still per check in this prototype. It does not watch uploaded videos or inspect links. Failed requests return the allowance.</p></Panel><Panel><h2>Want depth and a mentor?</h2><p>Craft is a separate 12-week course with your chosen mentor, weekly reviews and three portfolio projects.</p><Go href="/craft" outline>Discover mentor support</Go></Panel></div></div>{s.receipts.length>0&&<Panel><h2>Demo receipts</h2><p className="small">These are test records, not tax invoices or proof of payment.</p>{s.receipts.map((r:any)=><div className="receipt" key={r.id}><div><strong>{r.product}</strong><p><DateText value={r.date}/></p></div><strong>₹{r.amount.toLocaleString('en-IN')} · simulated</strong></div>)}</Panel>}</>}
export function Craft(){const {s}=useLearning();return <><PageHead eyebrow="YOUR JOURNEY · WITH A MENTOR" title="Take your next frame further."/><div className="craft-hero"><div><Badge>BEGINNER VIDEOGRAPHY</Badge><h2>Your practice.<br/>A mentor in your corner.</h2><p>Keep learning through projects, with a mentor you choose to guide your next attempt.</p><div className="button-row"><Go href={s.craft?'/craft/enrol':s.profile?'/mentors':'/diagnostic'}>{s.craft?'Continue mentor setup':s.profile?'Choose my mentor':'Find my starting point'}</Go><Go href="/mentors" outline>Meet the mentors</Go></div></div><div className="craft-facts"><div><strong>12</strong><span>weeks of practice</span></div><div><strong>3</strong><span>finished projects</span></div><div><strong>6h</strong><span>per week</span></div><div><strong>1:1</strong><span>weekly conversation</span></div></div></div><PhaseMap/><div className="project-sequence mentor-process"><span><BookOpen/>Learn at your pace</span><span><Sparkles/>AI first pass</span><span><Users/>Mentor review</span><span><Film/>Make it better</span></div><details className="lesson-details"><summary>What mentor support includes</summary><ul className="tick-list"><li><Check/>One assignment review each week</li><li><Check/>A weekly 30-minute conversation</li><li><Check/>Weekday questions and check-ins</li></ul><p>The pilot uses fictional mentors, private in-site conversations and calendar reminders. No live calls or WhatsApp messages are sent.</p><p>Final benchmark: 70/100, every rubric area at least 2/4, and all three projects reviewed. Demo reviews are not credentials.</p></details></>}
export {Home,Diagnostic,Workspace} from './journey';
