'use client';
import React,{useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';import {Progress} from '@/components/ui/progress';
import {Aperture,Clapperboard,ScanLine,Film,Check,Clock,BookOpen,Users,Calendar,Sparkles} from 'lucide-react';
import {paths,weeks,mentors,resources} from './catalog';
import {PhaseMap} from './phase-map';
import {useLearning,Go,Action,CheckField,PageHead,Panel,Badge,Gate,DateText,isExplore,isCraft,Resource,PathCard,AIBox,UploadField,SubmissionCard,FeedbackText} from './ui';
export function LegacyExplore(){return <><PageHead eyebrow="YOUR PRACTICE LIBRARY" title="A small project. A new skill." action={<Go href="/workspace" outline>My journey</Go>}/><PhaseMap/><div className="cards-grid">{paths.map(p=><PathCard key={p.id} path={p}/>)}</div><p className="small" style={{marginTop:24}}>Some lessons are free to practise. Sign in to save your work.</p></>}
export {Lesson} from './lesson';
export function Membership(){const {s,usage,mutate}=useLearning();const [terms,setTerms]=useState(false);const [returnTo,setReturnTo]=useState('/workspace');useEffect(()=>{const target=new URLSearchParams(window.location.search).get('return_to');if(target&&/^\/explore\/[a-z0-9-]+\/\d+(?:\?tab=assignment)?$/.test(target))setReturnTo(target)},[]);return <><PageHead eyebrow="YOUR ACCESS" title={isExplore(s)?'A year of possibilities.':'More room to explore.'}>Free: watch every module and do the tasks in the first two. Self-paced unlocks every task, AI reviews and your portfolio.</PageHead><div className="two-col"><Panel className="membership-card"><Badge>EXPLORE ANNUAL</Badge><div className="price">₹999<span> / year</span></div><p>One year. It won’t renew by itself. Practice checkout only.</p><ul className="tick-list"><li><Check/>All published Explore paths</li><li><Check/>12 practice-plan requests</li><li><Check/>120 short AI questions</li><li><Check/>12 AI feedback checks</li><li><Check/>Private notes, uploads and saved progress</li></ul><p className="small">These limits last for the whole year, across all levels.</p><Gate>{isExplore(s)?<div className="notice success"><strong>Demo membership active</strong><p>Valid until <DateText value={s.membership.expiresAt}/></p><Go href={returnTo}>Continue learning</Go></div>:<><CheckField checked={terms} onChange={setTerms}>I understand this is a practice checkout. No money is taken.</CheckField><Action disabled={!terms} onClick={()=>mutate('explore_activate',{terms})}>Activate demo annual access</Action></>}</Gate></Panel><div className="stack"><Panel><h2>Your shared AI help</h2>{[['plan','Practice plans',12],['question','Questions',120],['feedback','Feedback checks',12]].map(([kind,name,limit])=>{const used=usage.find((v:any)=>v.scope==='explore'&&v.kind===kind)?.used||0;return <div className="quota" key={String(kind)}><div className="row between"><span>{name}</span><strong>{Math.max(0,Number(limit)-used)} / {limit}</strong></div><Progress value={used/Number(limit)*100}/></div>})}<p className="small">AI reads your notes and one photo. It can’t watch videos or open links. If a request fails, it doesn’t count.</p></Panel><Panel><h2>Learn at your own pace</h2><p>Your plan picks lessons for your goal, skills and time. You can watch every module for free.</p><Go href="/explore" outline>Browse pathways</Go></Panel></div></div>{s.receipts.length>0&&<Panel><h2>Demo receipts</h2><p className="small">These are test records, not tax invoices or proof of payment.</p>{s.receipts.map((r:any)=><div className="receipt" key={r.id}><div><strong>{r.product}</strong><p><DateText value={r.date}/></p></div><strong>₹{r.amount.toLocaleString('en-IN')} · simulated</strong></div>)}</Panel>}</>}
export function Craft(){const {s}=useLearning();return <><PageHead eyebrow="YOUR JOURNEY · WITH A MENTOR" title="Take your next frame further."/><div className="craft-hero"><div><Badge>BEGINNER VIDEOGRAPHY</Badge><h2>Your practice.<br/>A mentor in your corner.</h2><p>Learn through projects, with a mentor you choose.</p><div className="button-row"><Go href={s.craft?'/craft/enrol':s.profile?'/mentors':'/diagnostic'}>{s.craft?'Continue mentor setup':s.profile?'Choose my mentor':'Find my starting point'}</Go><Go href="/mentors" outline>Meet the mentors</Go></div></div><div className="craft-facts"><div><strong>12</strong><span>weeks of practice</span></div><div><strong>3</strong><span>finished projects</span></div><div><strong>6h</strong><span>per week</span></div><div><strong>1:1</strong><span>weekly conversation</span></div></div></div><PhaseMap/><div className="project-sequence mentor-process"><span><BookOpen/>Learn at your pace</span><span><Sparkles/>AI first pass</span><span><Users/>Mentor review</span><span><Film/>Make it better</span></div><details className="lesson-details"><summary>What mentor support includes</summary><ul className="tick-list"><li><Check/>One assignment review each week</li><li><Check/>A weekly 30-minute conversation</li><li><Check/>Weekday questions and check-ins</li></ul><p>In this test version, mentors are made up. No calls or WhatsApp messages are sent.</p><p>To finish: score 70 or more, at least 2 out of 4 on every check, and get all three projects reviewed.</p></details></>}
export {Home,Diagnostic} from './journey';
export {BeginnerJourney as Workspace,BeginnerLibrary as Explore} from './beginner-pages';
