import {isFreeModule} from './videography/programme';
import {isVisualKey} from './lessons/content';
import {isScenarioProfile,buildScenarioPlan,isScenarioKey,scenarioLesson} from './scenario-engine';
import {coursePaths,CourseLesson,Level,activeLevel,levelNames} from './selfpaced-curriculum';
import {diagnosticResult,skillIds,Skill,skillNames} from './diagnostic-engine';
export type GoalKind='product'|'travel'|'documentary'|'social'|'editing'|'story';
export const goalKinds:Record<GoalKind,{label:string;object:string;viewer:string;finish:string;angle:string;examples:Record<string,string>}>= {
 product:{label:'Product & business',object:'one product you can film',viewer:'a customer deciding whether it is useful',finish:'a product reel',angle:'Show a benefit before asking for attention.',examples:{planning:'Open with the problem your product solves; let a real action prove the benefit.',camera:'Show the surface, label and working detail clearly. A dramatic image fails if the product becomes unreadable.',sound:'Record one recognisable use sound, such as a lid closing or a tool working. Keep any voice above the music.',editing:'Cut from a visible need to the product in use, then to its result. Remove a beautiful shot if it repeats the same information.',delivery:'Check the label and closing action on a small screen with the sound off.'}},
 travel:{label:'Travel & places',object:'one accessible place',viewer:'someone who has never visited this place',finish:'a travel story',angle:'Give a place a feeling, not just a collection of views.',examples:{planning:'Choose one small change: a market waking up, a path reaching a viewpoint or a street after rain.',camera:'Use a wide view to locate the viewer, then a detail that could only belong to this place.',sound:'Capture a short clean ambience at each location. Let a distinctive sound connect two shots.',editing:'Let the route or a small action connect the images. Avoid cutting between unrelated landmarks just to a beat.',delivery:'Keep a landscape master and reframe the important details deliberately for a vertical version.'}},
 documentary:{label:'People & documentary',object:'a person or process you have permission to film',viewer:'someone discovering this person’s experience',finish:'a short portrait',angle:'Make a person’s meaning clear without changing it.',examples:{planning:'Agree what can be recorded and shared. Choose one real action that reveals what matters to the person.',camera:'Keep the eyes and relevant surroundings readable. Cutaways should show the process being discussed.',sound:'Test speech in the actual room. Move the microphone closer before trying to repair distant sound.',editing:'Build a short sequence from the person’s meaning. Cutaways can hide edits but must not invent a false event.',delivery:'Proofread names and captions. Confirm that the shared version respects the person’s permissions.'}},
 social:{label:'Social & creator videos',object:'one idea you can demonstrate',viewer:'a scrolling viewer encountering you for the first time',finish:'a creator video',angle:'Make the first moment understandable, then deliver on it.',examples:{planning:'Choose a useful promise that a short video can actually fulfil. Sketch the first frame and the payoff.',camera:'Keep the action inside vertical safe zones. Leave room for captions without covering hands or faces.',sound:'Make the spoken idea understandable on phone speakers. Music should support the voice.',editing:'Remove empty pauses while keeping the action readable. Test the video with captions and sound off.',delivery:'Watch the exported vertical file with interface overlays in mind. Check text size on an actual phone.'}},
 editing:{label:'Editing & finishing',object:'your existing clips',viewer:'a viewer trying to follow the story in your footage',finish:'a stronger edit',angle:'Make the footage communicate before adding effects.',examples:{planning:'Audit the clips for an opening, a change and an ending. Write down what is missing before filming more.',camera:'Compare source shots for matching brightness, focus and direction. Capture only the inserts your edit lacks.',sound:'Repair the relationship between speech, ambience and music. Keep room tone across edits.',editing:'Make a simple assembly first. Change one cut at a time and compare what the viewer understands.',delivery:'Export a review version, watch it outside the editor and log exact timecodes for changes.'}},
 story:{label:'Stories & short films',object:'one everyday action',viewer:'someone who does not yet know your subject',finish:'a short film',angle:'Let the viewer see a clear beginning, change and ending.',examples:{planning:'Choose a small action with a visible result. Decide what the viewer should feel at the end.',camera:'Connect place, action and detail. Keep screen direction consistent when filming from another angle.',sound:'Collect a useful action sound and room tone. Silence can make the next sound more meaningful.',editing:'Ask whether each shot gives new information. Try a different opening before adding a transition.',delivery:'Check the ending, captions and credits in the actual exported file, then save a recoverable project.'}}
};
export function goalKind(profile:any):GoalKind{if(profile?.goalKind&&profile.goalKind in goalKinds)return profile.goalKind;const g=(profile?.goal||'').toLowerCase();return /product|business|brand|shop|café|cafe/.test(g)?'product':/travel|trip|landscape|place|holiday/.test(g)?'travel':/interview|documentary|portrait|people/.test(g)?'documentary':/edit|clip|cut|colour|color/.test(g)?'editing':/social|reel|youtube|instagram|creator/.test(g)?'social':'story'}
export const isPersonalized=(profile:any)=>profile?.diagnosticVersion==='visual-9-v1'&&Array.isArray(profile?.diagnosticAnswers)&&profile.diagnosticAnswers.length===9;
export function profileLevel(profile:any):Level{return isPersonalized(profile)?(profile.levelOverride||diagnosticResult(profile.diagnosticAnswers).level):activeLevel(profile)}
export function subjectFor(profile:any){return profile?.subject?.trim()||goalKinds[goalKind(profile)].object}
export function lessonSkill(key:string):Skill{const p=coursePaths.find(p=>key.startsWith(p.id+'-')),i=Number(key.split('-').at(-1));const l=p?.lessons[i];if(p?.level==='beginner'){const map:Skill[][]=[['planning','planning','planning','composition','planning'],['exposure','exposure','exposure','focus','exposure'],['composition','composition','focus','delivery','composition'],['lighting','lighting','colour','lighting','lighting'],['sound','sound','sound','sound','sound'],['composition','composition','composition','composition','composition'],['editing','editing','editing','colour','delivery'],['planning','planning','sound','planning','editing']];return map[p.week-1][i]}const t=(l?.title||'').toLowerCase();if(/sound|audio|dialogue|microphone|mix|room tone|listen/.test(t))return 'sound';if(/focus|depth/.test(t))return 'focus';if(/white|colour|color|neutral/.test(t))return 'colour';if(/light|contrast|shadow/.test(t))return 'lighting';if(/export|delivery|deliver|quality|archive|publish|version/.test(t))return 'delivery';if(/lens|exposure|shutter|motion|camera|settings|auto/.test(t))return 'exposure';if(/edit|cut|pace|organise|ingest|sequence/.test(t))return 'editing';if(/shot|frame|subject|coverage|movement|pans|tilts|line/.test(t))return 'composition';return l?.phase==='post'?'editing':'planning'}
function family(s:Skill){return ['composition','exposure','focus','lighting','colour'].includes(s)?'camera':s==='planning'?'planning':s==='sound'?'sound':s==='delivery'?'delivery':'editing'}
export type PersonalPath={id:string;title:string;why:string;keys:string[];minutes:number;order:number};
export type PersonalPlan={version:string;level:Level;title:string;goal:string;subject:string;paths:PersonalPath[];keys:string[];minutes:number;hoursPerWeek:number;weeks:number;budget:number;outcome:string;duration:string;needs:Skill[];strengths:Skill[]};
const priorities:Record<GoalKind,number[]>={product:[0,1,3,2,6,7,4,5],travel:[0,2,5,1,6,7,4,3],documentary:[0,4,5,7,6,1,3,2],social:[0,2,6,1,4,7,3,5],editing:[6,0,5,7,4,1,3,2],story:[0,5,7,2,6,4,1,3]};
export function buildPersonalPlan(profile:any):PersonalPlan{
 if(isScenarioProfile(profile))return buildScenarioPlan(profile) as any;
 const level=profileLevel(profile),g=goalKinds[goalKind(profile)],subject=subjectFor(profile),list=coursePaths.filter(p=>p.level===level),hours=Math.max(1,Math.min(20,Number(profile?.hours)||4)),weeks=[4,6,8,12].includes(Number(profile?.weeks))?Number(profile.weeks):6,budget=hours*weeks;
 const scores=isPersonalized(profile)?diagnosticResult(profile.diagnosticAnswers).scores:Object.fromEntries(skillIds.map(s=>[s,50]));
 const needs=skillIds.filter(s=>(scores[s]??0)<65).sort((a,b)=>(scores[a]??0)-(scores[b]??0));const strengths=skillIds.filter(s=>(scores[s]??0)>=75);
 const count=Math.min(list.length,Math.max(3,Math.floor(budget/6)));
 const mandatory=level==='beginner'?[0,6]:[0,3];
 const rank=list.map((p,i)=>({i,score:(level==='beginner'?10-priorities[goalKind(profile)].indexOf(i):[7,6,5,8][i])+p.lessons.reduce((n,l,j)=>n+(needs.includes(lessonSkill(p.id+'-'+j))?2:0),0)})).sort((a,b)=>b.score-a.score);
 const chosen=[...mandatory];for(const r of rank)if(chosen.length<count&&!chosen.includes(r.i))chosen.push(r.i);chosen.sort((a,b)=>a-b);
 const sessionsPerPath=budget/count>=6?5:budget/count>=4?4:3;
 const sessionMinutes=Math.max(15,Math.min(100,Math.floor(budget*60/(count*sessionsPerPath)/5)*5));
 const duration=budget<18?'15–30 seconds':budget<36?'30–60 seconds':level==='advanced'?'2–3 minutes':'60–90 seconds';
 const paths=chosen.map((n,order)=>{const p=list[n];const indices=sessionsPerPath===5?[0,1,2,3,4]:sessionsPerPath===4?[0,1,3,4]:[0,(goalKind(profile)==='editing'&&p.id==='basic-w7')?1:2,4];const keys=indices.map(i=>p.id+'-'+i);const focus=keys.map(lessonSkill).find(s=>needs.includes(s));const title=pathTitle(p.id,profile);return {id:p.id,title,keys,minutes:keys.length*sessionMinutes,order:order+1,why:focus?`${skillNames[focus]} needs practice in your diagnostic. Apply it to ${subject}.`:`Use ${p.title.toLowerCase()} to make ${g.finish} for ${g.viewer}.`}});
 return {version:'personal-v1',level,title:profile?.goal?.trim()||'Create '+g.finish,goal:g.label,subject,paths,keys:paths.flatMap(p=>p.keys),minutes:paths.reduce((n,p)=>n+p.minutes,0),hoursPerWeek:hours,weeks,budget,outcome:`A ${g.finish.replace(/^a /,'')} about ${subject}, lasting ${duration}, with a before/after comparison.`,duration,needs,strengths};
}
export function pathTitle(id:string,profile:any){const p=coursePaths.find(p=>p.id===id)!;const kind=goalKind(profile),s=subjectFor(profile);const theme=profile?.subject?.trim()?'your '+profile.subject.trim().replace(/^(my|our|the)\s+/i,'').slice(0,70):kind==='product'?'your product':kind==='travel'?'your place':kind==='documentary'?'your portrait':kind==='editing'?'your edit':kind==='social'?'your creator video':'your story';const titles:Record<string,string>={'basic-w1':`Find the idea for ${theme}`,'basic-w2':`Capture ${theme} clearly`,'basic-w3':`Frame what matters in ${theme}`,'basic-w4':`Shape the light for ${theme}`,'basic-w5':`Give ${theme} clear sound`,'basic-w6':`Gather the shots ${theme} needs`,'basic-w7':`Build ${theme} in the edit`,'basic-w8':`Finish and test ${theme}`,'intermediate-w1':`Choose the look of ${theme}`,'intermediate-w2':`Control light and sound for ${theme}`,'intermediate-w3':`Connect the scenes in ${theme}`,'intermediate-w4':`Refine and deliver ${theme}`,'advanced-w1':`Develop the treatment for ${theme}`,'advanced-w2':`Direct a controlled scene for ${theme}`,'advanced-w3':`Finish ${theme} for delivery`,'advanced-w4':`Make ${theme} portfolio-ready`};return titles[id]||p.title}
export function curatedLesson(profile:any,key:string):CourseLesson & {hook:string;why:string;sessionMinutes:number;personalized:boolean}{if(isScenarioKey(key))return scenarioLesson(key,profile);const path=coursePaths.find(p=>key.startsWith(p.id+'-'))!,index=Number(key.split('-').at(-1)),base=path.lessons[index],skill=lessonSkill(key),g=goalKinds[goalKind(profile)],subject=subjectFor(profile),plan=buildPersonalPlan(profile),selected=plan.paths.find(p=>p.keys.includes(key)),minutes=selected?selected.minutes/selected.keys.length:base.minutes,personalized=isPersonalized(profile);const context=g.examples[family(skill)];if(!personalized)return {...base,hook:base.title,why:context,sessionMinutes:base.minutes,personalized:false};
 const title=index===4?`Your ${g.finish.replace(/^a /,'')}: ${skillNames[skill].toLowerCase()} study`:`${base.title.replace(/\.$/,'')} for ${goalKind(profile)==='editing'?'your existing clips':subject}`;
 const tool=profile.gear==='Smartphone'?'Use your phone and a mobile editor. If manual controls are unavailable, label a planned comparison.':profile.gear==='Smartphone and computer'?'Capture on your phone; organise and compare the results in your desktop editor.':'Use your camera and editor. Log the settings that affect this test.';
 const scopedTask=base.do.replace(/\b(?:a |an )?\d+(?:[–-]\d+)?[- ](?:second|minute)s? (?=film|scene|interview|sequence|study|video|cut|reel|portrait|demonstration)/gi,'your planned ');
 const assignment=`Work with ${subject} for ${g.viewer}. ${scopedTask} Keep this practice focused on a ${plan.duration} study or labelled storyboard. ${tool}`;
 return {...base,title,do:assignment,example:context,hook:context,why:selected?.why||`An optional ${skillNames[skill].toLowerCase()} study for your goal.`,sessionMinutes:minutes,personalized:true,learn:base.learn,alternative:`Use labelled stills, settings notes or a storyboard of ${subject}. ${context} Describe planned decisions separately from anything you actually filmed. The same three criteria apply.`};
}
export function personalKeys(s:any,pathId?:string){const p=s?.profile;if(isScenarioProfile(p)){const plan=buildScenarioPlan(p);if(!pathId||plan.paths.some(x=>x.id===pathId))return plan.keys;}if(isPersonalized(p)){const plan=buildPersonalPlan(p);if(!pathId||plan.paths.some(x=>x.id===pathId))return plan.keys}return null}
export function freePathsFor(s:any):string[]{return s?.trialPathIds?.length?s.trialPathIds:['basic-w1','basic-w2']}
export function freeLessonKey(s:any,key:string){return isFreeModule(key)||['product-reel','everyday-story'].some(id=>key.startsWith(id+'-')&&isVisualKey(key))||freePathsFor(s).some(id=>key.startsWith(id+'-'))}
export function currentPlan(s:any):PersonalPlan|null{return isScenarioProfile(s?.profile)?buildScenarioPlan(s.profile) as unknown as PersonalPlan:isPersonalized(s?.profile)?buildPersonalPlan(s.profile):null}
