'use client';
import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {learningResources} from './learning-resources';
import {ResourcePlayer} from './resource-player';
import {levels,Level,levelNames,levelOutcome,keysForLevel,pathsForLevel,goalPractice} from './selfpaced-curriculum';
import {moduleHref} from './learning-rules';
import {useLearning,PageHead,Panel,Go,Gate,Action} from './ui';

export {ScenarioResources as ResourceLibrary} from "./resource-browser";
function LegacyResourceLibrary(){const [search,setSearch]=useState(''),[topic,setTopic]=useState('All'),[format,setFormat]=useState('All'),[selected,setSelected]=useState<string|null>(null);const list=learningResources.filter(r=>(topic==='All'||r.topic===topic)&&(format==='All'||(format==='Video'?r.type.toLowerCase().includes('video'):r.type.toLowerCase().includes('guide')))&&[r.title,r.creator,r.focus,r.topic].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <><PageHead eyebrow="WATCH · READ · PRACTISE" title="Your resource library">One useful idea, then try it yourself.</PageHead><div className="resource-filters"><label>Find a resource<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Exposure, sound, editing…"/></label><label>Topic<select aria-label="Topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['All',...new Set(learningResources.map(r=>r.topic))].map(t=><option key={t}>{t}</option>)}</select></label><label>Format<select aria-label="Format" value={format} onChange={e=>setFormat(e.target.value)}><option>All</option><option>Video</option><option>Reading guide</option></select></label></div><p className="small" role="status">{list.length} resources · external lessons remain credited to their creators</p><div className="resource-library-grid">{list.map((r,i)=><article className="library-resource" key={r.id}>{selected===r.id?<ResourcePlayer resource={r}/>:<><div className="library-resource-image"><div className="resource-topic-art" aria-hidden="true">{r.topic}<small>{r.host}</small></div><span>{r.type}</span></div><div className="library-resource-copy"><span className="small">{r.topic} · {r.creator}</span><h2>{r.title}</h2><p>{r.focus}</p><Button variant="outline" onClick={()=>setSelected(r.id)}>Open resource</Button></div></>}{selected===r.id&&<Button className="resource-close" variant="ghost" onClick={()=>setSelected(null)}>Close resource</Button>}</article>)}</div>{!list.length&&<Panel><h2>No matching resources</h2><p>Try another topic or a shorter search.</p><Button onClick={()=>{setSearch('');setTopic('All');setFormat('All')}}>Clear filters</Button></Panel>}<p className="small library-note">These videos play from YouTube or Vimeo. Some show older software. Each lesson also has its own reading and task.</p></>}

export function CourseFinish({level}:{level:string}){const {s,mutate}=useLearning();if(!levels.includes(level as Level))return <Panel><h1>Level not found</h1><Go href="/workspace">My journey</Go></Panel>;const l=level as Level,keys=keysForLevel(l),remaining=keys.find(k=>!s.progress[k]),next=levels[levels.indexOf(l)+1];
 return <><PageHead eyebrow={levelNames[l].toUpperCase()+' / YOUR WORK'} title={remaining?'Keep building your film':levelNames[l]+' journey complete'}/><Gate>{remaining?<Panel><p>Your next assignment brings you closer to: {levelOutcome[l]}</p><Go href={moduleHref(remaining)+'?tab=assignment'}>Continue my assignment</Go></Panel>:<><section className="finish-feature"><div className="finish-mark" aria-hidden="true">✓</div><div><span className="eyebrow">{keys.length} SESSIONS COMPLETED</span><h2>{levelOutcome[l]}</h2><p>This shows your self-checks and AI reviews. It is a record of your learning, not a qualification.</p><Go href="/portfolio">See my work</Go></div></section><Panel><h2>What to keep</h2><ul className="plain-list"><li>Your finished film and a before/after comparison.</li><li>A short explanation of three decisions that improved it.</li><li>One specific skill to practise next.</li></ul>{next?<Action onClick={async()=>{if(await mutate('learning_level',{level:next}))window.location.assign('/workspace')}}>Continue to {levelNames[next]}</Action>:<Go href="/diagnostic">Plan my next creative goal</Go>}</Panel></>}</Gate></>}

export function PilotHelp(){return <section className="calm-help"><PageHead eyebrow="A LITTLE HELP" title="Keep learning simple."/><div className="help-three"><details className="lesson-details"><summary>Where do I start?</summary><p>Pick what you like to film and answer 12 quick questions. We build a plan around your level and time. Open Journey any time to carry on.</p><Go href="/">Find my starting point</Go></details><details className="lesson-details"><summary>How do I learn and get feedback?</summary><p>Watch, try the task, then check your work. AI can read your notes and one photo. It can’t watch videos or hear sound.</p><p>In Reflect, check your work, note one thing to fix and answer three questions. You can move on with any score.</p><a className="text-link" href="/safety">Recording and sharing safely</a></details><details className="lesson-details"><summary>What is free, and what is not real yet?</summary><p>Free: watch every module and do the tasks in the first two. Self-paced and Mentor-led unlock the rest. Checkout is practice only, and mentors are made up.</p><p>Your work is private unless you choose to publish selected portfolio pieces.</p><Go href="/membership" outline>See access details</Go></details></div></section>}
