'use client';
import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {useLearning} from './ui';
import {scenarioLesson,scenarioRubric,caseById} from './scenario-engine';
import {resourcesFor} from './learning-resources';
import {ResourcePlayer} from './resource-player';
import {AdaptiveLab} from './adaptive-lab';

export function ScenarioLab({kind,lessonKey}:{kind:string;lessonKey:string}){const {s}=useLearning(),lesson=scenarioLesson(lessonKey,s.profile);const [on,setOn]=useState(false),[rate,setRate]=useState(12),[frames,setFrames]=useState(24),[order,setOrder]=useState([0,1,2]);
 if(kind==='skill')return <AdaptiveLab lessonKey={lesson.sourceModule}/>;
 if(kind==='time')return <div className="scenario-lab"><span className="eyebrow">FRAME-COUNT LAB</span><h2>Same frames. Different timing.</h2><div className="frame-strip" aria-label={frames+' source frames'}>{Array.from({length:Math.min(24,frames)},(_,i)=><i key={i} style={{opacity:.25+i/32}}>{i+1}</i>)}</div><div className="scenario-form-grid"><label>Source frames <output>{frames}</output><input aria-label="Source frames" type="range" min={12} max={120} step={12} value={frames} onChange={e=>setFrames(Number(e.target.value))}/></label><label>Playback frames per second <output>{rate}</output><input aria-label="Playback frames per second" type="range" min={6} max={30} step={6} value={rate} onChange={e=>setRate(Number(e.target.value))}/></label></div><p className="lab-result" aria-live="polite">{frames} ÷ {rate} = <strong>{(frames/rate).toFixed(1)} seconds</strong></p><p>Playback speed changes duration. It does not add captured detail or make movement analysis calibrated.</p></div>;
 if(kind==='live')return <div className="scenario-lab"><span className="eyebrow">CONNECTION REHEARSAL</span><h2>What survives a lost connection?</h2><div className="signal-flow"><div>Camera & sound<small>Still working</small></div><div className={on?'signal-missing':''}>Uplink<small>{on?'Disconnected':'Connected'}</small></div><div>Receiver<small>{on?'Frozen / unavailable':'Picture and sound'}</small></div></div><div className="local-record">Separate local recording <strong>Still available</strong></div><Button variant="outline" aria-pressed={on} onClick={()=>setOn(!on)}>{on?'Restore test connection':'Simulate connection loss'}</Button><p>This diagram assumes local recording was configured and tested. A live preview is not a backup; verify the saved file.</p></div>;
 if(kind==='screen')return <div className="scenario-lab"><span className="eyebrow">READABILITY & PRIVACY</span><h2>Choose what the viewer receives.</h2><div className={'capture-demo '+(on?'window-only':'')}><div className="capture-toolbar">{on?'Selected window':'Whole desktop'} · demo data</div><div className="capture-message"><strong>1. Open the sample</strong><p>2. Change one setting</p><strong>3. Check the result</strong></div>{!on&&<aside>Unrelated notification<br/><span>Private message could appear here</span></aside>}</div><Button variant="outline" aria-pressed={on} onClick={()=>setOn(!on)}>{on?'Show the whole desktop':'Capture only the useful window'}</Button><p>{on?'The action is larger and unrelated windows stay outside the recording.':'The viewer gets more clutter, smaller text and possible private information.'} Still disable notifications and inspect the actual output.</p></div>;
 if(kind==='captions')return <div className="scenario-lab"><span className="eyebrow">MEANING WITH SOUND OFF</span><h2>Keep the instruction understandable.</h2><div className="caption-demo"><span>Silent instruction sample</span><strong>{on?'Place the cup on the left shelf. [Timer beeps]':'[A person points and speaks]'}</strong></div><Button variant="outline" aria-pressed={on} onClick={()=>setOn(!on)}>{on?'Hide the text alternative':'Show words and meaningful sound'}</Button><p>Text can carry the instruction and a relevant sound cue. A descriptive transcript can also explain essential visual information. Check the actual audience’s needs.</p></div>;
 if(kind==='record'||kind==='privacy')return <div className="scenario-lab"><span className="eyebrow">{kind==='privacy'?'PERMISSION BOUNDARIES':'CONTEXT & ORIGINALS'}</span><h2>{kind==='privacy'?'The audience changes the permission.':'A detail needs its context.'}</h2><div className="record-demo">{kind==='privacy'?<><div><small>Permission given</small><strong>Private learning review</strong></div><div className={on?'signal-missing':''}><small>Proposed use</small><strong>{on?'Public advertisement':'Private learning review'}</strong></div></>:<>{on&&<div><small>Overview + identifying feature</small><strong>Whole object in its setting</strong></div>}<div><small>Close detail</small><strong>One visible mark</strong></div>{on&&<div><small>Unmodified source + log</small><strong>Context can be checked</strong></div>}</>}</div><Button variant="outline" aria-pressed={on} onClick={()=>setOn(!on)}>{kind==='privacy'?(on?'Return to agreed use':'Change to public advertising'):(on?'Show only the detail':'Include context and the original')}</Button><p aria-live="polite">{kind==='privacy'?(on?'A new audience and purpose need a new permission decision. An earlier agreement does not cover every use.':'The proposed use matches the stated boundary. Actual consent still needs to be agreed and documented.'):(on?'The surrounding view and log help connect the detail to the record. They do not prove a cause or legal admissibility.':'The close detail alone does not show which object, setting or sequence it belongs to.')}</p></div>;
 if(kind==='compare')return <div className="scenario-lab"><span className="eyebrow">CLAIM & EVIDENCE</span><h2>Make your reflection specific.</h2><div className="comparison-note">{on?'At 00:12 the opening label could not be read on my phone. I made the label larger and checked the new export at the same timecode.':'The video is much better now.'}</div><Button variant="outline" aria-pressed={on} onClick={()=>setOn(!on)}>{on?'Show the broad claim':'Show a specific comparison'}</Button><p>A concrete note records a test and a change. It is still your report; AI cannot verify the unseen video or sound.</p></div>;
 return <div className="scenario-lab"><span className="eyebrow">SEQUENCE WORKBENCH</span><h2>Change the order. Notice the meaning.</h2><div className="sequence-workbench">{order.map((id,i)=><div key={id}><small>{i+1}</small><strong>{['Context','Action','Result'][id]}</strong><p>{['Where and what the viewer needs to know','The change or important event','The state after the action'][id]}</p><Button variant="outline" disabled={i===0} onClick={()=>setOrder(v=>{const n=[...v];[n[i],n[i-1]]=[n[i-1],n[i]];return n;})} aria-label={'Move '+['context','action','result'][id]+' earlier'}>Move earlier</Button></div>)}</div><p aria-live="polite">{order[0]===0?'Context first helps a new viewer understand the action.':order[0]===2?'A result first can create curiosity; make sure the later context still explains it truthfully.':'Action first can draw attention, but an unfamiliar viewer may need context quickly.'} Factual records must preserve the actual sequence in the original.</p></div>;
}
export function ScenarioDiscovery({lessonKey,active,onMake}:{lessonKey:string;active:boolean;onMake:()=>void}){const {s}=useLearning(),lesson=scenarioLesson(lessonKey,s.profile),request=s.profile?.request,low=request?.starting?.bandwidth==='low'||request?.starting?.bandwidth==='offline';const [step,setStep]=useState(request?.preferences?.modality==='read'?1:request?.preferences?.modality==='watch'?3:0),[resource,setResource]=useState(0);const candidates=resourcesFor(lesson),resources=candidates.filter(r=>(!r.devices||r.devices.includes(request?.starting?.device||'android'))&&(!low||r.format==='read'||!r.youtubeId&&!r.vimeoId));const sections=['Explore','Understand','Example','Watch or read'];
 function download(){const rubric=scenarioRubric(lessonKey,s.profile),text=[lesson.title,'Framepath — English offline practice',lesson.learn,'EXAMPLE',lesson.example,'MAKE',lesson.do,'ALTERNATIVE',lesson.alternative,'REFLECT',...rubric.map((r:any)=>r.label+' ('+r.weight+'%): '+r.minimum),'AI reviews text and one still only. Offline work is not automatically synced. Return online and save your notes.','References',...candidates.map(r=>r.title+' — '+r.creator+'\n'+r.source)].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=lessonKey+'-offline.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="simple-learning"><div className="scenario-lesson-tools"><span className="small">Watch / Make / Reflect · {lesson.minutes} min</span><Button variant="ghost" onClick={download}>Save lesson for offline</Button></div><div className="lesson-card">{step===0?<ScenarioLab kind={lesson.scenarioLab} lessonKey={lessonKey}/>:step===1?<div className="concept-slide text-concept"><div><span className="eyebrow">THE IDEA</span><h2>{lesson.title}</h2>{lesson.learn.split(/(?<=\.)\s+/).reduce((parts:string[][],sentence,i)=>{if(i%3===0)parts.push([]);parts[parts.length-1].push(sentence);return parts},[]).map((p,i)=><p className="concept-copy" key={i}>{p.join(' ')}</p>)}</div></div>:step===2?<div className="example-slide"><h2>One practical example</h2><p>{lesson.example}</p><div className="example-task"><strong>Your task</strong><p>{lesson.hook}</p></div><p className="small">{lesson.why}</p></div>:<div className="deeper-slide"><h2>{low?'A light-data reading':'Go deeper if useful'}</h2><p className="small">External lessons are optional. The original reading and practical task are enough to begin.</p>{resources.length?<>{resources.length>1&&<div className="resource-choices">{resources.map((r,i)=><Button key={r.id} variant="outline" aria-pressed={resource===i} onClick={()=>setResource(i)}>{r.creator}</Button>)}</div>}<ResourcePlayer resource={resources[Math.min(resource,resources.length-1)]} active={active}/></>:<p>{lesson.learn}</p>}{!resources.length&&<p className="small">No external resource matches this device and connection. Use the reading above or save it for offline practice.</p>}</div>}</div><div className="slide-controls"><Button variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}>Back</Button><span aria-live="polite">{sections[step]} · {step+1}/4</span>{step<3?<Button onClick={()=>setStep(step+1)}>Next</Button>:<Button onClick={onMake}>Make your assignment</Button>}</div>{request?.preferences?.modality==='discuss'&&<p className="notice">Discussion brief: show your safe sample to someone you choose. Ask what they understood, what is missing and which revision would help. Record their words separately from your own reflection. No reviewer is assigned here.</p>}<div className="button-row"><Button variant="ghost" onClick={()=>setStep(0)}>Explore the demo</Button><Button variant="ghost" onClick={()=>setStep(1)}>Read the idea</Button><Button variant="ghost" onClick={onMake}>Open practical task</Button></div></section>;
}
