import raw from './scenario-runtime.json';
import {visualLesson,visualCriteria} from './lessons/content';
import {scenarioTeaching} from './scenario-content';
import {coursePaths,CourseLesson,Level} from './selfpaced-curriculum';
import {diagnosticPoints,validAnswer} from './diagnostic-engine';

export const scenarioData:any=raw;
export const scenarioVersion='scenario-v1';
export const categories:{id:string;name:string}[]=raw.categories;
export const scenarios:any[]=raw.use_cases;
export const archetypes:any[]=Object.values(raw.archetypes);
export const clusterNames:Record<string,string>=raw.skills;
export const caseById=(id:string)=>scenarios.find(c=>c.id===id);
export const isScenarioProfile=(p:any)=>p?.diagnosticVersion===scenarioVersion&&!!caseById(p?.request?.scenario?.use_case);
export const stages=['prepare','foundations','practice','stretch','finish','starter'] as const;
export type ScenarioStage=typeof stages[number];
const stageNames:Record<ScenarioStage,string>={prepare:'Prepare your recording',foundations:'Build the missing skills',practice:'Make your first version',stretch:'Test a harder version',finish:'Check and deliver',starter:'A small first try'};
const stopWords=new Set('a an and as at be by for from how i in into is it make my of on or our record recording some the their to using video videos want with'.split(' '));
const synonyms:Record<string,string>={wedding:'wedding ceremony',teacher:'education teaching lecture',teach:'teaching lesson',damage:'damage proof condition tenant',tenant:'property damage evidence',coach:'sports coaching analysis',realtor:'real estate property',ngo:'nonprofit fundraising',vlog:'travel vlogging',animation:'stop motion animation',return:'proof product returning',bug:'bug software screen',zoom:'meeting webinar remote',livestream:'live streaming',360:'360 immersive spatial'};
export function searchScenarios(query:string,category='',limit=12){const words=query.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).filter(w=>w.length>1&&!stopWords.has(w));const terms=[...new Set(words.flatMap(w=>(synonyms[w]||w).split(' ')))];return scenarios.filter(c=>!category||c.category_id===category).map(c=>{const name=c.source_text.toLowerCase(),detail=(c.learner_outcome+' '+c.archetype_name+' '+c.category).toLowerCase();return {scenario:c,score:terms.reduce((n,w)=>n+(name.includes(w)?4:detail.includes(w)?1:0),0)}}).filter(x=>!terms.length||x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
export function initialScenarioRequest(useCase='C01-04') {const c=caseById(useCase)||scenarios[0];return {scenario:{use_case:c.id,category:c.category_id,archetype:c.primary_archetype},outcome:{goal:c.learner_outcome,audience:'',orientation:'native',format:'',length_seconds:null as number|null,deadline_days:28,stakes:[...c.stakes]},starting:{gear:['phone'],device:'android',control:'controlled',outdoor:false,authorised:false,local_backup:false,screen_recorder:true,specialist:false,spatial:false,bandwidth:'standard',hours:2,weeks:4,language:'en',accessibility:[] as string[],skills:Object.fromEntries(Object.keys(clusterNames).map(k=>[k,null]))},preferences:{modality:'do',structure:'guided',pace:'steady',feedback:'self',sequence:'plan_first',assessment_comfort:'private',motivation:'finish_task'},checks:[] as {id:number;answer:any}[]};}
const pick=(v:any,values:any[],fallback:any)=>values.includes(v)?v:fallback;
function bounded(v:any,min:number,max:number,otherwise:number){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:otherwise;}
const txt=(v:any,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
export function activityIds(request:any){const c=caseById(request?.scenario?.use_case);const a=c?.primary_archetype;return a==='A12'?[7,5,8]:a==='A13'?[4,7,8]:a==='A19'?[2,6,8]:['A06','A11','A20'].includes(a)?[4,0,8]:['A02','A14','A15','A16'].includes(a)?[0,1,8]:a==='A05'?[4,1,8]:a==='A07'?[5,3,8]:[0,4,8];}
export function normalizeScenarioRequest(input:any,requireChecks=true){
 const c=caseById(input?.scenario?.use_case);if(!c)throw Error('Choose the closest video task so we can make a relevant route.');
 if(input.scenario.category!==c.category_id||input.scenario.archetype!==c.primary_archetype)throw Error('The selected task and category do not match. Choose the task again.');
 const fallback=initialScenarioRequest(c.id),o=input.outcome||{},s=input.starting||{},p=input.preferences||{};
 const req:any={scenario:{use_case:c.id,category:c.category_id,archetype:input.scenario.archetype},outcome:{goal:txt(o.goal)||c.learner_outcome,audience:txt(o.audience,200)||c.audience,orientation:pick(o.orientation,['native','landscape','portrait','square','spatial'],'native'),format:txt(o.format,240)||c.deliverable.format,length_seconds:o.length_seconds==null||o.length_seconds===''?null:bounded(o.length_seconds,1,14400,60),deadline_days:bounded(o.deadline_days,1,365,28),stakes:[...new Set([...c.stakes,...(Array.isArray(o.stakes)?o.stakes.filter((x:any)=>['personal','emotional','commercial','evidence','safety'].includes(x)):[])])]},starting:{gear:Array.isArray(s.gear)?[...new Set(s.gear.filter((g:any)=>['phone','camera','computer','microphone','tripod','drone','360_camera','specialist_capture'].includes(g)))]:['phone'],device:pick(s.device,['android','ios','desktop'],'android'),control:pick(s.control,['controlled','uncontrolled','real_time','one_take'],'controlled'),outdoor:s.outdoor===true,authorised:s.authorised===true,local_backup:s.local_backup===true,screen_recorder:s.screen_recorder===true,specialist:s.specialist===true,spatial:s.spatial===true,bandwidth:pick(s.bandwidth,['low','standard','stable','offline'],'standard'),hours:bounded(s.hours,.5,20,2),weeks:bounded(s.weeks,1,12,4),language:'en',accessibility:Array.isArray(s.accessibility)?s.accessibility.filter((v:any)=>['captions','descriptions','keyboard','reduced_motion','large_text'].includes(v)):[],skills:Object.fromEntries(Object.keys(clusterNames).map(k=>[k,Number.isInteger(s.skills?.[k])&&s.skills[k]>=0&&s.skills[k]<=4?s.skills[k]:null]))},preferences:{modality:pick(p.modality,['watch','read','do','discuss'],'do'),structure:pick(p.structure,['guided','open'],'guided'),pace:pick(p.pace,['gentle','steady','stretch'],'steady'),feedback:pick(p.feedback,['ai','mentor','peer','self'],'self'),sequence:pick(p.sequence,['plan_first','shoot_first'],'plan_first'),assessment_comfort:pick(p.assessment_comfort,['private','scored'],'private'),motivation:pick(p.motivation,['finish_task','build_confidence','improve_craft','career'],'finish_task')},checks:[]};
 if(!req.starting.gear.length)req.starting.gear=['phone'];
 const ids=activityIds(req),checks=input.checks;
 if(requireChecks&&(!Array.isArray(checks)||checks.length!==3||checks.some((x:any,i:number)=>x.id!==ids[i]||!validAnswer(ids[i],x.answer))))throw Error('Complete or skip each of the three practical checks. Skipped skills remain unassessed.');
 req.checks=(Array.isArray(checks)?checks:[]).filter((x:any,i:number)=>i<3&&x.id===ids[i]&&validAnswer(x.id,x.answer)).map((x:any)=>({id:x.id,answer:x.answer}));
 return req;
}
const signalCluster:Record<number,string>={0:'camera',1:'lighting',2:'camera',3:'lighting',4:'sound',5:'editing',6:'colour',7:'delivery',8:'workflow'};
export function scenarioSkills(request:any){const result:Record<string,{value:number|null;source:string;checks:number}>={};for(const k of Object.keys(clusterNames))result[k]={value:request?.starting?.skills?.[k]??null,source:'Self-reported',checks:0};const groups:Record<string,number[]>={};for(const x of request?.checks||[]){if(x.answer===null)continue;const k=signalCluster[x.id];(groups[k]||=[]).push(diagnosticPoints(x.id,x.answer));}for(const [k,v] of Object.entries(groups))result[k]={value:Math.round(v.reduce((a,b)=>a+b,0)/v.length*10)/10,source:'Practical check · limited sample',checks:v.length};for(const k of Object.keys(clusterNames)){const s=request?.assessedSkills?.[k];if(s&&(s.value===null||Number.isFinite(s.value)&&s.value>=0&&s.value<=4))result[k]={value:s.value,source:'Practical checks · limited sample',checks:s.checks||0};const override=request?.skillOverrides?.[k];if(Number.isFinite(override)&&override>=0&&override<=4)result[k]={value:override,source:'Adjusted by learner',checks:result[k].checks};}return result;}
export function scenarioLevel(request:any):Level {const c=caseById(request.scenario.use_case),s=scenarioSkills(request),values=c.skill_clusters.map((k:string)=>s[k]?.value).filter((v:any)=>v!==null&&v!==undefined);const mean=values.length?values.reduce((a:number,b:number)=>a+b,0)/values.length:0;return mean>=3.2?'advanced':mean>=2?'intermediate':'beginner';}
export function normalizeScenarioProfile(input:any){const request=normalizeScenarioRequest(input?.request),name=txt(input.name,60)||'Learner';return {diagnosticVersion:scenarioVersion,request,name,goal:request.outcome.goal,subject:txt(input.subject,120)||request.outcome.goal,gear:request.starting.gear.includes('camera')?'Camera and computer':request.starting.gear.includes('computer')?'Smartphone and computer':'Smartphone',hours:request.starting.hours,weeks:request.starting.weeks,people:'Ask permission',practiceMode:request.preferences.pace==='gentle'?'gentle':request.preferences.pace==='stretch'?'stretch':'core',experience:'Scenario diagnostic',answers:[0,0,0],level:scenarioLevel(request),updatedAt:new Date().toISOString()};}
export type RouteNotice={id:string;title:string;detail:string;blocking:boolean};
export function scenarioNotices(request:any):RouteNotice[]{const c=caseById(request.scenario.use_case),s=request.starting,o=request.outcome,p=request.preferences,req=c.production_requirements||[],a=request.scenario.archetype;const notes:RouteNotice[]=[];const add=(id:string,title:string,detail:string,blocking=false)=>notes.push({id,title,detail,blocking});
 if(o.orientation==='spatial'&&!['A18','A17'].includes(a))add('R03','Check the output format','This task does not need spatial delivery. Choose the original, portrait or landscape format.',true);
 if(req.includes('spatial_pipeline')&&o.orientation!=='native'&&o.orientation!=='spatial')add('R04','The target needs a spatial pipeline','A flat export will not meet the specified pipeline. Choose native/spatial or practise a labelled storyboard.',true);
 if(['A02','A14','A15','A16'].includes(a)&&o.orientation==='portrait')add('R05','Keep the full original','Forced portrait reframing may remove important context. Choose original format; a separate sharing copy can be reframed later.',true);
 if(req.includes('drone')&&(!s.gear.includes('drone')||!s.outdoor||!s.authorised))add('R06-R07','Ground rehearsal only','Actual aerial work needs suitable equipment, outdoor access and current permissions. Your practice stays on the ground.');
 if(req.includes('stable_uplink')&&s.bandwidth!=='stable')add('R08','Streaming remains untested','Use a local rehearsal. An actual live stream needs a stable tested uplink and a receiver check.');
 if(req.includes('local_backup')&&!s.local_backup)add('R09','Prepare a backup','Test a permitted local recording and a connection-failure fallback before a real live event.');
 if(req.includes('screen_recorder')&&!s.screen_recorder)add('R10','Use a screen storyboard','Screen capture is not available in your setup. Make a labelled sequence first; a recorded deliverable still needs a working capture tool.');
 if(s.bandwidth==='offline'&&p.feedback==='ai')add('R11','AI needs a connection','Keep the exercise locally and use a self-check. Request AI feedback when connected; nothing is sent while offline.');
 if((req.includes('specialist_capture')&&!s.specialist)||(req.includes('spatial_capture_or_pipeline')&&!s.spatial&&!s.gear.includes('360_camera')))add('R12','Specialist capture remains untested','Use a safe simulation or authorised sample. Real output requires the receiving team’s equipment, calibration and workflow.');
 if(c.review_policy!=='self_or_peer_with_evidence_limits'||['C12','C13','C14'].includes(c.category_id)||o.stakes.includes('safety'))add('R15','Qualified review is needed','This is filming practice, not medical, legal, scientific or safety advice. A qualified person must review real-world use.');
 if(['mentor','peer'].includes(p.feedback)||p.modality==='discuss')add('R18','Human feedback is pending','No reviewer is assigned by this self-paced pilot. Use the discussion brief with someone you choose; a self-check is not their approval.');
 if(c.legal_ethical_flags.some((f:string)=>/minor|clinical|patient|sensitive|private|legal/.test(f))||['C13','C14'].includes(c.category_id))add('R16','Use a harmless stand-in','Keep real private, clinical, legal-case or identifying material off this pilot. Practise with fictional data or your own objects.');
 if(o.stakes.includes('evidence')&&!['A02','A14','A15','A16'].includes(a))add('evidence-context','Keep an untouched original','Preserve the original, time and context separately from an edited sharing copy. A learning score does not establish evidentiary value.');
 if(a==='A05'&&scenarioLevel(request)==='beginner')add('event-readiness','Rehearse before taking responsibility','A staged exercise does not establish readiness to cover an unrepeatable paid event alone. Arrange supervised practice.');
 if(c.id==='C14-01')add('no-recording','A connection test, not a recorded consultation','Use dummy information. Do not record a consultation by default; recording needs a separate explicit permission and approved storage decision.');
 if(s.accessibility.length)add('R20','English text alternatives','Original readings and keyboard controls are available. External captions and descriptions vary; prefer the original text when an external resource does not meet your needs.');
 return notes;
}
function stageModules(c:any,stage:ScenarioStage):string[]{const a=scenarioData.archetypes[c.primary_archetype],base=scenarioData.pathways[c.pathway_id].module_order as string[];if(stage==='prepare')return base.slice(0,2);if(stage==='practice')return base.slice(2,5);if(stage==='finish')return base.slice(5);if(stage==='starter')return ['new:consent-privacy','new:'+a.new_core];if(stage==='stretch')return ['new:'+a.new_core,'new:reflect-revise'];return [...new Set(c.skill_clusters.map((k:string)=>scenarioData.foundation_modules[k]).filter((m:any)=>m&&!base.includes(m)))].slice(0,3) as string[];}
export function parseScenarioPath(pathId:string){const m=/^need-(c\d{2}-\d{2})-(prepare|foundations|practice|stretch|finish|starter)$/.exec(pathId),c=m&&caseById(m[1].toUpperCase());return c?{scenario:c,stage:m![2] as ScenarioStage}:null;}
export const isScenarioPath=(id:string)=>!!parseScenarioPath(id);
export function parseScenarioKey(key:string){const m=/^(need-c\d{2}-\d{2}-(?:prepare|foundations|practice|stretch|finish|starter))-(\d)$/.exec(key),p=m&&parseScenarioPath(m[1]);if(!p||!stageModules(p.scenario,p.stage)[Number(m![2])])return null;return {...p,pathId:m![1],index:Number(m![2])};}
export const isScenarioKey=(key:string)=>!!parseScenarioKey(key);
function applicableRequest(c:any,profile:any){return isScenarioProfile(profile)&&profile.request.scenario.use_case===c.id?profile.request:initialScenarioRequest(c.id);}
export function scenarioRubric(key:string,profile?:any){const visual=visualCriteria(key,profile);if(visual)return visual;const info=parseScenarioKey(key);if(!info)throw Error('This scenario assignment does not exist.');const {scenario:c,stage,index}=info,a=scenarioData.archetypes[c.primary_archetype],id=stageModules(c,stage)[index],source=scenarioData.modules[id];const specific=scenarioData.module_rubrics[id]||source?.source_checks?.map((label:string,i:number)=>[label,source.source_minimum[i]]);return a.rubric.map((r:any,i:number)=>{const label=specific?.[i]?.[0]||r.label,minimum=specific?.[i]?.[1]||r.anchors['2'];return {label,weight:r.weight,minimum,retry:'Repeat only this part and attach a specific comparison: '+minimum,anchors:['No relevant evidence is supplied.','An attempt is present, but part of this minimum is missing: '+minimum,minimum,'The minimum holds throughout this scoped sample, with a recorded playback or procedure check.','Meets 3, plus a before-and-after comparison shows a deliberate improvement without losing required context.'],example:`For this task: ${c.success_criteria[Math.min(i+1,c.success_criteria.length-1)]}`,aiObservability:r.ai_observability};});}
export function scenarioLesson(key:string,profile?:any):CourseLesson&{scenarioId:string;sourceModule:string;scenarioLab:string;mediaImage?:string;sessionMinutes:number;personalized:boolean;hook:string;why:string;level:Level}{const info=parseScenarioKey(key);if(!info)throw Error('This scenario lesson does not exist.');const {scenario:c,stage,index}=info,request=applicableRequest(c,profile),id=stageModules(c,stage)[index],m=scenarioData.modules[id],core=scenarioTeaching[id.replace('new:','')],path=coursePaths.find(p=>id.startsWith(p.id+'-')),base=path?.lessons[Number(id.split('-').at(-1))],a=scenarioData.archetypes[c.primary_archetype];const skill=scenarioSkills(request)[m?.skill],mode=skill?.value===null||skill?.value===undefined||skill.value<2?'foundation':skill.value>=3?'comparison':'applied';const gentle=request.preferences.pace==='gentle';const minutes=stage==='starter'?15:stage==='stretch'?45:gentle?25:30;
 const custom=scenarioData.case_adaptations[c.id]?.variant_task;
 let task=core?core.steps.join(' '):`Make a focused comparison for this task: ${c.learner_outcome}. ${base?.do||m.practice_template.replace('{outcome}',c.learner_outcome)}`;
 if(custom&&id==='new:'+a.new_core)task=custom+' '+(core?.steps.slice(-1)[0]||'');
 if(stage==='starter')task=index===0?'Use a harmless stand-in. Write the viewer, permission boundary and one part that must remain private.':(custom||m.practice_template)+' Keep the test to five minutes. Replay it and write one observation plus the next improvement. This is a starter sample, not the complete intended deliverable.';
 if(stage==='stretch')task+=' Compare two controlled versions or conditions. Log the trade-off, failure point and the version you would deliver.';
 if(!request.starting.gear.includes('camera')&&['camera','lighting','sound','screen','spatial'].includes(m?.skill))task+=' Use the controls your phone or learning device actually provides; label an unavailable control as a planned comparison.';
 if(mode==='foundation'&&stage!=='starter')task+=' Begin with one small test, then build the scoped sample. You do not need to finish the full original skill-bank exercise in this session.';
 if(request.preferences.sequence==='shoot_first'&&stage==='practice')task='After completing the preparation, make one safe five-minute test and note what is missing. '+task;
 if(mode==='comparison'&&stage!=='starter')task+=' Test a deliberate failure or harder condition and explain why the chosen approach still serves the task.';
 if(c.review_policy!=='self_or_peer_with_evidence_limits')task+=' Use a safe simulation; this exercise does not authorise real specialist work.';
 if(stage==='practice'||stage==='stretch'){task+=' Make this serve '+request.outcome.goal+' for '+(request.outcome.audience||c.audience)+'.';if(request.starting.control!=='controlled')task+=' Rehearse with a safe stand-in first. In the real setting, stay in an authorised position and do not interrupt or recreate an unrepeatable event for extra coverage.';}
 if(stage==='finish')task+=' Check the intended output: '+(request.outcome.length_seconds?request.outcome.length_seconds+' seconds; ':'duration agreed with the recipient; ')+(request.outcome.orientation==='native'?'retain the original picture shape':request.outcome.orientation)+'; '+(request.outcome.format||c.deliverable.format)+'.';
 const visual=visualLesson(key,profile);if(visual)return {mediaImage:visual.image,title:visual.title,minutes:visual.minutes,sessionMinutes:visual.minutes,phase:visual.phase,learn:visual.concept.text,do:visual.make.steps.join(' '),checks:[...visual.reflect],minimum:visual.minimum?[...visual.minimum]:[...visual.reflect],retry:visual.reflect.map(r=>'Repeat this part: '+r),resource:0,resourceIds:[],topic:m?.skill||'workflow',alternative:'Use a labelled storyboard and fictional data if capture is unavailable. This is a plan, not a finished recording.',example:visual.make.example.join(' → '),scenarioId:c.id,sourceModule:id,scenarioLab:core?.lab||'skill',personalized:true,hook:request.outcome.goal,why:visual.context?.why||visual.hook,level:mode==='comparison'?'advanced':mode==='applied'?'intermediate':'beginner'};
 const rubric=scenarioRubric(key,profile),needs=c.skill_clusters.map((k:string)=>clusterNames[k]).slice(0,3).join(', '),teaching=core?.idea||base?.learn||'';
 return {title:stage==='stretch'?(index===0?'Test the limit':'Explain your revision'):stage==='starter'?(index===0?'Set a safe scope':'Make one small test'):m?.title||base?.title||'Your recording',minutes,sessionMinutes:minutes,phase:stage==='prepare'||stage==='foundations'?'pre':stage==='finish'?'post':'production',learn:teaching,do:task,checks:rubric.map((r:any)=>r.label),minimum:rubric.map((r:any)=>r.minimum),retry:rubric.map((r:any)=>r.retry),resource:0,resourceIds:core?.resources||base?.resourceIds||m?.resources||[],topic:m?.skill||'workflow',alternative:`Use fictional notes, an owned object, a labelled storyboard or approved sample. Describe what is planned separately from what was captured. ${custom||c.learner_outcome}. Keep real private or specialist material off this pilot.`,lab:base?.lab,example:core?.example||base?.example||c.success_criteria[1],scenarioId:c.id,sourceModule:id,scenarioLab:core?.lab||'skill',personalized:true,hook:request.outcome.goal,why:`This practice supports ${needs} for ${request.outcome.audience||c.audience}.`,level:mode==='comparison'?'advanced':mode==='applied'?'intermediate':'beginner'};
}
export function scenarioPath(pathId:string,profile?:any){const p=parseScenarioPath(pathId);if(!p)return null;const request=applicableRequest(p.scenario,profile),keys=stageModules(p.scenario,p.stage).map((_,i)=>pathId+'-'+i),lessons=keys.map(key=>scenarioLesson(key,profile));return {id:pathId,title:stageNames[p.stage],caseTitle:p.scenario.learner_outcome,stage:p.stage,scenario:p.scenario,level:scenarioLevel(request),keys,lessons,minutes:lessons.reduce((n,l)=>n+l.minutes,0),why:p.stage==='foundations'?'Target the relevant skills that are new or not yet assessed.':p.stage==='stretch'?'Use the extra weekly time for a harder controlled comparison.':p.scenario.learner_outcome};}
export function buildScenarioPlan(profile:any){const request=profile.request,c=caseById(request.scenario.use_case);if(!c)throw Error('Choose a video task.');const signals=scenarioSkills(request),needs=c.skill_clusters.filter((k:string)=>signals[k]?.value===null||(signals[k]?.value??0)<2.5),strengths=c.skill_clusters.filter((k:string)=>(signals[k]?.value??0)>=3),notices=scenarioNotices(request);const prefix='need-'+c.id.toLowerCase()+'-',make=(stage:ScenarioStage)=>scenarioPath(prefix+stage,profile)!;
 let paths=[make('prepare'),make('practice'),make('finish')];const budgetMinutes=Math.floor(request.starting.hours*60*Math.min(request.starting.weeks,Math.max(1/7,request.outcome.deadline_days/7)));const coreMinutes=paths.reduce((n,p)=>n+p.minutes,0);
 if(needs.length&&stageModules(c,'foundations').length){const foundation=make('foundations');if(coreMinutes+foundation.minutes<=budgetMinutes)paths.splice(1,0,foundation);}
 if(request.starting.hours>=4&&request.preferences.pace!=='gentle'&&request.preferences.motivation!=='finish_task'){const stretch=make('stretch');if(paths.reduce((n,p)=>n+p.minutes,0)+stretch.minutes<=budgetMinutes)paths.splice(paths.length-1,0,stretch);}
 if(request.preferences.sequence==='shoot_first'){const foundation=paths.find(p=>p.stage==='foundations');if(foundation){paths=paths.filter(p=>p!==foundation);paths.splice(paths.findIndex(p=>p.stage==='practice')+1,0,foundation);}}
 const fullKeys=paths.flatMap(p=>p.keys),fullMinutes=paths.reduce((n,p)=>n+p.minutes,0),starterOnly=budgetMinutes<coreMinutes;if(starterOnly)paths=[make('starter')];const availableMinutes=Math.max(1,budgetMinutes),minutes=paths.reduce((n,p)=>n+p.minutes,0);
 if(starterOnly)notices.push({id:'R17',title:budgetMinutes<minutes?'More time is needed even for the starter':'Start with a small rehearsal',detail:`Your current window allows about ${budgetMinutes} minutes. The core route needs about ${coreMinutes} minutes. The ${minutes}-minute starter is a scoped exercise; the full task remains unfinished.`,blocking:budgetMinutes<minutes});
 const rehearsal=notices.some(n=>['R06-R07','R08','R10','R12','no-recording'].includes(n.id));
 const why=`You want to ${request.outcome.goal.charAt(0).toLowerCase()+request.outcome.goal.slice(1)}. This route prioritises ${needs.slice(0,3).map((k:string)=>clusterNames[k]).join(', ')||'applying your strongest skills'} for ${request.outcome.audience}. At ${request.starting.hours} hours a week, ${starterOnly?'start with one small rehearsal':`work through ${paths.length} pathways at a manageable pace`}. ${['A02','A14','A15','A16'].includes(c.primary_archetype)?'Keep factual context and originals; cinematic treatment is not the goal.':'Each assignment uses your intended audience and deliverable.'}`;
 return {version:scenarioVersion,scenarioId:c.id,archetype:c.primary_archetype,level:scenarioLevel(request),title:request.outcome.goal,goal:c.archetype_name,subject:request.outcome.goal,paths:paths.map((p,i)=>({...p,order:i+1})),keys:paths.flatMap(p=>p.keys),minutes,hoursPerWeek:request.starting.hours,weeks:request.starting.weeks,budget:availableMinutes/60,outcome:request.outcome.format||c.deliverable.format,duration:request.outcome.length_seconds?request.outcome.length_seconds+' seconds':'Match the recipient’s brief',needs,strengths,signals,notices,starterOnly,rehearsal,unscheduledKeys:starterOnly?fullKeys:[],fullMinutes,why,feedback:request.preferences.feedback,estimatedWeeks:Math.ceil(minutes/(request.starting.hours*60)*10)/10};
}
