'use client';
import React,{useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Search,Aperture,Check,SlidersHorizontal} from 'lucide-react';
import {categories,scenarios,archetypes,clusterNames,searchScenarios,caseById,initialScenarioRequest,activityIds,normalizeScenarioRequest,scenarioSkills,buildScenarioPlan,isScenarioProfile,scenarioVersion} from './scenario-engine';
import {DiagnosticControl,diagnosticQuestions,diagnosticDefaults} from './visual-diagnostic';
import {useLearning,Panel,Go,Gate} from './ui';
import {ScenarioSnapshot} from './scenario-pages';

const categoryLabels=['Everyday needs','Family & memories','Hobbies & creativity','Social & creator videos','Teaching & learning','Film & television','Marketing & commerce','Work & business','Events','News & documentary','Sport & fitness','Science & industry','Records & evidence','Health & wellbeing','Public service & nonprofits','Art & exhibitions','Travel & nature','Emerging uses'];
export function ScenarioHome(){const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[browse,setBrowse]=useState(false);const matches=searchScenarios(query,category,category?40:6);const show=!!query.trim()||!!category;return <section className="start-screen scenario-start"><div className="start-meta"><span>VIDEOGRAPHY / YOUR REAL GOAL</span><span>01 — START HERE</span></div><h1>What do you want to<br/>learn to <em>create?</em></h1><label className="scenario-search"><Search aria-hidden="true"/><span className="sr-only">What will your video help you do?</span><input type="search" value={query} maxLength={500} onChange={e=>setQuery(e.target.value)} placeholder="A lesson, a wedding film, proof of damage…"/></label><button className="text-link category-toggle" aria-expanded={browse} onClick={()=>setBrowse(!browse)}>{browse?'Hide categories':'Browse 18 categories'}</button>{browse&&<div className="category-grid" role="group" aria-label="Video goal categories">{categories.map((c,i)=><Button key={c.id} variant="outline" aria-pressed={category===c.id} onClick={()=>setCategory(category===c.id?'':c.id)}>{categoryLabels[i]}</Button>)}</div>}{show&&<section className="goal-results" aria-label="Matching video tasks"><div className="row between"><p className="small">{category?categories.find(c=>c.id===category)?.name:'Closest tasks — choose the one you mean'}</p>{category&&<Button variant="ghost" onClick={()=>setCategory('')}>All categories</Button>}</div>{matches.length?matches.map(({scenario:c})=><a className="scenario-result" key={c.id} href={'/diagnostic?case='+c.id+(query.trim()?'&goal='+encodeURIComponent(query.trim()):'')}><strong>{c.source_text}</strong><span>{c.archetype_name}</span></a>):<div className="notice"><p>No close match yet. Choose a category, then the nearest task. You can keep your own goal wording in the diagnostic.</p><Button variant="outline" onClick={()=>{setQuery('');setBrowse(true)}}>Choose a category</Button></div>}</section>}<p className="start-hint">A few practical checks. A route built around your task.</p><div className="journey-trail" aria-label="Your learning journey"><span className="active">Discover</span><i/><span>Learn</span><i/><span>Make</span><i/><span>Grow</span></div></section>}

const draftKey='framepath-scenario-diagnostic-v1';
const optionNames:Record<string,string>={phone:'Phone',camera:'Camera',computer:'Computer',microphone:'Microphone',tripod:'Stable support',drone:'Drone', '360_camera':'360 camera',specialist_capture:'Specialist capture system'};
const sectionTitles=['Your outcome','Your equipment','Your time','How you will learn','Your preferences','Your skills','Practical check','Practical check','Practical check'];
const quotes=['Make one small test. Notice one useful change.','Your task decides what a good video looks like.','A clear record can matter more than a beautiful frame.'];
function Options({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:string[][];label:string}){return <div className="diagnostic-toggle" role="group" aria-label={label}>{values.map(([v,t])=><Button variant="outline" aria-pressed={v===value} key={v} onClick={()=>onChange(v)}>{t}</Button>)}</div>}
export function ScenarioDiagnostic(){const {s,user,loaded,mutate}=useLearning();const [request,setRequest]=useState<any>(()=>initialScenarioRequest()),[name,setName]=useState(''),[step,setStep]=useState(0),[ready,setReady]=useState(false),[report,setReport]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<any>(null),[quote,setQuote]=useState(0);
 useEffect(()=>{if(!loaded||ready)return;const params=new URLSearchParams(location.search),selected=params.get('case'),goal=params.get('goal');let saved:any;try{saved=JSON.parse(sessionStorage.getItem(draftKey)||'null')}catch{}
 if(saved?.request&&caseById(saved.request.scenario?.use_case)&&(!selected||selected===saved.request.scenario.use_case)&&(!goal||goal===saved.request.outcome?.goal)){try{setRequest(normalizeScenarioRequest(saved.request,false));setName(typeof saved.name==='string'?saved.name:'');setStep(Math.min(8,Math.max(0,Number(saved.step)||0)));setReport(saved.report===true);setPending(saved.pending??null)}catch{}}
 else if(isScenarioProfile(s.profile)&&!selected&&!goal){setRequest(s.profile.request);setName(s.profile.name);setReport(true)}
 else {const c=caseById(selected||'')||searchScenarios(goal||'', '',1)[0]?.scenario||scenarios[0],next=initialScenarioRequest(c.id);if(goal)next.outcome.goal=goal;setRequest(next);setName(s.profile?.name||'');}
 setReady(true);
 },[loaded,ready]);
 useEffect(()=>{if(ready)try{sessionStorage.setItem(draftKey,JSON.stringify({request,name,step,report,pending}))}catch{}},[request,name,step,report,pending,ready]);
 useEffect(()=>{if(!loading)return;const timer=setInterval(()=>setQuote(n=>(n+1)%quotes.length),2200);return()=>clearInterval(timer)},[loading]);
 const c=caseById(request.scenario.use_case),checks=activityIds(request),activity=checks[step-6],question=diagnosticQuestions[activity],profile={diagnosticVersion:scenarioVersion,name:name.trim()||'Learner',request};
 const update=(layer:string,key:string,value:any)=>setRequest((r:any)=>({...r,[layer]:{...r[layer],[key]:value}}));
 const skills=scenarioSkills(request),observed=Object.values(skills).filter(v=>v.checks),meter=observed.length?Math.round(observed.reduce((n,v)=>n+(v.value||0),0)/observed.length*25):null;
 async function finish(next=request){setError('');setLoading(true);try{const clean=normalizeScenarioRequest(next);if(typeof navigator!=='undefined'&&!navigator.onLine){setRequest(clean);setReport(true);return}const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:{...profile,request:clean}}),signal:AbortSignal.timeout(15000)});const data:any=await response.json();if(!response.ok)throw Error(data.error||'Could not prepare your route.');setRequest(clean);setReport(true)}catch(e:any){setError(e.message||'Your answers are kept in this tab. Try again.')}finally{setLoading(false)}}
 async function save(){setLoading(true);const result=await mutate('profile',{profile});if(result){try{sessionStorage.removeItem(draftKey)}catch{}location.assign('/workspace')}else setLoading(false)}
 function next(skip=false){if(step<6){setStep(step+1);return}const answer=skip?null:pending??diagnosticDefaults[activity],changed={...request,checks:[...request.checks.slice(0,step-6),{id:activity,answer}]};setRequest(changed);setPending(null);if(step===8)void finish(changed);else setStep(step+1);}
 function restart(){setRequest((r:any)=>({...r,checks:[]}));setPending(null);setReport(false);setStep(6);setError('');}
 if(!ready)return <Panel><p role="status">Opening your starting point…</p></Panel>;
 if(loading)return <section className="curation-loading" aria-live="polite"><Aperture className="curation-spinner" size={48}/><h1>Building your route.</h1><p>{request.outcome.goal}</p><blockquote>{quotes[quote]}</blockquote><span className="small">Framepath practice notes</span></section>;
 if(report){const plan=buildScenarioPlan(profile);return <><div className="page-head"><div><span className="kicker">YOUR STARTING POINT</span><h1>{name?name+', your':'Your'} route</h1></div></div><ScenarioSnapshot profile={profile}/><div className="plan-actions">{user?<Button disabled={plan.notices.some(n=>n.blocking)} onClick={save}>Save & start my route</Button>:<Go href="/signin-with-chatgpt?return_to=%2Fdiagnostic">Sign in & save my route</Go>}<Button variant="outline" onClick={()=>{setRequest((r:any)=>({...r,checks:[]}));setPending(null);setReport(false);setStep(0)}}>Edit my answers</Button><Button variant="ghost" onClick={restart}>Retake practical checks</Button></div><p className="small">Your answers are kept in this tab until you save. Editing your route preserves previously saved work and does not reset free allowances.</p>{error&&<p className="notice" role="alert">{error}</p>}</>}
 return <section className="visual-diagnostic scenario-diagnostic"><div className="diagnostic-header"><span className="eyebrow">{sectionTitles[step]}</span><span>{step+1} / 9</span></div><div className="diagnostic-progress" role="progressbar" aria-label="Diagnostic progress" aria-valuemin={0} aria-valuemax={9} aria-valuenow={step}><i style={{width:step/9*100+'%'}}/></div>{step>=6&&<section className="live-level" aria-label="Submitted practical checks"><div><span>Practical starting signal</span><strong aria-live="polite">{meter===null?'Not assessed yet':meter>=80?'Advanced signal':meter>=50?'Intermediate signal':'Beginner signal'}</strong></div><div className="level-scale" role="meter" aria-label="Submitted check signal" aria-valuemin={0} aria-valuemax={100} aria-valuenow={meter??0} aria-valuetext={meter===null?'No scored checks':meter+' out of 100, limited sample'}><i style={{left:Math.max(2,Math.min(98,meter||0))+'%'}}/></div><div className="level-scale-labels"><span>Beginner</span><span>Intermediate</span><span>Advanced</span></div><p>{request.checks.length}/3 checks submitted · skips stay unassessed. Each skill gets its own starting point.</p></section>}
 <div className="visual-question">
 {step===0?<><h1>What should this video do?</h1><p className="small">{c.source_text} · <a className="text-link" href="/">Choose another task</a></p><label>Your goal<textarea aria-label="Your goal" rows={2} value={request.outcome.goal} maxLength={500} onChange={e=>update('outcome','goal',e.target.value)}/></label><div className="scenario-form-grid"><label>Your name · optional<input value={name} maxLength={60} autoComplete="given-name" onChange={e=>setName(e.target.value)}/></label><label>Who will use it?<input value={request.outcome.audience} maxLength={200} placeholder={c.audience} onChange={e=>update('outcome','audience',e.target.value)}/></label><label>Picture shape<select aria-label="Picture shape" value={request.outcome.orientation} onChange={e=>update('outcome','orientation',e.target.value)}><option value="native">Keep original / not sure</option><option value="landscape">Landscape</option><option value="portrait">Portrait</option><option value="square">Square</option><option value="spatial">Spatial / 360</option></select></label><label>Needed within<select aria-label="Needed within" value={request.outcome.deadline_days} onChange={e=>update('outcome','deadline_days',Number(e.target.value))}>{[[1,'Today'],[7,'One week'],[28,'Four weeks'],[56,'Eight weeks'],[84,'Twelve weeks']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><details className="lesson-details"><summary>Length, file format and stakes</summary><label>Length in seconds · optional<input type="number" min={1} max={14400} value={request.outcome.length_seconds??''} onChange={e=>update('outcome','length_seconds',e.target.value?Number(e.target.value):null)}/></label><label>Required format · optional<input maxLength={240} value={request.outcome.format} placeholder={c.deliverable.format} onChange={e=>update('outcome','format',e.target.value)}/></label><p className="small">Task stakes: {c.stakes.join(', ')}. Add any others.</p><div className="check-options">{['personal','emotional','commercial','evidence','safety'].map(v=><label key={v}><input type="checkbox" checked={request.outcome.stakes.includes(v)} disabled={c.stakes.includes(v)} onChange={e=>update('outcome','stakes',e.target.checked?[...request.outcome.stakes,v]:request.outcome.stakes.filter((x:string)=>x!==v))}/>{v}</label>)}</div></details></>
 :step===1?<><h1>What can you use?</h1><div className="check-options gear-options">{Object.entries(optionNames).map(([v,t])=><label key={v}><input type="checkbox" checked={request.starting.gear.includes(v)} onChange={e=>update('starting','gear',e.target.checked?[...request.starting.gear,v]:request.starting.gear.filter((x:string)=>x!==v))}/>{t}</label>)}</div><label>How much can you control?<select aria-label="How much can you control?" value={request.starting.control} onChange={e=>update('starting','control',e.target.value)}><option value="controlled">I can arrange and repeat the scene</option><option value="uncontrolled">I mainly observe what happens</option><option value="one_take">The moment cannot be repeated</option><option value="real_time">It happens live</option></select></label><div className="check-options">{[['outdoor','I have safe outdoor access'],['local_backup','I can make a separate local backup'],...(c.production_requirements.includes('screen_recorder')?[['screen_recorder','My device can record its screen']]:[]),...(c.production_requirements.includes('drone')?[['authorised','Current flight and location permissions have been checked']]:[]),...(c.production_requirements.includes('specialist_capture')?[['specialist','I have the required specialist equipment and supervision']]:[]),...(c.production_requirements.includes('spatial_capture_or_pipeline')?[['spatial','I can test the required spatial pipeline']]:[])].map(([v,t])=><label key={v}><input type="checkbox" checked={request.starting[v]} onChange={e=>update('starting',v,e.target.checked)}/>{t}</label>)}</div><p className="small">Leave an unsure item unchecked. Missing equipment gets a labelled rehearsal, not a claim of completed capture.</p></>
 :step===2?<><h1>How much time fits?</h1><label>Hours each week<select aria-label="Hours each week" value={request.starting.hours} onChange={e=>update('starting','hours',Number(e.target.value))}>{[.5,1,2,4,6,8,10,15,20].map(v=><option key={v} value={v}>{v} hours</option>)}</select></label><label>Learning window<select aria-label="Learning window" value={request.starting.weeks} onChange={e=>update('starting','weeks',Number(e.target.value))}>{[1,2,4,6,8,12].map(v=><option key={v} value={v}>{v} weeks</option>)}</select></label><div className="time-budget"><strong>{Math.round(request.starting.hours*Math.min(request.starting.weeks,Math.max(1,request.outcome.deadline_days/7))*10)/10}h</strong><span>Planned time before your deadline, assuming you can use this weekly allowance within it. If the full route will not fit, we will show a small first try and what remains.</span></div></>
 :step===3?<><h1>Make learning easy to access.</h1><div className="scenario-form-grid"><label>Learning device<select aria-label="Learning device" value={request.starting.device} onChange={e=>update('starting','device',e.target.value)}><option value="android">Android phone / tablet</option><option value="ios">iPhone / iPad</option><option value="desktop">Computer</option></select></label><label>Connection<select aria-label="Connection" value={request.starting.bandwidth} onChange={e=>update('starting','bandwidth',e.target.value)}><option value="low">Limited data / slow connection</option><option value="standard">Usually connected</option><option value="stable">Stable enough for a tested live stream</option><option value="offline">Mostly offline</option></select></label></div><p>English lessons, with original reading alternatives. Videos play only when you choose.</p><div className="check-options">{[['captions','Prefer captions and text'],['descriptions','Need visual descriptions'],['keyboard','Use keyboard controls'],['reduced_motion','Reduce motion'],['large_text','Larger text']].map(([v,t])=><label key={v}><input type="checkbox" checked={request.starting.accessibility.includes(v)} onChange={e=>update('starting','accessibility',e.target.checked?[...request.starting.accessibility,v]:request.starting.accessibility.filter((x:string)=>x!==v))}/>{t}</label>)}</div></>
 :step===4?<><h1>What helps you learn?</h1><Options label="Preferred way to learn" value={request.preferences.modality} onChange={v=>update('preferences','modality',v)} values={[["watch","Watch"],["read","Read"],["do","Try it"],["discuss","Discuss"]]}/><div className="scenario-form-grid"><label>Structure<select aria-label="Structure" value={request.preferences.structure} onChange={e=>update('preferences','structure',e.target.value)}><option value="guided">Guide me step by step</option><option value="open">Let me choose practice order</option></select></label><label>Feedback<select aria-label="Feedback" value={request.preferences.feedback} onChange={e=>update('preferences','feedback',e.target.value)}><option value="self">Self-check</option><option value="ai">AI first pass</option><option value="peer">Someone I choose</option><option value="mentor">A mentor, when available</option></select></label><label>Practice pace<select aria-label="Practice pace" value={request.preferences.pace} onChange={e=>update('preferences','pace',e.target.value)}><option value="gentle">Short, gentle attempts</option><option value="steady">One attempt, then revise</option><option value="stretch">Compare harder versions</option></select></label><label>Main motivation<select aria-label="Main motivation" value={request.preferences.motivation} onChange={e=>update('preferences','motivation',e.target.value)}><option value="finish_task">Finish this task</option><option value="build_confidence">Build confidence</option><option value="improve_craft">Improve my craft</option><option value="career">Prepare for professional work</option></select></label></div><details className="lesson-details"><summary>Practice order and scores</summary><label>Start with<select aria-label="Start with" value={request.preferences.sequence} onChange={e=>update('preferences','sequence',e.target.value)}><option value="plan_first">A short plan</option><option value="shoot_first">A safe tryout</option></select></label><label>Assessment comfort<select aria-label="Assessment comfort" value={request.preferences.assessment_comfort} onChange={e=>update('preferences','assessment_comfort',e.target.value)}><option value="private">Private reflection first</option><option value="scored">Show the score and criteria</option></select></label></details><p className="small">Human reviewers are not assigned in this pilot. Safety and consent come before a tryout.</p></>
 :step===5?<><h1>Which skills have you tried?</h1><p className="question-brief">Rate only what you have practised. “Not sure” stays unknown; it is not a failing score.</p><div className="skill-inputs">{c.skill_clusters.map((k:string)=><label key={k}>{clusterNames[k]}<select value={request.starting.skills[k]??'unknown'} onChange={e=>update('starting','skills',{...request.starting.skills,[k]:e.target.value==='unknown'?null:Number(e.target.value)})}><option value="unknown">Not sure / not assessed</option><option value={0}>I have not tried it</option><option value={1}>I need step-by-step help</option><option value={2}>I can do a simple task</option><option value={3}>I can repeat it reliably</option><option value={4}>I can handle difficult conditions</option></select></label>)}</div></>
 :<><h1>{question.title}</h1><p className="question-brief">{question.brief}</p><DiagnosticControl index={activity} value={pending} onChange={setPending}/><p className="small">This is one small signal for {activity===8?'production planning':activity===4?'sound':activity===5?'editing':activity===7?'delivery':'camera and image skills'}, not a qualification.</p></>}
 </div>{error&&<p className="notice" role="alert">{error}</p>}<div className="diagnostic-actions">{step<6?<Button variant="outline" disabled={!step} onClick={()=>setStep(step-1)}>Back</Button>:<Button variant="outline" onClick={()=>{setRequest((r:any)=>({...r,checks:[]}));setPending(null);setStep(0)}}>Restart setup</Button>}{step>0&&<Button variant="ghost" onClick={()=>next(true)}>{step>=6?'I’m not sure / skip':'Use defaults / skip'}</Button>}<Button disabled={step===0&&request.outcome.goal.trim().length<5} onClick={()=>next()}>{step===8?'See my route':step>=6?'Submit & next':'Continue'}</Button></div>{step>=6&&<p className="small diagnostic-note">The meter changes only after submitting. Submitted checks cannot be reopened during this attempt. You can edit your setup or retake checks from the result.</p>}</section>;
}
