import type {LearningResource} from './learning-resources';
import {archetypes} from './scenario-engine';
const all=['android','ios','desktop'];
function guide(id:string,title:string,creator:string,topic:string,source:string,focus:string,archetypes:string[],devices=all,verification='Source page checked; verify current device/version details'):LearningResource{return {id,title,creator,topic,type:'Reading guide',host:new URL(source).hostname,source,focus,level:'All levels',levels:['beginner','intermediate','advanced'],devices,archetypes,format:'read',bandwidth:'low',verification,checkedAt:'2026-10-07'};}
export const scenarioResources:LearningResource[]=[
 guide('android-screen','Record your Android screen','Google Android Help','Screen capture','https://support.google.com/android/answer/9075928?hl=en','Check the device and Android-version steps before recording dummy data.',['A03','A11','A12'],['android']),
 guide('iphone-screen','Take a screen recording on iPhone','Apple Support','Screen capture','https://support.apple.com/guide/iphone/take-a-screen-recording-iph52f6e1987/ios','Find the built-in recording controls; confirm which sound sources are actually captured.',['A03','A11','A12'],['ios']),
 guide('phone-video','Record video with your iPhone camera','Apple Support','Camera','https://support.apple.com/guide/iphone/record-a-video-iph61f49e4bb/ios','Use the capture modes supported by your own iPhone; optional features vary by model.',['A01','A05','A08','A09','A10','A11'],['ios']),
 guide('obs-start','OBS Studio quick start','OBS Project','Live and streaming','https://obsproject.com/kb/quick-start-guide','Set up sources, check audio and run a private recording or streaming test.',['A11','A12','A13'],['desktop']),
 guide('obs-audio','OBS audio mixer guide','OBS Project','Sound','https://obsproject.com/kb/audio-mixer-guide','Trace each source through the mixer and inspect the actual receiver or saved recording.',['A12','A13'],['desktop']),
 guide('witness-interview','Filming preliminary field interviews','WITNESS','Interviewing','https://library.witness.org/product/video-as-evidence-filming-preliminary-field-interviews-mini-guides/','Start with recording choices and informed consent. This specialist guide is not India-specific legal advice.',['A06','A14','A20']),
 guide('witness-ethics','Video as evidence: ethical guidelines','WITNESS','Ethics and consent','https://library.witness.org/product/video-as-evidence-ethical-guidelines/','Consider people, sources and the consequences of recording or sharing. Use safe simulations for this pilot.',archetypes.map(a=>a.id),all,'Source landing page checked; verify the linked guide and your local requirements'),
 guide('witness-preserve','Transferring video and its context','WITNESS','Archiving','https://archiving.witness.org/archive-guide/transfer/introduction/','Keep original files and their documentation connected; verify a transfer before relying on it.',['A01','A02','A14','A15','A16']),
 guide('wai-media','Making audio and video accessible','W3C Web Accessibility Initiative','Accessibility','https://www.w3.org/WAI/media/av/','Plan captions, descriptions and transcripts around the information your audience needs.',archetypes.map(a=>a.id)),
 guide('kinovea-guide','Kinovea reference manual','Kinovea','Observation and measurement','https://www.kinovea.org/help/en/','Read the capture, playback and measurement documentation; do not infer calibrated measurements from an arbitrary clip.',['A04','A15'],['desktop'],'Official manual checked; the linked manual is version 0.9.5 — verify against your installed release'),
 guide('stopmotion-guide','Stop Motion Studio help','Cateater / Stop Motion Studio','Animation and time','https://www.stopmotionstudio.com/help/stopmotion/en/','Use the capture and playback guidance for a short stable-frame experiment.',['A19'],all,'Official help index checked; controls and paid features differ by device'),
 guide('insta360-reframe','Insta360 app view adjustment','Insta360','Aerial and spatial capture','https://onlinemanual.insta360.com/app/en-us/operation-tutorial/edit-function/perspective-component','Distinguish a flat reframe from the original 360 viewing experience.',['A18'],['android','ios']),
 guide('insta360-manual','Insta360 X4 user manual','Insta360','Aerial and spatial capture','https://res.insta360.com/static/82bb5d1ffeb222da8c7755a153622469/X4_UserManual_EN.pdf','Check the camera-specific capture and delivery requirements; a different model needs its own manual.',['A18'],all,'Official PDF located; verify your exact model and firmware'),
 guide('aai-digitalsky','DigitalSky airspace portal','Airports Authority of India / DigitalSky','Aerial and spatial capture','https://digitalsky.aai.aero/','Check current official requirements for the actual location, date and operation. A course score is not authorisation.',['A17','A18'],all,'Verify before each real flight: the interactive map and current DGCA requirements cannot be certified by this lesson'),
];
const clusterByTopic:Record<string,string>={Story:'story',Camera:'camera',Lighting:'lighting',Sound:'sound',Editing:'editing',Colour:'colour',Delivery:'delivery'};
export function tagExistingResource(r:LearningResource):LearningResource{const desktop=/resolve|premiere|final cut|fusion|fairlight/i.test(r.title+' '+r.id),video=!!r.youtubeId||!!r.vimeoId;return {...r,devices:desktop?['desktop']:all,archetypes:archetypes.filter(a=>a.skills.includes(clusterByTopic[r.topic])||a.reuse_candidates.some((k:string)=>k.includes(r.id))).map(a=>a.id),levels:/advanced/i.test(r.level)?['advanced']:/intermediate/i.test(r.level)?['intermediate','advanced']:/beginner/i.test(r.level)?['beginner','intermediate']:['beginner','intermediate','advanced'],format:video?'watch':'read',bandwidth:video?'video':'low',verification:'Existing credited source; check availability and current software version before relying on it'};}
