'use client';
import React,{createContext,useContext,useState,useEffect,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Aperture,BookOpen,Compass,Users,FolderOpen,Sparkles,Menu,X,Check,Upload,Play,Clock,Film,Info} from 'lucide-react';
import {freshState,paths,weeks,resources} from './catalog';
import {isFreePath} from './learning-rules';
export const Learning=createContext<any>(null);
export const useLearning=()=>useContext(Learning);
export function Provider({children,route}:{children:React.ReactNode,route:string}){
 const [data,setData]=useState<any>({state:freshState(),revision:0,user:null,usage:[]});const [loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);const latest=useRef(data);latest.current=data;
 async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});const d:any=await r.json();if(r.status===401){setData({state:freshState(),revision:0,user:null,usage:[]});setError('')}else if(!r.ok)throw Error(d.error);else{setData(d);setError('')}}catch(e:any){setError(e.message||'Your learning is temporarily unavailable.')}finally{setLoaded(true)}}
 useEffect(()=>{void refresh()},[]);
 async function mutate(action:string,body:any={}){if(lock.current)return null;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body,revision:latest.current.revision})});const d:any=await r.json();if(!r.ok){if(r.status===409)await refresh();throw Error(d.error||'Could not save your change.')}setData((prev:any)=>({...prev,...d}));toast.success('Saved to your learning space');return d.state}catch(e:any){setError(e.message||'Could not save. Your input is still here.');toast.error(e.message||'Could not save.');return null}finally{lock.current=false;setBusy(false)}}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'read_framepath_progress',title:'Read Framepath progress',description:'Read the signed-in learner’s current completion and selected mentor. Does not change data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||Object.keys(input).length)throw Error('No arguments expected.');return {signedIn:!!latest.current.user,completedLessons:Object.keys(latest.current.state.progress),craftStatus:latest.current.state.craft?.status||null,mentorId:latest.current.state.craft?.mentorId||null}}},{signal:controller.signal})).catch(()=>{});Promise.resolve(ctx.registerTool({name:'open_framepath_lesson',title:'Open a lesson',description:'Navigate to a published Explore lesson. Does not mark it complete or purchase access.',inputSchema:{type:'object',properties:{pathId:{type:'string',enum:paths.map(p=>p.id)},lessonIndex:{type:'integer',minimum:0}},required:['pathId','lessonIndex'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input:any){const p=paths.find(p=>p.id===input?.pathId);if(!p||!Number.isInteger(input.lessonIndex)||!p.lessons[input.lessonIndex]||Object.keys(input).some(k=>!['pathId','lessonIndex'].includes(k)))throw Error('Choose a valid path and lesson.');const path='/explore/'+p.id+'/'+input.lessonIndex;window.location.assign(path);return {opened:path}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 return <Learning.Provider value={{s:data.state,user:data.user,usage:data.usage,loaded,busy,error,refresh,mutate,setUsage:(usage:any)=>setData((d:any)=>({...d,usage})),route}}>{children}<Toaster theme="dark" position="bottom-right" richColors/></Learning.Provider>
}
export function Go({href,children,outline=false,className=''}:any){return <Button asChild variant={outline?'outline':'default'} className={className}><a href={href}>{children}</a></Button>}
export function Action({children,onClick,disabled=false,outline=false,type='button'}:any){const {busy}=useLearning();return <Button type={type} disabled={busy||disabled} variant={outline?'outline':'default'} onClick={onClick}>{busy?'Saving…':children}</Button>}
export function CheckField({checked,onChange,children}:any){const id=React.useId();return <div className="check-row"><Checkbox id={id} checked={checked} onCheckedChange={v=>onChange(v===true)}/><label htmlFor={id}>{children}</label></div>}
export function Shell({children,home=false}:any){const {user,route,error,refresh}=useLearning();const [menu,setMenu]=useState(false);return <><a className="skip-link" href="#main">Skip to content</a><header className="topbar"><a className="brand" href="/" aria-label="Framepath home"><Aperture size={27}/><span>framepath<span className="brand-dot">.</span></span></a><nav className={'main-nav '+(menu?'open':'')} aria-label="Main navigation">{[['/workspace','My journey'],['/explore','Projects'],['/portfolio','My work']].map(([href,name])=><a key={href} href={href} aria-current={route.startsWith(href)?'page':undefined}>{name}</a>)}<a href={user?"/settings":"/auth/google?return_to=%2Fworkspace"} className="account-link">{user?"My account":"Sign in"}</a></nav><button className="mobile-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{!home&&<div className="pilot-strip"><span className="pill">PILOT</span><span>Personal pilot · simulated checkout & mentors</span><a href="/mentor-room">Open mentor demo</a></div>}{error&&<div className="global-error" role="alert"><Info size={18}/><span>{error}</span><button onClick={()=>refresh()}>Reload saved work</button></div>}<main id="main" className={home?'home':'page'}>{children}</main><footer className="footer"><span>FRAMEPATH / LEARN BY MAKING</span><div><a href="/help">How the pilot works</a><a href="/settings">Privacy & data</a><a href="/mentor-room">Mentor demo</a></div></footer></>}
export function PageHead({eyebrow,title,children,action}:any){return <div className="page-head"><div><div className="kicker">{eyebrow}</div><h1>{title}</h1>{children&&<p className="lede">{children}</p>}</div>{action}</div>}
export function Panel({children,className=''}:any){return <section className={'panel '+className}>{children}</section>}
export function Badge({children,tone=''}:any){return <span className={'badge '+tone}>{children}</span>}
export function Gate({children}:any){const {loaded,user,route}=useLearning();if(!loaded)return <Panel><p role="status">Opening your learning space…</p></Panel>;if(!user)return <Panel className="empty"><BookOpen size={32}/><h2>Keep your next frame.</h2><p>Sign in with ChatGPT to save progress, upload work and try the pilot. Your learning space is private to your account.</p><Go href={'/auth/google?return_to='+encodeURIComponent(typeof window==='undefined'?route:window.location.pathname+window.location.search)}>Sign in with ChatGPT</Go></Panel>;return children}
export function DateText({value}:any){return <>{new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</>}
export function isExplore(s:any){return !!s.membership&&new Date(s.membership.expiresAt).getTime()>Date.now()}
export function isCraft(s:any){return ['paid','active'].includes(s.craft?.status)}
export function Resource({index}:any){const r=resources[index];return <section className="video-resource"><div className="video-stage"><iframe src={'https://www.youtube-nocookie.com/embed/'+r.videoId+'?rel=0'} title={r.title+' — '+r.by} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="video-caption"><div><strong>{r.title}</strong><span>{r.by}</span></div><a className="text-link" href={'https://www.youtube.com/watch?v='+r.videoId} target="_blank" rel="noopener noreferrer">Watch on YouTube</a></div></section>}
export function PathProgress({path}:any){const {s}=useLearning();const count=path.lessons.filter((_:any,i:number)=>s.progress[path.id+'-'+i]).length;return <div className="path-progress"><div><span>{count} of {path.lessons.length} sessions</span><span>{Math.round(count/path.lessons.length*100)}%</span></div><Progress value={count/path.lessons.length*100}/></div>}
export function PathCard({path}:any){const {s}=useLearning();const next=path.lessons.findIndex((_:any,i:number)=>!s.progress[path.id+'-'+i]);return <article className="path-card"><div className={'path-art art-'+path.id}><div className="frame-guides"/><span className="art-number">{path.number}</span><span className="art-caption">{path.outcome}</span></div><div className="path-card-body"><div className="row between"><span className="eyebrow">{path.duration}</span>{isFreePath(path.id)&&<Badge tone="green">Free practice</Badge>}</div><h2>{path.title}</h2><p>{path.description}</p><PathProgress path={path}/><Go href={'/explore/'+path.id+'/'+Math.max(next,0)} outline>{next<0?'Revisit path':'Open path'}</Go></div></article>}
export function UploadField({onUpload,value,lessonKey}:any){const [busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef<HTMLInputElement>(null);async function upload(file?:File){if(!file)return;setError('');if(file.size>(file.type.startsWith('image/')?5:25)*1024*1024){setError('Use an image under 5 MB or a video under 25 MB.');return}setBusy(true);try{const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':file.type,'X-File-Size':String(file.size),'X-File-Name':encodeURIComponent(file.name),...(lessonKey?{'X-Lesson-Key':lessonKey}:{})},body:file});const d:any=await r.json();if(!r.ok)throw Error(d.error);onUpload(d);toast.success('Upload saved')}catch(e:any){setError(e.message||'Upload failed. Please choose the file again.')}finally{setBusy(false)}}return <div className="upload-box"><input aria-label="Upload assignment file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" ref={ref} disabled={busy} onChange={e=>upload(e.target.files?.[0])}/><Upload size={22}/><strong>{busy?'Uploading…':value?.name||'Add a still or a short video'}</strong><p>Images up to 5 MB · Videos up to 25 MB · 100 MB per learner</p>{error&&<p className="field-error" role="alert">{error}</p>}</div>}
export function FeedbackText({text}:any){return <div className="feedback-text">{text.split('\n').map((line:string,i:number)=>line?<p key={i}>{line.replace(/^#{1,4}\s*/,'').replace(/\*\*/g,'')}</p>:<br key={i}/>)}</div>}
export function AIBox({scope='explore',context='',uploadId='',onPlan}:any){const {s,user,usage,setUsage}=useLearning();const [kind,setKind]=useState(onPlan?'plan':'question'),[prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);const entitled=scope==='explore'?isExplore(s):isCraft(s);const count=(usage||[]).find((u:any)=>u.scope===scope&&u.kind===kind)?.used||0,limit=kind==='question'?120:kind==='plan'?12:scope==='craft'?24:12;
 async function ask(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setAnswer('');try{const full=(context?context+'\n':'')+prompt;const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,scope,prompt:full.slice(0,4000),uploadId:kind==='feedback'?uploadId:undefined,requestId:crypto.randomUUID()})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setAnswer(d.answer);setUsage(d.usage)}catch(e:any){setError(e.message||'AI could not respond. Please try again.')}finally{setBusy(false);lock.current=false}}
return <Panel className="ai-panel"><div className="row"><Sparkles size={20}/><h2>Your AI learning assistant</h2></div><p>Questions, schedules and first-pass feedback. You make the creative decisions.</p>{!user||!entitled?<div className="notice">Activate {scope==='explore'?'Explore annual access':'Craft'} to use AI. Free lesson resources remain available.</div>:<><label>Type of help<select value={kind} onChange={e=>{setKind(e.target.value);setAnswer('');setError('')}}><option value="question">Quick question</option><option value="plan">Adapt my pathway</option><option value="feedback">First-pass feedback</option></select></label><label>Your question or brief<textarea value={prompt} maxLength={Math.max(100,4000-context.length-1)} rows={4} onChange={e=>setPrompt(e.target.value)} placeholder="For example: I have 30 minutes each evening and a phone. How should I practise this week?"/></label><div className="row between"><span className="small">{Math.max(0,limit-count)} of {limit} {kind==='question'?'questions':kind==='plan'?'adaptations':'checks'} left · shared across {scope==='explore'?'all Explore paths this year':'this Craft course'}</span><Button disabled={busy||prompt.trim().length<5||count>=limit} onClick={ask}>{busy?'Thinking…':'Ask AI'}</Button></div><p className="small">Your text{kind==='feedback'&&uploadId?' and selected image':''} is sent to OpenAI. Video links and video files are not analysed. Failed requests return your allowance.</p>{error&&<div className="notice error" role="alert">{error}</div>}{answer&&<div className="ai-answer"><Badge>AI guidance</Badge><FeedbackText text={answer}/>{onPlan&&kind==='plan'&&<Button onClick={()=>onPlan(answer)}>Save as draft pathway</Button>}</div>}</>}</Panel>}
export function labelForKey(key:string){if(key.startsWith('craft-'))return 'Craft · '+(weeks[Number(key.split('-')[1])-1]?.title||'Module');for(const p of paths){if(key.startsWith(p.id+'-'))return p.title+' · '+(p.lessons[Number(key.slice(p.id.length+1))]?.title||'')}return key}
export function Attachment({sub,token}:any){return <div className="attachment-links">{sub.uploadId&&<a className="text-link" href={'/api/file/'+sub.uploadId+(token?'?portfolio='+token:'')} target="_blank" rel="noreferrer">View uploaded work</a>}{sub.url&&<a className="text-link" href={sub.url} target="_blank" rel="noreferrer">Watch video / open project</a>}</div>}
export function SubmissionCard({sub}:any){return <article className="submission"><div className="row between"><strong>{labelForKey(sub.key)}</strong><Badge tone={sub.status==='approved'?'green':''}>{sub.status.replaceAll('_',' ')}</Badge></div><p className="small"><DateText value={sub.createdAt}/></p><p className="prewrap">{sub.notes}</p><Attachment sub={sub}/>{sub.practiceScore!==undefined&&<p className="small">Practice self-check · {sub.practiceScore}/100</p>}{sub.feedback&&<div className="review-note"><strong>Mentor demo review · {sub.total}/100</strong><p>{sub.feedback}</p></div>}</article>}

