'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
export const learningPhotos={mug:'/learning/mug-deep-focus.webp',focus:'/learning/mug-shallow-focus.webp',work:'/learning/toy-repair.webp'};
type Mode='purpose'|'format'|'notice'|'sequence'|'exposure'|'motion'|'focus'|'framing'|'light'|'colour'|'sound'|'stability'|'pan'|'files'|'titles';
const modes:Mode[][]=[['purpose','format','notice','framing','sequence'],['exposure','exposure','motion','focus','exposure'],['framing','framing','focus','format','sequence'],['light','light','colour','light','light'],['sound','sound','sound','sound','sound'],['stability','pan','sequence','sequence','sequence'],['files','sequence','sequence','titles','format'],['sequence','purpose','sound','sequence','sequence']];
export const simpleTitles:Record<string,string>={'Find your why':'Video purpose','Know your viewer':'Your viewer','Learn to see':'Observation','Choose your shots':'Shot selection','Prove it':'Weekly project','Auto-mode truth and set-up':'Camera setup','Motion feel':'Motion','Colour and focus':'Colour and focus','Frame as a decision':'Shot sizes','Place the subject':'Subject placement','Depth and lines':'Depth and focus','Formats and safe zones':'Video formats','See the light':'Light direction','Window light and reflectors':'Window light','Mixed light and colour temperature':'Mixed light','Listen first':'Sound layers','Mics and placement':'Microphone position','Levels and monitoring':'Recording levels','Room tone, noise and wind':'Background noise','Steady the camera':'Camera stability','Pans and tilts':'Camera movement','Organise and ingest':'Organise your clips','Pace and sound':'Pacing and sound','Look and titles':'Colour and titles','Person, want, obstacle':'Story ideas','Hooks, endings and shoot':'Opening and ending','Capstone and review':'Your final film'};
export function lessonTitle(title:string){return simpleTitles[title]||title}
export function VisualLab({lessonKey,modeOverride}:{lessonKey:string;modeOverride?:string}){
 const week=Number(lessonKey.match(/w(\d+)/)?.[1]||1),session=Number(lessonKey.split('-').at(-1)||0),mode=(modeOverride||modes[week-1]?.[session]||'framing') as Mode;
 const [choice,setChoice]=useState(0),[amount,setAmount]=useState(mode==='sound'?-12:0),[playing,setPlaying]=useState(false),[order,setOrder]=useState([0,1,2]),[shown,setShown]=useState(0),[audioError,setAudioError]=useState('');
 const audio=useRef<AudioContext|null>(null);useEffect(()=>()=>{audio.current?.close().catch(()=>{})},[]);
 useEffect(()=>{if(!playing||mode!=='sequence')return;setShown(0);const timer=setInterval(()=>setShown(v=>{if(v>=2){setPlaying(false);return 2}return v+1}),1800);return()=>clearInterval(timer)},[playing,mode]);
 const picks=(labels:string[])=> <div className="visual-options">{labels.map((v,i)=><Button key={v} variant={choice===i?'default':'outline'} aria-pressed={choice===i} onClick={()=>{setChoice(i);setPlaying(false)}}>{v}</Button>)}</div>;
 const range=(label:string,min:number,max:number,step=1)=><label className="visual-slider">{label}<input aria-label={label} type="range" min={min} max={max} step={step} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>;
 const crop=(n:number)=>({transform:`scale(${[1,1.55,2.7][n]})`,transformOrigin:n===2?'48% 63%':'50% 55%'});
 let image=learningPhotos.work,style:React.CSSProperties={},caption='',control:React.ReactNode=null,overlay:React.ReactNode=null;
 if(['purpose','notice','framing'].includes(mode)){
  style=crop(choice);control=picks(mode==='purpose'?['The place','The process','The detail']:['Wide','Medium','Close']);
  caption=mode==='purpose'?['The wider view tells us where the work happens. A film about a welcoming workshop needs this context.','Hands and tools make the process the subject. A film about care can spend more time here.','The toy and its small parts reveal precision. A film about craftsmanship can build around this detail.'][choice]:['A wide frame gives the viewer a place and context.','A closer frame makes the action easier to read.','A detail directs attention and leaves out the setting.'][choice];
 }else if(mode==='exposure'){
  image=learningPhotos.mug;style={filter:`brightness(${Math.pow(2,amount/2)})`};control=range('Brightness',-2,2,.1);caption=amount>.7?'Bright areas start to lose separation. Watch the mug rim and the window.':amount<-.7?'The table and the mug’s shaded side become harder to read.':'Move the slider and follow one bright area and one dark area.';
 }else if(mode==='focus'){
  image=choice===0?learningPhotos.mug:learningPhotos.focus;control=picks(['Deep focus','Shallow focus']);caption=choice===0?'The café and mug stay readable. More of the scene competes for attention.':'The mug stays sharp while the background softens. Attention moves toward the mug.';
 }else if(mode==='format'){
  control=picks(['16:9','9:16','1:1']);caption=['A wide frame leaves room for the setting and action.','A tall frame removes side information. Check that the hands and toy still tell the story.','A square frame balances the subject and a smaller amount of context.'][choice];
 }else if(mode==='light'){
  image=learningPhotos.mug;control=picks(['Original','More contrast','Lift the shadows']);style={filter:choice===1?'contrast(1.45) brightness(.88)':choice===2?'contrast(.72) brightness(1.18)':'none'};caption=['Follow the window light from the left to the mug’s shaded side.','Stronger contrast makes the bright and shaded sides feel more distinct.','Lifting the shadows reveals more detail, but reduces contrast. A reflector is one way to change that balance during filming.'][choice];
 }else if(mode==='colour'){
  image=learningPhotos.mug;control=picks(['Neutral','Warm','Cool']);style={filter:choice===1?'sepia(.35) saturate(1.2)':choice===2?'sepia(.22) hue-rotate(165deg) saturate(1.25)':'none'};caption=['Use the neutral mug as a reference.','A warm cast changes the mug as well as the room.','A cool cast changes the feeling. Judge neutral objects and consistency, not only mood.'][choice];
 }else if(mode==='motion'||mode==='stability'){
  image=learningPhotos.work;control=<>{picks(mode==='stability'?['Supported','Unsteady']:['Crisp movement','Blurred movement'])}<Button variant="outline" onClick={()=>setPlaying(!playing)}>{playing?'Pause movement':'Play movement'}</Button></>;style={transform:'scale(1.15)',filter:mode==='motion'&&choice===1&&playing?'blur(2px)':'none'};caption=mode==='stability'?'Compare a steady view with simulated camera shake. The subject does not need the camera to move constantly.':'Compare the impression of crisp and blurred movement. In a real shot, shutter time affects motion blur; frame rate is a separate choice.';
 }else if(mode==='pan'){
  style={transform:'scale(1.65)',transformOrigin:`${50+amount}% 50%`};control=range('Move the frame',-35,35);caption='Move from the tools to the hands. Stop when the frame reveals the information you need.';
 }else if(mode==='titles'){
  control=picks(['Low contrast','Clear contrast']);overlay=<span className={'demo-title '+(choice?'readable':'')}>Repaired by hand</span>;caption=choice?'A backing and breathing room make the words easier to read.':'The words compete with the image. Toggle the treatment and compare at phone size.';
 }else if(mode==='sequence'){
  const n=order[shown];style=crop(n);control=<><div className="photo-timeline">{order.map((v,i)=><div key={v}><button className="timeline-photo" aria-label={'Preview '+['place','action','detail'][v]} onClick={()=>{setShown(i);setPlaying(false)}}><img src={image} alt="" style={crop(v)}/><span>{i+1} · {['Place','Action','Detail'][v]}</span></button><Button variant="ghost" disabled={i===0} aria-label={'Move '+['place','action','detail'][v]+' earlier'} onClick={()=>{setPlaying(false);setOrder(o=>{const a=[...o];[a[i-1],a[i]]=[a[i],a[i-1]];return a});setShown(0)}}>Move earlier</Button></div>)}</div><Button variant="outline" onClick={()=>setPlaying(!playing)}>{playing?'Pause sequence':'Play sequence'}</Button></>;caption=order[0]===0?'The place comes first. The closer shots then add information.':order[0]===2?'A detail comes first. The wider view can answer where this is happening.':'The action comes first. Add the setting before the viewer becomes disoriented.';
 }else if(mode==='files'){
  control=picks(['Unsorted','Organised']);overlay=<div className="file-demo">{(choice?['Footage / workshop-wide-01','Audio / workshop-room-tone','Exports / repair-film-v1']:['IMG_0187','final_FINAL_2','Untitled 03']).map(v=><span key={v}>{v}</span>)}</div>;caption=choice?'Names and folders tell you what a file contains before opening it. Keep a separate backup of source media.':'A folder full of vague names adds guesswork. Toggle to see the same project organised.';
 }else{
  image=learningPhotos.mug;const level=Math.max(.1,(amount+30)/30);control=<>{range('Recording level',-30,0)}<Button variant="outline" disabled={playing} onClick={async()=>{setAudioError('');try{await audio.current?.close();const ctx=new AudioContext();audio.current=ctx;await ctx.resume();const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.frequency.value=440;gain.gain.value=Math.min(.07,level*.07);oscillator.connect(gain).connect(ctx.destination);oscillator.start();setPlaying(true);oscillator.stop(ctx.currentTime+1.2);oscillator.onended=()=>{setPlaying(false);ctx.close().catch(()=>{})}}catch{setAudioError('Audio is unavailable in this browser. You can still compare the meter.');setPlaying(false)}}}>{playing?'Playing tone…':'Play test tone'}</Button>{audioError&&<p role="alert">{audioError}</p>}</>;
  overlay=<div className="audio-visual"><span>Simulated peak level</span><div className="photo-meter">{Array.from({length:20},(_,i)=><i key={i} className={i<(amount+30)/30*20?(i>17?'hot':'lit'):''}/>)}</div><strong>{amount} dBFS</strong></div>;caption=amount>=-3?'Near the digital ceiling, louder moments can clip. Leave headroom.':'Compare the meter and the test tone. Level is only one part of useful sound: placement and background noise also matter.';
 }
 const simulated=['exposure','colour','light','motion','stability','sound','focus'].includes(mode);
 return <div className={'photo-lab mode-'+mode}>
  <div className={'photo-view '+(mode==='format'?'format-'+choice:'')+(playing&&(mode==='stability'||mode==='motion')?' moving-'+(mode==='stability'?choice?'shake':'steady':'pan'):'')}><img src={image} alt={image.includes('toy')?'Hands repairing a wooden toy beside a workshop window':'A ceramic mug on a table in a café'} style={style} width={1536} height={1024}/>{overlay}</div>
  <div className="photo-controls">{control}</div><p className="visual-caption" aria-live="polite">{caption}</p>
  <small className="visual-source">{mode==='focus'?'Illustrative depth-of-field comparison. Aperture, distance and focal length all affect real depth of field.':simulated?'Illustrative simulation. Compare the same idea with your camera or microphone.':'Image crops demonstrate composition; they do not simulate changes in camera position.'} AI-generated teaching images.</small>
 </div>
}
