'use client';
import React from 'react';
import {Button} from '@/components/ui/button';
export const batchFourDefaults={'access-bridge':{mode:'both',viewed:[],caption:'',description:''},'steady-frame':{support:'handheld',seen:[]},'comparison-log':{pause:5,size:24,note:''}};
function Slider({label,value,min,max,change,unit=''}:{label:string;value:number;min:number;max:number;change:(n:number)=>void;unit?:string}){return <label className="vl-range"><span>{label}<output>{value}{unit}</output></span><input type="range" aria-label={label} min={min} max={max} value={value} onChange={e=>change(Number(e.target.value))}/></label>}
export function BatchFourInteractive({kind,d,update,id}:{kind:string;d:any;update:(p:any)=>void;id:string}){
 if(kind==='access-bridge')return <><div className="vl-choice-row" role="group" aria-label="Preview access mode">{[['both','Picture and sound'],['muted','Sound off'],['hidden','Picture off']].map(([mode,label])=><Button key={mode} variant={d.mode===mode?'default':'outline'} aria-pressed={d.mode===mode} onClick={()=>update({mode,viewed:[...new Set([...d.viewed,mode])]})}>{label}</Button>)}</div><svg viewBox="0 0 720 280" role="img" aria-label={d.mode==='hidden'?'The picture is hidden; use the description below.':'A labelled geometry demonstration: left edge moves to the centre line.'}><rect width="720" height="280" rx="12" fill="#14343b"/>{d.mode==='hidden'?<text x="360" y="150" textAnchor="middle" fill="#d9e8df" fontSize="30">Picture hidden</text>:<><rect x="180" y="45" width="360" height="185" fill="#8eaeb0"/><path d="M360 45V230" stroke="#13353b" strokeDasharray="6 7" strokeWidth="4"/><path d="M205 125H340M320 105L340 125L320 145" stroke="#172e37" strokeWidth="5" fill="none"/><text x="210" y="200" fill="#153039" fontSize="24">Left edge</text><text x="393" y="90" fill="#153039" fontSize="24">Centre</text></>}</svg><div className="vl-setup-card"><p><strong>Planned narration:</strong> {d.mode==='muted'?'Sound off — the caption carries this part.':(d.caption||'“Move this over here.”')} {d.mode!=='muted'&&'(Written preview; no recorded speech.)'}</p><p><strong>Caption:</strong> {d.caption||'Add the precise words below.'}</p>{d.mode==='hidden'&&<p><strong>Visual description:</strong> {d.description||'Describe the missing action below.'}</p>}</div><label>Caption for the step<textarea aria-label="Caption for the step" maxLength={180} rows={2} value={d.caption} onChange={e=>update({caption:e.target.value})} placeholder="Name the object, action and destination."/></label><label>Describe the visual action<textarea aria-label="Describe the visual action" maxLength={240} rows={2} value={d.description} onChange={e=>update({description:e.target.value})} placeholder="What changes, and how can the learner check it?"/></label></>;
 if(kind==='steady-frame'){const names={handheld:'Unsupported hold',elbows:'Supported elbows',stand:'Secure stand'},spread={handheld:22,elbows:8,stand:2}[d.support as 'handheld'];return <><svg viewBox="0 0 720 340" role="img" aria-label={`${names[d.support as keyof typeof names]}: conceptual movement outlines spread ${spread} units from the planned frame. No real footage is played.`}><rect width="720" height="340" rx="12" fill="#14343b"/><rect x="250" y="120" width="220" height="115" fill="#cadf9b"/><text x="360" y="183" textAnchor="middle" fill="#18343b" fontSize="28">Essential action</text>{[-1,-.4,.5,1].map((n,i)=><rect key={i} x={110+n*spread} y={55+(i%2?1:-1)*spread} width="500" height="235" rx="4" fill="none" stroke="#d7e4df" strokeWidth={i===3?3:1.5} opacity={i===3?1:.35}/>)}</svg><div className="vl-choice-row" role="group" aria-label="Camera support">{Object.entries(names).map(([support,label])=><Button key={support} aria-pressed={support===d.support} variant={support===d.support?'default':'outline'} onClick={()=>update({support,seen:[...new Set([...d.seen,support])]})}>{label}</Button>)}</div><p className="small">Still outlines make the comparison possible without motion. Real movement varies with technique, support, lens and the device.</p></>}
 if(kind==='comparison-log'){const changed=Number(d.pause!==5)+Number(d.size!==24);return <><svg viewBox="0 0 720 350" role="img" aria-label={`Version A: 5-second pause and size 24 caption. Version B: ${d.pause}-second pause and size ${d.size} caption. ${changed} settings differ.`}><rect width="720" height="350" rx="12" fill="#14343b"/>{[0,1].map(i=><g key={i}><text x={35+i*360} y="48" fill="#dce8e1" fontSize="30">Version {i?'B':'A'}</text><rect x={35+i*360} y="83" width="280" height="100" rx="8" fill="#10252c"/><text x={175+i*360} y="142" textAnchor="middle" fontSize={i?d.size:24} fill="#fff">Fold to the centre.</text><rect x={35+i*360} y="230" width={(i?d.pause:5)*13} height="28" fill="#cadf9b"/><text x={35+i*360} y="303" fill="#dce8e1" fontSize="24">Pause: {i?d.pause:5} seconds</text></g>)}</svg><Slider label="Version B pause" min={2} max={20} value={d.pause} unit=" sec" change={pause=>update({pause})}/><Slider label="Version B caption size" min={18} max={32} value={d.size} change={size=>update({size})}/><p role="status">{changed===1?'One setting differs. The other stays constant.':changed===0?'Change one setting to compare it.':'Two settings differ. Reset either pause to 5 or size to 24 for a fairer comparison.'}</p><label>What does the preview show?<textarea aria-label="Comparison observation" maxLength={240} rows={2} value={d.note} onChange={e=>update({note:e.target.value})} placeholder="Describe the visible change, without claiming a learner result."/></label></>}
 return null;
}
