'use client';
import React from 'react';
import {Button} from '@/components/ui/button';
import {reorder} from '../foundation/interactive-contract';
export const batchTwoDefaults:Record<string,any>={
 'light-direction':{angle:0,positions:[]},'shadow-fill':{size:20,fill:0,controls:[]},'setup-notes':{angle:90,fill:false,note:''},
 delivery:{shape:'landscape',titleY:70,shapes:[]},'privacy-map':{hidden:[]},'teaching-plan':{objective:'',order:[0,2,1,3],pause:5}
};
function Slider({label,value,min,max,onChange,suffix=''}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void;suffix?:string}){return <label className="vl-range"><span>{label}<output>{value}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function LightPlan({angle,fill=false,id}:{angle:number;fill?:boolean;id:string}){const rad=angle*Math.PI/180,x=360+Math.sin(rad)*220,y=170-Math.cos(rad)*120,shadowX=360-Math.sin(rad)*120,shadowY=170+Math.cos(rad)*65;return <svg className="vl-light-plan" viewBox="0 0 720 340" role="img" aria-label={`Top view. Light at ${angle} degrees; shadow extends away. ${fill?'White fill card on the shadow side.':''}`}><title>Light direction from above</title><defs><marker id={id} markerWidth="10" markerHeight="10" refX="8" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#d5e9aa"/></marker></defs><rect width="720" height="340" fill="#122f36" rx="16"/><ellipse cx="360" cy="170" rx="220" ry="120" fill="none" stroke="#78979a" strokeDasharray="4 8"/><path d={`M360 170L${shadowX} ${shadowY}`} stroke={fill?'#75867e':'#081a20'} strokeWidth="50" strokeLinecap="round"/><circle cx="360" cy="170" r="32" fill="#a5c1c0"/><circle cx={x} cy={y} r="25" fill="#e0efaa"/><path d={`M${x} ${y}L${360+(x-360)*.25} ${170+(y-170)*.25}`} stroke="#d5e9aa" strokeWidth="4" markerEnd={'url(#'+id+')'}/>{fill&&<path d={`M${shadowX-30} ${shadowY+30}h70`} stroke="#faf6df" strokeWidth="10"/>}<rect x="333" y="307" width="54" height="22" rx="3" fill="none" stroke="#dce8e1" strokeWidth="3"/></svg>}
export function BatchTwoInteractive({kind,d,update,id}:{kind:string;d:any;update:(p:Record<string,any>)=>void;id:string}){
 if(kind==='light-direction')return <><LightPlan angle={d.angle} id={id+'-ray'}/><Slider label="Light position" value={d.angle} min={0} max={360} suffix="°" onChange={angle=>update({angle,positions:[...new Set([...d.positions,Math.round(angle/45)*45])].slice(-9)})}/><div className="vl-comparison-key"><p><strong>Bright circle:</strong> light source</p><p><strong>Centre:</strong> subject. Camera stays at the bottom; shadow extends away from the light</p></div></>;
 if(kind==='shadow-fill')return <><div className="vl-shadow-model" role="img" aria-label={`Conceptual shadow edge. Source size ${d.size} percent, fill ${d.fill} percent.`}><div className="vl-shadow-surface"/><div className="vl-shadow-region" style={{filter:`blur(${d.size/4}px)`,opacity:1-d.fill/150}}/><span className="vl-shadow-tag">Lit surface → shadow</span></div><Slider label="Relative source size" value={d.size} min={0} max={100} suffix="%" onChange={size=>update({size,controls:[...new Set([...d.controls,'size'])]})}/><Slider label="Reflected fill" value={d.fill} min={0} max={100} suffix="%" onChange={fill=>update({fill,controls:[...new Set([...d.controls,'fill'])]})}/></>;
 if(kind==='setup-notes')return <><LightPlan angle={d.angle} fill={d.fill} id={id+'-setup-ray'}/><Slider label="Source direction" value={d.angle} min={0} max={360} suffix="°" onChange={angle=>update({angle})}/><Button variant={d.fill?'default':'outline'} aria-pressed={d.fill} onClick={()=>update({fill:!d.fill})}>{d.fill?'Fill card included':'Add a fill card'}</Button><label>Time and position note<input aria-label="Time and position note" maxLength={180} value={d.note} placeholder="For example: 9 am, table beside east window" onChange={e=>update({note:e.target.value})}/></label><div className="vl-setup-card"><strong>Your setup card</strong><p>Source: {d.angle}° · {d.fill?'With fill':'No fill'}</p><p>{d.note||'Add your actual setup note above.'}</p></div></>;
 if(kind==='delivery')return <><div className="vl-delivery-stage"><div className={'vl-delivery-crop '+d.shape} role="img" aria-label={`${d.shape} crop. Title at ${d.titleY} percent height. Side context is removed in portrait.`}><div className="vl-source-context"><span>Side context</span><strong>Essential action</strong><span>Side context</span></div><div className="vl-safe-area"/><span className="vl-delivery-caption" style={{top:d.titleY+'%'}}>Your key words</span></div></div><fieldset><legend>Delivery shape</legend><div className="vl-choice-row">{['landscape','portrait'].map(shape=><Button key={shape} aria-pressed={d.shape===shape} variant={d.shape===shape?'default':'outline'} onClick={()=>update({shape,shapes:[...new Set([...d.shapes,shape])]})}>{shape==='landscape'?'Landscape · 16:9':'Portrait · 9:16'}</Button>)}</div></fieldset><Slider label="Title position" value={d.titleY} min={15} max={85} suffix="%" onChange={titleY=>update({titleY})}/><p className="small">Preview geometry only. Keep your important action and words inside the intended crop.</p></>;
 if(kind==='privacy-map'){const zones=[{id:'names',title:'Class list',text:'Learner identifiers'},{id:'messages',title:'Notifications',text:'Private messages'},{id:'permission',title:'Source material',text:'Permission unknown'}];return <><div className="vl-privacy-board"><div className="vl-safe-demo"><strong>YOUR DEMONSTRATION</strong><span>Owned objects · fictional examples</span></div>{zones.map(z=><button type="button" className={'vl-privacy-zone '+(d.hidden.includes(z.id)?'cleared':'')} key={z.id} aria-pressed={d.hidden.includes(z.id)} aria-label={(d.hidden.includes(z.id)?'Restore ':'Hide ')+z.title} onClick={()=>update({hidden:d.hidden.includes(z.id)?d.hidden.filter((v:string)=>v!==z.id):[...d.hidden,z.id]})}><strong>{d.hidden.includes(z.id)?z.title+' hidden':z.title}</strong><span>{d.hidden.includes(z.id)?'Tap to compare':z.text}</span></button>)}</div><p className="small">A fictional workspace. Hide the three sensitive areas; your safe demonstration remains visible.</p></>}
 if(kind==='teaching-plan'){const names=['Name the action','Show the step','Pause to try','Check the result'];return <><label>One observable objective<input aria-label="One observable objective" maxLength={180} value={d.objective} placeholder="Fold one edge to meet the other" onChange={e=>update({objective:e.target.value})}/></label><div className="vl-teaching-sequence" aria-label="Your teaching sequence">{d.order.map((n:number,i:number)=><div key={n}><span>{i+1}</span><strong>{names[n]}</strong>{n===2&&<small>{d.pause} seconds to try</small>}</div>)}</div><ol className="vl-teaching-order">{d.order.map((n:number,i:number)=><li key={n}><strong>{names[n]}</strong><div className="vl-small-actions"><Button variant="outline" disabled={i===0} aria-label={'Move '+names[n]+' earlier'} onClick={()=>update({order:reorder(d.order,i,i-1)})}>Earlier</Button><Button variant="outline" disabled={i===3} aria-label={'Move '+names[n]+' later'} onClick={()=>update({order:reorder(d.order,i,i+1)})}>Later</Button></div></li>)}</ol><Slider label="Pause for practice" value={d.pause} min={5} max={20} suffix=" sec" onChange={pause=>update({pause})}/><p className="small">Try a different order, then keep the one that fits your demonstration. A recorded pause can invite the viewer to stop playback and practise for longer.</p></>}
 return null;
}
