'use client';
import React from 'react';
export const batchThreeDefaults={'mic-distance':{distance:100,noise:40,controls:[]},'caption-layout':{y:50,size:18,backing:false,controls:[]},'teaching-revision':{reveal:50,sawBefore:false,sawAfter:false}};
function Slider({label,value,min,max,unit='',change}:{label:string;value:number;min:number;max:number;unit?:string;change:(n:number)=>void}){return <label className="vl-range"><span>{label}<output>{value}{unit}</output></span><input type="range" aria-label={label} min={min} max={max} value={value} onChange={e=>change(Number(e.target.value))}/></label>}
export function BatchThreeInteractive({kind,d,update,id}:{kind:string;d:any;update:(p:any)=>void;id:string}){
 const control=(key:string,value:any)=>update({[key]:value,controls:[...new Set([...(d.controls||[]),key])]});
 if(kind==='mic-distance'){const signal=Math.min(95,1600/d.distance),noise=d.noise*.65;return <><svg viewBox="0 0 720 340" role="img" aria-label={`Relative signal model. Microphone ${d.distance} cm away; background setting ${d.noise}. Useful signal ${Math.round(signal)}, background ${Math.round(noise)} in illustrative units.`}><rect width="720" height="340" rx="14" fill="#15353e"/><text x="30" y="42" fill="#e1ece6" fontSize="24">VOICE POSITION</text><circle cx="70" cy="112" r="15" fill="#cddd9d"/><path d={`M90 112H${130+d.distance*2.2}`} stroke="#9fbabc" strokeDasharray="5 5"/><rect x={125+d.distance*2.2} y="80" width="15" height="65" fill="#cddd9d"/><text x="30" y="210" fill="#e1ece6" fontSize="23">Useful signal</text><rect x="220" y="188" height="28" width={signal*4.5} fill="#cddd9d"/><text x="30" y="278" fill="#e1ece6" fontSize="23">Background</text><rect x="220" y="256" height="28" width={noise*4.5} fill="#7dabb5"/></svg><Slider label="Microphone distance" min={20} max={200} value={d.distance} unit=" cm" change={n=>control('distance',n)}/><Slider label="Room noise model" min={0} max={100} value={d.noise} change={n=>control('noise',n)}/><p className="small">Moving closer raises the useful signal in this simplified model. It does not simulate a microphone, room reflections or speech intelligibility.</p></>}
 if(kind==='caption-layout'){const overlaps=d.y>=32&&d.y<=68;return <><svg viewBox="0 0 720 405" role="img" aria-label={`Caption at ${d.y} percent, size ${d.size}, ${d.backing?'with':'without'} a dark backing. ${overlaps?'It overlaps the demonstration area.':'It leaves the demonstration visible.'}`}><rect width="720" height="405" rx="14" fill="#608d96"/><path d="M20 90H700M20 315H700" stroke="#bcd0c7" strokeDasharray="7 7"/><rect x="190" y="130" width="340" height="140" fill="#ceceaa"/><text x="360" y="206" textAnchor="middle" fill="#24444d" fontSize="28">DEMONSTRATION AREA</text>{d.backing&&<rect x="130" y={d.y*4.05-28} width="460" height="50" rx="6" fill="#10252c"/>}<text x="360" y={d.y*4.05+7} textAnchor="middle" fontSize={d.size} fill="#fff">Fold the edge to the centre.</text></svg><Slider label="Caption position" min={15} max={85} value={d.y} unit="%" change={n=>control('y',n)}/><Slider label="Caption size" min={18} max={32} value={d.size} change={n=>control('size',n)}/><label className="vl-consent"><input type="checkbox" checked={d.backing} onChange={e=>control('backing',e.target.checked)}/>Add a dark caption backing</label><p className="small" role="status">{overlaps?'The caption overlaps the action. Move it into the clear area.':!d.backing?'Compare the caption with a dark backing.':d.size<24?'Try a larger size for a small screen.':'The diagram leaves room for both action and text. Check your real export too.'}</p></>}
 if(kind==='teaching-revision')return <><svg viewBox="0 0 720 300" role="img" aria-label={`Teaching draft: 8 seconds introduction, 12 demonstration, 10 learner practice, 6 check. Revision: 3 introduction, 12 demonstration, 10 learner practice, 6 check. ${d.reveal} percent revealed.`}><rect width="720" height="300" rx="14" fill="#15353e"/><text x="30" y="45" fill="#e1ece6" fontSize="26">DRAFT · 36 seconds</text>{[8,12,10,6].map((n,i)=><g key={i}><rect x={30+[0,8,20,30][i]*17} y="85" width={n*17-5} height="105" fill={i===2?'#cadf9b':'#72979d'}/><text x={30+([0,8,20,30][i]+n/2)*17} y="144" textAnchor="middle" fill="#142c34" fontSize="25">{n}s</text></g>)}<clipPath id={id+'-teaching-reveal'}><rect width={720*d.reveal/100} height="300"/></clipPath><g clipPath={`url(#${id}-teaching-reveal)`}><rect width="720" height="300" rx="14" fill="#203e47"/><text x="30" y="45" fill="#e1ece6" fontSize="26">REVISION · 31 seconds</text>{[3,12,10,6].map((n,i)=><g key={i}><rect x={30+[0,3,15,25][i]*17} y="85" width={n*17-5} height="105" fill={i===2?'#cadf9b':'#72979d'}/><text x={30+([0,3,15,25][i]+n/2)*17} y="144" textAnchor="middle" fill="#142c34" fontSize="25">{n}s</text></g>)}<text x="30" y="246" fill="#e1ece6" fontSize="23">Practice time stays: 10 seconds</text></g><line x1={720*d.reveal/100} x2={720*d.reveal/100} y1="0" y2="300" stroke="#fff" strokeWidth="3"/></svg><Slider label="Reveal the teaching revision" min={0} max={100} value={d.reveal} unit="%" change={reveal=>update({reveal,sawBefore:d.sawBefore||reveal<15,sawAfter:d.sawAfter||reveal>85})}/><p className="small">Introduction · Demonstration · Learner practice · Check. The useful practice pause is preserved.</p></>;
 return null;
}
