'use client';
import React,{lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Go,Panel,UploadField,useLearning,isExplore} from '../ui';
import {blockingModule,moduleHref,isFreePath,sequenceFor,moduleInfo} from '../learning-rules';
import {pathLessons,visualLesson,visualScenarioId,visualScenarioMatches,type VisualLesson,feedbackFor} from './content';
import {type ActivityEvidence,activityReady,validateActivityDraft} from './activity-rules';
import {TeachingCanvas} from './shared-lab';
import {sharedUnits,sharedPathTitle,sharedPathOutcome,sharedPathPreview} from './shared';
import {SharedClip} from './shared-clip';
import {LessonImage,Diagram} from './media';
import {LessonInteractive} from './interactives';
import {usesHookComparison} from './simple-interactive';
import {teachingMedia} from './teaching-media';
import {lessonVideos} from './videos';

const titles:Record<string,string>={'need-c01-03-starter':'Your first event rehearsal','need-c01-03-prepare':'Prepare for the performance','product-reel':'Your first product reel','everyday-story':'Your first everyday story','natural-light':'Better light, with your phone','first-edit':'Turn clips into a story','need-c05-01-starter':'A short teaching rehearsal','need-c05-01-prepare':'Plan your teaching film','need-c05-01-practice':'Record your teaching film','need-c05-01-finish':'Finish your teaching film','need-c05-01-foundations':'Build your teaching foundations','need-c05-01-stretch':'Test your teaching choices'};
const outcomes:Record<string,string>={'need-c01-03-starter':'A harmless framing test and a checked 30–45 second rehearsal. The actual event remains to be filmed.','need-c01-03-prepare':'A permission plan, a device rehearsal and a practical fallback for the event.','product-reel':'A 15–30 second vertical reel that shows one useful benefit.','everyday-story':'A 20–40 second film with a beginning, a change and an ending.','natural-light':'A two-setup lighting study, with notes you can repeat.','first-edit':'A checked 20–40 second edit with clear sound and readable captions.','need-c05-01-starter':'A safe teaching frame and a 30–60 second rehearsal. Your full lesson comes later.','need-c05-01-prepare':'A safe recording plan and a storyboard for one teachable action.','need-c05-01-practice':'A short teaching draft with clear steps, sound and captions.','need-c05-01-finish':'A checked 60–120 second teaching film, with captions and written steps.','need-c05-01-foundations':'Sound notes, an accessible step sample and a steady recording setup.','need-c05-01-stretch':'Two controlled teaching samples and an honest comparison log.'};
const labels=['Watch','Make','Reflect'];
function outcomeFor(id:string,s:any){const r=s.profile?.request;if(id.startsWith('need-c01-03-')&&r?.scenario?.use_case==='C01-03'&&!r.starting?.gear?.some((g:string)=>['phone','camera'].includes(g)))return 'A labelled event recording plan. Capture, sound and playback are still untested.';if(id.startsWith('need-c05-01-')&&r?.scenario?.use_case==='C05-01'){const g=r.starting?.gear||[];if(g.includes('computer')&&!g.some((v:string)=>['phone','camera'].includes(v))&&!r.starting.screen_recorder)return 'A labelled teaching plan. Recording and playback are still to test.';if(id.endsWith('-finish')&&r.outcome?.length_seconds>120)return 'One checked 60–120 second teaching chunk. Your longer goal still needs the remaining chunks.';}return outcomes[id]||sharedPathOutcome(id,s.profile);}
const AssignmentReflect=lazy(()=>import('./assignment-reflect'));
const blankReview=()=>({version:1 as const,answers:[-1,-1,-1],focus:-1,correction:'',checked:false});
function time(n:number){return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function videoKey(l:VisualLesson){return l.canonicalModule?teachingMedia[l.canonicalModule]?.lesson:l.key;}
function Clip({lesson:l}:{lesson:VisualLesson}){if(!videoKey(l))return <SharedClip lesson={l}/>;return <ExternalClip lesson={l}/>;}
function ExternalClip({lesson:l}:{lesson:VisualLesson}){const {loaded}=useLearning();const [play,setPlay]=useState(false),[standard,setStandard]=useState(false);const v=lessonVideos[videoKey(l)!];return <><div className="vl-video">{play?<iframe title={v.title+' · '+v.creator} key={String(standard)} src={`https://${standard?'www.youtube.com':'www.youtube-nocookie.com'}/embed/${v.id}?start=${v.start}&end=${v.end}&autoplay=1&cc_load_policy=1&rel=0`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<div className="vl-video-cover"><span aria-hidden="true" className="vl-play-symbol">▷</span><h3>{v.title}</h3><p>{v.creator} · {time(v.end-v.start)} excerpt</p><Button disabled={!loaded} onClick={()=>setPlay(true)}>Play lesson clip</Button><small>Loads YouTube only when you play.</small></div>}</div><p className="small"><a href={`https://www.youtube.com/watch?v=${v.id}&t=${v.start}s`} target="_blank" rel="noreferrer">Open video on YouTube</a> · {time(v.start)}–{time(v.end)}{v.preview?' · Preview':''}</p><details className="vl-reading"><summary>Video not playing?</summary><p>Some browsers restrict embedded playback. Open the creator’s video above, try the standard YouTube player, or use the visual example and reading below.</p><Button variant="outline" onClick={()=>{setStandard(true);setPlay(true)}}>Try standard YouTube player</Button><p className="small">This loads YouTube’s standard player, which may use cookies.</p></details><details className="vl-reading"><summary>About this clip</summary><p>{v.note}</p></details><details className="vl-reading"><summary>Read the teaching alternative</summary><p>{v.reading}</p><p className="small">Framepath’s text alternative, not a verbatim transcript. {v.transcript?<a href={v.transcript} target="_blank" rel="noreferrer">Creator’s transcript</a>:'YouTube captions are requested by the player; availability depends on the creator.'}</p><a href={v.source} target="_blank" rel="noreferrer">Credited source</a></details></>}
export function ProjectFilmstrip({id,s}:{id:string;s:any}){const used=new Set<string>();return <ol className="vl-filmstrip" style={{gridTemplateColumns:`repeat(${pathLessons(id).length},minmax(0,1fr))`,maxWidth:pathLessons(id).length<=2?520:undefined}} aria-label="Your project filmstrip">{pathLessons(id,s.profile).map((l,i)=>{const done=!!s.progress?.[l.key],d=s.drafts?.[l.key],image=done&&d?.uploadId&&d.uploadType?.startsWith('image/')&&!used.has(d.uploadId);if(image)used.add(d.uploadId);return <li key={l.key} className={done?'earned':''}><a href={moduleHref(l.key)}>{image?<img loading="lazy" src={'/api/file/'+d.uploadId} alt={'Your practice for '+l.title}/>:<div className="vl-frame-number"><span>{done?'✓':String(i+1).padStart(2,'0')}</span><small>{done?'Frame earned':l.phase==='pre'?'Plan':l.phase==='production'?'Shoot':'Edit'}</small></div>}<strong>{l.title}</strong></a></li>})}</ol>}
function Milestone({id,s}:{id:string;s:any}){const [message,setMessage]=useState(''),total=pathLessons(id).length,count=pathLessons(id).filter(l=>s.progress[l.key]).length;async function share(){const text=`I finished ${count} of ${total} practice sessions in ${(titles[id]||sharedPathTitle(id)).toLowerCase()} on Framepath. ${count===total?outcomeFor(id,s):'My next frame is in progress.'} This is a practice milestone, not a certification.`;try{if(navigator.share)await navigator.share({title:'My Framepath milestone',text});else{await navigator.clipboard.writeText(text);setMessage('Milestone text copied. It contains no work, name or private link.')}}catch(e:any){if(e.name!=='AbortError')setMessage('Sharing is unavailable. You can select and copy the milestone text below.')}}return <div className="vl-milestone"><span className="eyebrow">YOUR PRACTICE MILESTONE</span><h2>{count===total?'Your practice is ready to keep.':`${count} frame${count===1?'':'s'} earned.`}</h2><p>{count===total?outcomeFor(id,s):'Your work grows one session at a time.'}</p><p className="small">Practice completed, not a qualification. Your media stays private unless you choose to publish it in My work.</p><Button variant="outline" onClick={share}>Share milestone</Button>{message&&<p role="status">{message}</p>}<details><summary>Preview share text</summary><p>I finished {count} of {total} practice sessions in {(titles[id]||sharedPathTitle(id)).toLowerCase()} on Framepath. {count===total?outcomeFor(id,s):'My next frame is in progress.'} This is a practice milestone, not a certification.</p></details></div>}
export function VisualPath({id}:{id:string}){const {s}=useLearning(),lessons=pathLessons(id,s.profile),next=lessons.find(l=>!s.progress[l.key])||lessons[0],done=lessons.filter(l=>s.progress[l.key]).length,context=lessons[0].context;return <section className="vl-path"><header className="vl-path-head"><span className="eyebrow">{id.endsWith('-starter')?'YOUR SHORT REHEARSAL':id.startsWith('need-')?(titles[id]||sharedPathTitle(id)).toUpperCase():'YOUR VIDEO PROJECT'}{isFreePath(id,s)?' · FREE PRACTICE':''}</span><h1>{context?'Your route: '+context.goal:(titles[id]||sharedPathTitle(id))}</h1><p>{outcomeFor(id,s)}</p><p className="small">{lessons.length} sessions · {lessons.reduce((n,l)=>n+l.minutes,0)} guided minutes · works on phone or computer</p><Go href={moduleHref(next.key)}>{done===lessons.length?'Revisit project':'Continue project'}</Go></header><div className="path-outcome-visual">{lessons.find(l=>!l.image.startsWith('diagram:'))?<LessonImage id={lessons.find(l=>!l.image.startsWith('diagram:'))!.image} priority/>:<Diagram id={id+':outcome-preview'} labels={sharedPathPreview(id)} variant="timing"/>}</div><p className="small">{context?.why||'Your own frames appear below as you finish.'}</p><ProjectFilmstrip id={id} s={s}/><div className="vl-path-notes"><article><h2>One small session at a time</h2><p>Watch or read, explore a visual idea, make something, review your assignment and answer three short questions. Save your work to open the next session. Feedback scores never lock these sessions.</p></article><article><h2>Your weekly rhythm</h2><p>Try one or two sessions when they fit. No daily streak. The first session takes {lessons[0].minutes} minutes; leave more time for extra takes.</p></article></div>{done>0&&<Milestone id={id} s={s}/>}<details><summary>Already started this project?</summary><p>Your earlier assignments, scores and progress stay attached to the same sessions. Completed sessions remain open; you can add a new practice record without losing an older submission.</p></details></section>}

export function VisualSession({pathId,index}:{pathId:string;index:number}){
 const {s,user,loaded,mutate,busy,online,error:stateError}=useLearning();const l=visualLesson(pathId+'-'+index,s.profile)!;
 const [card,setCard]=useState(0),[notes,setNotes]=useState(''),[url,setUrl]=useState(''),[upload,setUpload]=useState<any>(null),[activity,setActivity]=useState<ActivityEvidence|undefined>(),[consent,setConsent]=useState(false),[saved,setSaved]=useState(''),[dirty,setDirty]=useState(false),[workMode,setWorkMode]=useState<'record'|'plan'>('record'),[review,setReview]=useState(blankReview),[attempted,setAttempted]=useState(false),[localError,setLocalError]=useState('');
 const initialized=useRef(false),heading=useRef<HTMLHeadingElement>(null),finishing=useRef(false);
 const draftKey='fp-lesson-draft:'+l.key+':'+(user?.email||'guest');
 useEffect(()=>{if(!loaded||initialized.current)return;initialized.current=true;if(s.profile?.request?.starting?.gear?.every((g:string)=>!['phone','camera'].includes(g)))setWorkMode('plan');
  const stored=s.drafts?.[l.key];let local:any=null;try{local=JSON.parse(sessionStorage.getItem(draftKey)||sessionStorage.getItem('fp-lesson-draft:'+l.key)||'null')}catch{}
  const d=local&&(!stored||Number(local.localAt)>Date.parse(stored.updatedAt||''))?local:stored;
  if(d){if(['plan','record'].includes(d.visualWorkMode))setWorkMode(d.visualWorkMode);setNotes(d.notes||'');setUrl(d.url||'');if(d.uploadId)setUpload({id:d.uploadId,type:d.uploadType,name:'Your saved practice'});try{setActivity(validateActivityDraft(l.key,d.visualActivity||d.activity))}catch{setActivity(undefined)}if(d.visualReview?.version===1)setReview(d.visualReview);setConsent(d.visualConsent===true||!!s.visualSessions?.[l.key]);setCard(d.visualCard===5?5:d.visualCard===4?4:0);}
 },[loaded,s,l.key,draftKey]);
 useEffect(()=>{heading.current?.focus()},[card]);
 const localDraft=()=>({notes,url,uploadId:upload?.id||'',uploadType:upload?.type||'',visualActivity:activity,visualReview:review,visualConsent:consent,visualCard:card,visualWorkMode:workMode,localAt:Date.now()});
 useEffect(()=>{if(!dirty||!initialized.current)return;try{sessionStorage.setItem(draftKey,JSON.stringify(localDraft()))}catch{}},[notes,url,upload,activity,review,consent,card,workMode,dirty,draftKey]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const scenarioId=visualScenarioId(pathId),needsProfile=!visualScenarioMatches(pathId,s.profile),canSave=!needsProfile&&(isFreePath(pathId,s)||isExplore(s)),blocked=blockingModule(s,l.key),done=!!s.progress?.[l.key],ready=activityReady(l.key,activity);
 const minNotes=workMode==='plan'&&!url.trim()&&!upload?.id?60:20;
 const validUrl=!url.trim()||(()=>{try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)}catch{return false}})();
 const workIssues=[notes.trim().length<minNotes?(workMode==='plan'?`Write your plan in at least ${minNotes} characters, including what remains untested.`:'Add a short practice note (at least 20 characters).'):'',workMode==='record'&&!url.trim()&&!upload?.id?'Attach a still, clip or viewing link. Or choose “Write a plan”.':'',!validUrl?'Use a complete http:// or https:// viewing link.':'',!consent?'Confirm that you have permission to save this practice.':''].filter(Boolean);
 const hasWork=workIssues.length===0;
 const body=()=>({key:l.key,notes,url,uploadId:upload?.id||'',activity,review,consent,card,workMode});
 function clearLocal(){try{sessionStorage.removeItem(draftKey);sessionStorage.removeItem('fp-lesson-draft:'+l.key)}catch{}}
 async function save(){setLocalError('');if(!user)return false;if(!online){setLocalError('You’re offline. Your draft is kept in this tab; reconnect and save again.');return false}const result=await mutate('visual_session_save',body());if(result){setDirty(false);clearLocal();setSaved('Draft saved. Continue whenever it fits.');return true}setLocalError('Your draft could not be saved. Your changes are still here. Try again.');return false;}
 async function finish(){if(finishing.current)return;setAttempted(true);setLocalError('');if(!online){setLocalError('You’re offline. Your answers are kept in this tab. Reconnect and try Save & continue again.');return;}if(!hasWork||!ready||!review.checked||review.answers.some(v=>v<0)||review.focus<0||review.correction.trim().length<12||blocked||!canSave)return;
  finishing.current=true;try{const result=await mutate('visual_session_complete',body());if(result){setDirty(false);clearLocal();setCard(6)}else setLocalError('We couldn’t save this time. Your assignment and answers are still here. Try Save & continue again.');}finally{finishing.current=false}
 }
 function guestDraft(){try{sessionStorage.setItem('fp-lesson-draft:'+l.key,JSON.stringify(localDraft()));setDirty(false)}catch{}}
 function change(){setDirty(true);setSaved('');setLocalError('')}
 function go(n:number){setSaved('');setLocalError('');if(n===5&&!hasWork){setAttempted(true);setCard(4);return;}setAttempted(false);setCard(n)}
 const lessons=pathLessons(pathId,s.profile),sequence=sequenceFor(pathId,s),position=sequence.indexOf(l.key),nextKey=position>=0?sequence[position+1]:lessons[index+1]?.key;
 const nextLesson=nextKey?visualLesson(nextKey,s.profile):undefined,nextInfo=nextKey?moduleInfo(nextKey,s.profile):null;
 const nextTitle=nextLesson?.title||nextInfo?.lesson.title,nextMinutes=nextLesson?.minutes||nextInfo?.lesson.minutes;
 return <section className="vl-session"><header className="vl-session-head"><a href={'/explore/'+pathId}>{titles[pathId]||sharedPathTitle(pathId)}</a><span className="small">Session {index+1} of {lessons.length} · {l.minutes} min · {l.phase==='pre'?'Pre-production':l.phase==='post'?'Post-production':'Production'}</span></header>
 <nav className="simple-lesson-tabs" aria-label="Session steps">{labels.map((label,i)=>{const target=[0,4,5][i];return <button key={label} aria-current={card===target?'step':undefined} onClick={()=>go(target)}><span>{i+1}</span>{label}</button>})}{done&&<small>Completed</small>}</nav>
 <article className={'vl-card vl-card-'+card}><h1 ref={heading} tabIndex={-1}>{card===0?l.title:card===4?l.make.title:card===5?'Make your work better':'One more frame earned.'}</h1>
 {card===0&&<>{l.context&&<p className="vl-personal-goal">For: <strong>{l.context.goal}</strong></p>}<div className="simple-lesson-media"><div className="vl-hook-photo">{usesHookComparison(l)?<fieldset className="simple-hero-compare" disabled={!loaded}><LessonInteractive key={l.key} lesson={l} value={activity} onChange={v=>{setActivity(v);change()}}/></fieldset>:l.image.startsWith('diagram:')?<TeachingCanvas family={l.labFamily!} title={l.title}/>:<LessonImage id={l.image} priority/>}</div><div className="simple-watch"><span className="eyebrow">WATCH THE EXAMPLE</span><Clip lesson={l}/></div></div><p className="vl-lede">{l.concept.text}</p>{!usesHookComparison(l)&&<fieldset className="simple-try" disabled={!loaded} aria-busy={!loaded}><h2>See the difference</h2><LessonInteractive key={l.key} lesson={l} value={activity} onChange={v=>{setActivity(v);change()}}/></fieldset>}{l.context&&<details><summary>Why this session?</summary><p>{l.context.why}</p></details>}</>}
 {card===4&&<><p className="vl-lede">Use your own footage, or work through the idea as a written plan.</p><fieldset className="simple-work-choice"><legend>How will you practise?</legend><div><button aria-pressed={workMode==='record'} onClick={()=>{setWorkMode('record');change()}}>Use footage</button><button aria-pressed={workMode==='plan'} onClick={()=>{setWorkMode('plan');change()}}>Write a plan</button></div></fieldset><div className="make-layout"><div><ol className="vl-make-steps">{(workMode==='record'?l.make.steps:[`Plan this task: ${l.make.title.toLowerCase()}.`,`Describe three moments: ${l.make.example.join(', ')}.`,`Explain one choice and what you still need to record or test.`]).map(step=><li key={step}>{step}</li>)}</ol><p className="vl-consent-note">{l.make.consent} <a href="/safety">Consent & safety</a></p><details><summary>What can I submit?</summary><p>{workMode==='plan'?'Your written plan is enough for this planning practice. A storyboard or annotated still is optional. It does not prove recording or playback skills.':l.make.evidence}</p></details></div><div className="make-input"><label>{workMode==='plan'?'Your written plan':'Your practice note'}<textarea aria-label={workMode==='plan'?'Your written plan':'Your practice note'} rows={6} maxLength={4000} value={notes} onChange={e=>{setNotes(e.target.value);change()}} placeholder={workMode==='plan'?'First I’ll show… Then… Finally… I chose this because… I still need to test…':'What did you make? What changed between your first and latest attempt?'}/></label><details className="vl-evidence" open={workMode==='record'?true:undefined}><summary>{workMode==='plan'?'Add a file or link · optional':'Add your file or viewing link'}</summary><label>Private viewing link<input type="url" value={url} maxLength={1200} onChange={e=>{setUrl(e.target.value);change()}} placeholder="https://…"/></label><p className="small">Private. AI cannot open your link.</p>{user&&canSave?<UploadField lessonKey={l.key} value={upload} onUpload={(f:any)=>{setUpload(f);setConsent(false);change()}}/>:<p className="small">{user?'Set up saving access below to upload a file.':'You can write a plan now. Sign in when you want to upload or save.'}</p>}</details>{upload?.id&&<p className="small">Practice file attached. <button className="text-link" onClick={()=>{setUpload(null);change()}}>Remove from draft</button></p>}<label className="vl-consent"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);change()}}/>I have permission to save this practice. It contains no identifying children or sensitive information.</label></div></div>{attempted&&!hasWork&&<div className="review-alert" role="alert"><strong>A little more before feedback</strong><ul>{workIssues.map(t=><li key={t}>{t}</li>)}</ul></div>}</>}
 {card===5&&(hasWork?<Suspense fallback={<p role="status">Opening your assignment review…</p>}><AssignmentReflect lesson={l} notes={notes} url={url} upload={upload} workMode={workMode} value={review} onChange={v=>{setReview({...v,checked:v.checked===true});change()}} onSave={save} onEdit={()=>go(4)}/></Suspense>:<div className="review-alert"><h2>Add your assignment first</h2><p>Feedback starts with something you made.</p><ul>{workIssues.map(t=><li key={t}>{t}</li>)}</ul><Button onClick={()=>go(4)}>Finish my assignment</Button></div>)}
 {card===6&&<><ProjectFilmstrip id={pathId} s={s}/><p>Your assignment, correction and score are saved in <a href="/my-work">My work</a>.</p><div className="vl-next"><span className="eyebrow">{nextKey?'NEXT IN YOUR ROUTE':'PRACTICE COMPLETE'}</span><h2>{nextKey?`${nextTitle} · ${nextMinutes} min`:l.next}</h2><p>{nextLesson?.hook||(nextKey?'This is the next session in your personal route.':outcomeFor(pathId,s))}</p><Go href={nextKey?moduleHref(nextKey):'/explore/'+pathId}>{nextKey?'Continue when ready':'See my project'}</Go></div><Milestone id={pathId} s={s}/></>}
 {card===5&&attempted&&<div className="review-alert" role="alert"><ul>{!ready&&<li><button className="text-link" onClick={()=>go(0)}>Compare both views in Watch</button></li>}{!hasWork&&<li><button className="text-link" onClick={()=>go(4)}>Finish your assignment</button></li>}{(review.focus<0||review.correction.trim().length<12)&&<li>Choose a review focus and write one correction or a reason to keep it (at least 12 characters).</li>}{(!review.checked||review.answers.some(v=>v<0))&&<li>Answer the three lesson questions and select “Check my answers”.</li>}{!canSave&&<li><a href={needsProfile?'/diagnostic?case='+scenarioId:'/membership?return_to='+encodeURIComponent(moduleHref(l.key))}>{needsProfile?'Set up this video goal to save your route':'View access for this pathway'}</a></li>}{blocked&&<li><a href={moduleHref(blocked)}>Finish the previous session first</a>. You can still explore this one.</li>}</ul></div>}
 {card<6&&<>{!online&&<p className="review-alert" role="status">You’re offline. Keep this tab open; reconnect to save your work.</p>}{(localError||stateError)&&<p className="review-alert" role="alert">{localError} {stateError}</p>}<div className="vl-card-actions"><Button variant="ghost" disabled={card===0} onClick={()=>go(card===5?4:0)}>Back</Button>{card<5?<Button disabled={!loaded} onClick={()=>go(card===0?4:5)}>{card===0?'Make my version →':'Review my assignment →'}</Button>:!user?<a className="vl-signin" onClick={guestDraft} href={'/auth/google?return_to='+encodeURIComponent(moduleHref(l.key))}>Sign in to save & continue</a>:<Button disabled={busy||!loaded} onClick={finish}>{busy?'Saving…':'Save & continue'}</Button>}</div></>}
 </article>{card<6&&<aside className="vl-session-extras">{user&&<><Button variant="outline" disabled={busy} onClick={save}>Save for later</Button>{saved&&<p role="status">{saved}</p>}</>}{user&&!canSave&&<p className="small"><a href={needsProfile?'/diagnostic?case='+scenarioId:'/membership?return_to='+encodeURIComponent(moduleHref(l.key))}>{needsProfile?'Set up this goal to save your practice':'See saving access for this pathway'}</a></p>}<details><summary>Go deeper · optional</summary><p className="small">None of these resources is required to finish the session.</p>{l.deeper.map((item,i)=><article key={l.key+':guide:'+i}><h3>{item.title}</h3><p>{item.text}</p>{item.url&&<a href={item.url}>Open guide</a>}</article>)}<button className="text-link" onClick={()=>{const text=l.deeper.map(d=>d.title+'\n'+d.text).join('\n\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));link.download=l.key+'-practice-notes.txt';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}}>Download practice notes</button><p><a href="/resources">More optional resources</a></p></details><details><summary>Image and video credits</summary>{l.canonicalModule?<p className="small">Original Framepath teaching diagrams and illustrative AI-generated scenario photographs, plus credited videos where available. Shared teaching units support different goals; your work remains specific to your route.</p>:<p className="small">Original illustrative images generated for Framepath with OpenAI. Video: {lessonVideos[videoKey(l)!].creator}. <a href={lessonVideos[videoKey(l)!].source} target="_blank" rel="noreferrer">Credited source</a>.</p>}</details></aside>}</section>
}
