'use client';
import {SimpleInteractive} from './simple-interactive';
import {SharedLab} from './shared-lab';
import React,{useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {reorder} from '../foundation/interactive-contract';
import {type VisualLesson} from './content';
import {type ActivityEvidence,activityReady} from './activity-rules';
import {LessonImage,Diagram} from './media';
import {BatchTwoInteractive,batchTwoDefaults} from './batch-two-interactives';
import {BatchThreeInteractive,batchThreeDefaults} from './batch-three-interactives';
import {BatchFiveInteractive,batchFiveDefaults} from './batch-five-interactives';
import {BatchFourInteractive,batchFourDefaults} from './batch-four-interactives';
type Props={lesson:VisualLesson;value?:ActivityEvidence;onChange:(v:ActivityEvidence)=>void};
function Range({label,value,min,max,step=1,onChange,unit=''}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void;unit?:string}){return <label className="vl-range"><span>{label}<output>{value}{unit}</output></span><input type="range" aria-label={label} min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
export function LessonInteractive(props:Props){return <SimpleInteractive {...props}/>;}
function ExistingInteractive({lesson:l,value,onChange}:Props){const defaults:Record<string,any>={...batchTwoDefaults,...batchThreeDefaults,...batchFourDefaults,...batchFiveDefaults,framing:{crop:100,position:50,compared:false},'shot-list':{shots:[{size:'Wide',purpose:''},{size:'Medium',purpose:''},{size:'Close',purpose:''}]},exposure:{iso:400,shutter:50,controls:[]},timeline:{order:[2,0,1,3],durations:[6,5,5,4]},captions:{caption:l.activity.caption||'Ready in two minuites.',seconds:2},'story-arc':{order:[0,1,2]},'shot-sorter':{order:[2,0,1]},'white-balance':{kelvin:5600,cool:false,warm:false},audio:{compared:false,method:'visual',selected:''},revision:{reveal:50,sawBefore:false,sawAfter:false}};
 const [d,setD]=useState<Record<string,any>>(()=>value?.data||{...defaults[l.activity.kind],changes:0});const drag=useRef<number|null>(null),[heard,setHeard]=useState<string[]>([]),audio=useRef<(HTMLAudioElement|null)[]>([]);
 function update(patch:Record<string,any>){const next={...d,...patch,changes:Math.min(10000,(d.changes||0)+1)};setD(next);onChange({version:1,kind:l.activity.kind,data:next});}
 const ready=activityReady(l.key,{version:1,kind:l.activity.kind,data:d});const sizeNames=['Wide','Medium','Close'],arcNames=l.activity.items||['Before','Change','After'],clipNames=l.activity.items||['Action','Detail','Result','Finish'],limits=l.activity.durationRange||[15,30];
 const move=(from:number,to:number)=>{if(from!==to)update({order:reorder(d.order,from,to)})};
 return <div className="vl-interactive" data-activity={l.activity.kind}>
 {l.activity.kind==='framing'&&<><svg viewBox="0 0 720 360" role="img" aria-label={`A framing diagram. Crop ${d.crop} percent, centre ${d.position} percent.`}><rect width="720" height="360" rx="12" fill="#15353e"/><path d="M80 235H640" stroke="#73989b" strokeDasharray="5 5"/><rect x="280" y="100" width="90" height="155" rx="4" fill="#cbdc9d"/><text x="325" y="290" textAnchor="middle" fill="#dce8e0" fontSize="30">Object</text><rect x="390" y="142" width="210" height="70" rx="4" fill="#79a9b5"/><text x="495" y="183" textAnchor="middle" fill="#102b32" fontSize="30">Action space</text><rect x={d.position*7.2-d.crop*2.7} y="55" width={d.crop*5.4} height="240" fill="none" stroke="#f6f0df" strokeWidth="4"/></svg><Range label="Frame width" value={d.crop} min={45} max={100} unit="%" onChange={crop=>update({crop,compared:true})}/><Range label="Frame position" value={d.position} min={20} max={80} unit="%" onChange={position=>update({position})}/><p className="small">A geometry model of framing. It does not crop a real camera image.</p></>}
 {l.activity.kind==='shot-list'&&<><Diagram id={l.key+':activity-diagram'} variant="frames" labels={d.shots.map((s:any)=>s.size)}/><ol className="vl-shotlist">{d.shots.map((s:any,i:number)=><li key={i}><label>Shot {i+1}<select aria-label={'Shot '+(i+1)+' size'} value={s.size} onChange={e=>update({shots:d.shots.map((v:any,n:number)=>i===n?{...v,size:e.target.value}:v)})}>{sizeNames.map(n=><option key={n}>{n}</option>)}</select></label><label>What does it show?<input value={s.purpose} maxLength={150} placeholder={['Introduce the object','Show it in use','Reveal the useful detail','Show the result','Leave room for words'][i]} onChange={e=>update({shots:d.shots.map((v:any,n:number)=>i===n?{...v,purpose:e.target.value}:v)})}/></label><div className="vl-small-actions"><Button variant="outline" disabled={i===0} aria-label={'Move shot '+(i+1)+' earlier'} onClick={()=>update({shots:reorder(d.shots,i,i-1)})}>Earlier</Button><Button variant="ghost" disabled={d.shots.length<=3} aria-label={'Remove shot '+(i+1)} onClick={()=>update({shots:d.shots.filter((_:any,n:number)=>n!==i)})}>Remove</Button></div></li>)}</ol><Button variant="outline" disabled={d.shots.length>=5} onClick={()=>update({shots:[...d.shots,{size:'Close',purpose:''}]})}>Add a shot</Button></>}
 {l.activity.kind==='exposure'&&<><div className="vl-photo"><LessonImage id={l.activity.image!} style={{filter:`brightness(${Math.max(.2,Math.min(3.5,(d.iso/400)*(50/d.shutter)))})`}}/><span className="vl-photo-label">{Math.log2((d.iso/400)*(50/d.shutter)).toFixed(1)} stops relative</span></div><div className="vl-control-pair"><label>ISO<select aria-label="ISO" value={d.iso} onChange={e=>update({iso:Number(e.target.value),controls:[...new Set([...d.controls,'iso'])]})}>{[100,200,400,800,1600].map(n=><option key={n}>{n}</option>)}</select></label><label>Shutter time<select aria-label="Shutter time" value={d.shutter} onChange={e=>update({shutter:Number(e.target.value),controls:[...new Set([...d.controls,'shutter'])]})}>{[25,50,100,250].map(n=><option key={n} value={n}>1/{n} second</option>)}</select></label></div><div className="vl-exposure-readings"><span>{d.iso>=800?'Higher ISO: watch noise':'Lower ISO: needs enough light'}</span><span>{d.shutter>=100?'Shorter exposure: less motion blur':'Longer exposure: more motion blur'}</span></div></>}
 {['story-arc','shot-sorter','timeline'].includes(l.activity.kind)&&<><div className="vl-timeline" aria-label="Your current sequence">{d.order.map((n:number,i:number)=><div key={n} style={{flex:l.activity.kind==='timeline'?d.durations[n]:1}}><strong>{l.activity.kind==='timeline'?clipNames[n]:l.activity.kind==='story-arc'?arcNames[n]:sizeNames[n]}</strong>{l.activity.kind==='timeline'&&<small>{d.durations[n]} sec</small>}</div>)}</div><ol className="vl-order">{d.order.map((n:number,i:number)=>{const label=l.activity.kind==='timeline'?clipNames[n]:l.activity.kind==='story-arc'?arcNames[n]:sizeNames[n];return <li key={n} draggable onDragStart={e=>{drag.current=i;e.dataTransfer.setData('text/plain',String(i));}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current!==null)move(drag.current,i);drag.current=null;}}><svg viewBox="0 0 200 125" role="img" aria-label={l.activity.kind==='shot-sorter'?label+' framing diagram':label+' timing diagram'}><rect width="200" height="125" rx="6" fill="#22434a"/>{l.activity.kind==='shot-sorter'?<><rect x={20+n*24} y="20" width={160-n*48} height="85" fill="none" stroke="#bfcebd" strokeDasharray="4 4"/><circle cx="100" cy="60" r={12+n*10} fill="#cddd9d"/></>:<><path d="M20 82H180" stroke="#7ea6a8"/>{[0,1,2,3].map(v=><rect key={v} x={25+v*40} y={v===n?36:61} width="28" height={v===n?45:20} fill={v===n?'#cddd9d':'#719493'}/>)}</>}</svg><strong>{label}</strong>{l.activity.kind==='timeline'&&<Range label={label+' duration'} value={d.durations[n]} min={2} max={10} unit=" sec" onChange={v=>update({durations:d.durations.map((x:number,k:number)=>k===n?v:x)})}/>}<div className="vl-small-actions"><Button variant="outline" disabled={i===0} aria-label={'Move '+label+' earlier'} onClick={()=>move(i,i-1)}>Earlier</Button><Button variant="outline" disabled={i===d.order.length-1} aria-label={'Move '+label+' later'} onClick={()=>move(i,i+1)}>Later</Button></div></li>})}</ol><p className="small">Drag to reorder, or use Earlier / Later. {l.activity.kind==='timeline'?`Total: ${d.durations.reduce((n:number,v:number)=>n+v,0)} seconds. Keep it between ${limits[0]} and ${limits[1]}.`:'Make two changes to compare your choices.'}</p></>}
 {l.activity.kind==='white-balance'&&<><div className="vl-photo"><LessonImage id={l.activity.image!}/><div className="vl-colour-overlay" style={{background:d.kelvin>5600?'#f89c31':'#236ce3',opacity:Math.abs(d.kelvin-5600)/8000}}/><span className="vl-photo-label">Illustrative colour cast</span></div><Range label="White balance" value={d.kelvin} min={2800} max={8000} step={100} unit=" K" onChange={kelvin=>update({kelvin,cool:d.cool||kelvin<4500,warm:d.warm||kelvin>6500})}/></>}
 {l.activity.kind==='captions'&&<><div className="vl-caption-preview"><svg viewBox="0 0 600 200" role="img" aria-label={`Caption timing diagram: ${d.seconds} seconds`}><path d="M30 100H570" stroke="#709295"/>{[0,2,4,6,8].map((n,i)=><g key={n}><text x={40+i*65} y="80" fill="#dae4e0">{n}s</text><path d={`M${40+i*65} 93v14`} stroke="#9ab8b9"/></g>)}<rect x="40" y="124" width={d.seconds*32.5} height="20" rx="5" fill="#ccdf9e"/></svg><p>{d.caption}</p></div><label>Your caption<textarea aria-label="Your caption" rows={2} maxLength={100} value={d.caption} onChange={e=>update({caption:e.target.value})}/></label><Range label="Time on screen" min={2} max={8} value={d.seconds} unit=" sec" onChange={seconds=>update({seconds})}/><p className="small">{d.caption.toLowerCase().includes('minuites')?'Check the spelling of “minutes”.':d.caption.length/d.seconds>17?'Shorten the caption or give it more time.':'Practice spelling and reading-speed checks look clear. Verify the meaning yourself.'}</p></>}
 {l.activity.kind==='audio'&&<><div className="vl-audio">{['quiet','noisy'].map((name,i)=><section key={name}><svg viewBox="0 0 280 120" role="img" aria-label={i?'A tapping pattern with constant background noise':'A tapping pattern with quiet gaps'}>{Array.from({length:64},(_,n)=>{const hit=[7,21,39,53].some(p=>Math.abs(n-p)<2);const h=hit?60:i?12+n*13%22:3;return <line key={n} x1={12+n*4} x2={12+n*4} y1={60-h/2} y2={60+h/2} stroke={i?'#93b6bb':'#cddd9d'} strokeWidth="2"/>})}</svg><h3>Sample {i?'B':'A'}</h3><audio ref={el=>{audio.current[i]=el}} controls preload="none" aria-label={'Sample '+(i?'B':'A')} src={'/lessons/'+(l.activity.audioPrefix||'story-audio')+'-'+name+'.wav'} onPlay={()=>audio.current.forEach((p,n)=>{if(n!==i)p?.pause()})} onEnded={()=>{const all=[...new Set([...heard,name])];setHeard(all);if(all.length===2)update({compared:true,method:'audio'});}}/><p className="small">{i?'Taps with a steady noisy background.':'Taps separated by quiet gaps.'}</p></section>)}</div>{!d.compared&&<Button variant="outline" onClick={()=>update({compared:true,method:'visual'})}>Use the waveform descriptions</Button>}<fieldset disabled={!d.compared}><legend>Choose a recording to keep</legend><div className="vl-choice-row">{['quiet','noisy'].map((name,i)=><Button key={name} variant={d.selected===name?'default':'outline'} aria-pressed={d.selected===name} onClick={()=>update({selected:name})}>Keep sample {i?'B':'A'}</Button>)}</div></fieldset></>}
 {l.activity.kind==='revision'&&<><div className="vl-reveal"><svg viewBox="0 0 720 260" role="img" aria-label={`Before: 8 seconds waiting, 12 seconds action, 8 seconds pause, 12 seconds result. After: 12 seconds action, 2 seconds pause, 12 seconds result. ${d.reveal} percent of the revision revealed.`}><rect width="720" height="260" fill="#15333a"/><text x="25" y="52" fill="#e1e7dd" fontSize="30">DRAFT · 40 seconds</text>{[8,12,8,12].map((n,i)=><g key={i}><rect x={30+[0,8,20,28][i]*15} y="90" width={n*15-4} height="95" rx="6" fill={i%2?'#638f99':'#8c745f'}/><text x={30+([0,8,20,28][i]+n/2)*15} y="149" textAnchor="middle" fill="#fff" fontSize="32">{n}s</text></g>)}<clipPath id={'reveal-'+l.key}><rect width={720*d.reveal/100} height="260"/></clipPath><g clipPath={'url(#reveal-'+l.key+')'}><rect width="720" height="260" fill="#1e4047"/><text x="25" y="52" fill="#e1e7dd" fontSize="30">REVISION · 26 seconds</text>{[12,2,12].map((n,i)=><g key={i}><rect x={30+[0,12,14][i]*15} y="90" width={n*15-4} height="95" rx="6" fill={i===1?'#8c9c72':'#ccdf9f'}/>{i!==1&&<text x={30+([0,12,14][i]+n/2)*15} y="149" textAnchor="middle" fill="#183439" fontSize="32">{n}s</text>}</g>)}</g><line x1={720*d.reveal/100} x2={720*d.reveal/100} y1="0" y2="260" stroke="#fff" strokeWidth="3"/></svg></div><Range label="Reveal the revised timeline" value={d.reveal} min={0} max={100} unit="%" onChange={reveal=>update({reveal,sawBefore:d.sawBefore||reveal<15,sawAfter:d.sawAfter||reveal>85})}/><div className="vl-comparison-key"><p><strong>Draft:</strong> Waiting · action · long pause · result</p><p><strong>Revision:</strong> Action · short pause · result</p></div></>}

 <BatchTwoInteractive kind={l.activity.kind} d={d} update={update} id={l.key}/>
 <BatchThreeInteractive kind={l.activity.kind} d={d} update={update} id={l.key}/>
 <BatchFourInteractive kind={l.activity.kind} d={d} update={update} id={l.key}/>
 <BatchFiveInteractive kind={l.activity.kind} d={d} update={update}/>
 <p className={'vl-activity-state '+(ready?'ready':'')} role="status">{ready?'Activity explored. Try these choices in your own work.':l.activity.instruction}</p><p>{l.activity.takeaway}</p></div>
}

