import {teachingMedia} from './teaching-media';
import model from '../scenario-runtime.json';
import {buildSharedUnits} from './shared-units';
import paths from './shared-paths.json';
import {labSpecs} from './lab-specs';
import type {VisualLesson} from './content';
export const sharedUnits:Record<string,any>=buildSharedUnits(model);
export const sharedPaths=paths;
const data:any=model;
export const sharedStages=['prepare','foundations','practice','stretch','finish','starter'];
export function sharedStageModules(c:any,stage:string):string[]{const a=data.archetypes[c.primary_archetype],base=data.pathways[c.pathway_id].module_order;if(stage==='prepare')return base.slice(0,2);if(stage==='practice')return base.slice(2,5);if(stage==='finish')return base.slice(5);if(stage==='starter')return ['new:consent-privacy','new:'+a.new_core];if(stage==='stretch')return ['new:'+a.new_core,'new:reflect-revise'];return [...new Set(c.skill_clusters.map((k:string)=>data.foundation_modules[k]).filter((m:any)=>m&&!base.includes(m)))].slice(0,3) as string[];}
export function sharedKeyInfo(key:string){const match=/^(need-(c\d{2}-\d{2})-(prepare|foundations|practice|stretch|finish|starter))-(\d+)$/.exec(key);if(match){const scenario=data.use_cases.find((c:any)=>c.id===match[2].toUpperCase());if(!scenario)return null;const source=sharedStageModules(scenario,match[3])[Number(match[4])];return source&&sharedUnits[source]?{source,scenario,stage:match[3],pathId:match[1],index:Number(match[4])}:null;}const p=sharedPaths.find(p=>p.keys.includes(key));return p?{source:key,scenario:null,stage:'skill',pathId:p.id,index:p.keys.indexOf(key)}:null;}
export function sharedPathKeys(id:string){const p=sharedPaths.find(p=>p.id===id);if(p)return p.keys;const m=/^need-(c\d{2}-\d{2})-(prepare|foundations|practice|stretch|finish|starter)$/.exec(id),c=m&&data.use_cases.find((c:any)=>c.id===m[1].toUpperCase());return c?sharedStageModules(c,m![2]).map((_:string,i:number)=>id+'-'+i):[];}
export const isSharedPath=(id:string)=>sharedPathKeys(id).length>0;
export const isSharedKey=(key:string)=>!!sharedKeyInfo(key);
export function sharedPathPreview(id:string){const info=sharedKeyInfo(sharedPathKeys(id)[0]||'');if(!info?.scenario)return ['Your starting point','One useful comparison','Your finished practice'];const a=data.archetypes[info.scenario.primary_archetype],u=sharedUnits['new:'+a.new_core];return (labSpecs[u.family]||labSpecs.sequence).labels;}
const stageNames:Record<string,string>={prepare:'Plan your recording',foundations:'Build the missing skills',practice:'Make your first version',stretch:'Compare a harder version',finish:'Check and deliver',starter:'Your first small try'};
export function sharedPathTitle(id:string){const p=sharedPaths.find(p=>p.id===id);return p?.title||stageNames[id.split('-').at(-1)!]||'Your practice';}
export function sharedPathOutcome(id:string,profile?:any){const keys=sharedPathKeys(id),info=keys.length?sharedKeyInfo(keys[0]):null;if(!info)return '';if(!info.scenario)return sharedPaths.find(p=>p.id===id)?.outcome||'';if(info.stage==='starter')return 'One safe rehearsal, a practical observation and your next step. The complete video comes later.';if(info.stage==='prepare')return 'A clear recording plan and a safe first test.';if(info.stage==='foundations')return 'Focused comparisons for the skills your goal needs.';if(info.stage==='stretch')return 'Two controlled versions, with the trade-off explained.';if(info.stage==='practice')return 'A scoped first version to check before the complete recording.';return profile?.request?.outcome?.format||info.scenario.deliverable.format;}
function brief(text:string,max=72){const words=String(text||'').split(/\s+/);if(words.length<=max)return text;const chunk=words.slice(0,max).join(' '),dot=chunk.lastIndexOf('. ');return dot>chunk.length/2?chunk.slice(0,dot+1):chunk+'…';}
export function sharedVisualLesson(key:string,profile?:any):VisualLesson|undefined{
 const info=sharedKeyInfo(key);if(!info)return;const u=sharedUnits[info.source],c=info.scenario,a=c?data.archetypes[c.primary_archetype]:null;
 const r=c&&profile?.request?.scenario?.use_case===c.id?profile.request:null,goal=r?.outcome?.goal||(c?.learner_outcome)||profile?.goal||'',audience=r?.outcome?.audience||c?.audience||'your intended viewer';
 const skill=r?.skillOverrides?.[u.skill]??(r?.assessedSkills?.[u.skill]?r.assessedSkills[u.skill].value:r?.starting?.skills?.[u.skill])??null,level=skill===null?'Not assessed':skill>=3.2?'Advanced':skill>=2.5?'Confident':skill>=1.5?'Building':'Starting';
 const lab=labSpecs[u.family]||labSpecs.sequence,first=info.index===0,short=info.stage==='starter'||first;
 const gear=r?.starting?.gear||[],requiresCapture=!['screen','files','archive','format','titles','privacy','claims','verification','aerial','spatial','revision'].includes(u.family),noCamera=!!r&&(requiresCapture&&!gear.some((g:string)=>['phone','camera'].includes(g))||u.family==='screen'&&(!gear.includes('computer')||!r.starting.screen_recorder));
 const specialist=c&&c.review_policy!=='self_or_peer_with_evidence_limits';
 const variant=c&&info.source==='new:'+a.new_core?data.case_adaptations[c.id]?.variant_task:'';
 const task=variant||u.steps.join(' '),scope=short?'Make one five-minute rehearsal with an owned object or fictional data. The full project comes later.':info.stage==='stretch'?'Compare two safe versions while changing one variable. Keep the earlier version.':skill!==null&&skill>=3?'Make two controlled samples; explain one deliberate trade-off.':'Make one small, repeatable sample. Check it before extending the recording.';
 const steps=[scope,brief(noCamera?'Make a labelled storyboard or recording plan. Capture, motion and sound remain untested. '+task:task,35),'Use your goal and audience above. Save a frame or private link and one observation.'];
 if(specialist)steps[1]=brief('Use a harmless simulation. This does not authorise specialist work. '+task,35);
 const checks=(u.checks?.length===3?u.checks:a?.rubric.map((q:any)=>q.label)||['The purpose is clear','I kept a safe sample','I named the next check']) as [string,string,string];
 const minutes=first?8:info.stage==='starter'?12:info.stage==='skill'?u.originalMinutes:info.stage==='stretch'?30:r?.preferences?.pace==='gentle'?15:20;
 const safe='Use owned objects, fictional data or consenting adults. Do not upload identifying children, private records or sensitive footage. Recording and sharing need separate permission.';
 const why=(goal?'For "'+goal+'", ':'')+(skill===null?'this skill has not been assessed yet, so start with a small comparison.':skill>=3?'your stronger starting point supports a controlled comparison.':'a small practical sample helps build '+(data.skills[u.skill]||u.skill)+'.')+(noCamera?' Your current equipment supports planning only.':'')+(r?.starting?.bandwidth==='low'?' Use the still diagrams and written alternative on limited data.':'');
 return {key,title:short&&u.title.length>45?'Try: '+u.title:u.title,minutes,phase:info.stage==='prepare'?'pre':info.stage==='finish'?'post':u.phase,hook:brief(u.example||u.idea,45),image:u.archetype?'shared:'+u.archetype:teachingMedia[info.source]?.image||'diagram:'+info.source,canonicalModule:info.source,labFamily:u.family,
 concept:{title:u.title,text:brief(u.idea),labels:lab.labels},activity:{kind:'shared-lab',title:lab.title,instruction:lab.instruction,takeaway:lab.takeaway},make:{title:noCamera?'Plan your first test':short?'Make a small first try':'Make your version',steps,example:lab.labels,evidence:noCamera?'A labelled storyboard or plan, with untested recording checks clearly named.':'A representative still or private link, plus a note on the decision and actual playback checks.',consent:safe+(specialist?' No medical or legal advice; qualified review is still required.':'')},reflect:checks,minimum:u.minimum||checks,weights:a?a.rubric.map((q:any)=>q.weight) as [number,number,number]:[40,35,25],context:goal?{goal,why,level}:undefined,next:'Keep your practice and choose the next useful step',deeper:[{title:'Full teaching notes',text:u.idea},{title:'Example to compare',text:u.example},{title:'Your scoped task',text:task},{title:'If equipment is unavailable',text:u.alternative||'Use fictional notes or a labelled storyboard. State what you planned separately from what you actually recorded.'},...u.resources.slice(0,3).map((id:string)=>({title:'Optional creator guide',text:'A credited external reference for this skill. No document is required to complete the session.',url:'/resources?resource='+encodeURIComponent(id)}))]};
}
