'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {labSpecs} from './lab-specs';
import {drawTeaching} from './shared-drawing';
import type {VisualLesson} from './content';
import type {ActivityEvidence} from './activity-rules';
export function TeachingCanvas({family,title,x,y,order=[0,1,2]}:{family:string;title:string;x?:number;y?:number;order?:number[]}){const canvas=useRef<HTMLCanvasElement>(null),spec=labSpecs[family]||labSpecs.sequence;useEffect(()=>{if(canvas.current)drawTeaching(canvas.current.getContext('2d'),720,430,spec,x??spec.start[0],y??spec.start[1],order,title)},[family,title,x,y,order.join(',')]);return <figure className="shared-visual"><canvas ref={canvas} width={720} height={430} role="img" aria-label={spec.title+'. '+spec.x+': '+(x??spec.start[0])+'. '+spec.y+': '+(y??spec.start[1])+'. '+spec.labels.join(', ')} /><figcaption>{spec.labels.join(' · ')}</figcaption></figure>}
export function SharedLab({lesson:l,value,onChange}:{lesson:VisualLesson;value?:ActivityEvidence;onChange:(v:ActivityEvidence)=>void}){const spec=labSpecs[l.labFamily!]||labSpecs.sequence;const [d,setD]=useState<any>(value?.data||{x:spec.start[0],y:spec.start[1],order:[0,1,2],controls:[],note:'',changes:0}),[before,setBefore]=useState(false);
 function update(p:any,control:string){const next={...d,...p,changes:Math.min(10000,d.changes+1),controls:[...new Set([...d.controls,control])]};setD(next);onChange({kind:'shared-lab',version:1,data:next});}
 return <div className="shared-lab" data-activity="shared-lab"><TeachingCanvas family={l.labFamily!} title={l.concept.title} x={before?spec.start[0]:d.x} y={before?spec.start[1]:d.y} order={before?[0,1,2]:d.order}/><Button variant="outline" aria-pressed={before} onClick={()=>setBefore(!before)}>{before?'Show my changes':'Compare the starting view'}</Button><div className="vl-control-pair">{(['x','y'] as const).map(k=>{const range=k==='x'?spec.range:spec.rangeY;return <label key={k}>{spec[k]} <output>{d[k]}</output><input type="range" aria-label={spec[k]} min={range[0]} max={range[1]} step={range[2]} value={d[k]} onChange={e=>update({[k]:Number(e.target.value)},k)}/></label>})}</div>{spec.mode==='sequence'&&<ol className="shared-order">{d.order.map((v:number,i:number)=><li key={v}><span>{spec.labels[v]}</span><Button variant="outline" disabled={i===0} aria-label={'Move '+spec.labels[v]+' earlier'} onClick={()=>{const order=[...d.order];[order[i],order[i-1]]=[order[i-1],order[i]];update({order},'order')}}>Earlier</Button></li>)}</ol>}<p>{spec.instruction}</p><label>Keep one observation<textarea aria-label="Keep one observation" rows={2} maxLength={300} value={d.note} onChange={e=>update({note:e.target.value},'note')} placeholder="Describe what changed in the visual and how you would use it."/></label><p className="small">{spec.takeaway}</p><p role="status" className="small">{d.controls.includes('x')&&d.controls.includes('y')&&d.note.trim().length>=20?'Exploration saved in this draft. Continue to your practical tryout.':'Explore both controls and keep one observation of at least 20 characters.'}</p></div>;
}
