// References to existing, credited teaching units. Media is owned once in the
// registry; a scenario route can point to that unit without copying its assets.
export const teachingMedia:Record<string,{lesson:string;image:string}>={
 'basic-w1-0':{lesson:'everyday-story-0',image:'story-01'},
 'basic-w1-2':{lesson:'product-reel-0',image:'product-01'},
 'basic-w1-3':{lesson:'everyday-story-1',image:'story-02'},
 'basic-w2-0':{lesson:'everyday-story-2',image:'story-03'},
 'basic-w2-1':{lesson:'natural-light-2',image:'light-03'},
 'basic-w4-0':{lesson:'natural-light-0',image:'light-01'},
 'basic-w4-1':{lesson:'natural-light-1',image:'light-02'},
 'basic-w4-3':{lesson:'natural-light-3',image:'light-04'},
 'basic-w4-4':{lesson:'product-reel-2',image:'product-03'},
 'basic-w5-0':{lesson:'need-c05-01-foundations-0',image:'teach-foundations-0'},
 'basic-w5-1':{lesson:'need-c05-01-practice-1',image:'teach-practice-1'},
 'basic-w5-3':{lesson:'everyday-story-3',image:'story-04'},
 'basic-w6-0':{lesson:'need-c05-01-foundations-2',image:'teach-foundations-2'},
 'basic-w6-2':{lesson:'product-reel-1',image:'product-02'},
 'basic-w7-0':{lesson:'first-edit-0',image:'edit-01'},
 'basic-w7-1':{lesson:'first-edit-1',image:'edit-02'},
 'basic-w7-2':{lesson:'first-edit-2',image:'edit-04'},
 'basic-w7-3':{lesson:'first-edit-3',image:'edit-03'},
 'basic-w7-4':{lesson:'product-reel-3',image:'product-04'},
 'intermediate-w4-3':{lesson:'first-edit-4',image:'edit-05'},
 'new:consent-privacy':{lesson:'need-c05-01-prepare-0',image:'teach-prepare-0'},
 'new:memory-capture':{lesson:'need-c01-03-starter-1',image:'event-starter-1'},
 'new:event-backup':{lesson:'need-c01-03-prepare-1',image:'event-prepare-1'},
 'new:teaching-chunks':{lesson:'need-c05-01-practice-0',image:'teach-practice-0'},
 'new:archive-preservation':{lesson:'everyday-story-4',image:'story-05'},
 'new:accessible-communication':{lesson:'need-c05-01-practice-2',image:'teach-practice-2'},
 'new:delivery-originals':{lesson:'product-reel-4',image:'product-05'},
 'new:reflect-revise':{lesson:'need-c05-01-finish-1',image:'teach-finish-1'},
};
