import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const learners=sqliteTable('learners',{userId:text('user_id').primaryKey(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull()});
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),type:text('type').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_uploads_owner').on(t.userId)]);
export const aiJobs=sqliteTable('ai_jobs',{id:text('id').primaryKey(),userId:text('user_id').notNull(),scope:text('scope').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),answer:text('answer'),createdAt:integer('created_at').notNull()},t=>[index('idx_ai_user_scope_date').on(t.userId,t.scope,t.createdAt),index('idx_ai_date').on(t.createdAt)]);
export const portfolios=sqliteTable('portfolios',{token:text('token').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull()},t=>[index('idx_portfolio_owner').on(t.userId)]);


export const reflectionAttempts=sqliteTable('reflection_attempts',{id:text('id').primaryKey(),userId:text('user_id').notNull(),moduleKey:text('module_key').notNull(),data:text('data').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_reflection_owner_module_date').on(t.userId,t.moduleKey,t.createdAt)]);

export const onboardingAttempts=sqliteTable('onboarding_attempts',{id:text('id').primaryKey(),userId:text('user_id'),guestHash:text('guest_hash').notNull(),revision:integer('revision').notNull().default(0),data:text('data').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_onboarding_owner').on(t.userId,t.updatedAt),index('idx_onboarding_guest').on(t.guestHash,t.updatedAt)]);
export const goalLogs=sqliteTable('goal_logs',{id:text('id').primaryKey(),attemptId:text('attempt_id').notNull(),userId:text('user_id'),words:text('words').notNull(),caseId:text('case_id').notNull(),confidence:integer('confidence').notNull(),clarification:text('clarification').notNull(),status:text('status').notNull().default('new'),createdAt:integer('created_at').notNull()},t=>[index('idx_goal_log_date').on(t.createdAt)]);
