import {cookieName,onboardingContext as context,syncProfile} from '../../onboarding/session';
import {getUser} from '../../user';
import {db,checkOrigin,errorResponse,readState,saveState,mentorFor} from '../../service';
import {classifyGoal,defaultSetup,validateSetup} from '../../onboarding/goals';
import {assess,commitAnswer,profileFor,planFor,chapters} from '../../onboarding/assessment';
import {upgradeAttempt,schedulePreview} from '../../onboarding/schedule';
import {onboardingVersion,Attempt} from '../../onboarding/types';
export const dynamic='force-dynamic';
function output(req:Request,c:any,a:Attempt|null){const ready=a&&['result','schedule','mode','ready'].includes(a.status);return Response.json({attempt:a,authenticated:!!c.user,assessment:a?assess(a):undefined,plan:ready?planFor(a):undefined,serverSavedAt:a?.updatedAt},{headers:{'Cache-Control':'no-store','Set-Cookie':`${cookieName}=${c.token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${new URL(req.url).protocol==='https:'?'; Secure':''}`}});}
export async function GET(req:Request){try{if(new URL(req.url).searchParams.get('history')==='1'){const user=await getUser();if(!user)throw Object.assign(Error('Sign in to export your diagnostic history.'),{status:401});const rows=await db().prepare('SELECT data FROM onboarding_attempts WHERE user_id=? ORDER BY created_at').bind(user.userId).all();return Response.json({history:rows.results.map((r:any)=>JSON.parse(r.data))},{headers:{'Cache-Control':'no-store'}});}const c=await context(req);if(c.row&&c.user&&!c.row.user_id){const r=await db().prepare('UPDATE onboarding_attempts SET user_id=? WHERE id=? AND user_id IS NULL AND guest_hash=?').bind(c.user.userId,c.row.id,c.hash).run();if(!r.meta.changes){const claimed:any=await db().prepare('SELECT user_id FROM onboarding_attempts WHERE id=?').bind(c.row.id).first();if(claimed?.user_id!==c.user.userId)throw Object.assign(Error('This draft has changed. Reload to continue.'),{status:409});}await db().prepare('UPDATE goal_logs SET user_id=? WHERE attempt_id=? AND user_id IS NULL').bind(c.user.userId,c.row.id).run();}const a=c.row?upgradeAttempt(JSON.parse(c.row.data)):null;if(a?.status==='ready'&&c.user)await syncProfile(c.user.userId,a);return output(req,c,a);}catch(e){return errorResponse(e)}}
export async function POST(req:Request){try{checkOrigin(req);if(!req.headers.get('content-type')?.includes('application/json'))throw Error('Send a valid learning update.');const raw=await req.text();if(raw.length>18000)throw Error('This update is too long.');const b=JSON.parse(raw),c=await context(req),now=new Date().toISOString();let a:Attempt=c.row?upgradeAttempt(JSON.parse(c.row.data)):null;
 if(b.action==='start'){
  if(a&&b.revision!==a.revision)throw Object.assign(Error('A saved route is already here. Reload before starting again.'),{status:409});
  const recent:any=await db().prepare('SELECT count(*) AS n FROM onboarding_attempts WHERE guest_hash=? AND created_at>?').bind(c.hash,Date.now()-3600000).first();if(recent.n>=8)throw Object.assign(Error('You have started several routes. Continue a saved route or try again later.'),{status:429});
  const goal=classifyGoal(b.words,b.caseId,b.clarification&&{subject:String(b.clarification.subject||'').slice(0,200),audience:String(b.clarification.audience||'').slice(0,200)});
  a={version:onboardingVersion,id:crypto.randomUUID(),revision:0,goal,setup:defaultSetup(goal.caseId),setupStep:0,answers:[],status:'setup',firstFrame:{note:'',made:false},startedAt:now,updatedAt:now,overrides:{},mode:null};
  await db().prepare('INSERT INTO onboarding_attempts(id,user_id,guest_hash,revision,data,status,created_at,updated_at) VALUES(?,?,?,0,?,?,?,?)').bind(a.id,c.user?.userId||null,c.hash,JSON.stringify(a),a.status,Date.now(),Date.now()).run();
  if(goal.custom)await db().prepare('INSERT INTO goal_logs(id,attempt_id,user_id,words,case_id,confidence,clarification,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),a.id,c.user?.userId||null,goal.words,goal.caseId,Math.round(goal.confidence*100),JSON.stringify(goal.clarification||{}),'new',Date.now()).run();return output(req,c,a);
 }
 if(!a)throw Error('Choose your video goal first.');if(b.revision!==a.revision||b.attemptId!==a.id)throw Object.assign(Error('Your answers changed in another tab. Reload to continue from the saved question.'),{status:409});
 const requireStatus=(...s:string[])=>{if(!s.includes(a.status))throw Error('This step has already been saved. Continue from the current screen.');};
 switch(b.action){
 case 'first-frame':requireStatus('first-frame');a.firstFrame={note:String(b.note||'').trim().slice(0,600),made:b.made===true};if(!a.firstFrame.made||a.firstFrame.note.length<3)throw Error('Make your first frame and add a short note about it.');a.status='setup';break;
 case 'setup':requireStatus('setup');a.setup=validateSetup({...a.setup,...b.setup},a.goal.caseId);a.setupStep++;if(a.setupStep>=2)a.status='questions';break;
 case 'answer':requireStatus('questions');a.answers.push(commitAnswer(a,b));if(assess(a).complete)a.status='result';break;
 case 'pause':requireStatus('questions');if(a.answers.length<12)throw Error('You can pause after the first twelve steps.');a.status='paused';break;
 case 'resume':requireStatus('paused');a.status='questions';break;
 case 'adjust':requireStatus('result','schedule','mode','ready');if(b.setup)a.setup=validateSetup({...a.setup,...b.setup},a.goal.caseId);if(b.words){const changed=classifyGoal(String(b.words),undefined,a.goal.clarification);if(changed.caseId!==a.goal.caseId&&changed.confidence>=.65)throw Error('This sounds like a different video task. Start a new goal so its practical checks and route fit; your saved work will stay available.');a.goal={...a.goal,words:changed.words};}if(b.overrides){a.overrides={};for(const ch of chapters)if(Number.isFinite(b.overrides[ch.id])&&b.overrides[ch.id]>=0&&b.overrides[ch.id]<=4)a.overrides[ch.id]=b.overrides[ch.id];}break;
 case 'accept':requireStatus('result');a.status='schedule';break;
 case 'schedule':requireStatus('schedule','ready');if(!Number.isFinite(b.hours)||b.hours<.5||b.hours>20||!Number.isInteger(b.weeks)||b.weeks<1||b.weeks>12)throw Error('Choose weekly hours and a window of 1–12 weeks.');a.setup=validateSetup({...a.setup,hours:b.hours,weeks:b.weeks},a.goal.caseId);if(!schedulePreview(profileFor(a),a.setup.hours,a.setup.weeks).fits)throw Error('Allow more time for this route.');if(a.status!=='ready')a.status='mode';break;
 case 'mode':requireStatus('mode','ready');if(!['self','mentor'].includes(b.mode))throw Error('Choose how you want to learn.');a.mode=b.mode;if(b.mode==='mentor'){mentorFor(b.mentorId);if(!['Weekday evenings','Weekend mornings','Flexible'].includes(b.callPreference))throw Error('Choose a call preference.');if(b.shareConsent!==true)throw Error('Choose whether to share your profile before continuing with a mentor. You can keep learning self-paced without sharing.');a.mentorId=b.mentorId;a.callPreference=b.callPreference;a.shareConsentAt=now;}else{delete a.mentorId;delete a.callPreference;delete a.shareConsentAt;}a.status='ready';break;
 default:throw Error('Unknown learning update.');}
 a.updatedAt=now;a.revision++;const changed=await db().prepare('UPDATE onboarding_attempts SET data=?,revision=?,status=?,updated_at=?,user_id=COALESCE(user_id,?) WHERE id=? AND revision=? AND (user_id=? OR (user_id IS NULL AND guest_hash=?))').bind(JSON.stringify(a),a.revision,a.status,Date.now(),c.user?.userId||null,a.id,b.revision,c.user?.userId||null,c.hash).run();if(!changed.meta.changes)throw Object.assign(Error('Your answers changed in another tab. Reload to continue.'),{status:409});if(a.status==='ready'&&c.user)await syncProfile(c.user.userId,a);return output(req,c,a);
 }catch(e){return errorResponse(e)}}

